### ISSUE TITLE
ConcurrentModificationException in BleedTimerTask

### ISSUE THREAD

**Issue by ExpoPvP** [mcMMO-Dev/mcMMO#2173]
I experience this issue running the latest dev build:
```
[04:37:32] [Server thread/WARN]: [mcMMO] Task #5 for mcMMO v1.5.01-SNAPSHOT-b231 generated an exception
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_11]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463) ~[?:1.8.0_11]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461) ~[?:1.8.0_11]
        at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:23) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-1589]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [spigot.jar:git-Spigot-1589]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:638) [spigot.jar:git-Spigot-1589]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1589]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1589]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1589]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1589]
```

**Comment by t00thpick1** [comment]
i believe this is fixed
