### ISSUE TITLE
ERROR Could not pass event FakeEntityDamageByEntityEvent

### ISSUE THREAD

**Issue by dotapurex1** [mcMMO-Dev/mcMMO#2207]
```
16.08 19:12:20 [Multicraft] Skipped 19 lines due to rate limit (30/s)
16.08 19:12:18 [Server] INFO at net.minecraft.server.v1_7_R4.EntityPlayer.damageEntity(EntityPlayer.java:464) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at net.minecraft.server.v1_7_R4.EntityHuman.damageEntity(EntityHuman.java:751) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:684) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at net.minecraft.server.v1_7_R4.EntityHuman.d(EntityHuman.java:810) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at net.minecraft.server.v1_7_R4.EntityLiving.d(EntityLiving.java:1040) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:581) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:462) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:549) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:108) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_55]
16.08 19:12:18 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_55]
16.08 19:12:18 [Server] INFO at sun.reflect.GeneratedMethodAccessor241.invoke(Unknown Source) ~[?:?]
16.08 19:12:18 [Server] INFO at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:221) [mcMMO.jar:?]
16.08 19:12:18 [Server] INFO at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:239) [mcMMO.jar:?]
16.08 19:12:18 [Server] INFO at com.gmail.nossr50.util.skills.CombatUtils.processSwordCombat(CombatUtils.java:71) [mcMMO.jar:?]
16.08 19:12:18 [Server] INFO at com.gmail.nossr50.skills.swords.SwordsManager.serratedStrikes(SwordsManager.java:103) [mcMMO.jar:?]
16.08 19:12:18 [Server] INFO at com.gmail.nossr50.util.skills.CombatUtils.applyAbilityAoE(CombatUtils.java:389) [mcMMO.jar:?]
16.08 19:12:18 [Server] INFO at com.gmail.nossr50.util.skills.CombatUtils.shouldBeAffected(CombatUtils.java:547) [mcMMO.jar:?]
16.08 19:12:18 [Server] INFO at com.gmail.nossr50.util.skills.CombatUtils.callFakeDamageEvent(CombatUtils.java:603) [mcMMO.jar:?]
16.08 19:12:18 [Server] INFO at com.gmail.nossr50.util.skills.CombatUtils.callFakeDamageEvent(CombatUtils.java:628) [mcMMO.jar:?]
16.08 19:12:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[spigot.jar:git-Spigot-1586]
16.08 19:12:18 [Server] INFO org.bukkit.event.EventException
16.08 19:12:18 [Server] ERROR Could not pass event FakeEntityDamageByEntityEvent to StrengthPotionNerf v1.0
```

**Comment by t00thpick1** [comment]
This is an issue with StrenghtPotionNerf  not mcMMO
