### ISSUE TITLE
[Cauldron] There was an error while enabling mcMMO!

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#2233]
McMMO dev 3679. Cauldron 1.1207.01.187.

It seems McMMO does not like modded servers?

```
[23:01:03] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.01-SNAPSHOT-b3679
[23:01:03] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[23:01:03] [Server thread/WARN]: java.lang.NullPointerException
[23:01:03] [Server thread/WARN]: 	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:340)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftItemStack.getDurability(CraftItemStack.java:170)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:130)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:31)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:15)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:19)
[23:01:03] [Server thread/WARN]: 	at net.minecraft.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:34)
[23:01:03] [Server thread/WARN]: 	at net.minecraft.item.crafting.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:13)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.RecipeIterator.next(RecipeIterator.java:32)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.RecipeIterator.next(RecipeIterator.java:10)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.getRecipesFor(CraftServer.java:1120)
[23:01:03] [Server thread/WARN]: 	at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:279)
[23:01:03] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.loadKeys(RepairConfig.java:139)
[23:01:03] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.<init>(RepairConfig.java:24)
[23:01:03] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfigManager.<init>(RepairConfigManager.java:34)
[23:01:03] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:428)
[23:01:03] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:142)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[23:01:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[23:01:03] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:459)
[23:01:03] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136)
[23:01:03] [Server thread/WARN]: 	at net.minecraft.world.World.<init>(World.java:352)
[23:01:03] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153)
[23:01:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356)
[23:01:03] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[23:01:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
[23:01:03] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:01:03] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.01-SNAPSHOT-b3679
[23:01:03] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.01-SNAPSHOT-b3679 (Is it up to date?)
java.lang.NullPointerException
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:246) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:392) [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:200) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:459) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:352) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]
```

**Comment by t00thpick1** [comment]
Does not seem to be something we can fix as its within nms classes.
