### ISSUE TITLE
/mcconvert experience linear

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2291]
[00:12:08] [Server thread/WARN]: [mcMMO] Task #1655 for mcMMO v1.5.01-SNAPSHOT-b3682 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Collections.java:3212) ~[?:1.7.0_65]
at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
at com.gmail.nossr50.util.player.UserManager.retrieveMcMMOPlayer(UserManager.java:108) ~[?:?]
at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:90) ~[?:?]
at com.gmail.nossr50.runnables.database.FormulaConversionTask.run(FormulaConversionTask.java:31) ~[?:?]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:600) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]

Version: 1.5.01 build 3682

**Comment by t00thpick1** [comment]
Hey bud, nothing personal but as long as you keep using that username I'm going to close your tickets, the username is really misleading especially given that you have elected to use @TfT-02's profile picture as well.
