### ISSUE TITLE
/mcconvert error

### ISSUE THREAD

**Issue by mcMMO** [mcMMO-Dev/mcMMO#2292]
[21:23:39] [Server thread/INFO]: [0;37;22mStarting conversion from UNKNOWN to LINEAR curve[m
[21:23:39] [Server thread/INFO]: [0;37;22mFormula conversion complete; now using LINEAR XP curve.[m
[21:23:39] [pool-3-thread-2/WARN]: java.lang.NullPointerException
[21:23:39] [pool-3-thread-2/WARN]: 	at com.gmail.nossr50.database.FlatfileDatabaseManager.saveUser(FlatfileDatabaseManager.java:275)
[21:23:39] [pool-3-thread-2/WARN]: 	at com.gmail.nossr50.datatypes.player.PlayerProfile.save(PlayerProfile.java:90)
[21:23:39] [pool-3-thread-2/WARN]: 	at com.gmail.nossr50.runnables.player.PlayerProfileSaveTask.run(PlayerProfileSaveTask.java:16)
[21:23:39] [pool-3-thread-2/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:53)
[21:23:39] [pool-3-thread-2/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[21:23:39] [pool-3-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[21:23:39] [pool-3-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[21:23:39] [pool-3-thread-2/WARN]: 	at java.lang.Thread.run(Unknown Source)

and

[13:32:39] [Server thread/INFO]: [0;37;22mStarting conversion from EXPONENTIAL to LINEAR curve[m
[13:32:39] [Server thread/WARN]: [mcMMO] Task #66 for mcMMO v1.5.01-SNAPSHOT-b3682 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.7.0_67]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.retrieveMcMMOPlayer(UserManager.java:108) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:90) ~[?:?]
	at com.gmail.nossr50.runnables.database.FormulaConversionTask.run(FormulaConversionTask.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:53) ~[minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:600) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:258) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:558) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:469) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [minecraft_server.jar:git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks]

1.5.01-SNAPSHOT-b3682

**Comment by t00thpick1** [comment]
Hey bud, nothing personal but as long as you keep using that username I'm going to close your tickets, the username is really misleading especially given that you have elected to use @TfT-02's profile picture as well.
