### ISSUE TITLE
Could not pass event McMMOPlayerLevelUpEvent

### ISSUE THREAD

**Issue by minecraft7net** [mcMMO-Dev/mcMMO#2351]
mcMMO v1.5.01-SNAPSHOT-b3704

```
[19:11:14] [Server thread/ERROR]: Could not pass event McMMOPlayerLevelUpEvent to mcMMO v1.5.01-SNAPSHOT-b3704
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at com.gmail.nossr50.util.EventUtils.handleLevelChangeEvent(EventUtils.java:71) [mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:505) [mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:479) [mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:442) [mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:432) [mcMMO.jar:?]
        at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:32) [mcMMO.jar:?]
        at com.gmail.nossr50.skills.herbalism.HerbalismManager.herbalismBlockCheck(HerbalismManager.java:168) [mcMMO.jar:?]
        at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:187) [mcMMO.jar:?]
        at sun.reflect.GeneratedMethodAccessor408.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_67]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_67]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.breakBlock(PlayerInteractManager.java:264) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.dig(PlayerInteractManager.java:164) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:552) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:41) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(PacketPlayInBlockDig.java:65) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_7_R4.scoreboard.CraftScoreboardComponent.checkState(CraftScoreboardComponent.java:13) ~[spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at org.bukkit.craftbukkit.v1_7_R4.scoreboard.CraftObjective.unregister(CraftObjective.java:106) ~[spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:366) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSkill(ScoreboardWrapper.java:280) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerSkillLevelUpScoreboard(ScoreboardManager.java:258) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.handleLevelUp(ScoreboardManager.java:214) ~[?:?]
        at com.gmail.nossr50.listeners.SelfListener.onPlayerLevelUp(SelfListener.java:24) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_67]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_67]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_67]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_67]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot-1.7.10-R0.1-SNAPSHOT-20140921a.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
        ... 30 more
```

spigot-1.7.10-R0.1-SNAPSHOT-20140921a
[06:27:24] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-205-g48578ee (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by Glitchfinder** [comment]
There are multiple issues on the tracker that appear to be the same as this, so I am consolidating them all to #3406.
