### ISSUE TITLE
1.8 errors

### ISSUE THREAD

**Issue by noorkoteb** [mcMMO-Dev/mcMMO#2403]
i get some weird errors sometimes 
```
[12:02:18 WARN]: [mcMMO] Task #4 for mcMMO v1.5.00-b3547 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:3212) ~[?:1.7.0_65]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.getPlayers(UserManager.java:65) ~[?:?]
	at com.gmail.nossr50.runnables.SaveTimerTask.run(SaveTimerTask.java:17) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-a6b08a3]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-a6b08a3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:695) [spigot.jar:git-Spigot-a6b08a3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-a6b08a3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:625) [spigot.jar:git-Spigot-a6b08a3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:528) [spigot.jar:git-Spigot-a6b08a3]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
```

**Comment by EvilOlaf** [comment]
Startup log? spigot version? Formatting? 
You don't use the latest official build, you may grab it here: http://www.spigotmc.org/resources/mcmmo.2445/

https://guides.github.com/features/mastering-markdown/
pastebin.com

**Comment by noorkoteb** [comment]
oh lol thank you sorry for bothering you didn't know mcmmo was on spigot

**Comment by TfT-02** [comment]
What @EvilOlaf says. v1.5.00 is outdated ;)
