### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to mcMMO

### ISSUE THREAD

**Issue by xtomyserrax** [mcMMO-Dev/mcMMO#2404]
Hello. I am using Spigot 1.7.10 and mcMMO plugin version: 1.5.00
I get this error:
```
[16:45:11] [Server thread/INFO]: xtomyserrax lost connection: Disconnected
[16:45:11] [Server thread/INFO]: 1234
[16:45:11] [Server thread/ERROR]: Could not pass event AsyncPlayerChatEvent to mcMMO v1.5.00-b3547
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1571]
	at de.tobiyas.racesandclasses.chat.channels.container.ChannelContainer.sendMessageInChannel(ChannelContainer.java:384) [RacesAndClasses.jar:?]
	at de.tobiyas.racesandclasses.chat.channels.container.ChannelContainer.removePlayerFromChannel(ChannelContainer.java:328) [RacesAndClasses.jar:?]
	at de.tobiyas.racesandclasses.chat.channels.ChannelManager.leaveChannel(ChannelManager.java:402) [RacesAndClasses.jar:?]
	at de.tobiyas.racesandclasses.chat.channels.ChannelManager.playerQuit(ChannelManager.java:612) [RacesAndClasses.jar:?]
	at de.tobiyas.racesandclasses.listeners.generallisteners.Listener_Player.onPlayerLeave(Listener_Player.java:63) [RacesAndClasses.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerList.disconnect(PlayerList.java:321) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:735) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:77) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1571]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.8.0_25]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:83) ~[?:?]
	at com.gmail.nossr50.listeners.PlayerListener.onPlayerChat(PlayerListener.java:638) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[spigot.jar:git-Spigot-1571]
	... 24 more
[16:45:17] [User Authenticator #3/INFO]: UUID of player xtomyserrax is 22015dbe-ffb1-3beb-94a3-df663ab2e95a
[16:45:17] [Server thread/ERROR]: Could not pass event AsyncPlayerChatEvent to mcMMO v1.5.00-b3547
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1571]
	at de.tobiyas.racesandclasses.chat.channels.container.ChannelContainer.sendMessageInChannel(ChannelContainer.java:384) [RacesAndClasses.jar:?]
	at de.tobiyas.racesandclasses.chat.channels.container.ChannelContainer.addPlayerToChannel(ChannelContainer.java:311) [RacesAndClasses.jar:?]
	at de.tobiyas.racesandclasses.chat.channels.ChannelManager.joinChannel(ChannelManager.java:364) [RacesAndClasses.jar:?]
	at de.tobiyas.racesandclasses.chat.channels.ChannelManager.playerLogin(ChannelManager.java:597) [RacesAndClasses.jar:?]
	at de.tobiyas.racesandclasses.listeners.generallisteners.Listener_Player.onPlayerJoin(Listener_Player.java:86) [RacesAndClasses.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1571]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:265) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:152) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:105) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:43) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:187) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:731) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1571]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1571]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.8.0_25]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:83) ~[?:?]
	at com.gmail.nossr50.listeners.PlayerListener.onPlayerChat(PlayerListener.java:638) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[spigot.jar:git-Spigot-1571]
	... 27 more
```

**Comment by TfT-02** [comment]
mcMMO v1.5.00 is outdated, please update to our latest version http://www.spigotmc.org/resources/mcmmo.2445/
