### ISSUE TITLE
UUID convertion failed.

### ISSUE THREAD

**Issue by sbHango** [mcMMO-Dev/mcMMO#2411]
Previous issue regarding this was deleted?

When trying to update mcmmo file on a fresh server:
http://pastebin.com/vCF3BZrb
then /stop
And mcmmo.users file only have 331 lines (before convert 9112).

Every time "Conversion progress: 200 users at 200.00 users/second" pops up on the console, file size of mcmmo.users goes down, so instead of converting it, it deletes most of them.

Reported this on spigot a week ago and on irc, not sure how to get any updates on my issue so posting this here.

**Comment by Jessicuhh13** [comment]
I am having the same problem.
This is what exactly what I did.
1) updated from a 1.7 mcmmo version to the 1.8 version. (my server is 1.8)
2) imported my old 1.7 flatfile into the new mcmmo folder.
3) restarted the server
4) checked /mctop and everything was fine. 
5) restarted the server again some time later.
6) checked /mctop and realized that many users had been deleted!!

The first time this happened is was pretty random in who it deleted. However, every time after that it was very specific. Now it leaves only two players on the users file; me and my brother.
I find this odd because our only similarities are that we are both on the same ip, but since the server is webhosted that really shouldn't matter.

I can recreate this bug over and over by following steps 2-6

This is a huge problem for an Mcmmo server. I truly hope you guys are able to fix this.

**Comment by Mikgreg** [comment]
Happened to me on updating too. Deleted many players but only kept some.

**Comment by DahFrozen** [comment]
How do you get it to start the conversion in the first place?

**Comment by DahFrozen** [comment]
nvm, got it to start converting. But only a certain amount of users keep their stats.

**Comment by Jessicuhh13** [comment]
Ok so I found out a few things since my previous post.
First, it seems that the only users that are converted successfully are the ones that are online at some point between the time you import your users file+reload and the next time you reload (and lose most of your data.)
Second, there is a way to manually convert the UUIDs (in Windows). However, I realize that this is very time consuming and probably next to impossible for large servers. If you would like to give it a shot here is the process.
1) Upload your backup mcmmo.users file (replacing the broken located at plugins/mcmmo/flatfile/mcmmo.users)

2) reload your server

3) Go take a look at your mcmmo.users file, you should find many users data that have the word NULL towards the every end of their row. It will look something like this:

Jessicuhh13:455:::2932:114:3271:2:28:3:0:34:56:37:45:480:885:799:50:1396:1693:1393:1492::1:380:0:0:1421029561:0:1418462278:1417032233:1421412967::5:950:0:1421413393:HEARTS:0:0:NULL:

The word NULL is where the players UUID should be. If NULL remains in this spot, this users data will be deleted the next time you reload.

4) Open your usercache.json and locate the player whose data you are currently trying to fix.
You will see something like this:
{"name":"Jessicuhh13","uuid":"ba25478d-a182-4654-b8fc-ebac6f8bcebc","expiresOn":"2015-02-08 17:17:02 -0700"}

5) Copy the players UUID. In this case it was: ba25478d-a182-4654-b8fc-ebac6f8bcebc

6) Go back to your mcmmo.users file and replace the word "NULL" with the players UUID "ba25478d-a182-4654-b8fc-ebac6f8bcebc"

7) Yay, you have successfully saved one user's data. The row in the mcmmo.users file should now look like this:
Jessicuhh13:455:::2932:114:3271:2:28:3:0:34:56:37:45:480:885:799:50:1396:1693:1393:1492::1:380:0:0:1421029561:0:1418462278:1417032233:1421412967::5:950:0:1421413393:HEARTS:0:0:ba25478d-a182-4654-b8fc-ebac6f8bcebc:

8) Repeat this process until you cant resist the urge to bang your head on your keyboard :)

9) After you have converted all the users, maybe make a back up mcmmo.users file and then reload your server. If you have followed the steps correctly none of your users will be deleted, and you wont have to worry about this issue ever again :D

*MAJOR TIP* 
Remember what I said in the beginning of this post? 
About how the users who have been online are successfully converted somehow? and the users who didn't get online were deleted... Well you can use this to your advantage. 
I recommend doing steps 1-2, and maybe start 3 just to make sure your data transferred over relatively ok. 
THEN WAIT! As long as possible, and get as many users online as you can so that they will automatically convert themselves, saving you some work. 
**Remember not to reload in this time period, and also make backups every now and then if you fear your server might crash, or stop for what ever reason.
After you feel you have waited long enough, you can then proceed to the next steps.

Good luck! I hope this helps at least one person :)

PS, while searching I also found someone who claimed to know how to fix it without the manual UUID conversion. Its a bit more advanced. But basically you need to open mcmmo.jar with WinRAR and edit hidden.yml with some sort of notepad program. I attached a picture of what the hidden.yml is supposed to look like. I have not tested this method however, so I'm not sure if it will work.
![screenshot 1](https://cloud.githubusercontent.com/assets/10560901/5794462/ed321410-9f22-11e4-882e-c780049110b6.png)

**Comment by DahFrozen** [comment]
Where do you put the hidden.yml?

**Comment by DahFrozen** [comment]
The hidden.yml doesn't make any difference, It only generates 190 out of 8600 users each time. T_T I don't want my players to lose their progress. @TfT-02 is there anyway we could fix this?

**Comment by Jessicuhh13** [comment]
Yeah that's a tough one. Maybe if you could find 22 trustworthy volunteers to help you manually convert.... It would only be 400 lines per person. Yeah it would take hours even then, but it's the only solution I have found. The makers of mcmmo haven't been very responsive about this issue. I doubt it will be fixed in a timely manner.

**Comment by sbHango** [comment]
Devs, any help?

**Comment by TfT-02** [comment]
@sbHango Sorry for the lack of response, but we have been quite busy over the past two weeks. We are aware of this issue and are working on a fix. Please bear with us!

**Comment by sbHango** [comment]
@TfT-02 
[03:57:27 INFO]: [mcMMO] Conversion progress: 200 users at 28.57 users/second
[03:57:35 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[03:57:42 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[03:57:50 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[03:57:57 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[03:58:05 INFO]: [mcMMO] Conversion progress: 200 users at Infinity users/second
[03:58:12 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[03:58:20 INFO]: [mcMMO] Conversion progress: 200 users at Infinity users/second
[03:58:27 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[03:58:35 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[03:58:42 INFO]: [mcMMO] Conversion progress: 200 users at Infinity users/second
[03:58:50 INFO]: [mcMMO] Conversion progress: 200 users at Infinity users/second
[03:58:57 INFO]: [mcMMO] Conversion progress: 200 users at Infinity users/second
[03:59:04 INFO]: [mcMMO] Conversion progress: 200 users at Infinity users/second
[03:59:12 INFO]: [mcMMO] Conversion progress: 200 users at Infinity users/second
[03:59:19 INFO]: [mcMMO] Conversion progress: 200 users at Infinity users/second
[03:59:27 INFO]: [mcMMO] Conversion progress: 200 users at Infinity users/second
[03:59:34 INFO]: [mcMMO] Conversion progress: 200 users at Infinity users/second
[03:59:41 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[03:59:49 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[03:59:56 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[04:00:04 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[04:00:11 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[04:00:19 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[04:00:26 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[04:00:34 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[04:00:41 INFO]: [mcMMO] Conversion progress: 200 users at 200.00 users/second
[04:07:26 WARN]: [mcMMO] Task #3 for mcMMO v1.5.02-SNAPSHOT-b27 generated an exception
java.lang.NullPointerException
        at com.gmail.nossr50.party.PartyManager.saveParties(PartyManager.java:574) ~[?:?]
        at com.gmail.nossr50.runnables.SaveTimerTask.run(SaveTimerTask.java:22) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-d0d1d87-15e81cf]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_10]

**Comment by tara81** [comment]
I still have this issue , tried multiple builds: 

Build #35 (Mar 2, 2015 3:14:35 PM) 
Success Build #27 (Jan 31, 2015 2:39:05 PM) 
No luck, all mcmmo.users is gone every time after conversion

**Comment by t00thpick1** [comment]
This should be fixed now, I personally fixed and tested it.

**Comment by tara81** [comment]
indeed u did ty so much <3
