### ISSUE TITLE
WARN Task #8 for mcMMO v1.5.02-SNAPSHOT-b23 generated an exception

### ISSUE THREAD

**Issue by Sckaletz** [mcMMO-Dev/mcMMO#2417]
After updating to the latest Spigot build I'm receiving this error on all my servers with MCMMO installed.

http://pastebin.com/EbW91i9C

**Comment by WhiteNightFury** [comment]
[12:14:12 WARN]: [mcMMO] Task #6 for mcMMO v1.5.02-SNAPSHOT-b23 generated an exception
	java.lang.NullPointerException
			at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftCriteria.getFromNMS(CraftCriteria.java:42) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftObjective.<init>(CraftObjective.java:19) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftScoreboard.getObjective(CraftScoreboard.java:40) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getPowerLevelObjective(ScoreboardManager.java:373) ~[?:?]
			at com.gmail.nossr50.util.scoreboards.ScoreboardManager.powerLevelHeartbeat(ScoreboardManager.java:336) ~[?:?]
			at com.gmail.nossr50.runnables.player.PowerLevelUpdatingTask.run(PowerLevelUpdatingTask.java:10) ~[?:?]
			at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:653) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
	[12:14:14 WARN]: [mcMMO] Task #6 for mcMMO v1.5.02-SNAPSHOT-b23 generated an exception
	java.lang.NullPointerException
			at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftCriteria.getFromNMS(CraftCriteria.java:42) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftObjective.<init>(CraftObjective.java:19) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftScoreboard.getObjective(CraftScoreboard.java:40) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getPowerLevelObjective(ScoreboardManager.java:373) ~[?:?]
			at com.gmail.nossr50.util.scoreboards.ScoreboardManager.powerLevelHeartbeat(ScoreboardManager.java:336) ~[?:?]
			at com.gmail.nossr50.runnables.player.PowerLevelUpdatingTask.run(PowerLevelUpdatingTask.java:10) ~[?:?]
			at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:653) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-00eba53]
			at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by QuarkTheAwesome** [comment]
Happening for me too. Possible fix at http://www.spigotmc.org/threads/latest-spigot-builds-scoreboard-problems.44751/ . Crazy NPE spam on Spigot git-Spigot-fa7cbf9-00eba53 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT).

**Comment by QuarkTheAwesome** [comment]
I fixed it on my fork (https://github.com/QuarkTheAwesome/mcMMO), hopefully this should be fixed in mainline soon too.

**Comment by WhiteNightFury** [comment]
Just got the latest version of bukkit using the spigot buildtools, problem seems to be solved, thanks for the info.

**Comment by t00thpick1** [comment]
This was a spigot issue,  I recommend updating spigot.
