### ISSUE TITLE
Many events resulting in exceptions

### ISSUE THREAD

**Issue by Zenexer** [mcMMO-Dev/mcMMO#2425]
Example:

```
[16:37:44 ERROR]: Could not pass event AsyncPlayerChatEvent to mcMMO v1.5.00-b3547
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[server.jar:git-Spigot-b1e6da1-17962f6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-b1e6da1-17962f6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-b1e6da1-17962f6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-b1e6da1-17962f6]
        at net.minecraft.server.v1_8_R1.PlayerConnection.chat(PlayerConnection.java:1036) [server.jar:git-Spigot-b1e6da1-17962f6]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:975) [server.jar:git-Spigot-b1e6da1-17962f6]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [server.jar:git-Spigot-b1e6da1-17962f6]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:47) [server.jar:git-Spigot-b1e6da1-17962f6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_25]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_25]
        at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
        at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:83) ~[?:?]
        at com.gmail.nossr50.listeners.PlayerListener.onPlayerChat(PlayerListener.java:638) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor215.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[server.jar:git-Spigot-b1e6da1-17962f6]
        ... 12 more
```

Easy fix; I'll be sending a pull request shortly.

**Comment by TfT-02** [comment]
mcMMO v1.5.00 is outdated. Please update to our latest version.
