### ISSUE TITLE
Few errors on console, ill just leave em here

### ISSUE THREAD

**Issue by jcbjoe** [mcMMO-Dev/mcMMO#2429]
```
[19:33:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'party' in plugin mcMMO v1.5.01-b8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.datatypes.party.Party.createMembersList(Party.java:325) ~[?:?]
	at com.gmail.nossr50.commands.party.PartyInfoCommand.displayMemberInfo(PartyInfoCommand.java:124) ~[?:?]
	at com.gmail.nossr50.commands.party.PartyInfoCommand.onCommand(PartyInfoCommand.java:34) ~[?:?]
	at com.gmail.nossr50.commands.party.PartyCommand.onCommand(PartyCommand.java:87) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-612de46-07c2162]
	... 14 more

=============================================================================================================================================================================================================================================


[19:36:36] [Server thread/WARN]: [mcMMO] Task #3948 for mcMMO v1.5.01-b8 generated an exception
java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftScoreboardComponent.checkState(CraftScoreboardComponent.java:13) ~[spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftObjective.getScore(CraftObjective.java:99) ~[spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.updateSidebar(ScoreboardWrapper.java:415) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.access$000(ScoreboardWrapper.java:30) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper$ScoreboardQuickUpdate.run(ScoreboardWrapper.java:75) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

=============================================================================================================================================================================================================================================


[19:37:54] [Server thread/ERROR]: Could not pass event McMMOPlayerLevelUpEvent to mcMMO v1.5.01-b8
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at com.gmail.nossr50.util.EventUtils.handleLevelChangeEvent(EventUtils.java:71) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:508) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:482) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:445) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:435) [mcMMO.jar:?]
	at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:32) [mcMMO.jar:?]
	at com.gmail.nossr50.skills.mining.MiningManager.miningBlockCheck(MiningManager.java:61) [mcMMO.jar:?]
	at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:194) [mcMMO.jar:?]
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.a(PlayerInteractManager.java:215) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:602) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-612de46-07c2162]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
```

**Comment by TfT-02** [comment]
Should all be fixed on v1.5.02-b34 and the latest Spigot build.
If not, please comment below with a new error log and I will reopen this ticket!
