### ISSUE TITLE
mcMMP just stopped working

### ISSUE THREAD

**Issue by jonnnnnyutah** [mcMMO-Dev/mcMMO#2438]
I know you don't have an offical version for 1.8.1, but it has been working for me in the past.  I'll post the error message below, if there is a work around you know of I would be much appreciative.  

Thanks!

[16:51:31] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[16:51:31] [Server thread/INFO]: [mcMMO] Attempting connection to MySQL...
[16:51:31] [Server thread/INFO]: [mcMMO] Connection to MySQL was a success!
[16:51:31] [Server thread/INFO]: [mcMMO] Killing orphans
[16:51:38] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[16:51:38] [Server thread/WARN]: java.lang.ClassCastException: com.gmail.nossr50.datatypes.player.McMMOPlayer cannot be cast to com.gmail.nossr50.datatypes.player.McMMOPlayer
[16:51:38] [Server thread/WARN]: 	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94)
[16:51:38] [Server thread/WARN]: 	at com.gmail.nossr50.util.player.UserManager.getPlayers(UserManager.java:65)
[16:51:38] [Server thread/WARN]: 	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.<init>(ScoreboardWrapper.java:61)
[16:51:38] [Server thread/WARN]: 	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.create(ScoreboardWrapper.java:68)
[16:51:38] [Server thread/WARN]: 	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.setupPlayer(ScoreboardManager.java:149)
[16:51:38] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:165)
[16:51:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[16:51:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[16:51:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:51:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355)
[16:51:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315)
[16:51:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:743)
[16:51:38] [Server thread/WARN]: 	at org.bukkit.Bukkit.reload(Bukkit.java:534)
[16:51:38] [Server thread/WARN]: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23)
[16:51:38] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:51:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[16:51:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[16:51:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[16:51:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[16:51:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[16:51:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[16:51:38] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:51:38] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[16:51:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
[16:51:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[16:51:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[16:51:38] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[16:51:38] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:51:38] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[16:51:38] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
[16:51:45] [Server thread/ERROR]: Error occurred while enabling PreciousStones v9.7.1-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/nossr50/mcMMO
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.PermissionsManager.detectMcMMO(PermissionsManager.java:82) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.managers.PermissionsManager.<init>(PermissionsManager.java:60) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.onEnable(PreciousStones.java:146) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-47b1dff-f233e7d]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:744) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_67]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_67]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-47b1dff-f233e7d]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.mcMMO
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_67]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_67]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_67]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_67]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-47b1dff-f233e7d]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-47b1dff-f233e7d]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	... 25 more

**Comment by jonnnnnyutah** [comment]
Fixed it.. NVM
