### ISSUE TITLE
Some Players aren't being saved to database (mySql)

### ISSUE THREAD

**Issue by cindyker** [mcMMO-Dev/mcMMO#2443]
When they log in it says their player database can not be loaded.
[12:30:46 ERROR]: [mcMMO] Giving up on attempting to load the PlayerProfile for DrPepsii
[12:30:46 INFO]: [A] mcMMO was unable to load the player data for DrPepsii. Please inspect your database setup.

**Database Query for user with issue**
MariaDB [mcMMOSurvival]> select * from mcmmo_users where user like 'DrPepsii';
Empty set (0.00 sec)

Using the Inspect command on them causes this error:
org.bukkit.command.CommandException: Unhandled exception executing command 'inspect' in plugin mcMMO v1.5.02-SNAPSHOT-b26
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-sur.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-sur.jar:git-Spigot-952179b-e87122e]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-sur.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-sur.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-sur.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-sur.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-sur.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-sur.jar:git-Spigot-952179b-e87122e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-sur.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-sur.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-sur.jar:git-Spigot-952179b-e87122e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-sur.jar:git-Spigot-952179b-e87122e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_31]
        at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
        at com.gmail.nossr50.util.player.UserManager.retrieveMcMMOPlayer(UserManager.java:108) ~[?:?]
        at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:90) ~[?:?]
        at com.gmail.nossr50.commands.player.InspectCommand.onCommand(InspectCommand.java:31) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-sur.jar:git-Spigot-952179b-e87122e]
        ... 14 more

I haven't figured out how to get them added yet.

**Comment by cindyker** [comment]
Ok I found this in my log, so it is failing to save players
[13:09:11 WARN]: [mcMMO] PlayerProfile saving failed for player: AdverseDuke11 0e91305d-89ed-4b42-a7a0-6cca93bb807e

Still haven't figured out why.

**Comment by t00thpick1** [comment]
should not be the case in current versions of mcMMO
