### ISSUE TITLE
Can't use two commands one after another

### ISSUE THREAD

**Issue by lanky5544** [mcMMO-Dev/mcMMO#2479]
When I use /acrobatics firstly that works fine but after that I try /mining and that Say "An internal Error has occurred....etc." and I check the log and console and this is the error I get
```
02.03 11:04:41 [Server] INFO ... 14 more
02.03 11:04:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at com.gmail.nossr50.commands.skills.SkillCommand.onCommand(SkillCommand.java:68) ~[?:?]
02.03 11:04:41 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerSkillScoreboard(ScoreboardManager.java:244) ~[?:?]
02.03 11:04:41 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSkill(ScoreboardWrapper.java:288) ~[?:?]
02.03 11:04:41 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:374) ~[?:?]
02.03 11:04:41 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftObjective.unregister(CraftObjective.java:104) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
02.03 11:04:41 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]
02.03 11:04:41 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_05]
02.03 11:04:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_05]
02.03 11:04:41 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
02.03 11:04:41 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mining' in plugin mcMMO v1.5.02-b35 
```
this has been in the last two MCMMO releases, it doesn't matter what two commands I used, i still get a similar error telling me pretty much the same thing.

**Comment by TfT-02** [comment]
Are you still having this issue? Have you tried updating Spigot and mcMMO to their latest available versions?

**Comment by t00thpick1** [comment]
This was a spigot issue
