### ISSUE TITLE
Could not initialize class com.gmail.nossr50.datatypes.skills.SkillType

### ISSUE THREAD

**Issue by WauloK** [mcMMO-Dev/mcMMO#2495]
[00:11:47] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[00:11:47] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[00:11:47] [Server thread/INFO]: [mcMMO] Please do not replace the mcMMO jar while the server is running.
[00:11:47] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[00:11:47] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.gmail.nossr50.datatypes.skills.SkillType
        at com.gmail.nossr50.config.AdvancedConfig.getMaxChance(AdvancedConfig.java:651) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.validateKeys(AdvancedConfig.java:47) ~[?:?]
        at com.gmail.nossr50.config.ConfigLoader.validate(ConfigLoader.java:62) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:21) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:26) ~[?:?]
        at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:51) ~[?:?]
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:203) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:392) [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:459) [ayq.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:350) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by t00thpick1** [comment]
Sounds like the jar was moved or replaced during runtime

**Comment by WauloK** [comment]
Hi.

No. I haven't moved it during runtime. This is the message after a boot. I don't move plugins while the server is on.

**Comment by t00thpick1** [comment]
Then its a corrupted jar, redownload and try again.
