### ISSUE TITLE
Error McMMO

### ISSUE THREAD

**Issue by alundra009** [mcMMO-Dev/mcMMO#2555]
Bukkit version: git-Spigot-c3c767f-33d5de3 (MC: 1.8)
Java version: 1.7.0_72 Oracle Corporation
Operating system: Linux 2.6.32-504.3.3.el6.x86_64 amd64

Last Severe error message: 
[01:13:30] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO v1.5.03-SNAPSHOT-b46
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:85) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:538) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:451) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:570) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.EntityLiving.d(EntityLiving.java:1096) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.EntityLiving.damageEntity(EntityLiving.java:737) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.EntityMonster.damageEntity(EntityMonster.java:44) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.EntityArrow.s_(EntityArrow.java:244) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1604) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.World.g(World.java:1579) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1422) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:772) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.7.0_72]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processArcheryCombat(CombatUtils.java:169) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:285) ~[?:?]
	at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:221) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor386.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	... 20 more
[01:13:40] [User Authenticator #31/INFO]: UUID of player semiboyHD is 3b1c91a8-9977-3286-9027-68fce6cf0755
[01:13:40] [Server thread/INFO]: semiboyHD[/124.6.181.194:33499] logged in with entity id 214663 at ([sanctuary] 256.69999998807907, 49.0, 391.69999998807907)
[01:13:40] [Craft Scheduler Thread - 579/INFO]: [GAListener] Player: semiboyHD has 9 votes
[01:13:44] [Server thread/INFO]: semiboyHD issued server command: /login france
[01:13:45] [Server thread/INFO]: [LoginSecurity] semiboyHD authenticated
[01:14:40] [Server thread/INFO]: Please wait as we generate the report

**Comment by t00thpick1** [comment]
Reproduce on an online mode server, otherwise I can't be sure this is an issue
