### ISSUE TITLE
New severe error

### ISSUE THREAD

**Issue by alundra009** [mcMMO-Dev/mcMMO#2573]
Last Severe error message: 
[03:10:18] [Server thread/ERROR]: Could not pass event McMMOPlayerLevelUpEvent to mcMMO v1.5.03-SNAPSHOT-b46
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at com.gmail.nossr50.util.EventUtils.handleLevelChangeEvent(EventUtils.java:70) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:508) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:482) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:445) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:435) [mcMMO.jar:?]
	at com.gmail.nossr50.runnables.skills.AwardCombatXpTask.run(AwardCombatXpTask.java:42) [mcMMO.jar:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.scoreboard.CraftObjective.unregister(CraftObjective.java:104) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:374) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSkill(ScoreboardWrapper.java:288) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerSkillLevelUpScoreboard(ScoreboardManager.java:258) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.handleLevelUp(ScoreboardManager.java:214) ~[?:?]
	at com.gmail.nossr50.listeners.SelfListener.onPlayerLevelUp(SelfListener.java:24) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
	... 16 more

**Comment by t00thpick1** [comment]
This was a spigot issue,  changing the version of spigot you use should resolve this
