### ISSUE TITLE
Asynchronous thread exeptions

### ISSUE THREAD

**Issue by xwct** [mcMMO-Dev/mcMMO#2656]
Keep getting these errors with the latest craftbukkit build from spigot build(craftbukkit-1.8.8-R0.1-SNAPSHOT.jar) and build #67 of mcmmo, nothing else than mcmmo on the server.
```
[01:10:33] [pool-3-thread-30/WARN]: Exception in thread "pool-3-thread-30" 
[01:10:33] [pool-3-thread-30/WARN]: org.apache.commons.lang.UnhandledException: Plugin mcMMO v1.5.04-SNAPSHOT-b67 generated an exception while executing task 9
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.gmail.nossr50.metrics.mcstats.Metrics.postPlugin(Metrics.java:502)
	at com.gmail.nossr50.metrics.mcstats.Metrics.access$500(Metrics.java:45)
	at com.gmail.nossr50.metrics.mcstats.Metrics$1.run(Metrics.java:353)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

[01:10:33] [pool-3-thread-31/WARN]: Exception in thread "pool-3-thread-31" 
[01:10:33] [pool-3-thread-31/WARN]: org.apache.commons.lang.UnhandledException: Plugin EMetrics v0.0.4 generated an exception while executing task 8
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.gmail.nossr50.metrics.mcstats.Metrics.postPlugin(Metrics.java:502)
	at com.gmail.nossr50.metrics.mcstats.Metrics.access$500(Metrics.java:45)
	at com.gmail.nossr50.metrics.mcstats.Metrics$1.run(Metrics.java:353)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

**Comment by t00thpick1** [comment]
Disable metrics I guess?
