### ISSUE TITLE
/skillreset and /mmoedit don't work for Smelting and Salvage

### ISSUE THREAD

**Issue by Drakorle** [mcMMO-Dev/mcMMO#2658]
Hello,
When I do these command, I get this error:

[15:55:41] [Server thread/INFO]: Drakorle issued server command: /skillreset smelting
[15:55:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'skillreset' in plugin mcMMO v1.5.03-b66
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_40]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at java.lang.Thread.run(Thread.java:724) [?:1.7.0_40]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.datatypes.player.PlayerProfile.getSkillXpLevelRaw(PlayerProfile.java:198) ~[?:?]
	at com.gmail.nossr50.commands.experience.SkillresetCommand.handleCommand(SkillresetCommand.java:114) ~[?:?]
	at com.gmail.nossr50.commands.experience.SkillresetCommand.editValues(SkillresetCommand.java:166) ~[?:?]
	at com.gmail.nossr50.commands.experience.SkillresetCommand.onCommand(SkillresetCommand.java:48) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	... 15 more

Thanks.

**Comment by bm01** [comment]
Smelting and Salvage are child skills, their level is the average of their parent skills and don't have experience on their own. In short, you need to reset parent skills.

**Comment by Drakorle** [comment]
Ok, that was why I thounk, but so, why /addxp work for these skill if u cant modify their level with command ?

**Comment by t00thpick1** [comment]
They aren't real skills and don't have  EXP or levels truly, to modify them you must modify the levels they are based off of
