### ISSUE TITLE
KCauldron can't load mcMMO

### ISSUE THREAD

**Issue by bangbang93** [mcMMO-Dev/mcMMO#2678]
[16:10:44] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.04-SNAPSHOT-b67
[16:10:44] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[16:10:44] [Server thread/INFO]: [mcMMO] Please do not replace the mcMMO jar while the server is running.
[16:10:44] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.04-SNAPSHOT-b67
[16:10:44] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.04-SNAPSHOT-b67 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.gmail.nossr50.datatypes.skills.SkillType
        at com.gmail.nossr50.config.AdvancedConfig.getMaxChance(AdvancedConfig.java:693) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.validateKeys(AdvancedConfig.java:48) ~[?:?]
        at com.gmail.nossr50.config.ConfigLoader.validate(ConfigLoader.java:62) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:22) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:27) ~[?:?]
        at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:51) ~[?:?]
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:214) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[JavaPlugin.class:1.7.10-1492.152]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:392) [JavaPluginLoader.class:1.7.10-1492.152]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [SimplePluginManager.class:1.7.10-1492.152]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:204) [mcMMO.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-1492.152]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1492.152]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1492.152]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1492.152]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1492.152]
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]

Server jar is KCauldron-1.7.10-1492.152-server.jar

**Comment by bm01** [comment]
Looks like you have a corrupted .jar or you tried to replace it while the server was running, hence the NoClassDefFoundError.

**Comment by bangbang93** [comment]
my server is in booting.So I didn't replace any jar.
jar file md5:b85cb92269ab21f1b83e8ac0b56e5ffe

**Comment by clive9455** [comment]
was a fix ever found for this?
