### ISSUE TITLE
mcMMO error: Could not pass event BlockBreakEvent to mcMMO

### ISSUE THREAD

**Issue by smartmadio** [mcMMO-Dev/mcMMO#2744]
```
[22:31:47] [Server thread/ERROR]: Could not pass event BlockBreakEvent to mcMMO v1.5.04-SNAPSHOT-b82
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-da8379f]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-da8379f]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-da8379f]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-da8379f]
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [spigot.jar:git-Spigot-db6de12-da8379f]
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:189) [spigot.jar:git-Spigot-db6de12-da8379f]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623) [spigot.jar:git-Spigot-db6de12-da8379f]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-db6de12-da8379f]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-db6de12-da8379f]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-da8379f]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-da8379f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-da8379f]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-da8379f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-da8379f]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-da8379f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.OutOfMemoryError: Java heap space
```

Spigot 1.8.8 & Java8

**Comment by EvilOlaf** [comment]
`Caused by: java.lang.OutOfMemoryError: Java heap space`
Allocate more RAM to your server or remove stuff that needs much memory.

**Comment by smartmadio** [comment]
Thank you ,I'll have a try.

**Comment by smartmadio** [comment]
But this problem hasn't happened until I updated my mcMMO,strange.

**Comment by EvilOlaf** [comment]
May your server run at its limits earlier and now .... don't know ^^
