### ISSUE TITLE
DEV b97 config rebuild/rewrite error

### ISSUE THREAD

**Issue by leasoncre** [mcMMO-Dev/mcMMO#2797]
i assume this is related to the plugin re-writeing the config on updating:

changing/upgrading dev server (test server) from 1.5.04-SNAPSHOT-b82 /on/ 1.8.8 git-Spigot-e4d4710-e1ebe52
//-to-// 1.5.04-SNAPSHOT-b97 /on/ 1.9 git-Spigot-b1c1b55-7d330bc

`[20:50:52] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.04-SNAPSHOT-b97
[20:50:52] [Server thread/ERROR]: Cannot load plugins\mcMMO\config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 156, column 9:
            Anvil_Placed_#
            ^
could not find expected ':'
 in 'string', line 157, column 1:
    #  Settings for sounds
    ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:187) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:162) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at com.gmail.nossr50.util.LogFilter.<init>(LogFilter.java:13) [mcMMO%20b97.jar:?]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:133) [mcMMO%20b97.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 156, column 9:
            Anvil_Placed_#
            ^
could not find expected ':'
 in 'string', line 157, column 1:
    #  Settings for sounds
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	... 15 more`

it tries to fix it 3 times on server start/load, looks like the file re-write process has a bug. deleting the config.yml and generating a new one doesn't have this issue.

**Comment by t00thpick1** [comment]
Fixed
