### ISSUE TITLE
Dev b109 startup error

### ISSUE THREAD

**Issue by leasoncre** [mcMMO-Dev/mcMMO#2802]
git-Spigot-b1c1b55-7d330bc (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
mmcMMO version 1.5.04-SNAPSHOT-b109
mcMMO-WorldGuard version 1.0.2

```
[00:20:15] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[00:20:15] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
[00:20:15] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.loadPotion(PotionConfig.java:132)
[00:20:15] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.loadPotionMap(PotionConfig.java:97)
[00:20:15] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.loadKeys(PotionConfig.java:52)
[00:20:15] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.<init>(PotionConfig.java:38)
[00:20:15] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.getInstance(PotionConfig.java:43)
[00:20:15] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:406)
[00:20:15] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
[00:20:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[00:20:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[00:20:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:20:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[00:20:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[00:20:15] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
[00:20:15] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[00:20:15] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:20:15] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.PotionData
[00:20:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[00:20:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[00:20:15] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:20:15] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:20:15] [Server thread/WARN]: 	... 15 more
[00:20:15] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.04-SNAPSHOT-b109
[00:20:15] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.04-SNAPSHOT-b109 (Is it up to date?)
java.lang.NullPointerException
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:247) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:201) [mcMMO%20b109.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
```

**Comment by DorCoMaNdO** [comment]
Update Spigot.

**Comment by t00thpick1** [comment]
Update spigot

**Comment by leasoncre** [comment]
Thanks, that fixed it
Except this?: `[21:28:35] [Server thread/ERROR]: ThrownPotion entity 353 has no item?!`

git-Spigot-6f291ea-55a8535 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
mcMMO version 1.5.04-SNAPSHOT-b116

**Comment by t00thpick1** [comment]
Thats not mcMMO
