### ISSUE TITLE
McMMO (Build #98 - 110)

### ISSUE THREAD

**Issue by ChibbyHD** [mcMMO-Dev/mcMMO#2808]
[09:18:40] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.04-SNAPSHOT-b110
[09:18:40] [Server thread/WARN]: [mcMMO] Invalid material: POTION_POISON
[09:18:40] [Server thread/WARN]: [mcMMO] Potion format for Treasures.yml has changed
[09:18:40] [Server thread/WARN]: [mcMMO] Invalid material: POTION_INSTANT_HEAL
[09:18:40] [Server thread/WARN]: [mcMMO] Potion format for Treasures.yml has changed
[09:18:40] [Server thread/WARN]: [mcMMO] Invalid material: POTION_FIRE_RESISTANCE
[09:18:40] [Server thread/WARN]: [mcMMO] Potion format for Treasures.yml has changed
[09:18:40] [Server thread/WARN]: [mcMMO] Invalid material: POTION_SPEED
[09:18:40] [Server thread/WARN]: [mcMMO] Potion format for Treasures.yml has changed
[09:18:40] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: WATER
[09:18:40] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: AWKWARD
[09:18:40] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: THICK
[09:18:40] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: MUNDANE_POTION_EXTENDED
[09:18:40] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: MUNDANE_POTION
[09:18:40] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[09:18:40] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
[09:18:40] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.loadPotion(PotionConfig.java:132)
[09:18:40] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.loadPotionMap(PotionConfig.java:97)
[09:18:40] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.loadKeys(PotionConfig.java:52)
[09:18:40] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.<init>(PotionConfig.java:38)
[09:18:40] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.getInstance(PotionConfig.java:43)
[09:18:40] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:406)
[09:18:40] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
[09:18:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[09:18:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[09:18:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[09:18:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[09:18:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[09:18:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
[09:18:40] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[09:18:40] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[09:18:40] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.PotionData
[09:18:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[09:18:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[09:18:40] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:18:40] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:18:40] [Server thread/WARN]: 	... 15 more
[09:18:40] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.04-SNAPSHOT-b110
[09:18:40] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.04-SNAPSHOT-b110 (Is it up to date?)
java.lang.NullPointerException
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:247) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d73fbb]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.9.jar:git-Spigot-b1c1b55-7d73fbb]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.9.jar:git-Spigot-b1c1b55-7d73fbb]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:201) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) [spigot-1.9.jar:git-Spigot-b1c1b55-7d73fbb]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-b1c1b55-7d73fbb]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-b1c1b55-7d73fbb]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-b1c1b55-7d73fbb]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-b1c1b55-7d73fbb]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.9.jar:git-Spigot-b1c1b55-7d73fbb]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-b1c1b55-7d73fbb]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]

**Comment by ChibbyHD** [comment]
I deleted the folder to see if that would fix it, and well it fixed McMMO not loading, but now there is this issue.

[09:26:49] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.04-SNAPSHOT-b110
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 832
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 1088
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 2112
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 2368
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 2880
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 3904
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 4416
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 5184
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 5440
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 5696
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 17216
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 17472
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 18496
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 18752
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 19264
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 20288
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 20800
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 21568
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 21824
[09:26:50] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 22080

**Comment by t00thpick1** [comment]
My default config has not been updated and certain data value potions do not exist in minecraft anymore.

**Comment by t00thpick1** [comment]
and the first errors were from outdated spigot which it looks like you resolved.

**Comment by ChibbyHD** [comment]
This server is running CraftBukkit version git-Spigot-6f291ea-6026dad (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

[09:58:31] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.04-SNAPSHOT-b110
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 832
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 1088
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 2112
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 2368
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 2880
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 3904
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 4416
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 5184
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 5440
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 5696
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 17216
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 17472
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 18496
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 18752
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 19264
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 20288
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 20800
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 21568
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 21824
[09:58:32] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 22080

**Comment by ChibbyHD** [comment]
Is this gonna be fixed soon? (:

**Comment by t00thpick1** [comment]
This is a configuration issue,  check back later today I should have an updated config for you
