### ISSUE TITLE
Error while enabling mcMMO

### ISSUE THREAD

**Issue by FatherWh0** [mcMMO-Dev/mcMMO#2820]
With the #116 (Mar 12, 2016 5:56:51 PM) build the following error occurred:

[02:52:52] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.04-SNAPSHOT-b115
[02:52:53] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[02:52:53] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
[02:52:53] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.loadPotion(PotionConfig.java:132)
[02:52:53] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.loadPotionMap(PotionConfig.java:97)
[02:52:53] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.loadKeys(PotionConfig.java:52)
[02:52:53] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.<init>(PotionConfig.java:38)
[02:52:53] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.alchemy.PotionConfig.getInstance(PotionConfig.java:43)
[02:52:53] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:406)
[02:52:53] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
[02:52:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[02:52:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[02:52:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[02:52:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[02:52:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[02:52:53] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
[02:52:53] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[02:52:53] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:52:53] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.PotionData
[02:52:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[02:52:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[02:52:53] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[02:52:53] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[02:52:53] [Server thread/WARN]: 	... 15 more
[02:52:53] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.04-SNAPSHOT-b115

It might be relevant that it loaded without error on my home system but broke on my provider's server. According to worldguard's report the provider is running java ver 1.7.0.

**Comment by t00thpick1** [comment]
update spigot
