### ISSUE TITLE
Issue caused when also running Jobs plug-in

### ISSUE THREAD

**Issue by t-train** [mcMMO-Dev/mcMMO#2833]
New I see a lot similar to this but unable to find a clear answer. I think the error is mcmmo related because when I disable mcmmo the error goes away, of course I'm trying to find out if there is a workable solution...

`[12:36:39] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Jobs v2.63.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.a(PlayerInteractManager.java:215) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:602) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NoClassDefFoundError: com/gmail/nossr50/api/AbilityAPI
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:323) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.api.AbilityAPI
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_66]
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onBlockBreak(JobsPaymentListener.java:323) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	... 16 more`

**Comment by t00thpick1** [comment]
Use our last 1.8 compatable build, it should have a listing on the spigot page.  The latest build is 1.9 only
