### ISSUE TITLE
Blockbreak event causing error

### ISSUE THREAD

**Issue by jenks1999** [mcMMO-Dev/mcMMO#2836]
[07:59:59] [Server thread/ERROR]: Could not pass event BlockBreakEvent to mcMMO v1.5.05-SNAPSHOT-b127
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:193) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:832) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.IllegalArgumentException: Material cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftInventory.contains(CraftInventory.java:132) ~[spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	at com.gmail.nossr50.skills.herbalism.HerbalismManager.processGreenThumbPlants(HerbalismManager.java:329) ~[?:?]
	at com.gmail.nossr50.skills.herbalism.HerbalismManager.herbalismBlockCheck(HerbalismManager.java:151) ~[?:?]
	at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:233) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_server.jar:git-Spigot-23e921f-8b69bdd]
	... 17 more

**Comment by t00thpick1** [comment]
Fixed
