### ISSUE TITLE
EventException - Could not pass event BlockBreakEvent to mcMMO

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#2841]
McMMO dev 127.
PaperSpigot dev 527.
```
[22:25:49] [Server thread/ERROR]: Could not pass event BlockBreakEvent to mcMMO v1.5.05-SNAPSHOT-b127
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.jar:git-Paper-527]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.jar:git-Paper-527]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-527]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-527]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-527]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) [patched_1.9.jar:git-Paper-527]
	at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) [patched_1.9.jar:git-Paper-527]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:847) [patched_1.9.jar:git-Paper-527]
	at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [patched_1.9.jar:git-Paper-527]
	at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [patched_1.9.jar:git-Paper-527]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-527]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-527]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-527]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-527]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-527]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-527]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.IllegalArgumentException: Material cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.9.jar:git-Paper-527]
	at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftInventory.contains(CraftInventory.java:132) ~[patched_1.9.jar:git-Paper-527]
	at com.gmail.nossr50.skills.herbalism.HerbalismManager.processGreenThumbPlants(HerbalismManager.java:329) ~[?:?]
	at com.gmail.nossr50.skills.herbalism.HerbalismManager.herbalismBlockCheck(HerbalismManager.java:151) ~[?:?]
	at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:233) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor42.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.jar:git-Paper-527]
	... 18 more
```

**Comment by t00thpick1** [comment]
Fixed
