### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to mcMMO

### ISSUE THREAD

**Issue by PhanaticD** [mcMMO-Dev/mcMMO#2842]
```
[11:22:08] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO v1.5.05-SNAPSHOT-b127
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.jar:git-Paper-531]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.jar:git-Paper-531]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-531]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-531]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-531]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [patched_1.9.jar:git-Paper-531]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:570) [patched_1.9.jar:git-Paper-531]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [patched_1.9.jar:git-Paper-531]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:602) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity0(EntityLiving.java:1217) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity0(EntityHuman.java:840) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:827) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity(EntityHuman.java:764) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.EntityPlayer.damageEntity(EntityPlayer.java:520) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.EntityHuman.attack(EntityHuman.java:1000) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.EntityPlayer.attack(EntityPlayer.java:1160) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1608) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-531]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-531]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-531]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at com.gmail.nossr50.util.ItemUtils.isHelmet(ItemUtils.java:171) ~[?:?]
    at com.gmail.nossr50.util.ItemUtils.isArmor(ItemUtils.java:259) ~[?:?]
    at com.gmail.nossr50.skills.axes.Axes.hasArmor(Axes.java:28) ~[?:?]
    at com.gmail.nossr50.skills.axes.AxesManager.canImpact(AxesManager.java:38) ~[?:?]
    at com.gmail.nossr50.util.skills.CombatUtils.processAxeCombat(CombatUtils.java:97) ~[?:?]
    at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:250) ~[?:?]
    at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:238) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor57.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.jar:git-Paper-531]
    ... 27 more
```

**Comment by TheBentoBox** [comment]
I'm still getting this occassionally http://pastebin.com/efyb6Hw6. I'm using the newest beta build, but I haven't updated Spigot in about 1.5 days. Could that be the issue?
