### ISSUE TITLE
mcMMO Issue [fixed]

### ISSUE THREAD

**Issue by Dragonslayer93** [mcMMO-Dev/mcMMO#2864]
11:06:06] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.05-SNAPSHOT-b133
[11:06:06] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[11:06:06] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
[11:06:06] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreaures(TreasureConfig.java:257)
[11:06:06] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:139)
[11:06:06] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:76)
[11:06:06] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:82)
[11:06:06] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:381)
[11:06:06] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:141)
[11:06:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[11:06:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[11:06:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:06:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[11:06:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[11:06:06] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
[11:06:06] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[11:06:06] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[11:06:06] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.PotionData
[11:06:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[11:06:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[11:06:06] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:06:06] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[11:06:06] [Server thread/WARN]: 	... 14 more
[11:06:06] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.05-SNAPSHOT-b133
[11:06:06] [Server thread/ERROR]: [mcMMO] Cannot read C:\Users\THRI-SERVER\Desktop\Minecraft_Server\Minecraft_Server Kopie\plugins\mcMMO\experience.yml(File Permissions?)
[11:06:06] [Server thread/ERROR]: [mcMMO] Cannot read C:\Users\THRI-SERVER\Desktop\Minecraft_Server\Minecraft_Server Kopie\plugins\mcMMO\repair.vanilla.yml(File Permissions?)
[11:06:06] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.05-SNAPSHOT-b133 (Is it up to date?)
java.lang.NullPointerException
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:241) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[spigot_server.jar:git-Spigot-b1c1b55-dd016e7]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot_server.jar:git-Spigot-b1c1b55-dd016e7]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot_server.jar:git-Spigot-b1c1b55-dd016e7]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:195) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) [spigot_server.jar:git-Spigot-b1c1b55-dd016e7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_server.jar:git-Spigot-b1c1b55-dd016e7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_server.jar:git-Spigot-b1c1b55-dd016e7]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot_server.jar:git-Spigot-b1c1b55-dd016e7]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot_server.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot_server.jar:git-Spigot-b1c1b55-dd016e7]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot_server.jar:git-Spigot-b1c1b55-dd016e7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
[11:06:06] [Server thread/INFO]: [Vault] Enabling Vault v1.5.6-b49

**Comment by Dragonslayer93** [comment]
newest Build: #133 (27.03.2016 12:46:14)
Spigot also updated to the newest version with BuildToolsUpdater

**Comment by Dragonslayer93** [comment]
Already fixed. For all with this problem. Update your spigot server and it will work.
