### ISSUE TITLE
Admin Chat "Async" event problem!

### ISSUE THREAD

**Issue by FabioZumbi12** [mcMMO-Dev/mcMMO#2937]
When i try to use the admin chat i have this:

`[05:55:35 ERROR]: Could not pass event AsyncPlayerChatEvent to mcMMO v1.5.05-SNAPSHOT-b136
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.4.jar:git-Paper-748]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.9.4.jar:git-Paper-748]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-748]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.4.jar:git-Paper-748]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.9.4.jar:git-Paper-748]
        at net.minecraft.server.v1_9_R2.PlayerConnection.chat(PlayerConnection.java:1302) [patched_1.9.4.jar:git-Paper-748]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1217) [patched_1.9.4.jar:git-Paper-748]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.9.4.jar:git-Paper-748]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_91]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Asynchronous Async Player Chunk Add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[patched_1.9.4.jar:git-Paper-748]
        at net.minecraft.server.v1_9_R2.PlayerChunkMap.a(PlayerChunkMap.java:425) ~[patched_1.9.4.jar:git-Paper-748]
        at net.minecraft.server.v1_9_R2.PlayerChunk.a(PlayerChunk.java:163) ~[patched_1.9.4.jar:git-Paper-748]
        at net.minecraft.server.v1_9_R2.PlayerChunkMap.flagDirty(PlayerChunkMap.java:255) ~[patched_1.9.4.jar:git-Paper-748]
        at net.minecraft.server.v1_9_R2.WorldManager.a(WorldManager.java:43) ~[patched_1.9.4.jar:git-Paper-748]
        at net.minecraft.server.v1_9_R2.World.notify(World.java:472) ~[patched_1.9.4.jar:git-Paper-748]
        at net.minecraft.server.v1_9_R2.TileEntityCommand$1.i(TileEntityCommand.java:35) ~[patched_1.9.4.jar:git-Paper-748]
        at net.minecraft.server.v1_9_R2.CommandBlockListenerAbstract.sendMessage(CommandBlockListenerAbstract.java:271) ~[patched_1.9.4.jar:git-Paper-748]
        at org.bukkit.craftbukkit.v1_9_R2.command.CraftBlockCommandSender.sendMessage(CraftBlockCommandSender.java:27) ~[patched_1.9.4.jar:git-Paper-748]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.broadcast(CraftServer.java:1318) ~[patched_1.9.4.jar:git-Paper-748]
        at com.gmail.nossr50.chat.AdminChatManager.sendMessage(AdminChatManager.java:20) ~[?:?]
        at com.gmail.nossr50.chat.ChatManager.handleChat(ChatManager.java:35) ~[?:?]
        at com.gmail.nossr50.chat.AdminChatManager.handleChat(AdminChatManager.java:15) ~[?:?]
        at com.gmail.nossr50.chat.ChatManager.handleChat(ChatManager.java:43) ~[?:?]
        at com.gmail.nossr50.listeners.PlayerListener.onPlayerChat(PlayerListener.java:667) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.4.jar:git-Paper-748]
        ... 12 more`

And the message is sent to both chats, public and admin!
Using Build #136 (28/04/2016 10:31:32) and tested with no other chat plugins.

**Comment by FatherWh0** [comment]
Same issue here. Btw you can use /ac <txt> without errors. The error occurs when admin chat is toggled on.
