### ISSUE TITLE
mcmmo not working

### ISSUE THREAD

**Issue by mappiemapijs** [mcMMO-Dev/mcMMO#2984]
i tried to install mcmmo on my craftbukkit server by just dragging it into the plugins folder, but an error occurs:

[http://imgur.com/61rcbi3](url)

^ a printscreen of my log, because the code below looks quite messy

`[14:50:38] [Server thread/INFO]: Starting minecraft server version 1.10.2
[14:50:39] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-0ebb9c7 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[14:50:39] [Server thread/INFO]: [mcMMO] Loading mcMMO v1.5.00-b3547
[14:50:39] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[14:50:39] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[14:50:39] [Server thread/WARN]: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
[14:50:39] [Server thread/WARN]:    at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:163)
[14:50:39] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[14:50:39] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[14:50:39] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[14:50:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:347)
[14:50:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:319)
[14:50:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.<init>(CraftServer.java:257)
[14:50:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.PlayerList.<init>(PlayerList.java:70)
[14:50:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedPlayerList.<init>(SourceFile:14)
[14:50:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:183)
[14:50:39] [Server thread/WARN]:    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:517)
[14:50:39] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
[14:50:39] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[14:50:39] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:53) ~[?:?]
    at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:204) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[craftbukkit.jar:git-Bukkit-0ebb9c7]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:356) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:347) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:319) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.<init>(CraftServer.java:257) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at net.minecraft.server.v1_10_R1.PlayerList.<init>(PlayerList.java:70) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at net.minecraft.server.v1_10_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:183) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit.jar:git-Bukkit-0ebb9c7]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
[14:50:39] [Server thread/INFO]: Preparing level "world"
[14:50:39] [Server thread/INFO]: Preparing start region for level 0 (Seed: -6046780064058051467)
[14:50:40] [Server thread/INFO]: Preparing spawn area: 77%
[14:50:41] [Server thread/INFO]: Preparing start region for level 1 (Seed: 2616010617041015684)
[14:50:42] [Server thread/INFO]: Preparing start region for level 2 (Seed: 2616010617041015684)
[14:50:42] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:50:42] [Server thread/INFO]: Done (2.645s)! For help, type "help" or "?"`

**Comment by mappiemapijs** [comment]
fixed, i didn't know mcmmo 1.5 was for minecraft 1.8.9
