### ISSUE TITLE
Cannot read...

### ISSUE THREAD

**Issue by XryanXnyanX** [mcMMO-Dev/mcMMO#2986]
[16:51:46 INFO]: [mcMMO] Enabling mcMMO v1.5.06-SNAPSHOT-b145
[16:51:46 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[16:51:46 WARN]: java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
[16:51:46 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreaures(TreasureConfig.java:258)
[16:51:46 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:143)
[16:51:46 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:80)
[16:51:46 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:86)
[16:51:46 WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:381)
[16:51:46 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:141)
[16:51:46 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
[16:51:46 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[16:51:46 WARN]:        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:141)
[16:51:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:51:46 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[16:51:46 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[16:51:46 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
[16:51:46 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[16:51:46 WARN]:        at java.lang.Thread.run(Thread.java:745)
[16:51:46 WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.PotionData
[16:51:46 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[16:51:46 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[16:51:46 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[16:51:46 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[16:51:46 WARN]:        ... 15 more
[16:51:46 INFO]: [mcMMO] Disabling mcMMO v1.5.06-SNAPSHOT-b145
[16:51:47 ERROR]: [mcMMO] Cannot read /home/gs/gs/data/servers/3414649/plugins/mcMMO/experience.yml(File Permissions?)
[16:51:47 ERROR]: [mcMMO] Cannot read /home/gs/gs/data/servers/3414649/plugins/mcMMO/repair.vanilla.yml(File Permissions?)
[16:51:47 ERROR]: Error occurred while disabling mcMMO v1.5.06-SNAPSHOT-b145 (Is it up to date?)
java.lang.NullPointerException
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:241) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[spigot-1.9.jar:git-Spigot-1a196e1-6f032cd]

**Comment by JayGamer128** [comment]
wtf?

**Comment by JayGamer128** [comment]
what can you not read?
