### ISSUE TITLE
IndexOutOfBoundsException: Index: 0

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#2987]
```
[03:19:43] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.06-SNAPSHOT-b145
[03:19:43] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.06-SNAPSHOT-b145 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0
    at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.8.0_92]
    at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
    at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:55) ~[?:?]
    at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[patched_1.10.2.jar:git-Paper-818]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:347) [patched_1.10.2.jar:git-Paper-818]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [patched_1.10.2.jar:git-Paper-818]
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [patched_1.10.2.jar:git-Paper-818]
    at org.bukkit.plugin.SimplePluginManager.clearPlugins(SimplePluginManager.java:473) [patched_1.10.2.jar:git-Paper-818]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.reload(CraftServer.java:742) [patched_1.10.2.jar:git-Paper-818]
    at org.bukkit.Bukkit.reload(Bukkit.java:556) [patched_1.10.2.jar:git-Paper-818]
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:43) [patched_1.10.2.jar:git-Paper-818]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) [patched_1.10.2.jar:git-Paper-818]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665) [patched_1.10.2.jar:git-Paper-818]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:628) [patched_1.10.2.jar:git-Paper-818]
    at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:442) [patched_1.10.2.jar:git-Paper-818]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:405) [patched_1.10.2.jar:git-Paper-818]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [patched_1.10.2.jar:git-Paper-818]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [patched_1.10.2.jar:git-Paper-818]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
```

**Comment by mibby** [comment]
Still occurring rarely on build 173.
https://ci.drtshock.net/job/mcMMO/
```
[19:52:47] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.07-SNAPSHOT-b${BUILD_NUMBER}
[19:52:47] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.07-SNAPSHOT-b${BUILD_NUMBER} (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_102]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:55) ~[?:?]
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[patched_1.10.2.jar:git-Paper-854]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.10.2.jar:git-Paper-854]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [patched_1.10.2.jar:git-Paper-854]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [patched_1.10.2.jar:git-Paper-854]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.disablePlugins(CraftServer.java:344) [patched_1.10.2.jar:git-Paper-854]
	at net.minecraft.server.v1_10_R1.MinecraftServer.stop(MinecraftServer.java:460) [patched_1.10.2.jar:git-Paper-854]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:667) [patched_1.10.2.jar:git-Paper-854]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by mibby** [comment]
Bump.

```
[07:00:25] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.08-SNAPSHOT (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_141]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:55) ~[?:?]
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:210) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.jar:git-Paper-1153]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.jar:git-Paper-1153]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [patched_1.12.jar:git-Paper-1153]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [patched_1.12.jar:git-Paper-1153]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:348) [patched_1.12.jar:git-Paper-1153]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:485) [patched_1.12.jar:git-Paper-1153]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:700) [patched_1.12.jar:git-Paper-1153]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```
