### ISSUE TITLE
Caused by: java.lang.NoSuchFieldError: LEVEL_UP

### ISSUE THREAD

**Issue by Punisher-biz** [mcMMO-Dev/mcMMO#2995]
The error appears all the time, full error:

```
[18:07:44 ERROR]: Could not pass event BlockBreakEvent to mcMMO v1.5.04-SNAPSHOT-b${BUILD_NUMBER}               
org.bukkit.event.EventException                                                                                 
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-
078e2f8-9ff3d7f]                                                                                                
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-07
8e2f8-9ff3d7f]                                                                                                  
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-
078e2f8-9ff3d7f]                                                                                                
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-
078e2f8-9ff3d7f]                                                                                                
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:293) [serve
r.jar:git-Spigot-078e2f8-9ff3d7f]                                                                               
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:219) [server.jar:git
-Spigot-078e2f8-9ff3d7f]                                                                                        
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:848) [server.jar:git-Spigot-07
8e2f8-9ff3d7f]                                                                                                  
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockDig.a(SourceFile:40) [server.jar:git-Spigot-078e2f8-9f
f3d7f]                                                                                                          
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockDig.a(SourceFile:10) [server.jar:git-Spigot-078e2f8-9f
f3d7f]                                                                                                          
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-078e2
f8-9ff3d7f]                                                                                                     
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]                 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]                                
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [server.jar:git-Spigot-078e2f8-9ff3d7f]   
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [server.jar:git-Spigot-078e
2f8-9ff3d7f]                                                                                                    
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git-Spigot-078e
2f8-9ff3d7f]                                                                                                    
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git-Spigot-078e
2f8-9ff3d7f]                                                                                                    
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:git-Spigot-07
8e2f8-9ff3d7f]                                                                                                  
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]                                                   
Caused by: java.lang.NoSuchFieldError: LEVEL_UP                                                                 
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:507) ~[?:?]                  
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:476) ~[?:?]              
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:439) ~[?:?]      
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:429) ~[?:?]              
        at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:32) ~[?:?]                       
        at com.gmail.nossr50.skills.woodcutting.WoodcuttingManager.woodcuttingBlockCheck(WoodcuttingManager.java
:67) ~[?:?]                                                                                                     
        at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:253) ~[?:?]                
        at sun.reflect.GeneratedMethodAccessor805.invoke(Unknown Source) ~[?:?]                                 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]  
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]                                       
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-
078e2f8-9ff3d7f]                                                                                                
        ... 17 more                                                                                             
>
```                                                                                      

Someone got this issue too? 

Kind regards
Punisher

**Comment by BrainlessBox** [comment]
I had that issue as well until I upgraded to 1.5.05.  That exact build that you have caused that error for me as well.
