### ISSUE TITLE
Mcmmo error

### ISSUE THREAD

**Issue by mcredragon** [mcMMO-Dev/mcMMO#3008]
I got this error when running mcmmo in my factions server.
[mcMMO] There was an error while enabling mcMMO!
[10:37:03 WARN]: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
[10:37:03 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:163)
[10:37:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[10:37:03 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[10:37:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:37:03 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
[10:37:03 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
[10:37:03 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203)
[10:37:03 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:540)
[10:37:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[10:37:03 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[10:37:03 ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:53) ~[?:?]
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:204) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[craftbukkit.jar:git-Spigot-9797151-301db84]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [craftbukkit.jar:git-Spigot-9797151-301db84]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [craftbukkit.jar:git-Spigot-9797151-301db84]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [craftbukkit.jar:git-Spigot-9797151-301db84]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-9797151-301db84]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-9797151-301db84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [craftbukkit.jar:git-Spigot-9797151-301db84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [craftbukkit.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [craftbukkit.jar:git-Spigot-9797151-301db84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:540) [craftbukkit.jar:git-Spigot-9797151-301db84]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by EvilOlaf** [comment]
Update mcmmo.
