### ISSUE TITLE
Mcmmo on 1.8.8

### ISSUE THREAD

**Issue by SmokinHigh** [mcMMO-Dev/mcMMO#3030]
Hey, im running spigot 1.8.8 using viaversion and all that.

But i have a problem with mcmmo, i hope anyone can help me with this (Sorry for the long code, lol)

[02:41:09] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.07-SNAPSHOT-b${BUILD_NUMBER}
[02:41:09] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[02:41:09] [Server thread/WARN]: java.lang.NoSuchFieldError: MENDING
[02:41:09] [Server thread/WARN]: 	at com.gmail.nossr50.util.EnchantmentUtils.<clinit>(EnchantmentUtils.java:34)
[02:41:09] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadEnchantments(TreasureConfig.java:461)
[02:41:09] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:139)
[02:41:09] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:80)
[02:41:09] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:86)
[02:41:09] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:381)
[02:41:09] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:141)
[02:41:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[02:41:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[02:41:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[02:41:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[02:41:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[02:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[02:41:09] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[02:41:09] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:41:09] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.07-SNAPSHOT-b${BUILD_NUMBER}
[02:41:09] [Server thread/ERROR]: [mcMMO] Cannot read C:\TCAFiles\Users\krilleh94\7\plugins\mcMMO\experience.yml(File Permissions?)
[02:41:09] [Server thread/ERROR]: [mcMMO] Cannot read C:\TCAFiles\Users\krilleh94\7\plugins\mcMMO\repair.vanilla.yml(File Permissions?)
[02:41:09] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.07-SNAPSHOT-b${BUILD_NUMBER} (Is it up to date?)
java.lang.NullPointerException
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:241) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:195) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by EvilOlaf** [comment]
Support for 1.8 has been dropped quite a while ago and it is unclear yet if and when it will be readded.

**Comment by SmokinHigh** [comment]
Alright thanks, what minecraft version would you recommend then :)? im using viaversion so i can allow multiple versions of minecraft, and i saw a 1.8.9 server using mcmmo - do you know what they did, and how?

**Comment by EvilOlaf** [comment]
I also run mcmmo on 1.8. It is quite easy to do this: run an earlier version that still supporting 1.8.

Now comes the tricky part: the CI who served all earlier builds has been renewed quite a while ago and all older builds are lost. So you may have to find someone who can provide such an old version. 
I will not provide mine as mcmmo is meant to be donated for and I changed some stuff on my own.

**Comment by SmokinHigh** [comment]
I wouldn't have any problem donating the 10$ to them if they got a working 1.8 version :p
