### ISSUE TITLE
Error with scoreboard

### ISSUE THREAD

**Issue by mkrtes** [mcMMO-Dev/mcMMO#3032]
Server Spigot 1.10

[15:33:00 ERROR]: Could not pass event McMMOPlayerLevelUpEvent to mcMMO v1.5.06-SNAPSHOT-b145
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at com.gmail.nossr50.util.EventUtils.handleLevelChangeEvent(EventUtils.java:70) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:503) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:477) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:440) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:430) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:32) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.skills.fishing.FishingManager.handleFishing(FishingManager.java:356) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.listeners.PlayerListener.onPlayerFishMonitor(PlayerListener.java:283) [mcMMO.1.5.06.jar:?]
        at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityFishingHook.j(EntityFishingHook.java:434) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.ItemFishingRod.a(ItemFishingRod.java:17) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.ItemStack.a(ItemStack.java:241) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:387) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:956) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:27) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftObjective.unregister(CraftObjective.java:104) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:374) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSkill(ScoreboardWrapper.java:288) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerSkillLevelUpScoreboard(ScoreboardManager.java:258) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.handleLevelUp(ScoreboardManager.java:214) ~[?:?]
        at com.gmail.nossr50.listeners.SelfListener.onPlayerLevelUp(SelfListener.java:24) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        ... 34 more
[15:33:53 ERROR]: Could not pass event McMMOPlayerLevelUpEvent to mcMMO v1.5.06-SNAPSHOT-b145
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at com.gmail.nossr50.util.EventUtils.handleLevelChangeEvent(EventUtils.java:70) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:503) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:477) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:440) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:430) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:32) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.skills.fishing.FishingManager.handleFishing(FishingManager.java:356) [mcMMO.1.5.06.jar:?]
        at com.gmail.nossr50.listeners.PlayerListener.onPlayerFishMonitor(PlayerListener.java:283) [mcMMO.1.5.06.jar:?]
        at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityFishingHook.j(EntityFishingHook.java:434) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.ItemFishingRod.a(ItemFishingRod.java:17) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.ItemStack.a(ItemStack.java:241) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:387) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:956) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:27) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftObjective.unregister(CraftObjective.java:104) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:374) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSkill(ScoreboardWrapper.java:288) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerSkillLevelUpScoreboard(ScoreboardManager.java:258) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.handleLevelUp(ScoreboardManager.java:214) ~[?:?]
        at com.gmail.nossr50.listeners.SelfListener.onPlayerLevelUp(SelfListener.java:24) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        ... 34 more
[15:33:53 WARN]: [mcMMO] Task #9164 for mcMMO v1.5.06-SNAPSHOT-b145 generated an exception
java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.scoreboard.CraftObjective.getScore(CraftObjective.java:97) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.updateSidebar(ScoreboardWrapper.java:423) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.access$000(ScoreboardWrapper.java:30) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper$ScoreboardQuickUpdate.run(ScoreboardWrapper.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10-R0.1.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[15:34:47 INFO]: Chiffa issued server command: /as tp 228
[15:34:49 INFO]: Chiffa issued server command: /we cui

**Comment by Glitchfinder** [comment]
There are multiple issues on the tracker that appear to be the same as this, so I am consolidating them all to #3406.
