### ISSUE TITLE
McMMO - brewing error + items not being consumed on crafting

### ISSUE THREAD

**Issue by Metisuneatn** [mcMMO-Dev/mcMMO#3071]
Error: 
[12:36:50] [Server thread/WARN]: [mcMMO] Task #8420 for mcMMO v1.5.06-b${BUILD_NUMBER} generated an exception
java.lang.NoSuchMethodError: org.bukkit.event.inventory.BrewEvent.<init>(Lorg/bukkit/block/Block;Lorg/bukkit/inventory/BrewerInventory;)V
	at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9) ~[?:?]
	at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:131) ~[?:?]
	at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:96) ~[?:?]
	at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:84) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_latest.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot_latest.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot_latest.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot_latest.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot_latest.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot_latest.jar:git-Spigot-f950f8e-eb6c1bf]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

What happens:

This is an exact quote from a player:

"When I use ANY Ingredient like spider eyes and whatnot
I put them into the brewing stand yeah?
When the potion is brewed Completely......
GUESS WHAT
The Ingredient Was Not Used Up!
And The Ingredient Wont be Used up even after 203203483494238424842
Times
Not Only THAT
Lets say i have a strength 1 Potion in the brewing stand
I put some glowstone
And boom.
It WONT start Brewing
So i CANT brew the upgraded version of a potion
From Lets say
Strength 1 -> Strength 2
          NOPE
Cant."

**Comment by Metisuneatn** [comment]
Oh right, latest version from spigot, Spigot version 1.11

**Comment by t00thpick1** [comment]
Fixed in latest dev builds
