### ISSUE TITLE
Unable to get mcmmo to run on server

### ISSUE THREAD

**Issue by Andriolf** [mcMMO-Dev/mcMMO#3082]
Ello everyone! I've been using mcmmo for 5 years now, and this is the first time I'm unable to get it running on a server without having to do anything (Tis one of my favorite plugins)

Below is the error code.

[21:32:27 INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[21:32:29 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[21:32:29 WARN]: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
[21:32:29 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:163)
[21:32:29 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[21:32:29 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:32:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[21:32:29 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375)
[21:32:29 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325)
[21:32:29 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205)
[21:32:29 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
[21:32:29 WARN]:        at java.lang.Thread.run(Thread.java:745)
[21:32:29 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[21:32:29 ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:53) ~[?:?]
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:204) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-f950f8e-0a6a5cb]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

Would it be because this is a .bukkit plugin trying to be installed on a .spigot server?

**Comment by Andriolf** [comment]
[01:43:47 INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[01:43:48 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[01:43:48 WARN]: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
[01:43:48 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:163)
[01:43:48 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[01:43:48 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[01:43:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[01:43:48 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375)
[01:43:48 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325)
[01:43:48 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205)
[01:43:48 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
[01:43:48 WARN]:        at java.lang.Thread.run(Thread.java:745)
[01:43:48 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[01:43:48 ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)

**Comment by EvilOlaf** [comment]
Update mcMMO
