### ISSUE TITLE
Brewing error no XP/item duplication bug

### ISSUE THREAD

**Issue by coolty** [mcMMO-Dev/mcMMO#3108]
[22:43:22 WARN]: [mcMMO] Task #1160 for mcMMO v1.5.07-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: org.bukkit.event.inventory.BrewEvent.<init>(Lorg/bukkit/block/Block;Lorg/bukkit/inventory/BrewerInventory;I)V
        at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9) ~[?:?]
        at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:131) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:99) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:87) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-a9631d2-2239ff0]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-a9631d2-2239ff0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:728) [spigot.jar:git-Spigot-a9631d2-2239ff0]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-a9631d2-2239ff0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-a9631d2-2239ff0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-a9631d2-2239ff0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[22:43:46 WARN]: [mcMMO] Task #1176 for mcMMO v1.5.07-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: org.bukkit.event.inventory.BrewEvent.<init>(Lorg/bukkit/block/Block;Lorg/bukkit/inventory/BrewerInventory;I)V
        at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9) ~[?:?]
        at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:131) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:99) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:87) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-a9631d2-2239ff0]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-a9631d2-2239ff0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:728) [spigot.jar:git-Spigot-a9631d2-2239ff0]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-a9631d2-2239ff0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot.jar:git-Spigot-a9631d2-2239ff0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot.jar:git-Spigot-a9631d2-2239ff0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

Server Version:
[22:44:52 INFO]: This server is running CraftBukkit version git-Spigot-a9631d2-2239ff0 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Plugins:

 TimTheEnchanter, ServerTokens, ChunkSpawnerLimiter, GroupManager, Craftconomy3, PlugMan, MineSecure, WorldBorder, BuycraftX, Votifier, Multiverse-Core, AutomaticInventory, FastAsyncWorldEdit, ViaVersion, mcMMO, Vault, MassiveCore, WorldEdit, Essentials, BattleTracker, MarriageMaster, CompatNoCheatPlus, Auctions, SignShop, WorldGuard, NoCheatPlus, EssentialsGeoIP, EssentialsChat, PlayerVaults, AdvancedKitsReloaded, EssentialsSpawn, RPGItems, PremiumVanish, Factions, BungeeTabListPlus, CombatTagPlus, FBasics, FactionChat, PurpleIRC

**Comment by pikminmovie** [comment]
This is fixed in the newest 1.11 version of mcMMO, if you are using it make sure to delete potions.yml and reset your server.

**Comment by coolty** [comment]
That's excellent. How about for those who aren't on 1.11? I am using the latest build of mcMMO from the CI.... is there another version somewhere that I am not aware of?

**Comment by pikminmovie** [comment]
I would try to reset your potions.yml, as in deleting it and reloading the server to regenerate it. This should work.

**Comment by coolty** [comment]
I tried deleting the potions.yml and restarting the server, same outcome.
WARNs in console and potion ingredients stay after potion is made.
