### ISSUE TITLE
1.11.2 Spigot mcMMO error

### ISSUE THREAD

**Issue by Macalite** [mcMMO-Dev/mcMMO#3113]
No idea what's causing this error, but it completely disabled McMMO using Spigot 1.11.2
[20:10:46] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[20:10:47] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[20:10:47] [Server thread/WARN]: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
[20:10:47] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:163)
[20:10:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[20:10:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[20:10:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:10:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
[20:10:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
[20:10:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205)
[20:10:47] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
[20:10:47] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:10:47] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[20:10:47] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:53) ~[?:?]
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:204) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

and then when Statz tries to enable:
[20:10:54] [Server thread/ERROR]: Error occurred while enabling Statz v1.4 (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/nossr50/mcMMO
	at me.staartvin.statz.hooks.handlers.McMMOHandler.get(McMMOHandler.java:36) ~[?:?]
	at me.staartvin.statz.hooks.handlers.McMMOHandler.isInstalled(McMMOHandler.java:124) ~[?:?]
	at me.staartvin.statz.hooks.handlers.McMMOHandler.setup(McMMOHandler.java:134) ~[?:?]
	at me.staartvin.statz.hooks.DependencyManager.loadDependencies(DependencyManager.java:221) ~[?:?]
	at me.staartvin.statz.Statz.onEnable(Statz.java:128) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.mcMMO
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-f709362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
	... 16 more

**Comment by LazoYoung** [comment]
Maybe you should try the latest dev version.
Head to spigot resource page.
