### ISSUE TITLE
mcMMO console warning ... What is this?

### ISSUE THREAD

**Issue by wpmidia** [mcMMO-Dev/mcMMO#3118]
What is this warning? 
```
        at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:131) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:99) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:87) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [server.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
[13:54:54 WARN]: [mcMMO] Task #321108 for mcMMO v1.5.07-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: org.bukkit.event.inventory.BrewEvent.<init>(Lorg/bukkit/block/Block;Lorg/bukkit/inventory/BrewerInventory;I)V
        at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9) ~[?:?]
        at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:131) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:99) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:87) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [server.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
```

**Comment by EvilOlaf** [comment]
Did you use mcmmo and updated spigot recently? 

By the way your Java installation seems to be outdated.

**Comment by Glitchfinder** [comment]
Is this still an issue you're running into? If so, does [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/) resolve it?
