### ISSUE TITLE
Premium Mcmmo is bugged?

### ISSUE THREAD

**Issue by RaidingMc** [mcMMO-Dev/mcMMO#3157]
Hello i have a 1.8.8 tacospigot server and when i download mcmmo it either doesnt work ( comes up red on /pl ) or works for one command then the plugin crashes and says "an internal server error occured while attempting to perform this command". Heres the debug msg! - I have tried all versions and none have successfully worked. Can anyone help?

Debug Message:
```
[20:09:07 INFO]: Lavva issued server command: /swords
[20:09:09 INFO]: Lavva issued server command: /swords
[20:09:09 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at me.dadus33.chatitem.filters.Log4jFilter.checkMessage(Log4jFilter.java:83) ~[?:?]
        at me.dadus33.chatitem.filters.Log4jFilter.filter(Log4jFilter.java:58) ~[?:?]
        at org.apache.logging.log4j.core.filter.CompositeFilter.filter(CompositeFilter.java:231) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.apache.logging.log4j.core.filter.AbstractFilterable.isFiltered(AbstractFilterable.java:124) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:400) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.apache.logging.log4j.core.Logger.log(Logger.java:110) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:609) [patched.jar:git-TacoSpigot-"c80c1e5"]
        at org.bukkit.craftbukkit.v1_8_R3.util.ForwardLogHandler.publish(ForwardLogHandler.java:33) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at java.util.logging.Logger.log(Logger.java:738) ~[?:1.8.0_121]
        at java.util.logging.Logger.doLog(Logger.java:765) ~[?:1.8.0_121]
        at java.util.logging.Logger.log(Logger.java:876) ~[?:1.8.0_121]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1195) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[patched.jar:git-TacoSpigot-"c80c1e5"]
```

**Comment by EvilOlaf** [comment]
Probably tried the latest build.
mcMMO is not backwards compatible, so try an older build.

**Comment by Glitchfinder** [comment]
If you're still using a 1.8 server, would you be able to tell me if [this build](https://www.t00thpick1.net/mcMMO/mcMMO_1_8.jar) resolves the issue?
