### ISSUE TITLE
mcMMO 1.5.00 Error? (Minecraft 1.7.9)

### ISSUE THREAD

**Issue by DMCheesecake** [mcMMO-Dev/mcMMO#3159]
I have a 1.7.9 R0.2 CraftBukkit server, and I've installed BarAPI, Essentials, EssentialsChat, SilkSpawners, WorldEdit, and mcMMO. All the plugins work except mcMMO. About halfway down the launch sequence, I get this message:
```
[14:44:22 INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[14:44:22 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[14:44:22 WARN]: java.lang.NullPointerException
[14:44:22 WARN]:        at java.io.Reader.<init>(Unknown Source)
[14:44:22 WARN]:        at java.io.InputStreamReader.<init>(Unknown Source)
[14:44:22 WARN]:        at com.gmail.nossr50.metrics.MetricsManager.setup(MetricsManager.java:72)
[14:44:22 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:173)
[14:44:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[14:44:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[14:44:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[14:44:22 WARN]:        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:446)
[14:44:22 WARN]:        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:380)
[14:44:22 WARN]:        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.<init>(CraftServer.java:318)
[14:44:22 WARN]:        at net.minecraft.server.v1_7_R3.PlayerList.<init>(PlayerList.java:68)
[14:44:22 WARN]:        at net.minecraft.server.v1_7_R3.DedicatedPlayerList.<init>(SourceFile:14)
[14:44:22 WARN]:        at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:126)
[14:44:22 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436)
[14:44:22 WARN]:        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
[14:44:22 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[14:44:26 ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.ExceptionInInitializerError
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:348) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:446) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:380) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.<init>(CraftServer.java:318) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at net.minecraft.server.v1_7_R3.PlayerList.<init>(PlayerList.java:68) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at net.minecraft.server.v1_7_R3.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:126) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_131]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.craftbukkit.v1_7_R3.CraftOfflinePlayer.<init>(CraftOfflinePlayer.java:34) ~[craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at org.bukkit.craftbukkit.v1_7_R3.CraftServer.getOfflinePlayer(CraftServer.java:1278) ~[craftbukkit-1.7.9-R0.2-3092.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:133) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:121) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.<clinit>(ScoreboardManager.java:43) ~[?:?]
        ... 16 more
```
Any help?

**Comment by Glitchfinder** [comment]
Is this still an issue you're running into? If so, are you able to tell me what happens if you disable scoreboards in the config?

**Comment by DMCheesecake** [comment]
Sheesh dude, I posted this a year ago. I don't even have the server anymore, so I have no idea.

**Comment by Glitchfinder** [comment]
All right,. thanks for getting back to me.
