### ISSUE TITLE
BlockPistonRetractEvent java.lang.ArrayIndexOutOfBoundsException: -1 PrimitiveChunkStore.setTrue

### ISSUE THREAD

**Issue by PhanaticD** [mcMMO-Dev/mcMMO#3172]
```
[09:48:50] [Server thread/ERROR]: Could not pass event BlockPistonRetractEvent to mcMMO v1.5.07-SNAPSHOT
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1092]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1092]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1092]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1092]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1092]
    at net.minecraft.server.v1_11_R1.BlockPiston.a(BlockPiston.java:329) [patched_1.11.2.jar:git-Paper-1092]
    at net.minecraft.server.v1_11_R1.BlockPiston.a(BlockPiston.java:221) [patched_1.11.2.jar:git-Paper-1092]
    at net.minecraft.server.v1_11_R1.BlockStateList$BlockData.a(SourceFile:413) [patched_1.11.2.jar:git-Paper-1092]
    at net.minecraft.server.v1_11_R1.WorldServer.a(WorldServer.java:1267) [patched_1.11.2.jar:git-Paper-1092]
    at net.minecraft.server.v1_11_R1.WorldServer.ao(WorldServer.java:1253) [patched_1.11.2.jar:git-Paper-1092]
    at net.minecraft.server.v1_11_R1.WorldServer.doTick(WorldServer.java:273) [patched_1.11.2.jar:git-Paper-1092]
    at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:882) [patched_1.11.2.jar:git-Paper-1092]
    at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1092]
    at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1092]
    at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1092]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
    at com.gmail.nossr50.util.blockmeta.chunkmeta.PrimitiveChunkStore.setTrue(PrimitiveChunkStore.java:57) ~[?:?]
    at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.setTrue(HashChunkManager.java:358) ~[?:?]
    at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.setTrue(HashChunkManager.java:367) ~[?:?]
    at com.gmail.nossr50.listeners.BlockListener.onBlockPistonRetract(BlockListener.java:91) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1092]
    ... 15 more
```

this spammed my console for a while, eventually had issues with a corrupt area that I had to regen with worldedit

**Comment by Coolguy3289** [comment]
Getting the same Error.
`[17:32:38 ERROR]: Could not pass event BlockPistonRetractEvent to mcMMO v1.5.07-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.2.jar:git-Paper-1099]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1099]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1099]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1099]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1099]
        at net.minecraft.server.v1_11_R1.BlockPiston.a(BlockPiston.java:329) [patched_1.11.2.jar:git-Paper-1099]
        at net.minecraft.server.v1_11_R1.BlockPiston.a(BlockPiston.java:221) [patched_1.11.2.jar:git-Paper-1099]
        at net.minecraft.server.v1_11_R1.BlockStateList$BlockData.a(SourceFile:413) [patched_1.11.2.jar:git-Paper-1099]
        at net.minecraft.server.v1_11_R1.WorldServer.a(WorldServer.java:1267) [patched_1.11.2.jar:git-Paper-1099]
        at net.minecraft.server.v1_11_R1.WorldServer.ao(WorldServer.java:1253) [patched_1.11.2.jar:git-Paper-1099]
        at net.minecraft.server.v1_11_R1.WorldServer.doTick(WorldServer.java:273) [patched_1.11.2.jar:git-Paper-1099]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:882) [patched_1.11.2.jar:git-Paper-1099]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1099]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754) [patched_1.11.2.jar:git-Paper-1099]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652) [patched_1.11.2.jar:git-Paper-1099]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at com.gmail.nossr50.util.blockmeta.chunkmeta.PrimitiveChunkStore.setTrue(PrimitiveChunkStore.java:60) ~[?:?]
        at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.setTrue(HashChunkManager.java:358) ~[?:?]
        at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.setTrue(HashChunkManager.java:367) ~[?:?]
        at com.gmail.nossr50.listeners.BlockListener.onBlockPistonRetract(BlockListener.java:91) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1099]
        ... 15 more
`

**Comment by duckweedvn** [comment]
Same problem ...

**Comment by Coolguy3289** [comment]
Bump on this issue. Has there been any update? I haven't used MCMMO since I reported it.
