### ISSUE TITLE
mcMMO Alchemy

### ISSUE THREAD

**Issue by raymundpalanca** [mcMMO-Dev/mcMMO#3183]
```
1.05 22:54:27 [Server] WARN Task #5015459 for mcMMO v1.5.07 generated an exception
31.05 22:54:27 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.event.inventory.BrewEvent.<init>(Lorg/bukkit/block/Block;Lorg/bukkit/inventory/BrewerInventory;I)V
31.05 22:54:27 [Server] INFO at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9) ~[?:?]
31.05 22:54:27 [Server] INFO at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:131) ~[?:?]
31.05 22:54:27 [Server] INFO at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:99) ~[?:?]
31.05 22:54:27 [Server] INFO at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:87) ~[?:?]
31.05 22:54:27 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[my.jar:git-Spigot-c3e4052-1953f52]
31.05 22:54:27 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [my.jar:git-Spigot-c3e4052-1953f52]
31.05 22:54:27 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [my.jar:git-Spigot-c3e4052-1953f52]
31.05 22:54:27 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [my.jar:git-Spigot-c3e4052-1953f52]
31.05 22:54:27 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [my.jar:git-Spigot-c3e4052-1953f52]
31.05 22:54:27 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [my.jar:git-Spigot-c3e4052-1953f52]
```
The skill doesn't work and gives alot of error on console. Currently using 1.10 Spigot and the latest build of mcmmo for it .

**Comment by raymundpalanca** [comment]
Anyone?

**Comment by NecroticWarrior** [comment]
I am having this same issue. I've been developing on a server for a while now and recently added mcmmo, however the plugin does have some issues, especially with alchemy. I'm getting the same error messages as raymund. When I place a potion ingredient into a brewing stand it brews the potion, but does not give alchemy experience nor does it use up the ingredient, rather the ingredient stays in the brewing stand and the potion is crafted. Please give info on how I can fix this

**Comment by Glitchfinder** [comment]
Is this still an issue you're running into? If so, is it resolved by [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
