### ISSUE TITLE
mcMMO won't run on my server? doesn't have a YamlConfiguration

### ISSUE THREAD

**Issue by person3000** [mcMMO-Dev/mcMMO#3211]
Hello,

I'm trying to run a private server for friends. I have Spigot-1.12 version #60 running and I'm only using WorldEdit and mcMMO. 

My mcMMO version is v1.5.00-b3547.

Here's my startup log
[startup error.txt](https://github.com/mcMMO-Dev/mcMMO/files/1099188/startup.error.txt)

**Comment by person3000** [comment]
Loading libraries, please wait...
[18:16:08 INFO]: Starting minecraft server version 1.12
[18:16:08 INFO]: Loading properties
[18:16:08 INFO]: Default game type: SURVIVAL
[18:16:08 INFO]: This server is running CraftBukkit version git-Spigot-b78586d-7638276 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[18:16:08 INFO]: Debug logging is disabled
[18:16:08 INFO]: Using 4 threads for Netty based IO
[18:16:08 INFO]: Server Ping Player Sample Count: 12
[18:16:08 INFO]: Generating keypair
[18:16:09 INFO]: Starting Minecraft server on *:25565
[18:16:09 INFO]: Using default channel type
[18:16:09 INFO]: Set PluginClassLoader as parallel capable
[18:16:09 INFO]: [WorldEdit] Loading WorldEdit v6.1.7;dd00bb1
[18:16:09 INFO]: [mcMMO] Loading mcMMO v1.5.00-b3547
[18:16:09 INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[18:16:09 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[18:16:09 WARN]: java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
[18:16:09 WARN]:        at com.gmail.nossr50.config.HiddenConfig.load(HiddenConfig.java:31)
[18:16:09 WARN]:        at com.gmail.nossr50.config.HiddenConfig.<init>(HiddenConfig.java:18)
[18:16:09 WARN]:        at com.gmail.nossr50.config.HiddenConfig.getInstance(HiddenConfig.java:23)
[18:16:09 WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:400)
[18:16:09 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[18:16:09 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:16:09 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[18:16:09 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[18:16:09 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
[18:16:09 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
[18:16:09 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[18:16:09 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[18:16:09 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:16:09 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[18:16:09 ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at com.gmail.nossr50.config.AutoUpdateConfigLoader.loadFile(AutoUpdateConfigLoader.java:29) ~[?:?]
        at com.gmail.nossr50.config.ConfigLoader.<init>(ConfigLoader.java:26) ~[?:?]
        at com.gmail.nossr50.config.AutoUpdateConfigLoader.<init>(AutoUpdateConfigLoader.java:23) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:20) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:26) ~[?:?]
        at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:51) ~[?:?]
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:203) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.12.jar:git-Spigot-b78586d-7638276]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.12.jar:git-Spigot-b78586d-7638276]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot-1.12.jar:git-Spigot-b78586d-7638276]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12.jar:git-Spigot-b78586d-7638276]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-b78586d-7638276]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-b78586d-7638276]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-b78586d-7638276]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-b78586d-7638276]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot-1.12.jar:git-Spigot-b78586d-7638276]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-b78586d-7638276]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[18:16:09 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[18:16:09 INFO]: Preparing level "world"
[18:16:09 INFO]: -------- World Settings For [world] --------
[18:16:09 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:16:09 INFO]: Item Despawn Rate: 6000
[18:16:09 INFO]: Item Merge Radius: 2.5
[18:16:09 INFO]: Arrow Despawn Rate: 1200
[18:16:09 INFO]: Nerfing mobs spawned from spawners: false
[18:16:09 INFO]: Zombie Aggressive Towards Villager: true
[18:16:09 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:16:09 INFO]: Experience Merge Radius: 3.0
[18:16:09 INFO]: View Distance: 10
[18:16:09 INFO]: Mob Spawn Range: 4
[18:16:09 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:16:09 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:16:09 INFO]: Cactus Growth Modifier: 100%
[18:16:09 INFO]: Cane Growth Modifier: 100000%
[18:16:09 INFO]: Melon Growth Modifier: 100%
[18:16:09 INFO]: Mushroom Growth Modifier: 100%
[18:16:09 INFO]: Pumpkin Growth Modifier: 100%
[18:16:09 INFO]: Sapling Growth Modifier: 100%
[18:16:09 INFO]: Wheat Growth Modifier: 100%
[18:16:09 INFO]: NetherWart Growth Modifier: 100%
[18:16:09 INFO]: Vine Growth Modifier: 100%
[18:16:09 INFO]: Cocoa Growth Modifier: 100%
[18:16:09 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:16:09 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:16:09 INFO]: Random Lighting Updates: true
[18:16:09 INFO]: Max TNT Explosions: 100
[18:16:09 INFO]: Structure Info Saving: true
[18:16:09 INFO]: -------- World Settings For [world_nether] --------
[18:16:09 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:16:09 INFO]: Item Despawn Rate: 6000
[18:16:09 INFO]: Item Merge Radius: 2.5
[18:16:09 INFO]: Arrow Despawn Rate: 1200
[18:16:09 INFO]: Nerfing mobs spawned from spawners: false
[18:16:09 INFO]: Zombie Aggressive Towards Villager: true
[18:16:09 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:16:09 INFO]: Experience Merge Radius: 3.0
[18:16:09 INFO]: View Distance: 10
[18:16:09 INFO]: Mob Spawn Range: 4
[18:16:09 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:16:09 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:16:09 INFO]: Cactus Growth Modifier: 100%
[18:16:09 INFO]: Cane Growth Modifier: 100000%
[18:16:09 INFO]: Melon Growth Modifier: 100%
[18:16:09 INFO]: Mushroom Growth Modifier: 100%
[18:16:09 INFO]: Pumpkin Growth Modifier: 100%
[18:16:09 INFO]: Sapling Growth Modifier: 100%
[18:16:09 INFO]: Wheat Growth Modifier: 100%
[18:16:09 INFO]: NetherWart Growth Modifier: 100%
[18:16:09 INFO]: Vine Growth Modifier: 100%
[18:16:09 INFO]: Cocoa Growth Modifier: 100%
[18:16:09 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:16:09 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:16:09 INFO]: Random Lighting Updates: true
[18:16:09 INFO]: Max TNT Explosions: 100
[18:16:09 INFO]: Structure Info Saving: true
[18:16:09 INFO]: -------- World Settings For [world_the_end] --------
[18:16:09 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:16:09 INFO]: Item Despawn Rate: 6000
[18:16:09 INFO]: Item Merge Radius: 2.5
[18:16:09 INFO]: Arrow Despawn Rate: 1200
[18:16:09 INFO]: Nerfing mobs spawned from spawners: false
[18:16:09 INFO]: Zombie Aggressive Towards Villager: true
[18:16:09 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:16:09 INFO]: Experience Merge Radius: 3.0
[18:16:09 INFO]: View Distance: 10
[18:16:09 INFO]: Mob Spawn Range: 4
[18:16:09 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:16:09 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:16:09 INFO]: Cactus Growth Modifier: 100%
[18:16:09 INFO]: Cane Growth Modifier: 100000%
[18:16:09 INFO]: Melon Growth Modifier: 100%
[18:16:09 INFO]: Mushroom Growth Modifier: 100%
[18:16:09 INFO]: Pumpkin Growth Modifier: 100%
[18:16:09 INFO]: Sapling Growth Modifier: 100%
[18:16:09 INFO]: Wheat Growth Modifier: 100%
[18:16:09 INFO]: NetherWart Growth Modifier: 100%
[18:16:09 INFO]: Vine Growth Modifier: 100%
[18:16:09 INFO]: Cocoa Growth Modifier: 100%
[18:16:09 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:16:09 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:16:09 INFO]: Random Lighting Updates: true
[18:16:09 INFO]: Max TNT Explosions: 100
[18:16:09 INFO]: Structure Info Saving: true
[18:16:09 INFO]: Preparing start region for level 0 (Seed: 2826657973802069840)
[18:16:10 INFO]: Preparing start region for level 1 (Seed: 2826657973802069840)
[18:16:11 INFO]: Preparing start region for level 2 (Seed: 2826657973802069840)
[18:16:11 INFO]: [WorldEdit] Enabling WorldEdit v6.1.7;dd00bb1
[18:16:11 INFO]: WEPIF: Using the Bukkit Permissions API.
[18:16:11 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R1 as the Bukkit adapter
[18:16:11 INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:16:11 INFO]: Done (2.084s)! For help, type "help" or "?"

**Comment by SXRWahrheit** [comment]
You need to download a newer developer build to use it on 1.12.

**Comment by person3000** [comment]
Where can I get the dev builds?

**Comment by SXRWahrheit** [comment]
From the linked site on the Spigot posting.
