### ISSUE TITLE
BlockPistonRetractEvent EventException: null

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#3216]
```
[19:49:10] [Server thread/ERROR]: Could not pass event BlockPistonRetractEvent to mcMMO v1.5.07-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1133]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.jar:git-Paper-1133]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1133]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1133]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.BlockPiston.a(BlockPiston.java:332) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.BlockPiston.a(BlockPiston.java:221) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.BlockStateList$BlockData.a(SourceFile:413) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:1314) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.WorldServer.aq(WorldServer.java:1300) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:330) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:894) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1133]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1133]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 256
	at com.gmail.nossr50.util.blockmeta.chunkmeta.PrimitiveChunkStore.setTrue(PrimitiveChunkStore.java:57) ~[?:?]
	at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.setTrue(HashChunkManager.java:358) ~[?:?]
	at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.setTrue(HashChunkManager.java:367) ~[?:?]
	at com.gmail.nossr50.listeners.BlockListener.onBlockPistonRetract(BlockListener.java:91) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1133]
	... 15 more
```

**Comment by Coolguy3289** [comment]
I am referencing a previously posted issue that I am pretty sure is the same issue: https://github.com/mcMMO-Dev/mcMMO/issues/3172
