### ISSUE TITLE
McMMO not working.

### ISSUE THREAD

**Issue by Duqqs** [mcMMO-Dev/mcMMO#3247]
I'm trying to make a 1.7.9 minecraft server. I'm using craftbukkit 1.7.9-R0.2, and when I install McMMO Version: 1.5.00 and I try to run commands like /mcstats it doesn't do anything, no error message, it just doesn't do anything. Anyone got any ideas?

Here's my start up log, about half way down it says
```
"There was an error enabling McMMO"
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.wooden_slab is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.sign is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.record_stal is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.jukebox is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.birch_stairs is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.timeSinceDeath is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.killEntity.Rabbit is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.ladder is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.dye is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.barrier is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.sapling is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.stone_slab is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.stone_stairs is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.sprintOneCm is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.dirt is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.crouchOneCm is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.planks is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.glowstone is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.potion is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.diamond_sword is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.waterlily is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.cobblestone is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.log is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.stone is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.recordPlayed is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.chest is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.useItem.minecraft.torch is
01.08 21:50:45 [Server] WARN Invalid statistic in ./ServerWorld/stats/b4fd17f6-d819-4155-ac83-4794a3209c60.json: Don't know what stat.chestOpened is
01.08 21:50:45 [Server] INFO UUID of player ArceusMC is b4fd17f6-d819-4155-ac83-4794a3209c60
01.08 21:50:20 [Server] Startup Done (7.809s)! For help, type "help" or "?"
01.08 21:50:20 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
01.08 21:50:20 [Server] INFO Preparing spawn area: 74%
01.08 21:50:19 [Server] INFO Preparing start region for level 2 (Seed: -7366314070695202415)
01.08 21:50:19 [Server] INFO Preparing spawn area: 98%
01.08 21:50:18 [Server] INFO Preparing spawn area: 81%
01.08 21:50:16 [Server] INFO Preparing spawn area: 64%
01.08 21:50:15 [Server] INFO Preparing spawn area: 39%
01.08 21:50:14 [Server] INFO Preparing spawn area: 16%
01.08 21:50:13 [Server] INFO Preparing start region for level 1 (Seed: -7366314070695202415)
01.08 21:50:13 [Server] INFO Preparing spawn area: 87%
01.08 21:50:13 [Server] WARN Skipping Entity with id Rabbit
01.08 21:50:13 [Server] WARN Skipping Entity with id Rabbit
01.08 21:50:13 [Server] WARN Skipping Entity with id Rabbit
01.08 21:50:13 [Server] WARN Skipping Entity with id Rabbit
01.08 21:50:13 [Server] WARN Skipping Entity with id Rabbit
01.08 21:50:13 [Server] WARN Skipping Entity with id Rabbit
01.08 21:50:13 [Server] WARN Skipping Entity with id Rabbit
01.08 21:50:13 [Server] WARN Skipping Entity with id Rabbit
01.08 21:50:13 [Server] WARN Skipping Entity with id Rabbit
01.08 21:50:13 [Server] WARN Skipping Entity with id Rabbit
01.08 21:50:12 [Server] INFO Preparing start region for level 0 (Seed: -7366314070695202415)
01.08 21:50:12 [Server] INFO ---- Migration of old the_end folder complete ----
01.08 21:50:12 [Server] INFO Success! To restore the_end in the future, simply move ServerWorld_the_end/DIM1 to ServerWorld/DIM1
01.08 21:50:12 [Server] INFO Attempting to move ServerWorld/DIM1 to ServerWorld_the_end/DIM1...
01.08 21:50:12 [Server] INFO We will move this folder for you, but it will mean that you need to move it back should you wish to stop using Bukkit in the future.
01.08 21:50:12 [Server] INFO Unfortunately due to the way that Minecraft implemented multiworld support in 1.6, Bukkit requires that you move your the_end folder to a new location in order to operate correctly.
01.08 21:50:12 [Server] INFO ---- Migration of old the_end folder required ----
01.08 21:50:12 [Server] INFO ---- Migration of old nether folder complete ----
01.08 21:50:12 [Server] INFO Success! To restore nether in the future, simply move ServerWorld_nether/DIM-1 to ServerWorld/DIM-1
01.08 21:50:12 [Server] INFO Attempting to move ServerWorld/DIM-1 to ServerWorld_nether/DIM-1...
01.08 21:50:12 [Server] INFO We will move this folder for you, but it will mean that you need to move it back should you wish to stop using Bukkit in the future.
01.08 21:50:12 [Server] INFO Unfortunately due to the way that Minecraft implemented multiworld support in 1.6, Bukkit requires that you move your nether folder to a new location in order to operate correctly.
01.08 21:50:12 [Server] INFO ---- Migration of old nether folder required ----
01.08 21:50:12 [Server] INFO Preparing level "ServerWorld"
01.08 21:50:12 [Server] INFO ... 16 more
01.08 21:50:12 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.&lt;clinit&gt;(ScoreboardManager.java:43) ~[?:?]
01.08 21:50:12 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:121) ~[?:?]
01.08 21:50:12 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:133) ~[?:?]
01.08 21:50:12 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.CraftServer.getOfflinePlayer(CraftServer.java:1278) ~[craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.CraftOfflinePlayer.&lt;init&gt;(CraftOfflinePlayer.java:34) ~[craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_111]
01.08 21:50:12 [Server] INFO at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_111]
01.08 21:50:12 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
01.08 21:50:12 [Server] INFO at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:126) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at net.minecraft.server.v1_7_R3.DedicatedPlayerList.&lt;init&gt;(SourceFile:14) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerList.&lt;init&gt;(PlayerList.java:68) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.CraftServer.&lt;init&gt;(CraftServer.java:318) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:380) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:446) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
01.08 21:50:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:348) [craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[craftbukkit-beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
01.08 21:50:12 [Server] INFO at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206) ~[?:?]
01.08 21:50:12 [Server] INFO java.lang.ExceptionInInitializerError
01.08 21:50:12 [Server] ERROR Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
01.08 21:50:10 [Server] INFO Disabling mcMMO v1.5.00-b3547
01.08 21:50:10 [Server] WARN at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
01.08 21:50:10 [Server] WARN at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436)
01.08 21:50:10 [Server] WARN at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:126)
01.08 21:50:10 [Server] WARN at net.minecraft.server.v1_7_R3.DedicatedPlayerList.&lt;init&gt;(SourceFile:14)
01.08 21:50:10 [Server] WARN at net.minecraft.server.v1_7_R3.PlayerList.&lt;init&gt;(PlayerList.java:68)
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.CraftServer.&lt;init&gt;(CraftServer.java:318)
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:380)
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:446)
01.08 21:50:10 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
01.08 21:50:10 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
01.08 21:50:10 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
01.08 21:50:10 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:173)
01.08 21:50:10 [Server] WARN at com.gmail.nossr50.metrics.MetricsManager.setup(MetricsManager.java:72)
01.08 21:50:10 [Server] WARN at java.io.InputStreamReader.&lt;init&gt;(Unknown Source)
01.08 21:50:10 [Server] WARN at java.io.Reader.&lt;init&gt;(Unknown Source)
01.08 21:50:10 [Server] WARN java.lang.NullPointerException
01.08 21:50:10 [Server] ERROR There was an error while enabling mcMMO!
01.08 21:50:10 [Server] WARN ... 5 more
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.libs.com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.libs.com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
01.08 21:50:10 [Server] WARN Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 7
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.updater.AutoUpdater$1.run(AutoUpdater.java:77)
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.updater.BukkitDLUpdaterService.getArtifact(BukkitDLUpdaterService.java:30)
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.v1_7_R3.updater.BukkitDLUpdaterService.fetchArtifact(BukkitDLUpdaterService.java:53)
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:694)
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:755)
01.08 21:50:10 [Server] WARN at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
01.08 21:50:10 [Server] WARN org.bukkit.craftbukkit.libs.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 7
01.08 21:50:10 [Server] WARN Exception in thread "Thread-7" 
01.08 21:50:09 [Server] INFO Enabling mcMMO v1.5.00-b3547
01.08 21:50:09 [Server] INFO Loading mcMMO v1.5.00-b3547
01.08 21:50:09 [Server] INFO This server is running CraftBukkit version git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks (MC: 1.7.9) (Implementing API version 1.7.9-R0.2)
01.08 21:50:09 [Server] INFO Starting Minecraft server on 119.81.145.73:50625
01.08 21:50:09 [Server] INFO Generating keypair
01.08 21:50:09 [Server] INFO Default game type: SURVIVAL
01.08 21:50:09 [Server] INFO Loading properties
01.08 21:50:09 [Server] INFO Starting minecraft server version 1.7.9
01.08 21:50:02 [Server] INFO Loading libraries, please wait...
01.08 21:50:01 [Multicraft] Loaded config for "Default"
01.08 21:50:01 [Multicraft] Starting server!
01.08 21:50:01 [Multicraft] Loading server properties
01.08 21:50:01 [Multicraft] Received start command
01.08 21:49:55 [Multicraft] Loading server properties
01.08 21:49:10 [Multicraft] Server stopped
``

**Comment by SXRWahrheit** [comment]
You are running 1.7.9, and that build was probably designed for 1.7.10.
