### ISSUE TITLE
Blastmining Detonation not Working

### ISSUE THREAD

**Issue by Michielfx** [mcMMO-Dev/mcMMO#3258]
Shift right clicking with a Flint and Steel generates the following code. Aiming at a block of tnt or not while doing this, both result in the following. 

This broke with the 1.12.1 update of spigot. I confirmed this working on Spigot 1.12. No other plugins were present during testing

`[Server thread/ERROR]: Could not pass event PlayerInteractEvent to mcMMO v1.5.08-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:983) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
	at com.gmail.nossr50.skills.mining.MiningManager.remoteDetonation(MiningManager.java:97) ~[?:?]
	at com.gmail.nossr50.listeners.PlayerListener.onPlayerInteractMonitor(PlayerListener.java:594) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1.12.1.jar:git-Spigot-5340a52-27b8bf9]
	... 18 more`

**Comment by ezeiger92** [comment]
I knew I should look in other issues for you... Who are you to claim this?

This is caused by the same thing as the fishing issue, getTargetBlock(HashSet<Byte>) was removed and must be replaced with getTargetBlock(HashSet<Material>)

I have a patch swapping all instances of that function [(see my post here)](https://www.spigotmc.org/threads/mcmmo-paid.39629/page-80#post-2611172) so it will fix this as well.
