### ISSUE TITLE
mcmmo not able to run? (disabled)

### ISSUE THREAD

**Issue by carscraft** [mcMMO-Dev/mcMMO#3264]
I have MCMMO 1.5.00 and craftbukkit 1.7.10. When I startup my server it says it disabled it. Here are my logs: [08:15:27 INFO]: This server is running CraftBukkit version git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[08:15:28 INFO]: [mcMMO] Loading mcMMO v1.5.00-b3547
[08:15:28 INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[08:15:28 WARN]: Exception in thread "Thread-7" 
[08:15:28 WARN]: org.bukkit.craftbukkit.libs.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 7
[08:15:28 WARN]: 	at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
[08:15:28 WARN]: 	at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:755)
[08:15:28 WARN]: 	at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:694)
[08:15:28 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.updater.BukkitDLUpdaterService.fetchArtifact(BukkitDLUpdaterService.java:53)
[08:15:28 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.updater.BukkitDLUpdaterService.getArtifact(BukkitDLUpdaterService.java:30)
[08:15:28 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.updater.AutoUpdater$1.run(AutoUpdater.java:77)
[08:15:28 WARN]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 7
[08:15:28 WARN]: 	at org.bukkit.craftbukkit.libs.com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
[08:15:28 WARN]: 	at org.bukkit.craftbukkit.libs.com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
[08:15:28 WARN]: 	at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
[08:15:28 WARN]: 	... 5 more
[08:15:29 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[08:15:29 WARN]: java.lang.NullPointerException
[08:15:29 WARN]: 	at java.io.Reader.<init>(Reader.java:78)
[08:15:29 WARN]: 	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
[08:15:29 WARN]: 	at com.gmail.nossr50.metrics.MetricsManager.setup(MetricsManager.java:72)
[08:15:29 WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:173)
[08:15:29 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[08:15:29 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[08:15:29 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[08:15:29 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455)
[08:15:29 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389)
[08:15:29 WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.<init>(CraftServer.java:327)
[08:15:29 WARN]: 	at net.minecraft.server.v1_7_R4.PlayerList.<init>(PlayerList.java:68)
[08:15:29 WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedPlayerList.<init>(SourceFile:14)
[08:15:29 WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:133)
[08:15:29 WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436)
[08:15:29 WARN]: 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[08:15:29 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[08:16:07 ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:348) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.<init>(CraftServer.java:327) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.PlayerList.<init>(PlayerList.java:68) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:133) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_144]
	at org.bukkit.craftbukkit.v1_7_R4.CraftOfflinePlayer.<init>(CraftOfflinePlayer.java:34) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.getOfflinePlayer(CraftServer.java:1347) ~[craftbukkit.jar:git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:133) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:121) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.<clinit>(ScoreboardManager.java:43) ~[?:?]
	... 16 more
[08:16:07 INFO]: Preparing level "world"
[08:16:07 INFO]: Preparing start region for level 0 (Seed: -4177988763269907676)
[08:16:08 INFO]: Preparing spawn area: 34%
[08:16:09 INFO]: Preparing spawn area: 74%
[08:16:09 INFO]: Preparing start region for level 1 (Seed: -4177988763269907676)
[08:16:11 INFO]: Preparing spawn area: 77%
[08:16:11 INFO]: Preparing start region for level 2 (Seed: -4177988763269907676)
[08:16:12 INFO]: Server permissions file permissions.yml is empty, ignoring it
[08:16:12 INFO]: Done (5.172s)! For help, type "help" or "?"
>

**Comment by AllPlayed** [comment]
That's the plugin, this will be fixed (we all think) on the new 1.12.1 version

**Comment by ezeiger92** [comment]
Looks like some issue setting up metrics. My first suggestion would be update your server and mcmmo to the latest builds, but I'm guessing that's not an option for you.

in config.yml, see if you can set "Stats_Tracking" to "false". That's the name of the current metrics toggle, I don't know if it's the same in your version.

**Comment by ezeiger92** [comment]
@AllPlayed You are not helping, unless you have something of substance to add to these issues stop posting.

**Comment by AllPlayed** [comment]
Wow? Why... This is a public thing, you cannot tell me to stop

**Comment by ezeiger92** [comment]
If you are actually trying to help like you claimed in #3251, you should stop because you are not helping. No, there is nothing I can do to make you stop posting, but from here on out I have to assume you are just a troll that, for some reason, wants to waste peoples time and bother the devs. I don't know why you would do that, but to each his own.

**Comment by t00thpick1** [comment]
yeah so this is a really old version, even if I wanted to fix it I dont have the ability to test it, nor do I have the code state from back then.
