### ISSUE TITLE
Error while using 1.5.04-SNAPSHOT (Premium version from spigot)

### ISSUE THREAD

**Issue by EwansXD** [mcMMO-Dev/mcMMO#3271]
```
18.08 20:30:47 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
18.08 20:30:47 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
18.08 20:30:47 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
18.08 20:30:47 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
18.08 20:30:47 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
18.08 20:30:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
18.08 20:30:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
18.08 20:30:47 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
18.08 20:30:47 [Server] INFO at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:204) [mcMMO%20(3).jar:?]
18.08 20:30:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
18.08 20:30:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
18.08 20:30:47 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
18.08 20:30:47 [Server] INFO at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:250) ~[?:?]
18.08 20:30:47 [Server] INFO java.lang.NullPointerException
18.08 20:30:47 [Server] ERROR Error occurred while disabling mcMMO v1.5.04-SNAPSHOT-b82 (Is it up to date?)
18.08 20:30:47 [Server] ERROR Cannot read /plugins/mcMMO/repair.vanilla.yml(File Permissions?)
18.08 20:30:47 [Server] ERROR Cannot read /plugins/mcMMO/experience.yml(File Permissions?)
18.08 20:30:47 [Server] INFO Disabling mcMMO v1.5.04-SNAPSHOT-b82
18.08 20:30:47 [Server] WARN at java.lang.Thread.run(Thread.java:748)
18.08 20:30:47 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
18.08 20:30:47 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
18.08 20:30:47 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
18.08 20:30:47 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
18.08 20:30:47 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
18.08 20:30:47 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
18.08 20:30:47 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
18.08 20:30:47 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:146)
18.08 20:30:47 [Server] WARN at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:406)
18.08 20:30:47 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:80)
18.08 20:30:47 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:74)
18.08 20:30:47 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:137)
18.08 20:30:47 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreaures(TreasureConfig.java:242)
18.08 20:30:47 [Server] WARN at java.lang.String.substring(String.java:1931)
18.08 20:30:47 [Server] WARN java.lang.StringIndexOutOfBoundsException: String index out of range: -1
18.08 20:30:47 [Server] ERROR There was an error while enabling mcMMO!
18.08 20:30:46 [Server] INFO Enabling mcMMO v1.5.04-SNAPSHOT-b82
```

**Comment by Glitchfinder** [comment]
Is this still an error you're running into? If so, and you're still running a 1.8 server, does [this 1.8 build fix it](https://www.t00thpick1.net/mcMMO/mcMMO_1_8.jar)?
