### ISSUE TITLE
Launching issue [Error]

### ISSUE THREAD

**Issue by ThatzGaming** [mcMMO-Dev/mcMMO#3274]
```
[20:28:30] [Server thread/INFO]: Starting minecraft server version 1.12.1
[20:28:30] [Server thread/INFO]: Loading properties
[20:28:30] [Server thread/INFO]: Default game type: SURVIVAL
[20:28:30] [Server thread/INFO]: Generating keypair
[20:28:30] [Server thread/INFO]: Starting Minecraft server on 131.153.29.226:25570
[20:28:30] [Server thread/INFO]: Using epoll channel type
[20:28:30] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
[20:28:30] [Server thread/INFO]: [mcMMO] Loading mcMMO v1.5.07
[20:28:30] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.07
[20:28:31] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[20:28:31] [Server thread/WARN]: java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
[20:28:31] [Server thread/WARN]: at com.gmail.nossr50.config.HiddenConfig.load(HiddenConfig.java:33)
[20:28:31] [Server thread/WARN]: at com.gmail.nossr50.config.HiddenConfig.<init>(HiddenConfig.java:20)
[20:28:31] [Server thread/WARN]: at com.gmail.nossr50.config.HiddenConfig.getInstance(HiddenConfig.java:25)
[20:28:31] [Server thread/WARN]: at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:382)
[20:28:31] [Server thread/WARN]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:141)
[20:28:31] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:28:31] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
[20:28:31] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:401)
[20:28:31] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:366)
[20:28:31] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
[20:28:31] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:189)
[20:28:31] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522)
[20:28:31] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
[20:28:31] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.07
[20:28:31] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.07 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
at com.gmail.nossr50.config.AutoUpdateConfigLoader.loadFile(AutoUpdateConfigLoader.java:28) ~[?:?]
at com.gmail.nossr50.config.ConfigLoader.<init>(ConfigLoader.java:26) ~[?:?]
at com.gmail.nossr50.config.AutoUpdateConfigLoader.<init>(AutoUpdateConfigLoader.java:22) ~[?:?]
at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:21) ~[?:?]
at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:27) ~[?:?]
at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:51) ~[?:?]
at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:205) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[minecraft_server.jar:git-Bukkit-357b573]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:353) [minecraft_server.jar:git-Bukkit-357b573]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:420) [minecraft_server.jar:git-Bukkit-357b573]
at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:195) [mcMMO.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [minecraft_server.jar:git-Bukkit-357b573]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [minecraft_server.jar:git-Bukkit-357b573]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:401) [minecraft_server.jar:git-Bukkit-357b573]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:366) [minecraft_server.jar:git-Bukkit-357b573]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [minecraft_server.jar:git-Bukkit-357b573]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:189) [minecraft_server.jar:git-Bukkit-357b573]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [minecraft_server.jar:git-Bukkit-357b573]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[20:28:31] [Server thread/INFO]: Preparing level "world"
[20:28:31] [Server thread/INFO]: Preparing start region for level 0 (Seed: -1530611771247839180)
[20:28:32] [Server thread/INFO]: Preparing spawn area: 73%
[20:28:32] [Server thread/INFO]: Preparing start region for level 1 (Seed: -1530611771247839180)
[20:28:33] [Server thread/INFO]: Preparing start region for level 2 (Seed: 8389603868307942373)
[20:28:33] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:28:33] [Server thread/INFO]: Done (2.352s)! For help, type "help" or "?"
[20:28:33] [Server thread/INFO]: Starting GS4 status listener
```

**Comment by Glitchfinder** [comment]
Is this still an error you're running into? If so, does it still happen on [the latest dev build](https://popicraft.net/jenkins/job/mcMMO/)?
