### ISSUE TITLE
MMOEdit broken on smelting

### ISSUE THREAD

**Issue by xcrafter40** [mcMMO-Dev/mcMMO#3293]
Whenever attempting to use /mmoedit user Smelting 1 it throws out this error:
It doesn't do it with any other skills

[19:34:20 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mmoedit' in plugin mcMMO v1.5.09-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.1.jar:git-Paper-1175]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.1.jar:git-Paper-1175]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.12.1.jar:git-Paper-1175]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425) ~[patched_1.12.1.jar:git-Paper-1175]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230) ~[patched_1.12.1.jar:git-Paper-1175]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.1.jar:git-Paper-1175]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.1.jar:git-Paper-1175]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.1.jar:git-Paper-1175]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.1.jar:git-Paper-1175]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.1.jar:git-Paper-1175]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1175]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1175]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1175]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.gmail.nossr50.datatypes.player.PlayerProfile.getSkillXpLevelRaw(PlayerProfile.java:198) ~[?:?]
        at com.gmail.nossr50.commands.experience.MmoeditCommand.handleCommand(MmoeditCommand.java:27) ~[?:?]
        at com.gmail.nossr50.commands.experience.ExperienceCommand.editValues(ExperienceCommand.java:143) ~[?:?]
        at com.gmail.nossr50.commands.experience.ExperienceCommand.onCommand(ExperienceCommand.java:89) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.1.jar:git-Paper-1175]
        ... 15 more

**Comment by Momshroom** [comment]
Smelting is a child skill.   Just mmoedit their fishing and repair.

**Comment by Glitchfinder** [comment]
@t00thpick1 it looks like some of our skill commands either currently or previously needed safety features to prevent errors on child skills. Is this still an issue?

**Comment by t00thpick1** [comment]
Checks added in https://github.com/mcMMO-Dev/mcMMO/commit/29c55312a566b6dfc9d35c5e3837f215babe1caf
