### ISSUE TITLE
Error while enabling mcMMO!

### ISSUE THREAD

**Issue by Hartii14** [mcMMO-Dev/mcMMO#3309]
## **[13:08:06 ERROR]: [mcMMO] There was an error while enabling mcMMO!**
[13:08:06 WARN]: java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
[13:08:06 WARN]: at com.gmail.nossr50.config.HiddenConfig.load(HiddenConfig.java:31)
[13:08:06 WARN]: at com.gmail.nossr50.config.HiddenConfig.‹init›(HiddenConfig.java:18)
[13:08:06 WARN]: at com.gmail.nossr50.config.HiddenConfig.getInstance(HiddenConfig.java:23)
[13:08:06 WARN]: at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:400)
[13:08:06 WARN]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[13:08:06 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:08:06 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:08:06 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[13:08:06 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
[13:08:06 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
[13:08:06 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[13:08:06 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[13:08:06 WARN]: at java.lang.Thread.run(Thread.java:745)
[13:08:06 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547

**Im using Java 8 and minecraft version of server is 1.12 spigot**

### **Any help to fix that problem?**

**Comment by Hartii14** [comment]
@AgentBaron

**Comment by AgentBaron** [comment]
@Hartii14 This is what happens when you receive a summon to GitHub via an email mention expecting something worthwhile and only to find out that people simply don't understand that you're there answering questions on your time and not theirs.

I will look at this when I have time, like the plugin developers do. Please respect that.

**Comment by AgentBaron** [comment]
Are you using any other plugins? There is presently a version 1.5.09-SNAPSHOT that seems to work fine on vanilla. I recommend trying that one out without any custom configuration and if it still doesn't work, post the complete console log here.

**Comment by Glitchfinder** [comment]
You have a version mismatch. You're using a very old version of mcMMO with a current version of Minecraft. It should work if you update to a newer build from [here](https://popicraft.net/jenkins/job/mcMMO/),
