### ISSUE TITLE
Server spams this error, not sure what it is.

### ISSUE THREAD

**Issue by darktrend** [mcMMO-Dev/mcMMO#3310]
```
[10:25:36 WARN]: [mcMMO] Task #116684 for mcMMO v1.5.09-SNAPSHOT generated an exception
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$SubList.checkForComodification(Unknown Source) ~[?:1.8.0_131]
        at java.util.ArrayList$SubList.listIterator(Unknown Source) ~[?:1.8.0_131]
        at java.util.AbstractList.listIterator(Unknown Source) ~[?:1.8.0_131]
        at java.util.ArrayList$SubList.iterator(Unknown Source) ~[?:1.8.0_131]
        at com.gmail.nossr50.runnables.commands.MctopCommandDisplayTask.displayChat(MctopCommandDisplayTask.java:72) ~[?:?]
        at com.gmail.nossr50.runnables.commands.MctopCommandDisplayTask.run(MctopCommandDisplayTask.java:41) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-8bf06d6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```
----------------------------------------------------------------------------------------------------------

I think it has to do with my scoreboards I have on my server that shows power ranking. 

I am using both the HolographicDisplays & HolographicScoreboard mod to display the ranking. 
The mods refresh the scores every 10 minutes or so.

My server will produce the aforementioned error every 30 minutes or so. 

Thanks

**Comment by Glitchfinder** [comment]
Is this still an issue you're having? It looks like something is controlling scoreboards in a multithreaded fashion, which probably isn't a good idea.
