### ISSUE TITLE
There was an error enabling MCMMO(v1.5.00-b3547)

### ISSUE THREAD

**Issue by rsmcnoobie** [mcMMO-Dev/mcMMO#3325]
I'm attempting to run a bukkit server(git-Bukkit-1.7.9-R0.2-20-g0b2ed13-b3108jnks) with MCMMO using the version v1.5.00-b3547

Anytime I try to run the server it works fine but I keep getting this error for MCMMO plugin

> [02:48:31] [Server thread/INFO]: [AutoSaveWorld] Enabling AutoSaveWorld v4.15
[02:48:31] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[02:48:32] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[02:48:32] [Server thread/WARN]: java.lang.NullPointerException
[02:48:32] [Server thread/WARN]: 	at java.io.Reader.<init>(Unknown Source)
[02:48:32] [Server thread/WARN]: 	at java.io.InputStreamReader.<init>(Unknown Source)
[02:48:32] [Server thread/WARN]: 	at com.gmail.nossr50.metrics.MetricsManager.setup(MetricsManager.java:72)
[02:48:32] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:173)
[02:48:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[02:48:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[02:48:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[02:48:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:455)
[02:48:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:389)
[02:48:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.<init>(CraftServer.java:327)
[02:48:32] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.PlayerList.<init>(PlayerList.java:68)
[02:48:32] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedPlayerList.<init>(SourceFile:14)
[02:48:32] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:133)
[02:48:32] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:436)
[02:48:32] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[02:48:32] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[02:48:32] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206) ~[?:?]

**Comment by t00thpick1** [comment]
Sorry the versions you are running are very old...
