### ISSUE TITLE
Error after typing any mcmmo command (Plugin Crashes)

### ISSUE THREAD

**Issue by tyrus7141** [mcMMO-Dev/mcMMO#3332]
[01:26:36 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mcstats' in plugin mcMMO v1.5.09-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:631) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1333) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1193) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:111) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.unregister(CraftObjective.java:103) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:374) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSelfStats(ScoreboardWrapper.java:299) ~[?:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerStatsScoreboard(ScoreboardManager.java:267) ~[?:?]
        at com.gmail.nossr50.commands.player.McstatsCommand.onCommand(McstatsCommand.java:34) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        ... 15 more

**Comment by MetalGearDaner** [comment]
Did you try to update to the latest mcMMO and Spigot version?

**Comment by Glitchfinder** [comment]
There are multiple issues on the tracker that appear to be the same as or related this, so I am consolidating them all to #3406.
