### ISSUE TITLE
Correct version for mcMMO 1.8.8

### ISSUE THREAD

**Issue by CreeperHang** [mcMMO-Dev/mcMMO#3337]
My mcMMO plugin is not working
```
16.11 17:53:17 [Server] INFO [mcMMO] Enabling mcMMO v1.5.04-SNAPSHOT-b82
16.1117:53:18 [Server] ERROR [mcMMO] There was an error while enabling mcMMO!
16.11 17:53:18 [Server] WARN java.lang.StringIndexOutOfBoundsException: String index out of range: -1 
16.11 17:53:18 [Server] WARN at java.lang.String.substring(String.java:1931)
16.11 17:53:18 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreaures(TreasureConfig.java:242)
16.11 17:53:18 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:137)
16.11 17:53:18 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:74)
16.11 17:53:18 [Server] WARN at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:80)
16.11 17:53:18 [Server] WARN at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:406)
16.11 17:53:18 [Server] WARN at com.gmail.nossr50.mcMMo_OnEnable(mcMMO.java:146)
16.11 17:53:18 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
16.11 17:53:18 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
16.11 17:53:18 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
16.11 17:53:18 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
16.11 17:53:18 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
16.11 17:53:18 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
16.11 17:53:18 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
16.11 17:53:18 [Server] WARN at java.lang.Thread.run(Thread.java:748)
16.11 17:53:18 [Server] INFO [mcMMO] Disabling mcMMO v1.5.04-SNAPSHOT-b82
16.11 17:53:18 [Server] ERROR [mcMMO] Cannot read /plugins/mcMMO/experience.yml(File Permissions?)
16.11 17:53:18 [Server] ERROR [mcMMO] Cannot read /plugins/mcMMO/repair.vanilla.yml(File Permissions?)
16.11 17:53:18 [Server] ERROR Error occurred while disabling mcMMO v1.5.04-SNAPSHOT-b82 (Is it up to date?)
```
I own it 
https://proxy.spigotmc.org/718f4093340f57330d2decfcdb6fa475808fa7b3?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F370197218243772416%2F380397330756534272%2Funknown.png

**Comment by Glitchfinder** [comment]
So, that looks like it was an error with the treasure config. If you still want to use mcMMO and are still having this issue, try deleting your treasure config and then installing [this 1.8 build](https://www.t00thpick1.net/mcMMO/mcMMO_1_8.jar) to see if that works.

**Comment by neg0doce** [comment]
> So, that looks like it was an error with the treasure config. If you still want to use mcMMO and are still having this issue, try deleting your treasure config and then installing [this 1.8 build](https://www.t00thpick1.net/mcMMO/mcMMO_1_8.jar) to see if that works.

do u got this build yet buddy?
