### ISSUE TITLE
mcMMO not loading in new server

### ISSUE THREAD

**Issue by Eldeluc** [mcMMO-Dev/mcMMO#3341]
I recently setup a new server for my wife and I to play on. I noticed mcMMO did not load. In the console I do have a couple issues. The one regarding sqlite is pertaining to ChestShop but the boldened error is the error I receive about mcMMO. I did also install mcMMO Horses, which I don't think would cause the issue but should be mentioned.

I should be using the latest version of craftbukkit and mcMMO, at least they were when I downloaded them.

Any help would be greatly appreciated as mcMMO has been one of our go-to plugins for ages.

"
[14:17:09 INFO]: Starting minecraft server version 1.12.2
[14:17:09 INFO]: Loading properties
[14:17:09 INFO]: Default game type: SURVIVAL
[14:17:09 INFO]: Generating keypair
[14:17:09 INFO]: Starting Minecraft server on *:25565
[14:17:09 INFO]: Using default channel type
[14:17:10 INFO]: This server is running CraftBukkit version git-Bukkit-f46ccd7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[14:17:10 ERROR]: Could not load 'plugins\sqlite-jdbc-3.21.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[craftbukkit.jar:git-Bukkit-f46ccd7]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:304) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:188) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more
[14:17:11 INFO]: [dynmap] Loading dynmap v2.5-Dev201706100405
[14:17:11 INFO]: [dynmap] version=git-Bukkit-f46ccd7 (MC: 1.12.2)
[14:17:11 INFO]: [dynmap] Mod Support API available
[14:17:11 INFO]: [PluginConstructorAPI] Loading PluginConstructorAPI v1.0.11
[14:17:11 INFO]: [WorldEdit] Loading WorldEdit v6.1.8-SNAPSHOT;cd4729f
[14:17:11 INFO]: [TimTheEnchanter] Loading TimTheEnchanter v3.0
[14:17:11 INFO]: [Glassification] Loading Glassification v1.2.1
[14:17:11 INFO]: [NBTEditor] Loading NBTEditor v2.0.1
[14:17:11 INFO]: [ArmoredElytra] Loading ArmoredElytra v1.11
[14:17:11 INFO]: [Spawner] Loading Spawner v2.8.3-1603e95
[14:17:11 INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5.0-b727
[14:17:11 INFO]: [WorldGuard] Loading WorldGuard v6.2.1;84bc322
[14:17:11 INFO]: [AutoSaveWorld] Loading AutoSaveWorld v4.15
[14:17:11 INFO]: [Shopkeepers] Loading Shopkeepers v1.83
[14:17:11 INFO]: [UnlimitedElytra] Loading UnlimitedElytra v1.0
[14:17:11 INFO]: [Multiverse-SignPortals] Loading Multiverse-SignPortals v2.4-b523
[14:17:11 INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[14:17:11 INFO]: [mcMMOHorse] Loading mcMMOHorse v4.3.6
[14:17:11 INFO]: [Zenchantments] Loading Zenchantments v1.4.1
[14:17:11 INFO]: [CS-CoreLib] Loading CS-CoreLib v1.5.16
[14:17:11 INFO]: [mcMMO] Loading mcMMO v1.5.00-b3547
[14:17:11 INFO]: [Multiverse-NetherPortals] Loading Multiverse-NetherPortals v2.4-b530
[14:17:11 INFO]: [Multiverse-Portals] Loading Multiverse-Portals v2.5.0-b751
[14:17:11 INFO]: [Invsee_v1.0.3] Loading Invsee_v1.0.3 v1.0
[14:17:11 INFO]: [Vault] Loading Vault v1.5.6-b49
[14:17:11 INFO]: [MassiveCore] Loading MassiveCore v2.13.2
[14:17:11 INFO]: [ChestShop] Loading ChestShop v3.8.12
[14:17:11 INFO]: [Essentials] Loading Essentials v2.0.1-b488
[14:17:11 INFO]: [LiftSign] Loading LiftSign v0.4.1
[14:17:11 INFO]: [Factions] Loading Factions v2.13.2
[14:17:11 INFO]: [Slimefun] Loading Slimefun v4.1.10
[14:17:11 INFO]: [AutoSaveWorld] Enabling AutoSaveWorld v4.15
**[14:17:11 INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[14:17:11 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[14:17:11 WARN]: java.lang.NoSuchMethodError: **org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;**
[14:17:11 WARN]: at com.gmail.nossr50.config.HiddenConfig.load(HiddenConfig.java:31)
[14:17:11 WARN]: at com.gmail.nossr50.config.HiddenConfig.(HiddenConfig.java:18)
[14:17:11 WARN]: at com.gmail.nossr50.config.HiddenConfig.getInstance(HiddenConfig.java:23)
[14:17:11 WARN]: at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:400)
[14:17:11 WARN]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[14:17:11 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:17:11 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329)
[14:17:11 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[14:17:11 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:368)
[14:17:11 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329)
[14:17:11 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:189)
[14:17:11 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522)
[14:17:11 WARN]: at java.lang.Thread.run(Unknown Source)
[14:17:11 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[14:17:11 ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
at com.gmail.nossr50.config.AutoUpdateConfigLoader.loadFile(AutoUpdateConfigLoader.java:29) ~[?:?]
at com.gmail.nossr50.config.ConfigLoader.(ConfigLoader.java:26) ~[?:?]
at com.gmail.nossr50.config.AutoUpdateConfigLoader.(AutoUpdateConfigLoader.java:23) ~[?:?]
at com.gmail.nossr50.config.AdvancedConfig.(AdvancedConfig.java:20) ~[?:?]
at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:26) ~[?:?]
at com.gmail.nossr50.skills.alchemy.Alchemy.(Alchemy.java:51) ~[?:?]
at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:203) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[craftbukkit.jar:git-Bukkit-f46ccd7]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:353) [craftbukkit.jar:git-Bukkit-f46ccd7]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [craftbukkit.jar:git-Bukkit-f46ccd7]
at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [craftbukkit.jar:git-Bukkit-f46ccd7]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit.jar:git-Bukkit-f46ccd7]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Bukkit-f46ccd7]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:368) [craftbukkit.jar:git-Bukkit-f46ccd7]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [craftbukkit.jar:git-Bukkit-f46ccd7]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:189) [craftbukkit.jar:git-Bukkit-f46ccd7]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit.jar:git-Bukkit-f46ccd7]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]**
[14:17:11 INFO]: [Vault] Enabling Vault v1.5.6-b49
[14:17:11 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[14:17:11 INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[14:17:11 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[14:17:11 INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[14:17:11 INFO]: [Vault] Enabled Version 1.5.6-b49
[14:17:11 INFO]: [MassiveCore] Enabling MassiveCore v2.13.2
[14:17:11 INFO]: [MassiveCore 2.13.2] === ENABLE START ===
[14:17:12 INFO]: [MassiveCore 2.13.2] Loading Cachefile datas...
[14:17:12 INFO]: [MassiveCore 2.13.2] Loading Onlineplayer datas...
[14:17:12 INFO]: [MassiveCore 2.13.2] Loading Registry datas...
[14:17:12 INFO]: [MassiveCore 2.13.2] Saving Cachefile...
[14:17:12 INFO]: [MassiveCore 2.13.2] Setup of IdUtil took 20ms.
[14:17:13 INFO]: [MassiveCore 2.13.2] Integration Activated IntegrationLiabilityAreaEffectCloud
[14:17:13 INFO]: [MassiveCore 2.13.2] Integration Activated IntegrationVault
[14:17:13 INFO]: [MassiveCore 2.13.2] === ENABLE COMPLETE (Took 1651ms) ===
[14:17:13 INFO]: Preparing level "world"
[14:17:14 INFO]: Preparing start region for level 0 (Seed: -878844257865637085)
[14:17:15 INFO]: Preparing spawn area: 0%
[14:17:16 INFO]: Preparing spawn area: 62%
[14:17:16 INFO]: Preparing start region for level 1 (Seed: 4204507391965698344)
[14:17:17 INFO]: Preparing start region for level 2 (Seed: 4204507391965698344)
[14:17:17 INFO]: [dynmap] Enabling dynmap v2.5-Dev201706100405
[14:17:17 INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[14:17:17 INFO]: [PermissionsEx] Initializing file backend
[14:17:17 INFO]: [PermissionsEx] Permissions file successfully reloaded
[14:17:17 INFO]: [Vault][Permission] PermissionsEx hooked.
[14:17:17 INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
[14:17:17 INFO]: [dynmap] Using PermissionsEx 1.23.4 for access control
[14:17:18 INFO]: [dynmap] Mod Support processing completed
[14:17:19 INFO]: [dynmap] Loaded 23 shaders.
[14:17:19 INFO]: [dynmap] Loaded 82 perspectives.
[14:17:19 INFO]: [dynmap] Loaded 14 lightings.
[14:17:19 INFO]: [dynmap] Web server started on address 0.0.0.0:8123
[14:17:19 INFO]: [dynmap] version 2.5-Dev201706100405 is enabled - core version 2.5-Dev201706100401
[14:17:19 INFO]: [dynmap] Loaded 3 maps of world 'world'.
[14:17:19 INFO]: [dynmap] Loaded 2 maps of world 'world_nether'.
[14:17:19 INFO]: [dynmap] Loaded 2 maps of world 'world_the_end'.
[14:17:19 INFO]: [dynmap] Enabled
[14:17:19 INFO]: [PluginConstructorAPI] Enabling PluginConstructorAPI v1.0.11
[14:17:19 INFO]: [WorldEdit] Enabling WorldEdit v6.1.8-SNAPSHOT;cd4729f
[14:17:20 INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[14:17:20 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R2 as the Bukkit adapter
[14:17:20 INFO]: [TimTheEnchanter] Enabling TimTheEnchanter v3.0
[14:17:20 INFO]: [Tim] Unused enchantments: MENDING(70) VANISHING_CURSE(71) DEPTH_STRIDER(8) FROST_WALKER(9) BINDING_CURSE(10) SWEEPING_EDGE(22) LUCK(61) LURE(62)
[14:17:20 INFO]: [TimTheEnchanter] There are some who call me... Tim?
[14:17:20 INFO]: [Glassification] Enabling Glassification v1.2.1
[14:17:20 INFO]: Glassification v1.2.1 enabled
[14:17:20 INFO]: [NBTEditor] Enabling NBTEditor v2.0.1
[14:17:20 ERROR]: [NBTEditor] Error preparing reflection objects
java.lang.RuntimeException: Error while preparing NBT wrapper classes.
        at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:53) ~[NBTEditor.jar:?]
        at com.goncalomb.bukkit.nbteditor.NBTEditor.onEnable(NBTEditor.java:72) [NBTEditor.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:368) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.ItemStack.createStack(net.minecraft.server.v1_12_R1.NBTTagCompound)
        at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_151]
        at com.goncalomb.bukkit.mylib.reflect.NBTUtils.prepareReflection(NBTUtils.java:65) ~[?:?]
        at com.goncalomb.bukkit.mylib.reflect.NBTBase.prepareReflection(NBTBase.java:51) ~[?:?]
        ... 12 more
[14:17:20 ERROR]: [NBTEditor] This version of NBTEditor is not compatible with this version of Bukkit
[14:17:20 INFO]: [ArmoredElytra] Enabling ArmoredElytra v1.11
[14:17:20 WARN]: [AutoSaveWorld] Plugin ArmoredElytra attempted to establish connection https://api.curseforge.com/servermods/files?projectIds=278437 in main server thread
[14:17:20 INFO]: [ArmoredElytra] You seem to be using the latest version of this plugin!
[14:17:20 INFO]: [ArmoredElytra] Enabling stats!
[14:17:20 INFO]: [ArmoredElytra] Allowed enchantments:
[14:17:20 INFO]: [ArmoredElytra]  - DURABILITY
[14:17:20 INFO]: [ArmoredElytra]  - PROTECTION_FIRE
[14:17:20 INFO]: [ArmoredElytra]  - PROTECTION_EXPLOSIONS
[14:17:20 INFO]: [ArmoredElytra]  - PROTECTION_PROJECTILE
[14:17:20 INFO]: [ArmoredElytra]  - PROTECTION_ENVIRONMENTAL
[14:17:20 INFO]: [ArmoredElytra]  - THORNS
[14:17:20 INFO]: [ArmoredElytra] Curses on armored elytras are
[14:17:20 INFO]: [Spawner] Enabling Spawner v2.8.3-1603e95
[14:17:20 INFO]: [Spawner] Loading support for v1_12_R1
[14:17:20 ERROR]: [Spawner] Plugin Spawner v2.8.3-1603e95 has failed to register events for class me.ryvix.spawner.SpawnerEvents because org/bukkit/event/entity/SpawnerSpawnEvent does not exist.
[14:17:20 INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5.0-b727
[14:17:21 WARN]: [Multiverse-Core] Exception while loading value for environment
[14:17:21 WARN]: [Multiverse-Core] Exception while loading value for environment
[14:17:21 WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: Fiorecraft
[14:17:21 WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!
[14:17:21 INFO]: [Multiverse-Core] 3 - World(s) loaded.
[14:17:21 INFO]: [Multiverse-Core] Version 2.5.0-b727 (API v20) Enabled - By Rigby, fernferret, lithium3141, main-- and dumptruckman
[14:17:21 INFO]: [WorldGuard] Enabling WorldGuard v6.2.1;84bc322
[14:17:21 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[14:17:21 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[14:17:21 INFO]: [WorldGuard] (world) Lava fire is blocked.
[14:17:21 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[14:17:21 INFO]: [WorldGuard] Loaded configuration for world 'world'
[14:17:21 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[14:17:21 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[14:17:21 INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[14:17:21 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[14:17:21 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[14:17:21 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[14:17:21 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[14:17:21 INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[14:17:21 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[14:17:21 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[14:17:21 INFO]: [WorldGuard] Loading region data...
[14:17:21 INFO]: [Shopkeepers] Enabling Shopkeepers v1.83
[14:17:22 INFO]: [UnlimitedElytra] Enabling UnlimitedElytra v1.0
[14:17:22 ERROR]: [UnlimitedElytra] Plugin UnlimitedElytra v1.0 has failed to register events for class it.lupus.plugin.Main because org/bukkit/event/player/PlayerItemDamageEvent does not exist.
[14:17:22 INFO]: [Multiverse-SignPortals] Enabling Multiverse-SignPortals v2.4-b523
[14:17:22 INFO]: [Multiverse-SignPortals] - Version 2.4-b523 Enabled - By Rigby and fernferret
[14:17:22 INFO]: [mcMMOHorse] Enabling mcMMOHorse v4.3.6
[14:17:22 WARN]: [AutoSaveWorld] Plugin mcMMOHorse attempted to establish connection https://api.curseforge.com/servermods/files?projectIds=61609 in main server thread
[14:17:22 INFO]: [Zenchantments] Enabling Zenchantments v1.4.1
[14:17:22 INFO]: [CS-CoreLib] Enabling CS-CoreLib v1.5.16
[14:17:22 INFO]: [Multiverse-NetherPortals] Enabling Multiverse-NetherPortals v2.4-b530
[14:17:22 INFO]: [MultiVerse-NetherPortals] - Version 2.4-b530 Enabled - By Rigby and fernferret
[14:17:22 INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.5.0-b751
[14:17:22 INFO]: [Multiverse-Portals] - Version 2.5.0-b751 Enabled - By Rigby and fernferret
[14:17:22 INFO]: [MVPLogging] 0 - Portals(s) loaded
[14:17:22 INFO]: [Multiverse-Portals] Found WorldEdit. Using it for selections.
[14:17:22 INFO]: [Invsee_v1.0.3] Enabling Invsee_v1.0.3 v1.0
[14:17:22 INFO]: [Invsee] Invsee v1.0.3 by TehCoderHD has been enabled successfully!
[14:17:22 INFO]: [ChestShop] Enabling ChestShop v3.8.12
[14:17:23 ERROR]: WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
[14:17:23 INFO]: creating table 'items'
[14:17:23 INFO]: executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `items` (`id` INTEGER PRIMARY KEY AUTOINCREMENT , `code` VARCHAR NOT NULL ,  UNIQUE (`code`))
[14:17:23 ERROR]: WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
[14:17:23 INFO]: creating table 'accounts'
[14:17:23 INFO]: creating index 'accounts_shortName_idx' for table 'accounts
[14:17:23 INFO]: executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `accounts` (`lastSeenName` VARCHAR NOT NULL , `name` VARCHAR NOT NULL , `shortName` VARCHAR NOT NULL , `uuid` VARCHAR NOT NULL , PRIMARY KEY (`name`) )
[14:17:23 INFO]: executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_shortName_idx` ON `accounts` ( `shortName` )
[14:17:23 WARN]: [AutoSaveWorld] Plugin ChestShop attempted to establish connection socket://api.mojang.com:443 in main server thread
[14:17:23 INFO]: [ChestShop] Vault loaded! Found an economy plugin!
[14:17:23 INFO]: [Essentials] Enabling Essentials v2.0.1-b488
[14:17:23 INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[14:17:23 INFO]: [Essentials] Using Reflection based provider as spawn egg provider.
[14:17:23 INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
[14:17:23 INFO]: Using locale en_US
[14:17:24 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[14:17:24 INFO]: [Vault][Economy] Essentials Economy hooked.
[14:17:24 INFO]: [Essentials] Using Vault based permissions (PermissionsEx)
[14:17:24 INFO]: [LiftSign] Enabling LiftSign v0.4.1
[14:17:24 INFO]: [LiftSign] Loaded 6 locale strings (0 overrides)
[14:17:24 INFO]: [LiftSign] using VAULT:PermissionsEx for permissions
[14:17:24 INFO]: [LiftSign] version 0.4.1, build 252 is enabled
[14:17:24 INFO]: [Factions] Enabling Factions v2.13.2
[14:17:24 INFO]: [Factions 2.13.2] === ENABLE START ===
[14:17:25 INFO]: [Factions 2.13.2] Integration Activated IntegrationV18
[14:17:25 INFO]: [Factions 2.13.2] Integration Activated IntegrationV19
[14:17:25 INFO]: [Factions 2.13.2] Integration Activated IntegrationSpigot
[14:17:25 INFO]: [Factions 2.13.2] Integration Activated IntegrationWorldGuard
[14:17:25 INFO]: [Factions 2.13.2] === ENABLE COMPLETE (Took 991ms) ===
[14:17:25 INFO]: [Slimefun] Enabling Slimefun v4.1.10
[14:17:25 INFO]: [Slimefun] Loading Files...
[14:17:25 INFO]: [Slimefun] Loading Config...
[14:17:25 INFO]: [Slimefun] Loading Items...
[14:17:26 INFO]: [Slimefun] Loading Researches...
[14:17:26 INFO]: [Slimefun] Loading World Generators...
[14:17:26 INFO]: [Slimefun - GEO] Registering Ore Gen: Oil
[14:17:26 INFO]: [Slimefun - GEO] Registering Ore Gen: Nether Ice
[14:17:26 INFO]: [Slimefun] Successfully hooked into WorldEdit!
[14:17:26 INFO]: [Slimefun] Finished!
[14:17:26 INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:17:26 INFO]: Done (13.115s)! For help, type "help" or "?"
[14:17:26 INFO]: [CS-CoreLib - Protection] Loaded Protection Module "WorldGuard"
[14:17:26 INFO]: [CS-CoreLib - Protection] Loaded Protection Module "Factions"
[14:17:26 WARN]: [ChestShop] Plugin ChestShop v3.8.12 generated an exception while executing task 110
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.Acrobot.ChestShop.Metrics.postPlugin(Metrics.java:335) ~[?:?]
        at com.Acrobot.ChestShop.Metrics.access$400(Metrics.java:57) ~[?:?]
        at com.Acrobot.ChestShop.Metrics$1.run(Metrics.java:223) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit.jar:git-Bukkit-f46ccd7]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit.jar:git-Bukkit-f46ccd7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_151]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[14:17:26 INFO]: ###################### - Slimefun - ######################
[14:17:26 INFO]: Successfully loaded 464 Items (224 Researches)
[14:17:26 INFO]: ( 464 Items from Slimefun, 0 Items from Addons )
[14:17:26 INFO]: ##########################################################
[14:17:27 INFO]: [Slimefun] Loading Blocks for World "world"
[14:17:27 INFO]: [Slimefun] This may take a long time...
[14:17:27 INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 0ms)
[14:17:27 INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world"
[14:17:27 INFO]: [Slimefun] Loading Blocks for World "world_nether"
[14:17:27 INFO]: [Slimefun] This may take a long time...
[14:17:27 INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 1ms)
[14:17:27 INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world_nether"
[14:17:27 INFO]: [Slimefun] Loading Blocks for World "world_the_end"
[14:17:27 INFO]: [Slimefun] This may take a long time...
[14:17:27 INFO]: [Slimefun] Loading Blocks... 100% (FINISHED - 0ms)
[14:17:27 INFO]: [Slimefun] Loaded a total of 0 Blocks for World "world_the_end"
[14:17:27 INFO]: [Vault] Checking for Updates ...
[14:17:27 INFO]: [Vault] No new version available
[14:17:28 INFO]: [CS-CoreLib - Updater] Slimefun is up to date!
[14:17:31 INFO]:
[14:17:31 INFO]: ____----====[ Sponsored by ServerMiner ]====----____
[14:17:31 INFO]: Get a FREE 2GB RAM Premium Minecraft Server at ServerMiner:
[14:17:31 INFO]: https://ServerMiner.com/free
[14:17:31 INFO]:
[14:17:31 INFO]: Factions and MassiveCore is sponsored by ServerMiner.com!
[14:17:31 INFO]: They help us fund the development of new plugin features.
[14:17:31 INFO]:
[14:17:31 INFO]: Only server operators get this message, not regular players.
[14:17:31 INFO]: Type /mcore sponsor to disable it.
"

**Comment by t00thpick1** [comment]
Use a newer version of mcMMO the version you are running is about 3-4 years old
