### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WindUnwaken** [mcMMO-Dev/mcMMO#3344]
```[03:19:43 WARN]: [mcMMO] Task #26 for mcMMO v1.5.09-SNAPSHOT generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_151]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_151]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_151]
	at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:24) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched.jar:git-TacoSpigot-"fe7806b0"]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched.jar:git-TacoSpigot-"fe7806b0"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched.jar:git-TacoSpigot-"fe7806b0"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched.jar:git-TacoSpigot-"fe7806b0"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched.jar:git-TacoSpigot-"fe7806b0"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched.jar:git-TacoSpigot-"fe7806b0"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

```
Sometimes, it show on console, but really don't know how it happend,

**Comment by LogGits** [comment]
I am also getting this error on paperspigot:
```
02:53:33[mcMMO] Task #21 for mcMMO v1.5.09-SNAPSHOT generated an exception
Console 13/02/2018 02:53:33
02:53:33java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_161]
at java.util.HashMap$EntryIterator.next(HashMap.java:1476) ~[?:1.8.0_161]
at java.util.HashMap$EntryIterator.next(HashMap.java:1474) ~[?:1.8.0_161]
at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:24) ~[mcMMO.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1322]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1322]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1322]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1322]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1322]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1322]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by Glitchfinder** [comment]
I see that [this line](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/runnables/skills/BleedTimerTask.java#L24) is what causes the error, but I'm not entirely sure why that's throwing a concurrency error, since that's a threading issue and bleed shouldn't be threaded.

@t00thpick1, any ideas?

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
