### ISSUE TITLE
mcMMO 1.8 Not Working From Dev Builds

### ISSUE THREAD

**Issue by nblockbuster2500** [mcMMO-Dev/mcMMO#3357]
My server is running spigot 1.8.8 with viaversion upgrading it from 1.8.x-1.12.x

Here's the issue in my server log:
```
[16:14:13] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[16:14:13] [Server thread/WARN]: [mcMMO] Invalid Potion_Type: 0|POISON
[16:14:13] [Server thread/WARN]: [mcMMO] Invalid Potion_Type: POTION|0|INSTANT_HEAL
[16:14:13] [Server thread/WARN]: [mcMMO] Invalid Potion_Type: POTION|0|FIRE_RESISTANCE
[16:14:13] [Server thread/WARN]: [mcMMO] Invalid Potion_Type: POTION|0|SPEED
[16:14:13] [Server thread/WARN]: [mcMMO] Invalid material: INVENTORY
[16:14:13] [Server thread/WARN]: [mcMMO] Amount of INVENTORY must be greater than 0! 0
[16:14:13] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[16:14:13] [Server thread/WARN]: java.lang.NullPointerException
[16:14:13] [Server thread/WARN]: 	at java.io.Reader.<init>(Reader.java:78)
[16:14:13] [Server thread/WARN]: 	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
[16:14:13] [Server thread/WARN]: 	at com.gmail.nossr50.metrics.MetricsManager.setup(MetricsManager.java:72)
[16:14:13] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:173)
[16:14:13] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[16:14:13] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[16:14:13] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:14:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[16:14:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[16:14:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[16:14:13] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[16:14:13] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:14:13] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[16:14:32] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_91]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_91]
	at org.bukkit.craftbukkit.v1_8_R3.CraftOfflinePlayer.<init>(CraftOfflinePlayer.java:34) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.getOfflinePlayer(CraftServer.java:1335) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.getOfflinePlayer(CraftServer.java:1304) ~[spigot.jar:git-Spigot-db6de12-d3e0b6f]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:133) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:121) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.<clinit>(ScoreboardManager.java:43) ~[?:?]
	... 13 more
```

**Comment by popcorn9499** [comment]
I dont know much all i know is i saw this. https://github.com/mcMMO-Dev/mcMMO/issues/3030 Apparently they dont support 1.8.8 no more

**Comment by Glitchfinder** [comment]
Is this still an issue you're having? I know one of the last commits for 1.8 removed Metrics, which shows up in your error stacktrace. If you're still running the 1.8 server and having this issue, would you be able to try [this build](https://www.t00thpick1.net/mcMMO/mcMMO_1_8.jar) to see if it works?
