### ISSUE TITLE
mcMMO start up error

### ISSUE THREAD

**Issue by Flavourized** [mcMMO-Dev/mcMMO#3367]
Getting this error on the December 17, 2017 mcmmo build. October 27, 2017 build works fine. 

We are using Paper 1.11.2 b1104. 

```
[05:18:06] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.09-SNAPSHOT
[05:18:06] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[05:18:06] [Server thread/WARN]: java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
[05:18:06] [Server thread/WARN]: 	at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:161)
[05:18:06] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)
[05:18:06] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
[05:18:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[05:18:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[05:18:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[05:18:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378)
[05:18:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328)
[05:18:06] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:209)
[05:18:06] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612)
[05:18:06] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[05:18:06] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.NamespacedKey
[05:18:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[05:18:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[05:18:06] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[05:18:06] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[05:18:06] [Server thread/WARN]: 	... 11 more
[05:18:06] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.09-SNAPSHOT

```

**Comment by t00thpick1** [comment]
Gah spigot should not break something and replace it in the same release... Now I have to do hacky things to support both new and old version ._.

**Comment by Flavourized** [comment]
Nothing wrong with my server right? 

More worried that if mcmmo is broken, other stuff might break too

**Comment by t00thpick1** [comment]
No its API changes in the latest versions of spigot that I updated to but apparently aren't backwards compatible.

**Comment by ZMASLO** [comment]
Is there any fix for that issue? Having same problem on version 1.11

**Comment by Aquind** [comment]
Should we just use an older version?  I am having the same issue running 1.11
-------------------
07.02 21:21:21 [Server] ERROR There was an error while enabling mcMMO!
07.02 21:21:21 [Server] WARN java.lang.NoClassDefFoundError: org/bukkit/NamespacedKey
07.02 21:21:21 [Server] WARN at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:161)
07.02 21:21:21 [Server] WARN at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)
07.02 21:21:21 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
07.02 21:21:21 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
07.02 21:21:21 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
07.02 21:21:21 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
07.02 21:21:21 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
07.02 21:21:21 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
07.02 21:21:21 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205)
07.02 21:21:21 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
07.02 21:21:21 [Server] WARN at java.lang.Thread.run(Thread.java:745)
07.02 21:21:21 [Server] WARN Caused by: java.lang.ClassNotFoundException: org.bukkit.NamespacedKey
07.02 21:21:21 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
07.02 21:21:21 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
07.02 21:21:21 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
07.02 21:21:21 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
07.02 21:21:21 [Server] WARN ... 11 more
07.02 21:21:21 [Server] INFO Disabling mcMMO v1.5.09-SNAPSHOT

**Comment by Glitchfinder** [comment]
@t00thpick1 does this mean there's an explicit version break now, or have you managed to address this somehow?

**Comment by t00thpick1** [comment]
There is an explicit version break.
