### ISSUE TITLE
Spamming error messages

### ISSUE THREAD

**Issue by freethemice** [mcMMO-Dev/mcMMO#3389]
`[08:23:25] [Server thread/WARN]: [mcMMO] Task #24059010 for mcMMO v1.5.09-SNAPSHOT generated an exception
java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.getScore(CraftObjective.java:97) ~[spigot.jar:git-Spigot-549c1fa-45c8386]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.updateSidebar(ScoreboardWrapper.java:423) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.access$000(ScoreboardWrapper.java:30) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper$ScoreboardQuickUpdate.run(ScoreboardWrapper.java:75) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

and this one to
`[08:25:19] [Server thread/ERROR]: Could not pass event McMMOPlayerLevelUpEvent to mcMMO v1.5.09-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at com.gmail.nossr50.util.EventUtils.handleLevelChangeEvent(EventUtils.java:70) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:503) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:477) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:440) [mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:430) [mcMMO.jar:?]
	at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:32) [mcMMO.jar:?]
	at com.gmail.nossr50.skills.mining.MiningManager.miningBlockCheck(MiningManager.java:62) [mcMMO.jar:?]
	at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:210) [mcMMO.jar:?]
	at sun.reflect.GeneratedMethodAccessor433.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:192) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:875) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-549c1fa-45c8386]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:112) ~[spigot.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.unregister(CraftObjective.java:104) ~[spigot.jar:git-Spigot-549c1fa-45c8386]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:374) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSkill(ScoreboardWrapper.java:288) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerSkillLevelUpScoreboard(ScoreboardManager.java:258) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.handleLevelUp(ScoreboardManager.java:214) ~[?:?]
	at com.gmail.nossr50.listeners.SelfListener.onPlayerLevelUp(SelfListener.java:24) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-549c1fa-45c8386]
	... 32 more`

have the lasted version on the spigot website of the plugin and spigot is uptodate

**Comment by Glitchfinder** [comment]
There are multiple issues on the tracker that appear to be the same as this, so I am consolidating them all to #3406.
