### ISSUE TITLE
Can't convert levels from linear to exponential

### ISSUE THREAD

**Issue by Prxmium** [mcMMO-Dev/mcMMO#3408]
Server version: git-Spigot-4bd94dc-fb414fe (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Version: mcMMO v1.5.09

I'm trying to /mcconvert experience EXPONENTIAL and it's saying "starting conversion from UNKNOWN to EXPONENTIAL curve", and then it writes out this error to the console

```
[06:11:39] [Server thread/WARN]: [mcMMO] Task #728 for mcMMO v1.5.09-SNAPSHOT generated an exception
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_151]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:101) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.retrieveMcMMOPlayer(UserManager.java:115) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:97) ~[?:?]
	at com.gmail.nossr50.runnables.database.FormulaConversionTask.run(FormulaConversionTask.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by cbassett1000** [comment]
I second this on 1.6.0, 1.13 server.  Bug still exists.

**Comment by NicsGames** [comment]
Also can confirm it is still happening. 1.13.2 paper server.

11.12 15:32:07 [Server] WARN Task #11 for mcMMO v1.6.0-SNAPSHOT generated an exception
11.12 15:32:07 [Server] INFO java.util.ConcurrentModificationException: null
11.12 15:32:07 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_191]
11.12 15:32:07 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1476) ~[?:1.8.0_191]
11.12 15:32:07 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1474) ~[?:1.8.0_191]
11.12 15:32:07 [Server] INFO at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:24) ~[?:?]
11.12 15:32:07 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-474]
11.12 15:32:07 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-474]
11.12 15:32:07 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-474]
11.12 15:32:07 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-474]
11.12 15:32:07 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-474]
11.12 15:32:07 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-474]
11.12 15:32:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
