### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by MrKiller01** [mcMMO-Dev/mcMMO#3410]
[12:17:02 INFO]: [mcMMO] Enabling mcMMO v1.5.09-SNAPSHOT
[12:17:02 WARN]: Enabled plugin with unregistered PluginClassLoader mcMMO v1.5.0
9-SNAPSHOT
[12:17:02 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[12:17:02 WARN]: java.lang.IllegalArgumentException: Stream cannot be null
[12:17:02 WARN]:        at org.apache.commons.lang.Validate.notNull(Validate.jav
a:192)
[12:17:02 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadC
onfiguration(YamlConfiguration.java:201)
[12:17:02 WARN]:        at com.gmail.nossr50.config.AutoUpdateConfigLoader.loadF
ile(AutoUpdateConfigLoader.java:28)
[12:17:02 WARN]:        at com.gmail.nossr50.config.ConfigLoader.<init>(ConfigLo
ader.java:26)
[12:17:02 WARN]:        at com.gmail.nossr50.config.AutoUpdateConfigLoader.<init
>(AutoUpdateConfigLoader.java:22)
[12:17:02 WARN]:        at com.gmail.nossr50.skills.child.ChildConfig.<init>(Chi
ldConfig.java:13)
[12:17:02 WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:38
9)
[12:17:02 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
[12:17:02 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlug
in.java:264)
[12:17:02 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(
JavaPluginLoader.java:337)
[12:17:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(Si
mplePluginManager.java:403)
[12:17:02 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.
java:366)
[12:17:02 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(Load
Command.java:114)
[12:17:02 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(
PlugManCommandHandler.java:95)
[12:17:02 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[12:17:02 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[12:17:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchC
ommand(CraftServer.java:648)
[12:17:02 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchS
erverCommand(CraftServer.java:634)
[12:17:02 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(Dedi
catedServer.java:444)
[12:17:02 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(Dedic
atedServer.java:407)
[12:17:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(Minec
raftServer.java:679)
[12:17:02 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(Min
ecraftServer.java:577)
[12:17:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:17:02 INFO]: [mcMMO] Disabling mcMMO v1.5.09-SNAPSHOT

**Comment by MrKiller01** [comment]
I think the problem was related to the mysql connection.... Now that I have that in order, i do not see anything weird.... Hope this explains it.
