### ISSUE TITLE
McMMo not working

### ISSUE THREAD

**Issue by yitzil** [mcMMO-Dev/mcMMO#3414]
[01:15:37 INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
>
[01:15:37 ERROR]: [mcMMO] There was an error while enabling mcMMO!
> [01:15:37 WARN]: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
> [01:15:37 WARN]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:163)
> [01:15:37 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291)
> [01:15:37 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
> [01:15:37 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
> [01:15:37 WARN]: at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
> [01:15:37 WARN]: at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
> [01:15:37 WARN]: at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202)
> [01:15:37 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522)
> [01:15:37 WARN]: at java.lang.Thread.run(Thread.java:748)
> [01:15:37 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
>
[01:15:37 ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:53) ~[?:?]
at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:204) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-7d15d07-c194444]
at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-7d15d07-c194444]
at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot.jar:git-Spigot-7d15d07-c194444]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-7d15d07-c194444]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
>

**Comment by Glitchfinder** [comment]
You're trying to use an mcMMO build made for Mincraft 1.12 on a Minecraft 1.9 server. You're going to need an older version made for Minecraft 1.9 (or earlier) if you want it to work properly.
