### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mayzone** [mcMMO-Dev/mcMMO#3425]
Might be replicated from mobarena

```
[00:52:40] [Server thread/ERROR]: Could not pass event EntityDamageEvent to MobArena v0.99
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:580) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:566) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:612) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity0(EntityLiving.java:1344) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:868) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityHorseAbstract.damageEntity(EntityHorseAbstract.java:166) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.Entity.Y(Entity.java:439) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityLiving.Y(EntityLiving.java:204) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityInsentient.Y(EntityInsentient.java:186) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.Entity.B_(Entity.java:320) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1871) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityHorseAbstract.B_(EntityHorseAbstract.java:526) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ClassCastException
[00:55:10] [Server thread/INFO]: R.I.P mekkil was slain by Enderman
[00:57:18] [Async Chat Thread - #32/INFO]: mekkil [Hardcore] [Novice-Miner] i hate endermens... i cant shot them whit my bow... and im useles with a sword XD
[00:57:23] [Server thread/INFO]: mekkil issued server command: /home
[00:57:25] [Async Chat Thread - #32/INFO]: killzone014 [Admin] [Novice-Miner] XD
[00:57:34] [Server thread/INFO]: mekkil issued server command: /ma leave
[00:57:34] [Server thread/INFO]: [@: Set mekkil's spawn point to (1532, 43, 906)]
[00:57:37] [Server thread/INFO]: [@: Set mekkil's spawn point to (1532, 43, 906)]
[00:57:38] [Server thread/INFO]: [@: Set mekkil's spawn point to (1532, 43, 906)]
[00:57:43] [Server thread/INFO]: mekkil issued server command: /home
[00:58:39] [Server thread/INFO]: Mayzone lost connection: Disconnected
[00:58:39] [Thread-23/INFO]: SaveRunner:me.dablakbandit.bank.players.Players@7b6c992c
[00:58:39] [Thread-23/INFO]: [Bank] Saving Bank for 26e81705-c68f-4d10-b67e-53aefa4890fe to SQLLite
[00:58:39] [Thread-23/INFO]: [Bank] Saved Bank for 26e81705-c68f-4d10-b67e-53aefa4890fe to SQLLite, took 1 ms
[00:59:04] [Server thread/INFO]: mekkil lost connection: Disconnected
[00:59:04] [Thread-23/INFO]: SaveRunner:me.dablakbandit.bank.players.Players@2a7ea69a
[00:59:04] [Thread-23/INFO]: [Bank] Saving Bank for 852427f3-7b91-49dd-9059-e1b04180ab75 to SQLLite
[00:59:04] [Thread-23/INFO]: [Bank] Saved Bank for 852427f3-7b91-49dd-9059-e1b04180ab75 to SQLLite, took 0 ms
[01:00:42] [Server thread/INFO]: Given [Iron Nugget] * 1 to namtrah
[01:02:02] [Server thread/INFO]: killzone014 issued server command: /gms
[01:02:06] [Server thread/INFO]: killzone014 issued server command: /fly
[01:02:34] [Server thread/INFO]: killzone014 issued server command: /shop
[01:02:37] [Server thread/INFO]: killzone014 issued server command: /spawn
[01:02:38] [Server thread/INFO]: [@: Set killzone014's spawn point to (1532, 43, 906)]
[01:03:06] [Server thread/INFO]: killzone014 issued server command: /back

[01:04:31] [Server thread/ERROR]: Could not pass event PlayerStatisticIncrementEvent to mcMMO v1.5.09-SNAPSHOT
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleStatisticsIncrease(CraftEventFactory.java:1003) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.StatisticManager.b(StatisticManager.java:14) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:962) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityHuman.b(EntityHuman.java:1382) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityHuman.cu(EntityHuman.java:1397) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.moveOnCurrentHeading(EntityHumanNPC.java:354) [Citizens.jar:?]
at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:146) [Citizens.jar:?]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1007) [Citizens.jar:?]
at net.citizensnpcs.util.NMS.tick(NMS.java:270) [Citizens.jar:?]
at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [Citizens.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_141]
at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:101) ~[?:?]
at com.gmail.nossr50.util.HolidayManager.levelUpApril(HolidayManager.java:378) ~[?:?]
at com.gmail.nossr50.util.HolidayManager.handleStatisticEvent(HolidayManager.java:373) ~[?:?]
at com.gmail.nossr50.listeners.PlayerListener.onPlayerStatisticIncrementEvent(PlayerListener.java:707) ~[?:?]
at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
... 21 more
[01:04:32] [Server thread/INFO]: killzone014 lost connection: Disconnected
[01:04:32] [Thread-23/INFO]: SaveRunner:me.dablakbandit.bank.players.Players@77564d77
[01:04:32] [Thread-23/INFO]: [Bank] Saving Bank for f6fbf911-7daa-4b52-ae0c-fbeb31680d45 to SQLLite
[01:04:32] [Thread-23/INFO]: [Bank] Saved Bank for f6fbf911-7daa-4b52-ae0c-fbeb31680d45 to SQLLite, took 0 ms
[01:04:36] [User Authenticator #51/INFO]: UUID of player killzone014 is f6fbf911-7daa-4b52-ae0c-fbeb31680d45
[01:04:36] [Server thread/INFO]: #killzone014 joined - Welcome!
[01:04:36] [Server thread/INFO]: killzone014[/107.190.102.67:38826] logged in with entity id 1172969 at ([world]1896.1963208992076, 63.0, 1340.0259655548293)
[01:04:36] [Thread-23/INFO]: LoadRunner:me.dablakbandit.bank.players.Players@3e145ec3
[01:04:36] [Thread-23/INFO]: [Bank] Loading Bank for f6fbf911-7daa-4b52-ae0c-fbeb31680d45 from SQLLite
[01:04:36] [Thread-23/INFO]: [Bank] Loaded Bank for f6fbf911-7daa-4b52-ae0c-fbeb31680d45 from SQLLite, took 0 ms
[01:06:48] [Server thread/INFO]: killzone014 issued server command: /home
[01:07:00] [Server thread/INFO]: killzone014 issued server command: /home drgon
[01:08:30] [Server thread/INFO]: namtrah issued server command: /home
[01:12:32] [Thread-17/INFO]: [Bank] Giving money interest
[01:12:32] [Thread-17/INFO]: [Bank] Finished giving money interest, took 0ms
[01:20:36] [Server thread/INFO]: namtrah issued server command: /HOME

[01:20:42] [Server thread/ERROR]: Could not pass event PlayerStatisticIncrementEvent to mcMMO v1.5.09-SNAPSHOT
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleStatisticsIncrease(CraftEventFactory.java:1003) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.StatisticManager.b(StatisticManager.java:14) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:962) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityHuman.b(EntityHuman.java:1382) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.EntityHuman.cu(EntityHuman.java:1397) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.moveOnCurrentHeading(EntityHumanNPC.java:354) [Citizens.jar:?]
at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:146) [Citizens.jar:?]
at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1007) [Citizens.jar:?]
at net.citizensnpcs.util.NMS.tick(NMS.java:270) [Citizens.jar:?]
at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) [Citizens.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_141]
at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:101) ~[?:?]
at com.gmail.nossr50.util.HolidayManager.levelUpApril(HolidayManager.java:378) ~[?:?]
at com.gmail.nossr50.util.HolidayManager.handleStatisticEvent(HolidayManager.java:373) ~[?:?]
at com.gmail.nossr50.listeners.PlayerListener.onPlayerStatisticIncrementEvent(PlayerListener.java:707) ~[?:?]
at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigotmc-1.12.2-R0.1.jar:git-Spigot-4bd94dc-c765646]
... 21 more
```

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
