### ISSUE TITLE
Plugin won't work

### ISSUE THREAD

**Issue by CR7Joyce** [mcMMO-Dev/mcMMO#3430]
Hi, I am running a server on 1.12.1 and the plugin won't work for some reason. When I try to use the commands, nothing shows up in the chat. They show up as normal commands that do work, but the difference is that they don't work. I was wondering if I am doing something wrong, since I would like to use this plugin. 
Oh and btw, I am using a Spigot server. All the other bukkit plugins work on it, so that shouldn't be the issue I guess?

**Comment by Glitchfinder** [comment]
Is there any sort of error in the startup log, or when a command is used? When you run /plugins, does mcMMO show up in red, or does it show up like the rest of the plugin?

**Comment by CR7Joyce** [comment]
The plugin shows up in red. I am not that good with servers and plugins. What to do to make it work?

**Comment by Glitchfinder** [comment]
It sounds like there was an error during startup. Do you have access to the server's log? If so, can you find part of the log with the text "nossr50" (Not including the quotes), and copy all of the surrounding text into a response here? It'll probably look something like what you see in issue #3425.

**Comment by CR7Joyce** [comment]
I have access to the server's log since I am the owner of the server.
You mean this part?  [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:400)

Maybe it is easier to communicate through discord chat if you want to, you can add me if you like CR7Joyce#4365

**Comment by Glitchfinder** [comment]
Can you copy all the text around that part as well? That looks to be a warning rather than an error, but there should be a big block of text that looks like the text in that issue I mentioned above. I can use that to help narrow down the cause of the issue.

**Comment by CR7Joyce** [comment]
[19:42:49] [Server thread/INFO]: Starting minecraft server version 1.12.1
[19:42:49] [Server thread/WARN]: To start the server with more ram, launch it as "java -Xmx1024M -Xms1024M -jar minecraft_server.jar"
[19:42:49] [Server thread/INFO]: Loading properties
[19:42:49] [Server thread/INFO]: Default game type: SURVIVAL
[19:42:50] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-edd0396-2a927e8 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
[19:42:50] [Server thread/INFO]: Server Ping Player Sample Count: 12
[19:42:50] [Server thread/INFO]: Using 4 threads for Netty based IO
[19:42:50] [Server thread/INFO]: Debug logging is disabled
[19:42:50] [Server thread/INFO]: Generating keypair
[19:42:51] [Server thread/INFO]: Starting Minecraft server on 5.255.85.206:25900
[19:42:51] [Server thread/INFO]: Using epoll channel type
[19:42:51] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[19:42:51] [Server thread/INFO]: [Fly] Loading Fly v4.0
[19:42:51] [Server thread/INFO]: [mcMMO] Loading mcMMO v1.5.00-b3547
[19:42:51] [Server thread/INFO]: [FarmProtect] Loading FarmProtect v1.8.4
[19:42:51] [Server thread/INFO]: [Glowing] Loading Glowing v1.2
[19:42:51] [Server thread/INFO]: [MultiHomes] Loading MultiHomes vv2.0
[19:42:51] [Server thread/INFO]: [ColorChatting] Loading ColorChatting v1.0
[19:42:51] [Server thread/INFO]: [SilkSpawners] Loading SilkSpawners v5.0.0
[19:42:51] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[19:42:52] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[19:42:52] [Server thread/WARN]: java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
[19:42:52] [Server thread/WARN]: 	at com.gmail.nossr50.config.HiddenConfig.load(HiddenConfig.java:31)
[19:42:52] [Server thread/WARN]: 	at com.gmail.nossr50.config.HiddenConfig.<init>(HiddenConfig.java:18)
[19:42:52] [Server thread/WARN]: 	at com.gmail.nossr50.config.HiddenConfig.getInstance(HiddenConfig.java:23)
[19:42:52] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:400)
[19:42:52] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[19:42:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:42:52] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[19:42:52] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[19:42:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374)
[19:42:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323)
[19:42:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[19:42:52] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[19:42:52] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[19:42:52] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[19:42:52] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at com.gmail.nossr50.config.AutoUpdateConfigLoader.loadFile(AutoUpdateConfigLoader.java:29) ~[?:?]
	at com.gmail.nossr50.config.ConfigLoader.<init>(ConfigLoader.java:26) ~[?:?]
	at com.gmail.nossr50.config.AutoUpdateConfigLoader.<init>(AutoUpdateConfigLoader.java:23) ~[?:?]
	at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:20) ~[?:?]
	at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:26) ~[?:?]
	at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:51) ~[?:?]
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:203) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot121.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot121.jar:git-Spigot-edd0396-2a927e8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[19:42:52] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[19:42:52] [Server thread/INFO]: Preparing level "world"
[19:42:52] [Server thread/INFO]: -------- World Settings For [world] --------
[19:42:52] [Server thread/INFO]: Cactus Growth Modifier: 100%
[19:42:52] [Server thread/INFO]: Cane Growth Modifier: 100%
[19:42:52] [Server thread/INFO]: Melon Growth Modifier: 100%
[19:42:52] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[19:42:52] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[19:42:52] [Server thread/INFO]: Sapling Growth Modifier: 100%
[19:42:52] [Server thread/INFO]: Wheat Growth Modifier: 100%
[19:42:52] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[19:42:52] [Server thread/INFO]: Vine Growth Modifier: 100%
[19:42:52] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[19:42:52] [Server thread/INFO]: Mob Spawn Range: 4
[19:42:52] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[19:42:52] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[19:42:52] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[19:42:52] [Server thread/INFO]: Random Lighting Updates: false
[19:42:52] [Server thread/INFO]: Structure Info Saving: true
[19:42:52] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[19:42:52] [Server thread/INFO]: Max TNT Explosions: 100
[19:42:52] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[19:42:52] [Server thread/INFO]: Item Despawn Rate: 6000
[19:42:52] [Server thread/INFO]: Item Merge Radius: 2.5
[19:42:52] [Server thread/INFO]: Arrow Despawn Rate: 1200
[19:42:52] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[19:42:52] [Server thread/INFO]: View Distance: 10
[19:42:52] [Server thread/INFO]: Experience Merge Radius: 3.0
[19:42:52] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[19:42:52] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[19:42:53] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[19:42:53] [Server thread/INFO]: Cactus Growth Modifier: 100%
[19:42:53] [Server thread/INFO]: Cane Growth Modifier: 100%
[19:42:53] [Server thread/INFO]: Melon Growth Modifier: 100%
[19:42:53] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[19:42:53] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[19:42:53] [Server thread/INFO]: Sapling Growth Modifier: 100%
[19:42:53] [Server thread/INFO]: Wheat Growth Modifier: 100%
[19:42:53] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[19:42:53] [Server thread/INFO]: Vine Growth Modifier: 100%
[19:42:53] [Server thread/INFO]: Cocoa Growth Modifier: 100%

**Comment by ElvenDemolisher** [comment]
If there is/was a solution found, I would like to know because I am also having the same issue

**Comment by Glitchfinder** [comment]
It looks like you're using an out of date version of mcMMO on a current server. Builds of this plugin are forward compatible up to a point where the Bukkit API changes, which appears to be the case here. Mind trying the [latest build here](https://popicraft.net/jenkins/job/mcMMO/) and telling me if that works?

**Comment by CR7Joyce** [comment]
I tried the latest build as you suggested. It works now, thank you very much!
