### ISSUE TITLE
NullPointerExceptions on player matching commands

### ISSUE THREAD

**Issue by GiovanH** [mcMMO-Dev/mcMMO#3433]
Version: 
McMMO Jenkins Build #7 (Apr 15, 2018 2:18:08 PM), version 1.5.09-SNAPSHOT
Spigot 1.12-R0.1

How to produce: run any command that targets a specific player, like /inspect or /party invite

Stack Trace:
```[20:21:35] [Server thread/INFO]: GiovanH issued server command: /inspect GiovanH
[20:21:35] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'party' in plugin mcMMO v1.5.09-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.util.commands.CommandUtils.matchPlayer(CommandUtils.java:307) ~[?:?]
	at com.gmail.nossr50.util.commands.CommandUtils.getMatchedPlayerName(CommandUtils.java:268) ~[?:?]
	at com.gmail.nossr50.commands.party.PartyInviteCommand.onCommand(PartyInviteCommand.java:20) ~[?:?]
	at com.gmail.nossr50.commands.party.PartyCommand.onCommand(PartyCommand.java:127) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigotmc-1.12-R0.1.jar:git-Spigot-596221b-9a1fc1e]
	... 15 more
```

**Comment by GiovanH** [comment]
Tested this on a freshly built revision and also on the paid binary provided on spigot. Issue persists.

**Comment by Glitchfinder** [comment]
There's an uncaught NPE in the party manager somewhere that only triggers when the server fails to load one of the party data files. I don't know the exact context of it, but it should probably be replaced with a catch/warning combination. @t00thpick1

**Comment by GiovanH** [comment]
It looks like there must be some data stored within the world file that's causing McMMO to bug out, as I set mcmmo on a similar environment but deleted the world files. Looking for a way to surgically remove the corrupt data in the short term, and figure a way for McMMO to handle bad data in the long term, then.

**Comment by GiovanH** [comment]
Also, I received a github email notification saying that I got the following comment on this thread:

> There's an uncaught NPE in the party manager somewhere that only triggers when the server fails to load one of the party data files. I don't know the exact context of it, but it should probably be replaced with a catch/warning combination. @t00thpick1

I'm not sure why it's not showing up here, but it seems relevant.

**Comment by Glitchfinder** [comment]
Because I double-checked and realized it's more general than that. There *was* an old issue with the party config, but as best I know, that's been resolved. Looking at the code, the faulty line is [this one](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/util/commands/CommandUtils.java#L307), but it's an odd case.

In theory, this error shouldn't happen. The error is being thrown because the variable 'playerName' is null on that line. However, that variable would only be null if the server has never seen a player by that name before. And yes, the exception happens in a loop that explicitly checks a list of players the server *has* seen.

There's only one use case I can think of that might potentially cause this. Is your server in offline mode? If not currently, has it ever been in the past? The short of it is that the server keeps an internal list of players who have logged in, and at least one player in that list doesn't actually seem to exist. Either the list is damaged, or there is no actual account. I could drop in a simple nullcheck, but finding the cause of the issue would be more beneficial than slapping a band-aid on it and calling it a day.

**Comment by GiovanH** [comment]
As far as I'm aware, it's never been in offline mode. Furthermore, I've tested /inspect on players who are online, players who are offline, and even myself. The same error is thrown each time.

**Comment by Glitchfinder** [comment]
If the server has never been in offline mode, then the server's player database has been damaged at some point, as one of the UUIDs stored in it no longer corresponds to an actual player. If you copy the map over to a test server and get the error, does it go away when you delete the playerdata folder inside the map folder?

**Comment by Glitchfinder** [comment]
Anyway, @t00thpick1, thoughts on using a nullcheck in combination with a warning to print the flawed UUID to console (Along with instructions), to help server owners track down the specific issue?

**Comment by t00thpick1** [comment]
hmm, yeah that would likely be more useful than random errors...

**Comment by GiovanH** [comment]
Or just an option to make a backup, log to console, and delete the affected data.

**Comment by GiovanH** [comment]
Created a working patch with pull 3440
May need tidying to conform with standards, this is my first time working with this project.
Built, confirmed that it works properly.
