### ISSUE TITLE
Ability API error

### ISSUE THREAD

**Issue by ak521** [mcMMO-Dev/mcMMO#3439]
Devving a server using AntiAura and mcMMO
This spams console any time a player is online. And I mean-- SPAMS.
Doubt this has anything to do with AntiAura, if you want the owner's name, I can give it to you to confirm that this is not a leaked plugin.

[29-04-2018 10:21:19] Task #483 for AntiAura v10.79 generated an exception
[29-04-2018 10:21:19] java.lang.NoClassDefFoundError: com/gmail/nossr50/api/AbilityAPI
[29-04-2018 10:21:19] at a.ec.a(ec.java:20) ~[?:?]
[29-04-2018 10:21:19] at a.u.run(u.java:2053) ~[?:?]
[29-04-2018 10:21:19] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
[29-04-2018 10:21:19] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
[29-04-2018 10:21:19] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
[29-04-2018 10:21:19] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
[29-04-2018 10:21:19] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
[29-04-2018 10:21:19] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
[29-04-2018 10:21:19] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

I also saw this message once;

Error calculating ping: System does not have the required software.

Is it a problem with the host? I tried using every version of free mcmmo i can find- orginial-mcmmo, the snapshot, the one on bukkitdev (Sorry, I'm low on money, but when donations come in, I'll try to donate to you!).
How should I fix this? 1.8.8 spigot server.

**Comment by t00thpick1** [comment]
Huh.  it looks like they can't find the api classes....  So my guess would be mcMMO is failing to start

**Comment by Glitchfinder** [comment]
You're running a 1.8 server. Is your copy of mcMMO a 1.8 build, or is it a newer one? And, if so, is your copy of AntiAura designed to be compatible with an older build of mcMMO?

**Comment by ak521** [comment]
How may I get the mcMMO 1.8 build? Also, another error in console once starting the server; 
[19:30:57] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[19:30:58] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[19:30:58] [Server thread/WARN]: java.lang.NullPointerException
[19:30:58] [Server thread/WARN]: 	at java.io.Reader.<init>(Reader.java:78)
[19:30:58] [Server thread/WARN]: 	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
[19:30:58] [Server thread/WARN]: 	at com.gmail.nossr50.metrics.MetricsManager.setup(MetricsManager.java:72)
[19:30:58] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:173)
[19:30:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[19:30:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[19:30:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:30:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[19:30:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[19:30:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[19:30:58] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[19:30:58] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:30:58] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[19:31:59] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_121]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_121]
	at org.bukkit.craftbukkit.v1_8_R3.CraftOfflinePlayer.<init>(CraftOfflinePlayer.java:34) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.getOfflinePlayer(CraftServer.java:1335) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.getOfflinePlayer(CraftServer.java:1304) ~[spigot46.jar:git-Spigot-21fe707-e1ebe52]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:133) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getOfflinePlayer(ScoreboardManager.java:121) ~[?:?]
	at com.gmail.nossr50.util.scoreboards.ScoreboardManager.<clinit>(ScoreboardManager.java:43) ~[?:?]
	... 13 more

**Comment by ak521** [comment]
#
#  mcMMO configuration
#  Last updated on 1.5.00-b3547
#
#####
#
#  Settings for mcMMO in general
###
General:
    Locale: en_US
    MOTD_Enabled: true
    # Amount of time (in minutes) to wait between saves of player information
    Save_Interval: 10
    # Allow mcMMO to report on basic anonymous usage
    Stats_Tracking: true
    # Allow mcMMO to check if a new version is available
    Update_Check: true
    Prefer_Beta: false
    # Allow mcMMO to inform other plugins of damage being dealt
    Event_Callback: true
    Power_Level_Cap: 0
    # Should mcMMO print out debug messages?
    Verbose_Logging: false
    # Should mcMMO over-write configs to update, or make new ones ending in .new?
    Config_Update_Overwrite: true
    # Play level-up sounds
    LevelUp_Sounds: true
#
#  Settings for the mcMMO scoreboards
###
Scoreboard:
    # Display player's power levels below their names?
    Power_Level_Tags: false
    # Allow players to use "/mcscoreboard keep" to keep the scoreboard up
    Allow_Keep: true
    # Add some more color on the board :-)
    Rainbows: false
    # Settings for each type of scoreboard
    # Print: Should the command output be printed in chat?
    # Board: Should the command output be displayed in the scoreboard sidebar?
    # Display_Time: Amount of time (seconds) to display in the sidebar before clearing.
    # To display permanently, use "/mcscoreboard keep" or set to -1
    Types:
        # Settings for /mcrank
        # The sub-options (Print, Board, Display_Time) are the same for each type.
        Rank:
            Print: false
            Board: true
            Display_Time: 15
        # Settings for /mctop
        Top:
            Print: true
            Board: true
            Display_Time: 15
        # Settings for /mcstats
        Stats:
            Print: false
            Board: true
            Display_Time: 15
        # Settings for /inspect
        Inspect:
            Print: false
            Board: true
            Display_Time: 20
        # Settings for /mccooldown
        Cooldown:
            Print: true
            Board: true
            Display_Time: 41
        # Settings for /<skillname> (e.g. /mining, /unarmed)
        # No "print" option is given here; the information will always be displayed in chat.
        # It should also be noted that this display is pretty dang cool.
        Skill:
            Board: true
            Display_Time: 30
            # Should the board be shown when a player levels up, and for how long?
            # It is recommended to NOT have LevelUp_Time be -1, as this may confuse players.
            LevelUp_Board: true
            LevelUp_Time: 5
Mob_Healthbar:
    # Display_Type: Default display for mob health bars - HEARTS, BAR, or DISABLED
    # Display_Time: Amount of time (in seconds) to display. To display permanently, set to -1
    Display_Type: HEARTS
    Display_Time: 3
Database_Purging:
    # Amount of time (in hours) to wait between database purging
    # To only run at server start, set to 0
    # To never run, set to -1
    Purge_Interval: -1
    # Any user who hasn't connected in this many months will be purged from the database
    # To never purge old users, set to -1
    Old_User_Cutoff: 6
#
#  Settings for Backups
#  Allow mcMMO to create zip backups for config files and flatfile data on shutdown.
###
Backups:
    Enabled: true
    Keep:
        Last_24_Hours: true
        Daily_Last_Week: true
        Weekly_Past_Months: true
#
#  Settings for using a mySQL database
###
MySQL:
    Enabled: false
    Database:
        User_Name: UserName
        User_Password: UserPassword
        Name: DataBaseName
        TablePrefix: mcmmo_
    Server:
        Port: 3306
        Address: localhost
#
#  Settings for Hardcore mode
#  Players will not lose stats when their level is below the Level_Threshold
###
Hardcore:
    Death_Stat_Loss:
        Penalty_Percentage: 75.0
        Level_Threshold: 0
        Enabled:
            Acrobatics: false
            Alchemy: false
            Archery: false
            Axes: false
            Excavation: false
            Fishing: false
            Herbalism: false
            Mining: false
            Repair: false
            Swords: false
            Taming: false
            Unarmed: false
            Woodcutting: false
    Vampirism:
        Leech_Percentage: 5.0
        Level_Threshold: 0
        Enabled:
            Acrobatics: false
            Alchemy: false
            Archery: false
            Axes: false
            Excavation: false
            Fishing: false
            Herbalism: false
            Mining: false
            Repair: false
            Swords: false
            Taming: false
            Unarmed: false
            Woodcutting: false
#
#  Settings for SMP Mods
###
Mods:
    Tool_Mods_Enabled: false
    Armor_Mods_Enabled: false
    Block_Mods_Enabled: false
    Entity_Mods_Enabled: false
#
#  Settings for mcMMO items
###
Items:
    Chimaera_Wing:
        Enabled: true
        Cooldown: 240
        Warmup: 5
        RecentlyHurt_Cooldown: 60
        Prevent_Use_Underground: true
        Use_Cost: 1
        Recipe_Cost: 5
        Item_Name: FEATHER
        Sound_Enabled: true
#
#  Settings for Parties
###
Party:
    # Amount of time (in hours) to wait between automatically kicking old party members
    # To only run at server start, set to 0
    # To never kick old users, set to -1
    AutoKick_Interval: 12
    # Any user who hasn't connected in this many days will get kicked from their party
    Old_Party_Member_Cutoff: 7
    # Settings for party share modes
    Sharing:
        ExpShare_bonus_base: 1.1
        ExpShare_bonus_increase: 1.05
        ExpShare_bonus_cap: 1.5
        Range: 75.0
    # Party members level up their party by earning individual experience
    # Newly created parties will not immediately have access to all the party features
    # and have to level up the party a bit before they can use them.
    Leveling:
        Level_Cap: 10
        # Uses the regular XP formula but is multiplied by <amount of party members> + <Xp_Curve_Modifier>
        Xp_Curve_Modifier: 3
        Near_Members_Needed: false
        Inform_All_Party_Members_On_LevelUp: false
        Chat_UnlockLevel: 1
        Teleport_UnlockLevel: 2
        Alliance_UnlockLevel: 5
        ItemShare_UnlockLevel: 8
        XpShare_UnlockLevel: 10
#
#  Settings for Abilities
###
Abilities:
    Enabled: true
    Messages: true
    Activation:
        Only_Activate_When_Sneaking: false
    Cooldowns:
        Berserk: 240
        Blast_Mining: 60
        Giga_Drill_Breaker: 240
        Green_Terra: 240
        Serrated_Strikes: 240
        Skull_Splitter: 240
        Super_Breaker: 240
        Tree_Feller: 240
    Max_Seconds:
        Berserk: 0
        Blast_Mining: 0
        Giga_Drill_Breaker: 0
        Green_Terra: 0
        Serrated_Strikes: 0
        Skull_Splitter: 0
        Super_Breaker: 0
        Tree_Feller: 0
    Limits:
        Tree_Feller_Threshold: 500
    Tools:
        # Use more tool durability while using abilities. Set Durability_Loss to 0 to disable the extra durability damage.
        Durability_Loss: 1
#
#  Settings for Skills
#  Level cap of 0 for no limit
###
Skills:
    Acrobatics:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Prevent_AFK_Leveling: true
        Max_Tries_At_Same_Location: 3
        Prevent_Dodge_Lightning: false
        # Prevent earning Acrobatics XP a few seconds after teleporting
        XP_After_Teleport_Cooldown: 5
        Level_Cap: 0
    Alchemy:
        # Allow Hoppers to transfer ingredients and brew Rank 1 Alchemy potions
        Enabled_for_Hoppers: true
        # Prevent Hoppers from transferring ingredients into Brewing Stands
        Prevent_Hopper_Transfer: false
        Level_Cap: 0
    Archery:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
    Axes:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
    Excavation:
        Level_Cap: 0
    Fishing:
        Level_Cap: 0
        Drops_Enabled: true
        Override_Vanilla_Treasures: true
        # Always catch fish, even when treasure is found
        Extra_Fish: false
    Herbalism:
        Level_Cap: 0
        Prevent_AFK_Leveling: true
    Mining:
        Level_Cap: 0
        Detonator_Name: FLINT_AND_STEEL
    Repair:
        Level_Cap: 0
        Anvil_Messages: true
        Anvil_Placed_Sounds: true
        Anvil_Use_Sounds: true
        Anvil_Material: IRON_BLOCK
        Salvage_Anvil_Material: GOLD_BLOCK
        Salvage_tools: true
        Salvage_armor: true
        # Ask for a confirmation when a player tries to repair an enchanted item
        Confirm_Required: true
    Smelting:
        Level_Cap: 0
    Swords:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
    Taming:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
        Call_Of_The_Wild:
            # Item_Material: Material of the item needed to summon the pet
            # Item_Amount: Amount of items required to summon the pet
            # Summon_Amount: Amount of pets to summon when using Call Of The Wild
            Wolf:
                Item_Material: BONE
                Item_Amount: 10
                Summon_Amount: 1
            Ocelot:
                Item_Material: RAW_FISH
                Item_Amount: 10
                Summon_Amount: 1
            Horse:
                Item_Material: APPLE
                Item_Amount: 10
                Summon_Amount: 1
            # Range to check for nearby pets when using Call Of The Wild, 0 will disable the check
            Range: 40.0
    Unarmed:
        Enabled_For_PVP: true
        Enabled_For_PVE: true
        Level_Cap: 0
        Block_Cracker:
            SmoothBrick_To_CrackedBrick: true
    Woodcutting:
        Tree_Feller_Sounds: true
        Level_Cap: 0
#
#  Settings for Double Drops
###
Double_Drops:
    Herbalism:
        Brown_Mushroom: true
        Cactus: true
        Carrot: true
        Cocoa: true
        Crops: true
        Melon_Block: true
        Nether_Warts: true
        Potato: true
        Pumpkin: true
        Red_Mushroom: true
        Red_Rose: true
        Sugar_Cane_Block: true
        Vine: true
        Water_Lily: true
        Yellow_Flower: true
    Mining:
        Coal_Ore: true
        Diamond_Ore: true
        Emerald_Ore: true
        Ender_Stone: true
        Glowstone: true
        Gold_Ore: true
        Iron_Ore: true
        Lapis_Ore: true
        Mossy_Cobblestone: true
        Netherrack: true
        Obsidian: true
        Quartz_Ore: true
        Redstone_Ore: true
        Sandstone: true
        Stone: true
    Woodcutting:
        Acacia: true
        Birch: true
        Dark_Oak: true
        Generic: true
        Jungle: true
        Redwood: true
#
#  Settings for commands
###
Commands:
    Generic:
        # If true, when using partial names in commands mcMMO will try to look for a match from
        # the offline players. Enabling this might slow the server down if there are a lot of offline players.
        Match_OfflinePlayers: false
    Database:
        # Database command cooldown in milliseconds, cannot be changed below the default value. (1750)
        # Prevents players from spamming /mctop or /mcrank
        Player_Cooldown: 1750
    mcmmo:
        Donate_Message: true
    inspect:
        Max_Distance: 30.0
    ptp:
        Cooldown: 120
        Warmup: 5
        RecentlyHurt_Cooldown: 60
        Accept_Required: true
        Request_Timeout: 300
        # If true, require players to have a mcmmo.commands.ptp.world.[WorldName] permission
        # to teleport to, from, or within any given world.
        World_Based_Permissions: false
    partychat:
        Chat_Prefix_Format: '[[GREEN]]([[WHITE]]{0}[[GREEN]])'
        Use_Display_Names: true
        Chat_Prefix_Format_Ally: '[[GREEN]](A)[[RESET]]'
    adminchat:
        Chat_Prefix_Format: '[[AQUA]][[[WHITE]]{0}[[AQUA]]]'
        Use_Display_Names: true
#
#  Settings for particles
###
Particles:
    # These settings determine if fireworks should get launched when a player activates/deactivates an ability
    Ability_Activation: true
    Ability_Deactivation: true
    # Determines if the fireworks should be a large ball or a small one
    LargeFireworks: true
    # Use particle effect when these abilities trigger
    Dodge: true
    Bleed: true
    Greater_Impact: true
    # These settings determine if fireworks should get launched when a player levels-up,
    # this will happen by default for every 100 levels.
    LevelUp_Enabled: true
    LevelUp_Tier: 100

config, server ip is 158.69.39.61:25566 so if i have to change the host somewhere..

**Comment by Glitchfinder** [comment]
So the build you have is an older build, and the one you need is apparently no longer offline. @t00thpick1, would you mind re-uploading an official 1.8 build somewhere and fixing the non-paywalled link on Spigot? Otherwise I can upload a build myself, but it'll have a blank {build number} variable if I do.

**Comment by ak521** [comment]
Hey! I would really like the 1.8.8 version as soon as possible! I plan on posting my server tomorrow and want to have mcmmo working for the players :)

**Comment by ak521** [comment]
Anyone there?

**Comment by Glitchfinder** [comment]
All right, so [this right here](http://files.glitchkey.com/archives/mcMMO_1_5_04.zip) is a compile of the plugin as of the last commit prior to the 1.9 break. It's going to show in logs as an unknown build number, but in theory it should load on a 1.8 server. I know for a fact it doesn't launch of current versions because too many API changes have happened, but the commit itself is marked as 1.8 compatible.

**Comment by Glitchfinder** [comment]
For reference, the last commit before the 1.9 breakpoint is this one: https://github.com/mcMMO-Dev/mcMMO/commit/6a0529f02de3d798fa861a5b2302ac80bf3241f3.

**Comment by ak521** [comment]
Fixed. Thanks so much!
