### ISSUE TITLE
McMMO active abilities not working

### ISSUE THREAD

**Issue by Lxzl** [mcMMO-Dev/mcMMO#3444]
Hey all,

Recently been having an issue where (all) McMMO active abilities don't toggle. I'm getting the following error in the logs;

[22:21:18 ERROR]: Could not pass event PlayerInteractEvent to mcMMO v1.5.09-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
        at com.gmail.nossr50.listeners.PlayerListener.onPlayerInteractMonitor(PlayerListener.java:527) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-ca057a3]
        ... 17 more

A little new to this so any help would be appreciated.

Take care,

**Comment by Momshroom** [comment]
I think this is a result of spigot updating.  Do you have your server set to automatically update or did you manually update your spigot version?  Our server has just started having the same issue and I believe a Spigot update is the cause.

**Comment by Momshroom** [comment]
Confirmed. Rolling back to an older version of spigot fixed the issue.

**Comment by Glitchfinder** [comment]
While this one was filed earlier, #3446 has more information on the issue.
