### ISSUE TITLE
Party chat breaks

### ISSUE THREAD

**Issue by Magnum97** [mcMMO-Dev/mcMMO#3455]
Running git-spigot-2086bb0-d0a3620 MC:1.12.2 API: 1.12.2-R0.1-SNAPSHOT 
mcMMO ver: 1.5.09-SNAPSHOT

Parties keep disbanding and have to be recreated after restart. An exerpt from serverlog during shutdown:
```
[20:52:45] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.09-SNAPSHOT
[20:52:45] [Server thread/INFO]: [Lockette] Disabled link to plugin mcMMO, version 1.5.09-SNAPSHOT
[20:52:45] [Server thread/WARN]: Tue May 15 20:52:45 GMT+01:00 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[20:52:45] [Server thread/WARN]: [mcMMO] Could not delete party file. Party saving failed!
[20:52:45] [Server thread/WARN]: java.io.FileNotFoundException: plugins\mcMMO\flatfile\formula.yml (Access is denied)
[20:52:45] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.open0(Native Method)
[20:52:45] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.open(Unknown Source)
[20:52:45] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
[20:52:45] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
[20:52:45] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:70)
[20:52:45] [Server thread/WARN]: 	at com.gmail.nossr50.util.experience.FormulaManager.saveFormula(FormulaManager.java:159)
[20:52:45] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:214)
[20:52:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[20:52:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[20:52:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422)
[20:52:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415)
[20:52:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:349)
[20:52:45] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465)
[20:52:45] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613)
[20:52:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[20:52:45] [Server thread/ERROR]: [mcMMO] java.io.FileNotFoundException: plugins\mcMMO\flatfile\anniversary.2018.yml (Access is denied)
```
We converted from flatfile to SQL a couple weeks ago. It happened before that as well.

**Comment by Glitchfinder** [comment]
So, it's looking like some I/O errors. For some reason, mcMMO isn't being allowed to edit/create files or directories. I'm not sure of the extent of the issue, but can you make sure that the plugins\mcMMO\flatfile\ directory exists and that the server has permission to create/edit files in that directory?

**Comment by Magnum97** [comment]
Directory and files do exist. It did have perms will double check they didnt change. idk if it is relevant but the contents of forumula.yml:
`Previous_Formula: UNKNOWN`

**Comment by Glitchfinder** [comment]
That is the default for that file. So it sounds like the directory exists, but that for some reason it's unable to modify those files. Specifically, I'm seeing an inability to delete plugins\mcMMO\flatfile\parties.yml, and a lack of permissions to modify plugins\mcMMO\flatfile\formula.yml and plugins\mcMMO\flatfile\anniversary.2018.yml.
