### ISSUE TITLE
Bug #Config.yml

### ISSUE THREAD

**Issue by N0atak** [mcMMO-Dev/mcMMO#3478]
[16:12:00 INFO]: [mcMMO] Enabling mcMMO v1.5.04-SNAPSHOT-b82
[16:12:01 ERROR]: Cannot load plugins\mcMMO\config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 23, column 5:
        Truncate#
        ^
could not find expected ':'
 in 'string', line 24, column 1:
    #  Settings for Skills
    ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:188) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:162) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at com.gmail.nossr50.util.LogFilter.<init>(LogFilter.java:13) [mcMMO.jar:?]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134) [mcMMO.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 23, column 5:
        Truncate#
        ^
could not find expected ':'
 in 'string', line 24, column 1:
    #  Settings for Skills
    ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 15 more
[16:12:01 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[16:12:01 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[16:12:01 WARN]:        at java.base/java.lang.String.substring(Unknown Source)
[16:12:01 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreaures(TreasureConfig.java:242)
[16:12:01 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:137)
[16:12:01 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:74)
[16:12:01 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:80)
[16:12:01 WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:406)
[16:12:01 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:146)
[16:12:01 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[16:12:01 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[16:12:01 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:12:01 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[16:12:01 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[16:12:01 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[16:12:01 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[16:12:01 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[16:12:01 INFO]: [mcMMO] Disabling mcMMO v1.5.04-SNAPSHOT-b82
[16:12:01 ERROR]: Cannot load plugins\mcMMO\config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 23, column 5:
        Truncate#
        ^
could not find expected ':'
 in 'string', line 24, column 1:
    #  Settings for Skills
    ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at com.gmail.nossr50.config.ConfigLoader.loadFile(ConfigLoader.java:44) [mcMMO.jar:?]
        at com.gmail.nossr50.config.AutoUpdateConfigLoader.loadFile(AutoUpdateConfigLoader.java:28) [mcMMO.jar:?]
        at com.gmail.nossr50.config.ConfigLoader.<init>(ConfigLoader.java:26) [mcMMO.jar:?]
        at com.gmail.nossr50.config.AutoUpdateConfigLoader.<init>(AutoUpdateConfigLoader.java:23) [mcMMO.jar:?]
        at com.gmail.nossr50.config.Config.<init>(Config.java:23) [mcMMO.jar:?]
        at com.gmail.nossr50.config.Config.getInstance(Config.java:29) [mcMMO.jar:?]
        at com.gmail.nossr50.locale.LocaleLoader.initialize(LocaleLoader.java:80) [mcMMO.jar:?]
        at com.gmail.nossr50.locale.LocaleLoader.getString(LocaleLoader.java:33) [mcMMO.jar:?]
        at com.gmail.nossr50.locale.LocaleLoader.getString(LocaleLoader.java:21) [mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.skills.ToolType.<clinit>(ToolType.java:10) [mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.skills.SkillType.<clinit>(SkillType.java:42) [mcMMO.jar:?]
        at com.gmail.nossr50.config.AdvancedConfig.getMaxChance(AdvancedConfig.java:693) [mcMMO.jar:?]
        at com.gmail.nossr50.config.AdvancedConfig.validateKeys(AdvancedConfig.java:48) [mcMMO.jar:?]
        at com.gmail.nossr50.config.ConfigLoader.validate(ConfigLoader.java:62) [mcMMO.jar:?]
        at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:22) [mcMMO.jar:?]
        at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:27) [mcMMO.jar:?]
        at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:51) [mcMMO.jar:?]
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:214) [mcMMO.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:204) [mcMMO.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 23, column 5:
        Truncate#
        ^
could not find expected ':'
 in 'string', line 24, column 1:
    #  Settings for Skills
    ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 33 more
[16:12:01 ERROR]: [mcMMO] Cannot read C:\Users\eden\Desktop\Server\plugins\mcMMO\experience.yml(File Permissions?)
[16:12:01 ERROR]: [mcMMO] Cannot read C:\Users\eden\Desktop\Server\plugins\mcMMO\repair.vanilla.yml(File Permissions?)
[16:12:01 ERROR]: Error occurred while disabling mcMMO v1.5.04-SNAPSHOT-b82 (Is it up to date?)
java.lang.NullPointerException
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:250) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:204) [mcMMO.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
