### ISSUE TITLE
mcMMO not working for me

### ISSUE THREAD

**Issue by RagingRhino489** [mcMMO-Dev/mcMMO#3488]
I get this error every time I try to start up the server.
10.07 12:13:11 [Server] ERROR Cannot read /plugins/mcMMO/experience.yml(File Permissions?)
10.07 12:13:11 [Server] INFO Disabling mcMMO v1.5.10
10.07 12:13:11 [Server] WARN at java.lang.Thread.run(Unknown Source)
10.07 12:13:11 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
10.07 12:13:11 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
10.07 12:13:11 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
10.07 12:13:11 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
10.07 12:13:11 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
10.07 12:13:11 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
10.07 12:13:11 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
10.07 12:13:11 [Server] WARN at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
10.07 12:13:11 [Server] WARN at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)
10.07 12:13:11 [Server] WARN at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:161)
10.07 12:13:11 [Server] WARN at org.bukkit.NamespacedKey.&lt;init&gt;(NamespacedKey.java:72)
10.07 12:13:11 [Server] WARN at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
10.07 12:13:11 [Server] WARN java.lang.IllegalArgumentException: key
10.07 12:13:11 [Server] ERROR There was an error while enabling mcMMO!
10.07 12:13:09 [Server] INFO Enabling mcMMO v1.5.10
Could someone possibly help me with my situation here. I just paid 11 dollars for this plugin and it is not working!

**Comment by RagingRhino489** [comment]
Never mind the host was corrupting the File. I used Filezilla to manually upload the file into the direct server archive. Make sure if you have the same error to repeat the same steps to fix it!
