### ISSUE TITLE
Cannot load experience.yml ("No file permissions")

### ISSUE THREAD

**Issue by NiveryIGN** [mcMMO-Dev/mcMMO#3490]
[23:41:42 WARN]: Enabled plugin with unregistered PluginClassLoader mcMMO v1.5.10
[23:41:42 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[23:41:42 WARN]: java.lang.IllegalArgumentException: key
[23:41:42 WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[23:41:42 WARN]: 	at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72)
[23:41:42 WARN]: 	at com.gmail.nossr50.util.ChimaeraWing.getChimaeraWingRecipe(ChimaeraWing.java:161)
[23:41:42 WARN]: 	at com.gmail.nossr50.mcMMO.registerCustomRecipes(mcMMO.java:437)
[23:41:42 WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
[23:41:42 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[23:41:42 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[23:41:42 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[23:41:42 WARN]: 	at com.rylinaux.plugman.util.PluginUtil.enable(PluginUtil.java:62)
[23:41:42 WARN]: 	at com.rylinaux.plugman.command.RestartCommand.execute(RestartCommand.java:124)
[23:41:42 WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[23:41:42 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:41:42 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:41:42 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[23:41:42 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634)
[23:41:42 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[23:41:42 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[23:41:42 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[23:41:42 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[23:41:42 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[23:41:42 INFO]: [mcMMO] Disabling mcMMO v1.5.10
[23:41:42 ERROR]: [mcMMO] Cannot read /home/gs/gs/data/servers/10136826/plugins/mcMMO/experience.yml(File Permissions?)

**Comment by NiveryIGN** [comment]
I'm using server.pro as my a server host, using the latest version of Spigot (1.12.2).
It sends that error message everytime I reload the server / restart the plugin with PlugMan. I know a lot of people commented about that but I don't know how to fix it everything I do just won't work.

**Comment by NiveryIGN** [comment]
Found how to fix it.

**Comment by gaiaweylyn** [comment]
Care to share? I was able to get things working by using a slightly older version of Spigot, but I kinda want to know what the issue was.

**Comment by t00thpick1** [comment]
Closing due to 1.13 overhaul changes in progress touching the affected areas.
