### ISSUE TITLE
McMMO not working for 1.13 spigot server.

### ISSUE THREAD

**Issue by RjVid** [mcMMO-Dev/mcMMO#3501]
Whenever I try to run it on the server it says this
25.07 00:02:29 [Server] WARN CARROT_STICK has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: CARROT_STICK
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN DIAMOND_SPADE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: DIAMOND_SPADE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN GOLD_BOOTS has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_BOOTS
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN GOLD_LEGGINGS has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_LEGGINGS
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN GOLD_CHESTPLATE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_CHESTPLATE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN GOLD_HELMET has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_HELMET
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN GOLD_HOE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_HOE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN GOLD_AXE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_AXE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN GOLD_PICKAXE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_PICKAXE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN GOLD_SPADE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_SPADE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN GOLD_SWORD has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_SWORD
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN IRON_SPADE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: IRON_SPADE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN STONE_SPADE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: STONE_SPADE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN WOOD_HOE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: WOOD_HOE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN WOOD_AXE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: WOOD_AXE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN WOOD_PICKAXE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: WOOD_PICKAXE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN WOOD_SPADE has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: WOOD_SPADE
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN WOOD_SWORD has an invalid salvage material: null
25.07 00:02:29 [Server] WARN Invalid material: WOOD_SWORD
25.07 00:02:29 [Server] WARN The following issues were found:
25.07 00:02:29 [Server] WARN Errors have been found in: salvage.vanilla.yml
25.07 00:02:29 [Server] WARN Maximum durability of CARROT_STICK must be greater than 0!
25.07 00:02:29 [Server] WARN CARROT_STICK has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: CARROT_STICK
25.07 00:02:29 [Server] WARN Maximum durability of DIAMOND_SPADE must be greater than 0!
25.07 00:02:29 [Server] WARN DIAMOND_SPADE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: DIAMOND_SPADE
25.07 00:02:29 [Server] WARN Maximum durability of GOLD_BOOTS must be greater than 0!
25.07 00:02:29 [Server] WARN GOLD_BOOTS has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_BOOTS
25.07 00:02:29 [Server] WARN Maximum durability of GOLD_LEGGINGS must be greater than 0!
25.07 00:02:29 [Server] WARN GOLD_LEGGINGS has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_LEGGINGS
25.07 00:02:29 [Server] WARN Maximum durability of GOLD_CHESTPLATE must be greater than 0!
25.07 00:02:29 [Server] WARN GOLD_CHESTPLATE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_CHESTPLATE
25.07 00:02:29 [Server] WARN Maximum durability of GOLD_HELMET must be greater than 0!
25.07 00:02:29 [Server] WARN GOLD_HELMET has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_HELMET
25.07 00:02:29 [Server] WARN Maximum durability of GOLD_HOE must be greater than 0!
25.07 00:02:29 [Server] WARN GOLD_HOE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_HOE
25.07 00:02:29 [Server] WARN Maximum durability of GOLD_AXE must be greater than 0!
25.07 00:02:29 [Server] WARN GOLD_AXE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_AXE
25.07 00:02:29 [Server] WARN Maximum durability of GOLD_PICKAXE must be greater than 0!
25.07 00:02:29 [Server] WARN GOLD_PICKAXE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_PICKAXE
25.07 00:02:29 [Server] WARN Maximum durability of GOLD_SPADE must be greater than 0!
25.07 00:02:29 [Server] WARN GOLD_SPADE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_SPADE
25.07 00:02:29 [Server] WARN Maximum durability of GOLD_SWORD must be greater than 0!
25.07 00:02:29 [Server] WARN GOLD_SWORD has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: GOLD_SWORD
25.07 00:02:29 [Server] WARN Maximum durability of IRON_SPADE must be greater than 0!
25.07 00:02:29 [Server] WARN IRON_SPADE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: IRON_SPADE
25.07 00:02:29 [Server] WARN Maximum durability of STONE_SPADE must be greater than 0!
25.07 00:02:29 [Server] WARN STONE_SPADE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: STONE_SPADE
25.07 00:02:29 [Server] WARN Maximum durability of WOOD_HOE must be greater than 0!
25.07 00:02:29 [Server] WARN WOOD_HOE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: WOOD_HOE
25.07 00:02:29 [Server] WARN Maximum durability of WOOD_AXE must be greater than 0!
25.07 00:02:29 [Server] WARN WOOD_AXE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: WOOD_AXE
25.07 00:02:29 [Server] WARN Maximum durability of WOOD_PICKAXE must be greater than 0!
25.07 00:02:29 [Server] WARN WOOD_PICKAXE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: WOOD_PICKAXE
25.07 00:02:29 [Server] WARN Maximum durability of WOOD_SPADE must be greater than 0!
25.07 00:02:29 [Server] WARN WOOD_SPADE has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: WOOD_SPADE
25.07 00:02:29 [Server] WARN Maximum durability of WOOD_SWORD must be greater than 0!
25.07 00:02:29 [Server] WARN WOOD_SWORD has an invalid repair material: null
25.07 00:02:29 [Server] WARN Invalid material: WOOD_SWORD
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: INK_SACK
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: LONG_GRASS:2
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: SPECKLED_MELON
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: RAW_FISH:3
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: CARROT_ITEM
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: SPECKLED_MELON
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: NETHER_STALK
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Saturation II: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Resistance II: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Nausea II: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Hunger II: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Health Boost II: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Haste II: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Dullness II: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Decay II: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Blindness II: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Absorption II: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Saturation Extended: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Resistance Extended: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Nausea Extended: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Hunger Extended: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Health Boost Extended: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Haste Extended: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Dullness Extended: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Decay Extended: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Blindness Extended: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Absorption Extended: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Saturation: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Resistance: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Nausea: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Hunger: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Health Boost: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Haste: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Dullness: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Decay: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Blindness: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Splash Potion Of Absorption: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: SPECKLED_MELON
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: CARROT_ITEM
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: LONG_GRASS:2
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: INK_SACK
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: RAW_FISH:3
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: NETHER_STALK
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: SPECKLED_MELON
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion null: DRAGONS_BREATH
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Saturation II: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Resistance II: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Nausea II: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Hunger II: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Health Boost II: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Haste II: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Dullness II: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Decay II: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Blindness II: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Absorption II: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Saturation Extended: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Resistance Extended: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Nausea Extended: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Hunger Extended: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Health Boost Extended: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Haste Extended: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Dullness Extended: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Decay Extended: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Blindness Extended: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Absorption Extended: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Saturation: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Resistance: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Nausea: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Hunger: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Health Boost: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Haste: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Dullness: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Decay: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Blindness: SULPHUR
25.07 00:02:29 [Server] WARN Failed to parse child for potion Potion Of Absorption: SULPHUR

**Comment by RjVid** [comment]
Also this,
25.07 00:03:40 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
25.07 00:03:40 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_172]
25.07 00:03:40 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_172]
25.07 00:03:40 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:692) ~[Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[Spigot.jar:git-Spigot-a85f7ec-5870145]
25.07 00:03:40 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'mcmmo' in plugin mcMMO v1.6.0-SNAPSHOT - plugin is disabled.
25.07 00:03:40 [Server] ERROR null
