### ISSUE TITLE
McMMO broken?

### ISSUE THREAD

**Issue by RussianHacker69** [mcMMO-Dev/mcMMO#3504]
When i try to load the plugin it says the next error, i'm using latest version of paper spigot 1.12.2:

[14:32:22 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[14:32:22 WARN]: java.lang.NoSuchFieldError: INK_SAC
[14:32:22 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreasures(TreasureConfig.java:140)
[14:32:22 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:96)
[14:32:22 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:40)
[14:32:22 WARN]:        at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:46)
[14:32:22 WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:373)
[14:32:22 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:133)
[14:32:22 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:32:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[14:32:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:32:22 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
[14:32:22 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[14:32:22 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[14:32:22 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:32:22 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[14:32:22 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[14:32:22 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1473)
[14:32:22 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1278)
[14:32:22 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:32:22 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[14:32:22 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[14:32:22 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:32:22 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:32:22 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[14:32:22 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849)
[14:32:22 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[14:32:22 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[14:32:22 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[14:32:22 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by RussianHacker69** [comment]
Nevermind, I downgraded to build #21 and it works now.
