### ISSUE TITLE
Erorr 1.13

### ISSUE THREAD

**Issue by Aides123** [mcMMO-Dev/mcMMO#3515]
```[21:54:09] [Server thread/ERROR]: Could not pass event BlockBreakEvent to mcMMO v1.6.0-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:218) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1166) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [server.jar:git-Spigot-f68f5a8-4b00823]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [server.jar:git-Spigot-f68f5a8-4b00823]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [server.jar:git-Spigot-f68f5a8-4b00823]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [server.jar:git-Spigot-f68f5a8-4b00823]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [server.jar:git-Spigot-f68f5a8-4b00823]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalArgumentException: Invalid block type for tree species
	at org.bukkit.material.Wood.setSpecies(Wood.java:164) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at org.bukkit.material.Wood.<init>(Wood.java:51) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at org.bukkit.material.Tree.<init>(Tree.java:72) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at org.bukkit.material.Tree.<init>(Tree.java:50) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	at com.gmail.nossr50.skills.woodcutting.Woodcutting.checkForDoubleDrop(Woodcutting.java:60) ~[?:?]
	at com.gmail.nossr50.skills.woodcutting.WoodcuttingManager.woodcuttingBlockCheck(WoodcuttingManager.java:57) ~[?:?]
	at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:223) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[server.jar:git-Spigot-f68f5a8-4b00823]
	... 17 more```

**Comment by Glitchfinder** [comment]
Duplicate of #3414.
