### ISSUE TITLE
Error occurred while disabling mcMMO v1.6.0-SNAPSHOT (Is it up to date?)

### ISSUE THREAD

**Issue by sniprcrazy** [mcMMO-Dev/mcMMO#3521]
I tried 1.5.10 an 1.6.0 not work, but the version 1.5.9 works

server 1.11.2 paperspigot

```
[16:09:10] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.6.0-SNAPSHOT
[16:09:10] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[16:09:10] [Server thread/WARN]: java.lang.NoSuchFieldError: INK_SAC
[16:09:10] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreasures(TreasureConfig.java:139)
[16:09:10] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:95)
[16:09:10] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:40)
[16:09:10] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:46)
[16:09:10] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:373)
[16:09:10] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:133)
[16:09:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[16:09:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[16:09:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[16:09:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378)
[16:09:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328)
[16:09:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:209)
[16:09:10] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612)
[16:09:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:09:10] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.6.0-SNAPSHOT
[16:09:10] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.6.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:233) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[PaperSpigot-1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [PaperSpigot-1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [PaperSpigot-1.11.2.jar:git-Paper-1104]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:187) [mcMMO%20(5).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [PaperSpigot-1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [PaperSpigot-1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot-1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [PaperSpigot-1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [PaperSpigot-1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:209) [PaperSpigot-1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [PaperSpigot-1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
/mcmmo and /mcmmo help do not respond

**Comment by Glitchfinder** [comment]
1.6.0 and 1.5.10 are not compatible with Minecraft 1.11 servers. 1.5.10 would be, but Bukkit changed some of their API in a destructive fashion. Theoretically, [this](https://popicraft.net/jenkins/job/mcMMO/3/) is the most recent build that is compatible with a 1.11 server.

**Comment by sniprcrazy** [comment]
ok, thank you.
