### ISSUE TITLE
Error on enable on 1.13 - Cannot get data for not block IRON_INGOT

### ISSUE THREAD

**Issue by FabioZumbi12** [mcMMO-Dev/mcMMO#3530]
Getting this error on enable mcmmo on 1.13:

```
[23:57:21 INFO]: [mcMMO] Enabling mcMMO v1.6.0-SNAPSHOT
[23:57:21 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[23:57:21 WARN]: java.lang.IllegalArgumentException: Cannot get data for not block IRON_INGOT
[23:57:21 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
[23:57:21 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.block.data.CraftBlockData.newData(CraftBlockData.java:420)
[23:57:21 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1883)
[23:57:21 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.createBlockData(CraftServer.java:1858)
[23:57:21 WARN]:        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1228)
[23:57:21 WARN]:        at org.bukkit.Material.createBlockData(Material.java:1980)
[23:57:21 WARN]:        at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:281)
[23:57:21 WARN]:        at com.gmail.nossr50.config.skills.repair.RepairConfig.loadKeys(RepairConfig.java:139)
[23:57:21 WARN]:        at com.gmail.nossr50.config.skills.repair.RepairConfig.<init>(RepairConfig.java:24)
[23:57:21 WARN]:        at com.gmail.nossr50.config.skills.repair.RepairConfigManager.<init>(RepairConfigManager.java:34)
[23:57:21 WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:399)
[23:57:21 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:133)
[23:57:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[23:57:21 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[23:57:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[23:57:21 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:432)
[23:57:21 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:346)
[23:57:21 WARN]:        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:231)
[23:57:21 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764)
[23:57:21 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:57:21 INFO]: [mcMMO] Disabling mcMMO v1.6.0-SNAPSHOT
```

This is my repair.vanilla.yml:

```
#
#  Repair configuration
#  Last updated on 1.6.0-SNAPSHOT-b${BUILD_NUMBER}
#
# Any file named repair.*.yml in the mcmmmo folder will be loaded as a repair config
# All repair configs have a main section titled "Repairables"
# Afterwards, all sub-items are considered a Repairable to be loaded. The names of each subitem should be the exact material name.
# The bare minimum of a Repairable is that it have a RepairMaterial and a MaximumDurability
#
# ItemType: This is the type of item to be repaired, this is only important to permissions.
## Valid values are ARMOR, TOOL, and OTHER.
## This defaults to OTHER.
#
# MaterialType: This is the type of the material of the item to be repaired, this is only important for permissions.
## Valid values are STRING, LEATHER, WOOD, STONE, IRON, GOLD, DIAMOND, and OTHER
## This defaults to OTHER.
#
# RepairMaterial: This is the material name of the item used to repair this repairable.
## This is required to be set.
#
# RepairMaterialMetadata: This is the metadata of the item used to repair this repairable.
## A value of -1 means to ignore all metadata when repairing.
## This defaults to -1
#
# MaximumDurability: This is the maximum durability of the item.
## This is required to be set.
#
# MinimumLevel: This is the minimum repair level needed to repair this item.
## Valid values are => 0
## This defaults to 0
#
# MinimumQuantity: This is the minimum number of items needed to repair this item ignoring all other repair bonuses.
## This is typically the number of the repair material needed to create a new item, for example for a sword it is 2, for an axe it is 3
## This defaults to 2
#
# XpMultiplier: This is the amount to multiply the xp bonus by.
## This defaults to 1
#
#
# The following is the default repair config that ships with mcMMO, it contains all vanilla items that are repairable.
#
#
###
Repairables:
    #
    # Wooden repairables
    ###
    # Tools
    WOODEN_SWORD:
        MinimumLevel: 0
        XpMultiplier: .25
    WOODEN_SHOVEL:
        MinimumLevel: 0
        XpMultiplier: .16
    WOODEN_PICKAXE:
        MinimumLevel: 0
        XpMultiplier: .5
    WOODEN_AXE:
        MinimumLevel: 0
        XpMultiplier: .5
    WOODEN_HOE:
        MinimumLevel: 0
        XpMultiplier: .25
    #
    # Stone repairables
    ###
    # Tools
    STONE_SWORD:
        MinimumLevel: 0
        XpMultiplier: .25
    STONE_SHOVEL:
        MinimumLevel: 0
        XpMultiplier: .16
    STONE_PICKAXE:
        MinimumLevel: 0
        XpMultiplier: .5
    STONE_AXE:
        MinimumLevel: 0
        XpMultiplier: .5
    STONE_HOE:
        MinimumLevel: 0
        XpMultiplier: .25
    #
    # Iron repairables
    ###
    # Tools
    IRON_SWORD:
        MinimumLevel: 0
        XpMultiplier: .5
    IRON_SHOVEL:
        MinimumLevel: 0
        XpMultiplier: .3
    IRON_PICKAXE:
        MinimumLevel: 0
        XpMultiplier: 1
    IRON_AXE:
        MinimumLevel: 0
        XpMultiplier: 1
    IRON_HOE:
        MinimumLevel: 0
        XpMultiplier: .5
    SHEARS:
        MinimumLevel: 0
        XpMultiplier: .5
    FLINT_AND_STEEL:
        MinimumLevel: 0
        XpMultiplier: .3
    # Armor
    IRON_HELMET:
        MinimumLevel: 0
        XpMultiplier: 2
    IRON_CHESTPLATE:
        MinimumLevel: 0
        XpMultiplier: 2
    IRON_LEGGINGS:
        MinimumLevel: 0
        XpMultiplier: 2
    IRON_BOOTS:
        MinimumLevel: 0
        XpMultiplier: 2
    #
    # Gold repairables
    ###
    # Tools
    GOLDEN_SWORD:
        MinimumLevel: 0
        XpMultiplier: 4
    GOLDEN_SHOVEL:
        MinimumLevel: 0
        XpMultiplier: 2.6
    GOLDEN_PICKAXE:
        MinimumLevel: 0
        XpMultiplier: 8
    GOLDEN_AXE:
        MinimumLevel: 0
        XpMultiplier: 8
    GOLDEN_HOE:
        MinimumLevel: 0
        XpMultiplier: 4
    # Armor
    GOLDEN_HELMET:
        MinimumLevel: 0
        XpMultiplier: 4
    GOLDEN_CHESTPLATE:
        MinimumLevel: 0
        XpMultiplier: 4
    GOLDEN_LEGGINGS:
        MinimumLevel: 0
        XpMultiplier: 4
    GOLDEN_BOOTS:
        MinimumLevel: 0
        XpMultiplier: 4
    #
    # Diamond repairables
    ###
    # Tools
    DIAMOND_SWORD:
        MinimumLevel: 50
        XpMultiplier: .5
    DIAMOND_SHOVEL:
        MinimumLevel: 50
        XpMultiplier: .3
    DIAMOND_PICKAXE:
        MinimumLevel: 50
        XpMultiplier: 1
    DIAMOND_AXE:
        MinimumLevel: 50
        XpMultiplier: 1
    DIAMOND_HOE:
        MinimumLevel: 50
        XpMultiplier: .5
    # Armor
    DIAMOND_HELMET:
        MinimumLevel: 50
        XpMultiplier: 6
    DIAMOND_CHESTPLATE:
        MinimumLevel: 50
        XpMultiplier: 6
    DIAMOND_LEGGINGS:
        MinimumLevel: 50
        XpMultiplier: 6
    DIAMOND_BOOTS:
        MinimumLevel: 50
        XpMultiplier: 6
    #
    # Leather repairables
    ###
    # Armor
    LEATHER_HELMET:
        MinimumLevel: 0
        XpMultiplier: 1
    LEATHER_CHESTPLATE:
        MinimumLevel: 0
        XpMultiplier: 1
    LEATHER_LEGGINGS:
        MinimumLevel: 0
        XpMultiplier: 1
    LEATHER_BOOTS:
        MinimumLevel: 0
        XpMultiplier: 1
    #
    # String repairables
    ###
    # Tools
    FISHING_ROD:
        MinimumLevel: 0
        XpMultiplier: .5
    BOW:
        MinimumLevel: 0
        XpMultiplier: .5
    CARROT_ON_A_STICK:
        MinimumLevel: 0
        XpMultiplier: .5
```
Theres no IRON_INGOT there, and looking on code i dont know form where it gets iron_ingot o.O

**Comment by Glitchfinder** [comment]
That would be because we default certain config data. There are a couple of lines that could be at fault, such as [this one](https://github.com/mcMMO-Dev/mcMMO/blob/ee324c77a9f94b3a1e97a92ebf0b9af5038e7609/src/main/java/com/gmail/nossr50/util/skills/SkillUtils.java#L252). Anyway, there's already a copy of this error in #3498, where we're tacking the 1.13 update bugs.

**Comment by FabioZumbi12** [comment]
HUm, ok.

For now, to go away, i've added this on line 282:

```
BlockData repairData;
        try{
            repairData = repairMaterial != null ? repairMaterial.createBlockData() : null;
        } catch (Exception ex){
            return 0;
        }
```
