### ISSUE TITLE
There was an error while enableing mcMMO!

### ISSUE THREAD

**Issue by RyanO8** [mcMMO-Dev/mcMMO#3548]
I am trying to run a 1.13 server with mcMMO. This was my first time starting the server, I have not messed with any settings or config. 

[13:15:37] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:15:37] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:15:37] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:15:37] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:15:37] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:15:38] [main/INFO]: Loaded 0 recipes
[13:15:38] [Server thread/INFO]: Starting minecraft server version 1.13
[13:15:38] [Server thread/INFO]: Loading properties
[13:15:38] [Server thread/INFO]: Default game type: SURVIVAL
[13:15:38] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-2b0e71c-c0df4b8 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[13:15:38] [Server thread/INFO]: Debug logging is disabled
[13:15:38] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:15:38] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:15:38] [Server thread/INFO]: Generating keypair
[13:15:38] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:15:38] [Server thread/INFO]: Using default channel type
[13:15:41] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[13:15:41] [Server thread/INFO]: [ClearLag] Loading ClearLag v2.9.7
[13:15:41] [Server thread/INFO]: [SetHome] Loading SetHome v1.4
[13:15:41] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.0.0-SNAPSHOT;3817-f96487a
[13:15:41] [Server thread/INFO]: [mcMMO] Loading mcMMO v1.5.00-b3547
[13:15:41] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v7.0.0-SNAPSHOT;1738-44e3f72
[13:15:41] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[13:15:41] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[13:15:41] [Server thread/WARN]: java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
[13:15:41] [Server thread/WARN]: 	at com.gmail.nossr50.config.HiddenConfig.load(HiddenConfig.java:31)
[13:15:41] [Server thread/WARN]: 	at com.gmail.nossr50.config.HiddenConfig.<init>(HiddenConfig.java:18)
[13:15:41] [Server thread/WARN]: 	at com.gmail.nossr50.config.HiddenConfig.getInstance(HiddenConfig.java:23)
[13:15:41] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:400)
[13:15:41] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[13:15:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:15:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[13:15:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[13:15:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426)
[13:15:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340)
[13:15:41] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:214)
[13:15:41] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
[13:15:41] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:15:41] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[13:15:41] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at com.gmail.nossr50.config.AutoUpdateConfigLoader.loadFile(AutoUpdateConfigLoader.java:29) ~[?:?]
	at com.gmail.nossr50.config.ConfigLoader.<init>(ConfigLoader.java:26) ~[?:?]
	at com.gmail.nossr50.config.AutoUpdateConfigLoader.<init>(AutoUpdateConfigLoader.java:23) ~[?:?]
	at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:20) ~[?:?]
	at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:26) ~[?:?]
	at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:51) ~[?:?]
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:203) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-2b0e71c-c0df4b8]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:363) [spigot.jar:git-Spigot-2b0e71c-c0df4b8]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot.jar:git-Spigot-2b0e71c-c0df4b8]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-2b0e71c-c0df4b8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-2b0e71c-c0df4b8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-2b0e71c-c0df4b8]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [spigot.jar:git-Spigot-2b0e71c-c0df4b8]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [spigot.jar:git-Spigot-2b0e71c-c0df4b8]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:214) [spigot.jar:git-Spigot-2b0e71c-c0df4b8]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot.jar:git-Spigot-2b0e71c-c0df4b8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[13:15:41] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[13:15:41] [Server thread/INFO]: Preparing level "world"
[13:15:41] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[13:15:42] [Server thread/INFO]: Loaded 524 recipes
[13:15:42] [Server thread/INFO]: -------- World Settings For [world] --------
[13:15:42] [Server thread/INFO]: Arrow Despawn Rate: 1200
[13:15:42] [Server thread/INFO]: Item Despawn Rate: 6000
[13:15:42] [Server thread/INFO]: Item Merge Radius: 2.5
[13:15:42] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:15:42] [Server thread/INFO]: View Distance: 10
[13:15:42] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[13:15:42] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[13:15:42] [Server thread/INFO]: Experience Merge Radius: 3.0
[13:15:42] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:15:42] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[13:15:42] [Server thread/INFO]: Random Lighting Updates: false
[13:15:42] [Server thread/INFO]: Cactus Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Cane Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Melon Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Sapling Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Wheat Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Vine Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Mob Spawn Range: 6
[13:15:42] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:15:42] [Server thread/INFO]: Max TNT Explosions: 100
[13:15:42] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:15:42] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[13:15:42] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[13:15:42] [Server thread/INFO]: Arrow Despawn Rate: 1200
[13:15:42] [Server thread/INFO]: Item Despawn Rate: 6000
[13:15:42] [Server thread/INFO]: Item Merge Radius: 2.5
[13:15:42] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:15:42] [Server thread/INFO]: View Distance: 10
[13:15:42] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[13:15:42] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[13:15:42] [Server thread/INFO]: Experience Merge Radius: 3.0
[13:15:42] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:15:42] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[13:15:42] [Server thread/INFO]: Random Lighting Updates: false
[13:15:42] [Server thread/INFO]: Cactus Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Cane Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Melon Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Sapling Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Wheat Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Vine Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[13:15:42] [Server thread/INFO]: Mob Spawn Range: 6
[13:15:42] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:15:42] [Server thread/INFO]: Max TNT Explosions: 100
[13:15:42] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:15:42] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[13:15:42] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[13:15:42] [Server thread/INFO]: Arrow Despawn Rate: 1200
[13:15:42] [Server thread/INFO]: Item Despawn Rate: 6000
[13:15:42] [Server thread/INFO]: Item Merge Radius: 2.5
[13:15:42] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:15:42] [Server thread/INFO]: View Distance: 10
[13:15:42] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[13:15:42] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[13:15:42] [Server thread/INFO]: Experience Merge Radius: 3.0
[13:15:42] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:15:42] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[13:15:43] [Server thread/INFO]: Random Lighting Updates: false
[13:15:43] [Server thread/INFO]: Cactus Growth Modifier: 100%
[13:15:43] [Server thread/INFO]: Cane Growth Modifier: 100%
[13:15:43] [Server thread/INFO]: Melon Growth Modifier: 100%
[13:15:43] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[13:15:43] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[13:15:43] [Server thread/INFO]: Sapling Growth Modifier: 100%
[13:15:43] [Server thread/INFO]: Wheat Growth Modifier: 100%
[13:15:43] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[13:15:43] [Server thread/INFO]: Vine Growth Modifier: 100%
[13:15:43] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[13:15:43] [Server thread/INFO]: Mob Spawn Range: 6
[13:15:43] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[13:15:43] [Server thread/INFO]: Max TNT Explosions: 100
[13:15:43] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:15:43] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
[13:15:43] [Server thread/INFO]: Preparing start region for level 0 (Seed: 2996565479740155322)
[13:15:43] [Server thread/INFO]: Preparing spawn area: 4%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 8%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 12%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 16%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 20%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 24%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 28%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 32%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 36%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 40%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 44%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 48%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 52%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 56%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 60%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 64%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 68%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 72%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 76%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 80%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 84%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 88%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 92%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 96%
[13:15:43] [Server thread/INFO]: Preparing spawn area: 100%
[13:15:43] [Server thread/INFO]: Preparing start region for level 1 (Seed: 2996565479740155322)
[13:15:44] [Server thread/INFO]: Preparing spawn area: 4%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 8%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 12%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 16%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 20%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 24%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 28%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 32%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 36%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 40%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 44%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 48%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 52%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 56%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 60%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 64%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 68%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 72%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 76%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 80%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 84%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 88%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 92%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 96%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 100%
[13:15:44] [Server thread/INFO]: Preparing start region for level 2 (Seed: 2996565479740155322)
[13:15:44] [Server thread/INFO]: Preparing spawn area: 4%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 8%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 12%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 16%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 20%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 24%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 28%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 32%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 36%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 40%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 44%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 48%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 52%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 56%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 60%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 64%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 68%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 72%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 76%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 80%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 84%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 88%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 92%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 96%
[13:15:44] [Server thread/INFO]: Preparing spawn area: 100%
[13:15:44] [Server thread/INFO]: [ClearLag] Enabling ClearLag v2.9.7
[13:15:44] [Server thread/INFO]: [ClearLag] Loading modules...
[13:15:44] [Server thread/INFO]: [ClearLag] Modules enabed, loading config values
[13:15:44] [Server thread/INFO]: [ClearLag] Modules have been loaded!
[13:15:44] [Server thread/INFO]: [ClearLag] Clearlag is now enabled!
[13:15:45] [Thread-7/INFO]: [ClearLag] Checking for updates compatible with your bukkit version [1.13]...
[13:15:45] [Server thread/INFO]: [SetHome] Enabling SetHome v1.4
[13:15:45] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.0.0-SNAPSHOT;3817-f96487a
[13:15:45] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R1 as the Bukkit adapter
[13:15:45] [Server thread/WARN]: [WorldEdit] Unknown block: minecraft:tnt[unstable=false]
[13:15:45] [Server thread/WARN]: [WorldEdit] Unknown block: minecraft:tnt[unstable=true]
[13:15:45] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[13:15:45] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v7.0.0-SNAPSHOT;1738-44e3f72
[13:15:45] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[13:15:45] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[13:15:45] [Server thread/INFO]: [WorldGuard] (world) Lava fire is blocked.
[13:15:45] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[13:15:45] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[13:15:45] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[13:15:45] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[13:15:45] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[13:15:45] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[13:15:45] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[13:15:45] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[13:15:45] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[13:15:45] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[13:15:45] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[13:15:45] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[13:15:45] [Server thread/INFO]: [WorldGuard] Loading region data...
[13:15:46] [Thread-7/INFO]: [ClearLag] No updates found!
[13:15:46] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:15:46] [Server thread/INFO]: Time elapsed: 3508 ms
[13:15:46] [Server thread/INFO]: Done (4.731s)! For help, type "help"
[13:15:46] [Server thread/INFO]: Starting remote control listener
[13:15:46] [Server thread/WARN]: No rcon password set in 'C:\Users\mobuc\Desktop\1.13 server\server.properties', rcon disabled!
[13:19:02] [Server thread/INFO]: Stopping the server
[13:19:02] [Server thread/INFO]: Stopping server
[13:19:02] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v7.0.0-SNAPSHOT;1738-44e3f72
[13:19:02] [Server thread/INFO]: [WorldGuard] Shutting down executor and waiting for any pending tasks...
[13:19:02] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v7.0.0-SNAPSHOT;3817-f96487a
[13:19:02] [Server thread/INFO]: [SetHome] Disabling SetHome v1.4
[13:19:02] [Server thread/INFO]: [ClearLag] Disabling ClearLag v2.9.7
[13:19:02] [Server thread/INFO]: [ClearLag] Clearlag is now disabled!
[13:19:02] [Server thread/INFO]: Saving players
[13:19:02] [Server thread/INFO]: Saving worlds
[13:19:02] [Server thread/INFO]: Saving chunks for level 'world'/overworld
[13:19:02] [Server thread/INFO]: Saving chunks for level 'world_nether'/the_nether
[13:19:02] [Server thread/INFO]: Saving chunks for level 'world_the_end'/the_end

**Comment by Geekerandy** [comment]
The same issue, but here it looks cleaner: https://pastebin.com/R0PC46cq
After world load, I did /plugins, then tested /mcmmo, then /stop 

Running on Spigot-1.12.2.
The only plugin is McMMO, the latest build on https://popicraft.net/jenkins/job/mcMMO/38/
Build #38
(aka the free version)

**Comment by t00thpick1** [comment]
Same as your other ticket.

**Comment by Glitchfinder** [comment]
To clarify, you're using an mcMMO 1.5.00 build, which was for Minecraft 1.7. For Minecraft 1.13, you're going to need a much newer build, specifically one of the in-progress [development builds](https://popicraft.net/jenkins/job/mcMMO/). Be warned that the 1.13 update is very much a work in progress and that it is currently prone to all sorts of issues.
