### ISSUE TITLE
Mcmmo Getting disabled

### ISSUE THREAD

**Issue by doggybears** [mcMMO-Dev/mcMMO#3549]
Hi in my server mcmmo is getting disabled here is the error from console

[13:50:26] [Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547
[13:50:28] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[13:50:28] [Server thread/WARN]: java.lang.NullPointerException
[13:50:28] [Server thread/WARN]: 	at java.io.Reader.<init>(Unknown Source)
[13:50:28] [Server thread/WARN]: 	at java.io.InputStreamReader.<init>(Unknown Source)
[13:50:28] [Server thread/WARN]: 	at com.gmail.nossr50.metrics.MetricsManager.setup(MetricsManager.java:72)
[13:50:28] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:173)
[13:50:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[13:50:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[13:50:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:50:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356)
[13:50:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316)
[13:50:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:157)
[13:50:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:540)
[13:50:28] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:50:28] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[13:50:54] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:206) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[paperspigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [paperspigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [paperspigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) [mcMMO%20(6).jar:?]

**Comment by t00thpick1** [comment]
this is an ancient build of mcMMO

**Comment by Glitchfinder** [comment]
It's also running on a 1.8 server. The most recent build of mcMMO that should be compatible with your server is [this one](https://popicraft.net/jenkins/job/mcMMO/). 1.500 builds were for 1.7, and there are evidently some compatibility issues. Though there may also be an issue with the configuration file, if I remember this error correctly.
