### ISSUE TITLE
Error using any version of MCMMO [Spigot - Server version 1.8.8]

### ISSUE THREAD

**Issue by chaosworlds1** [mcMMO-Dev/mcMMO#3557]
Here is the error I get no matter what version I use for mcmmo. This is an error that seemed to happen randomly. Currently players can't join the server either (Not sure if this bug is the cause I'm still looking into it) I've tried removing everything and adding a fresh mcmmo that generates new files and this still happens.

> [23:50:53 INFO]: [mcMMO] Enabling mcMMO v1.5.09-SNAPSHOT
> [23:50:53 ERROR]: [mcMMO] There was an error while enabling mcMMO!
> [23:50:53 WARN]: java.lang.NoSuchFieldError: MENDING
> [23:50:53 WARN]: at com.gmail.nossr50.util.EnchantmentUtils.<clinit>(EnchantmentUtils.java:34)
> [23:50:53 WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.loadEnchantments(TreasureConfig.java:368)
> [23:50:53 WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:105)
> [23:50:53 WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:46)
> [23:50:53 WARN]: at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:52)
> [23:50:53 WARN]: at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:385)
> [23:50:53 WARN]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:145)
> [23:50:53 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
> [23:50:53 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
> [23:50:53 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
> [23:50:53 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
> [23:50:53 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
> [23:50:53 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
> [23:50:53 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
> [23:50:53 WARN]: at java.lang.Thread.run(Thread.java:748)
> [23:50:53 INFO]: [mcMMO] Disabling mcMMO v1.5.09-SNAPSHOT
> [23:50:53 ERROR]: [mcMMO] Cannot read /home/container/plugins/mcMMO/experience.yml(File Permissions?)
> [23:50:53 ERROR]: [mcMMO] Cannot read /home/container/plugins/mcMMO/repair.vanilla.yml(File Permissions?)
> [23:50:53 ERROR]: Error occurred while disabling mcMMO v1.5.09-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:245) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot.jar:git-Spigot-db6de12-18fbb24]
at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:199) [mcMMO%20(4).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Glitchfinder** [comment]
mcMMO 1.5.09 is too new for a Minecraft 1.8 server. The most recent build that functions on 1.8 is [this one](https://www.t00thpick1.net/mcMMO/mcMMO_1_8.jar).
