### ISSUE TITLE
FurnaceExtractEvent Error - PaperSpigot 1.13.1

### ISSUE THREAD

**Issue by Tomographix** [mcMMO-Dev/mcMMO#3590]
Hi,
Latest MCMMO build off spigot with 1.13.1 PaperSpigot.

```01.10 12:35:15 [Server] ERROR Could not pass event FurnaceExtractEvent to mcMMO v1.6.0-SNAPSHOT
01.10 12:35:15 [Server] INFO org.bukkit.event.EventException: null
01.10 12:35:15 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.SlotFurnaceResult.c(SlotFurnaceResult.java:80) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.SlotFurnaceResult.a(SlotFurnaceResult.java:40) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.Slot.a(SourceFile:27) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.ContainerFurnace.shiftClick(ContainerFurnace.java:136) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.Container.a(Container.java:249) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2291) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
01.10 12:35:15 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-317]
01.10 12:35:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
01.10 12:35:15 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by Tomographix** [comment]
Anyone have any ideas?

**Comment by Tomographix** [comment]
Potentially! I am running PaperSpigot if that helps :)

**Comment by t00thpick1** [comment]
Can you figure out what item is causing the error?  Some item being cooked in a furnace is causing it.

**Comment by Tomographix** [comment]
Hmm could be nearly impossible to work that out seeing there are normally 40 online.
Run some tests do you think?

**Comment by Tomographix** [comment]
Several days of testing - yet to find a specific item yet.
But is very hard to tell if the errors are occurring due to your testing or other people online.

**Comment by Tomographix** [comment]
So I think we have concluded it is not caused by any specific item. Just removing items manually from a furnace causes it.
If the items are removed by a hopper then no error occurs.

**Comment by nossr50** [comment]
I'll see if I can reproduce this on my end

**Comment by Tomographix** [comment]
Any update on this bug at all? :) Thanks

**Comment by nossr50** [comment]
@Tomographix are you still having this on the latest dev builds?

**Comment by Tomographix** [comment]
> @Tomographix are you still having this on the latest dev builds?

I believe I am running one of the later dev builds. I'll double check. Do you have the download link for the dev builds please? I can't seem to find it now.

**Comment by nossr50** [comment]
ecocitycraft hosts a jenkins with builds courtesy of @andrewkm 
https://ci.ecocitycraft.com/job/McMMO/

**Comment by Tomographix** [comment]
No luck on latest dev builds. Still errors.

**Comment by nossr50** [comment]
how do you reproduce this error?

**Comment by Tomographix** [comment]
You don't need to do anything special. Simply removing stuff out of a furnace causes it.

**Comment by nossr50** [comment]
It's not causing it for me. I'm not getting reports of this from any other server admins either. Can you come talk to me in our discord?

https://discord.gg/bJ7pFS9

**Comment by Quavelen** [comment]
Closed for two reasons:

1. This is the overhaul repository, please use https://github.com/mcMMO-Dev/mcMMO-Classic for issues pertaining to mcMMO versions `1.6.x` and older.
2. nossr50 requested this issue be further discussed in the discord server.
