### ISSUE TITLE
Concurrent Modification Exceptio

### ISSUE THREAD

**Issue by Sakanas** [mcMMO-Dev/mcMMO#3592]
```
02.10 06:23:46 [Server] WARN [mcMMO] Task #21 for mcMMO v1.5.10-SNAPSHOT generated an exception
02.10 06:23:46 [Server] INFO java.util.ConcurrentModificationException: null
02.10 06:23:46 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_144]
02.10 06:23:46 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1471) ~[?:1.8.0_144]
02.10 06:23:46 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1469) ~[?:1.8.0_144]
02.10 06:23:46 [Server] INFO at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:24) ~[?:?]
02.10 06:23:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1572]
02.10 06:23:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1572]
02.10 06:23:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1572]
02.10 06:23:46 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1572]
02.10 06:23:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1572]
02.10 06:23:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1572]
02.10 06:23:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by Glitchfinder** [comment]
[This](https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/runnables/skills/BleedTimerTask.java#L24) appears to be the faulty line, though I don't have time to trace a threading error before work.

**Comment by nossr50** [comment]
Thanks for the report I'll take a look

**Comment by Quavelen** [comment]
This is the overhaul repository, please use https://github.com/mcMMO-Dev/mcMMO-Classic for issues pertaining to versions older than mcMMO `2.1xx`.
