### ISSUE TITLE
Mcmmo Disabled

### ISSUE THREAD

**Issue by LuxOfCrownGuard** [mcMMO-Dev/mcMMO#3603]
```
19:05:11  [Error] nullorg.bukkit.command.CommandException: Cannot execute command 'stats' in plugin mcMMO v1.6.0-SNAPSHOT - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-1cf8b5d]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181].
```

**Comment by nossr50** [comment]
Try running mcMMO alone by itself without any other plugins in your plugins folder and let me know if this problem still happens

**Comment by Quavelen** [comment]
This is the overhaul repository, please use https://github.com/mcMMO-Dev/mcMMO-Classic for issues pertaining to mcMMO versions `1.6.x` and older.
