### ISSUE TITLE
Error on PlayerPickupArrowEvent

### ISSUE THREAD

**Issue by FabioZumbi12** [mcMMO-Dev/mcMMO#3604]
```
[00:52:07 ERROR]: Could not pass event PlayerPickupArrowEvent to mcMMO v1.6.0-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-375]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-375]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-375]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.EntityArrow.d(EntityArrow.java:500) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.EntityThrownTrident.d(EntityThrownTrident.java:142) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.EntityHuman.c(EntityHuman.java:496) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.EntityHuman.k(EntityHuman.java:471) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2182) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:163) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:402) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.PlayerConnection.Y_(PlayerConnection.java:145) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:253) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:130) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1118) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-375]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-375]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassCastException

```

Using mcmmo build 51 on **git-Paper-375 (MC: 1.13.1)**

**Comment by nossr50** [comment]
Does this still happen in 2.0.0?

**Comment by FabioZumbi12** [comment]
Nope, thanks!!
