### ISSUE TITLE
Error enabling mcmmo

### ISSUE THREAD

**Issue by DivineSouls83** [mcMMO-Dev/mcMMO#3678]
I'm getting this error even though the version is for 1.7.9

[mcMMO] Enabling mcMMO v1.5.00-b3547
[13:09:57] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[13:09:57] [Server thread/WARN]: java.lang.NullPointerException
[13:09:57] [Server thread/WARN]: 	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:261)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftItemStack.getDurability(CraftItemStack.java:170)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:130)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:34)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftShapelessRecipe.<init>(CraftShapelessRecipe.java:15)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.CraftShapelessRecipe.<init>(CraftShapelessRecipe.java:19)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.item.crafting.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:32)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.item.crafting.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:15)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.RecipeIterator.next(RecipeIterator.java:32)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.inventory.RecipeIterator.next(RecipeIterator.java:10)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.getRecipesFor(CraftServer.java:1143)
[13:09:57] [Server thread/WARN]: 	at com.gmail.nossr50.skills.repair.Repair.getRepairAndSalvageQuantities(Repair.java:85)
[13:09:57] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.loadKeys(RepairConfig.java:139)
[13:09:57] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.<init>(RepairConfig.java:24)
[13:09:57] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfigManager.<init>(RepairConfigManager.java:34)
[13:09:57] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:424)
[13:09:57] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
[13:09:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.world.World.<init>(World.java:374)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
[13:09:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
[13:09:57] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:09:57] [Server thread/INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[13:09:57] [Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)

**Comment by DivineSouls83** [comment]
Is there a way to get it working for 1.7.10?
    	

    	
    
  



On Thu, Jan 3, 2019 at 1:27 PM -0800, "Robert A. C." <notifications@github.com> wrote:












I believe 1.5.00 was for 1.12


With that said, I don't offer support for older versions of mcMMO at this time.
