### ISSUE TITLE
Could not find locale string: Commands.XPGain.Smelting, Salvage

### ISSUE THREAD

**Issue by andris155** [mcMMO-Dev/mcMMO#3697]
```
[14:11:37] [Server thread/WARN]: [mcMMO] Could not find locale string: Commands.XPGain.Smelting
[14:11:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'smelting' in plugin mcMMO v2.1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1790) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1598) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-495]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-495]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.datatypes.player.PlayerProfile.getSkillXpLevelRaw(PlayerProfile.java:198) ~[?:?]
	at com.gmail.nossr50.datatypes.player.PlayerProfile.getSkillXpLevel(PlayerProfile.java:202) ~[?:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.getSkillXpLevel(McMMOPlayer.java:866) ~[?:?]
	at com.gmail.nossr50.commands.skills.SkillCommand.sendSkillCommandHeader(SkillCommand.java:151) ~[?:?]
	at com.gmail.nossr50.commands.skills.SkillCommand.onCommand(SkillCommand.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-495]
	... 15 more
```
```
[14:11:17] [Server thread/WARN]: [mcMMO] Could not find locale string: Commands.XPGain.Salvage
[14:11:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'salvage' in plugin mcMMO v2.1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1790) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1598) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-495]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-495]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.datatypes.player.PlayerProfile.getSkillXpLevelRaw(PlayerProfile.java:198) ~[?:?]
	at com.gmail.nossr50.datatypes.player.PlayerProfile.getSkillXpLevel(PlayerProfile.java:202) ~[?:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.getSkillXpLevel(McMMOPlayer.java:866) ~[?:?]
	at com.gmail.nossr50.commands.skills.SkillCommand.sendSkillCommandHeader(SkillCommand.java:151) ~[?:?]
	at com.gmail.nossr50.commands.skills.SkillCommand.onCommand(SkillCommand.java:71) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-495]
	... 15 more
```

**Comment by nossr50** [comment]
should be fixed
