### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to mcMMO v2.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by andris155** [mcMMO-Dev/mcMMO#3698]
```
[12:19:10] [Async Chat Thread - #47/ERROR]: Could not pass event AsyncPlayerChatEvent to mcMMO v2.1.0-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-495]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-495]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PlayerConnection.chat(PlayerConnection.java:1703) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1618) ~[patched_1.13.2.jar:git-Paper-495]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[patched_1.13.2.jar:git-Paper-495]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4481) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:101) ~[?:?]
	at com.gmail.nossr50.chat.ChatManager.handleChat(ChatManager.java:54) ~[?:?]
	at com.gmail.nossr50.chat.PartyChatManager.handleChat(PartyChatManager.java:23) ~[?:?]
	at com.gmail.nossr50.chat.ChatManager.handleChat(ChatManager.java:77) ~[?:?]
	at com.gmail.nossr50.listeners.PlayerListener.onPlayerChat(PlayerListener.java:655) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor33.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-495]
	... 11 more
```

**Comment by nossr50** [comment]
Hmm, I haven't seen this one before.
I'll look into it.

**Comment by andris155** [comment]
![51444141-ff750300-1cf3-11e9-85d0-be2473dd6825](https://user-images.githubusercontent.com/8324198/51460734-9c6b8680-1d5c-11e9-8e7d-d412471bff37.png)
This is a party chat error. Sometimes party chat on write to normal chat and party chat.

**Comment by andris155** [comment]
Maybe cause ChatControl and mcMMO conflict?

**Comment by Momshroom** [comment]
I’ve been using the free version of chat control alongside mcmmo for quite
a while with no issues, though I am still using toothpick’s version of
mcmmo.

**Comment by andris155** [comment]
I am using ChatControl Pro.
