### ISSUE TITLE
Error could not pass event playerinteractevent to MCmmo v2.1.11

### ISSUE THREAD

**Issue by Stefansonson** [mcMMO-Dev/mcMMO#3791]
Every time someone tries to use an ability on my server i get an error message and the ability doesn't activate.

 Could not pass event PlayerInteractEvent to mcMMO v2.1.11
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:304) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:458) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1201) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(SourceFile:53) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(SourceFile:11) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [craftbukkit.jar:git-Bukkit-c7ba979]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:839) [craftbukkit.jar:git-Bukkit-c7ba979]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:382) [craftbukkit.jar:git-Bukkit-c7ba979]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792) [craftbukkit.jar:git-Bukkit-c7ba979]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695) [craftbukkit.jar:git-Bukkit-c7ba979]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.processAbilityActivation(McMMOPlayer.java:908) ~[?:?]
        at com.gmail.nossr50.listeners.PlayerListener.onPlayerInteractMonitor(PlayerListener.java:626) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.processAbilityActivation(McMMOPlayer.java:908) ~[?:?]
        at com.gmail.nossr50.listeners.PlayerListener.onPlayerInteractMonitor(PlayerListener.java:626) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[craftbukkit.jar:git-Bukkit-c7ba979]
        ... 17 more

**Comment by nossr50** [comment]
You need to use Spigot or Paper instead of Bukkit to run mcMMO

https://mcmmo.org/wiki/Installation_guide#Fresh_Install
