### ISSUE TITLE
Running /mcrank on an offlineplayer errors because the player is null

### ISSUE THREAD

**Issue by Nicofisi** [mcMMO-Dev/mcMMO#3796]
https://github.com/mcMMO-Dev/mcMMO/blob/29befac27e507d7ab42c7b162223d8da7ea994da/src/main/java/com/gmail/nossr50/runnables/commands/McrankCommandDisplayTask.java#L43-L51
```
[14:48:23 WARN]: [mcMMO] Task #40713 for mcMMO v2.2.0-SNAPSHOT generated an exception
java.lang.NullPointerException: null
        at com.gmail.nossr50.util.Permissions.skillEnabled(Permissions.java:134) ~[?:?]
        at com.gmail.nossr50.datatypes.skills.PrimarySkillType.getPermissions(PrimarySkillType.java:228) ~[?:?]
        at com.gmail.nossr50.runnables.commands.McrankCommandDisplayTask.displayChat(McrankCommandDisplayTask.java:51) ~[?:?]
        at com.gmail.nossr50.runnables.commands.McrankCommandDisplayTask.run(McrankCommandDisplayTask.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-524]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-524]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-524]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-524]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-524]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-524]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

and then you can't run any further summary commands before the server is restarted because:
![image](https://user-images.githubusercontent.com/12614053/52900787-d3697680-31fa-11e9-80bd-3784373e9423.png)

Maybe some better error handling could be added, so that bugs like this aren't kinda game breaking?

Cheers,
mcMMO lover <3

**Comment by nossr50** [comment]
@Nicofisi Thanks for the report, to be honest I've never seen this reported before so I almost wonder if its a plugin conflict. I'll test it out and see if I can reproduce.

**Comment by nossr50** [comment]
This was fixed
