### ISSUE TITLE
WorldEdit Supervisor Stacktrace

### ISSUE THREAD

**Issue by GreatThane** [mcMMO-Dev/mcMMO#3824]
I have world edit installed on my server, and at random points this stacktrace will fill the logs. Even after fully resetting the server after uninstallling both world edit and world guard, the issue persists. It doesn't seem to impact the players other than they stop earning experience until I either restart the server, or do a /reload.
`[07:44:40 ERROR]: Could not pass event PlayerInteractEvent to mcMMO v2.1.12
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:304) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:271) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1162) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/util/task/Supervisor
	at com.gmail.nossr50.worldguard.WorldGuardManager.hasMainFlag(WorldGuardManager.java:42) ~[?:?]
	at com.gmail.nossr50.listeners.PlayerListener.onPlayerInteractMonitor(PlayerListener.java:606) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor1035.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot_server.jar:git-Spigot-3cb9dcb-77ca7ca]
`

**Comment by nossr50** [comment]
update both your World Edit and World Guard to the latest version
