### ISSUE TITLE
IndexOutOfBoundsException: Index: 0

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#3859]
Paper dev 603 (Spigot 1.13.2)
McMMO dev 614

```
[10:30:31] [Craft Scheduler Thread - 250/WARN]: [mcMMO] Plugin mcMMO v2.1.36 generated an exception while executing task 263888
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4481) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:99) ~[?:?]
	at com.gmail.nossr50.util.player.NotificationManager.sendPlayerInformation(NotificationManager.java:31) ~[?:?]
	at com.gmail.nossr50.runnables.skills.AbilityCooldownTask.run(AbilityCooldownTask.java:26) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-603]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-603]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-603]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by nossr50** [comment]
Thanks for the report I'll take a look soon.

**Comment by mibby** [comment]
No worries, let me know if you need any additional information or assistance in testing.

**Comment by nossr50** [comment]
Currently waiting for my headache to die down, which it slowly is. I'll check on this exception soon :)
