### ISSUE TITLE
Could not pass event inventorymoveitemevent to mcMMO error

### ISSUE THREAD

**Issue by Raigna** [mcMMO-Dev/mcMMO#3871]
since a update to 2.1.41 i've been receiving this error, I also now have a player that has doesnt have a power level but has his other stats and he cant gain anymore mcmmo xp

`[05:10:41] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to mcMMO v2.1.41
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at net.minecraft.server.v1_13_R2.TileEntityHopper.s(TileEntityHopper.java:220) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at net.minecraft.server.v1_13_R2.TileEntityHopper.a(TileEntityHopper.java:136) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at net.minecraft.server.v1_13_R2.TileEntityHopper.tick(TileEntityHopper.java:118) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1193) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:968) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-f56e2e7-ed274c5]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:106) ~[?:?]
	at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.getValidIngredients(AlchemyPotionBrewer.java:96) ~[?:?]
	at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.isValidIngredient(AlchemyPotionBrewer.java:86) ~[?:?]
	at com.gmail.nossr50.listeners.InventoryListener.onInventoryMoveItemEvent(InventoryListener.java:427) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-f56e2e7-ed274c5]
	... 13 more
`

**Comment by nossr50** [comment]
@Raigna Can I get your full log file.

**Comment by nossr50** [comment]
Try 2.1.42

**Comment by PulseBeat02** [comment]
Hi, I also seem to be getting this issue.

**Comment by darbyjack** [comment]
Pulse, can  you share a copy of your log file? Thanks.

**Comment by PulseBeat02** [comment]
@darbyjack It’s all good now. I contacted the discord and they fixed the issue. You can close the issue now.
