### ISSUE TITLE
Getting this warning every time server shut's down or restarts.

### ISSUE THREAD

**Issue by WhyDoWeWonder** [mcMMO-Dev/mcMMO#3947]
`[22:40:08 INFO]: [mcMMO] Disabling mcMMO v2.1.69
[22:40:08 WARN]: java.lang.NullPointerException
[22:40:08 WARN]:        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:257)
[22:40:08 WARN]:        at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:69)
[22:40:08 WARN]:        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:321)
[22:40:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[22:40:08 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
[22:40:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:452)
[22:40:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:438)
[22:40:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[22:40:08 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:398)
[22:40:08 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:713)
[22:40:08 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:732)
[22:40:08 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.close(MinecraftServer.java:689)
[22:40:08 WARN]:        at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:92)
[22:40:08 WARN]:        at org.spigotmc.RestartCommand.restart(RestartCommand.java:61)
[22:40:08 WARN]:        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40)
[22:40:08 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer$5.restart(CraftServer.java:2040)
[22:40:08 WARN]:        at net.craftersland.data.bridge.commands.handlers.SaveAndKickCmd$1.run(SaveAndKickCmd.java:64)
[22:40:08 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[22:40:08 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[22:40:08 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1114)
[22:40:08 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
[22:40:08 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060)
[22:40:08 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904)
[22:40:08 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by nossr50** [comment]
How are you shutting down the server?

**Comment by nossr50** [comment]
Update your server, this should be fixed now.
