### ISSUE TITLE
Unexpected exception while parsing console command "mcnotify"

### ISSUE THREAD

**Issue by RalphORama** [mcMMO-Dev/mcMMO#3982]
System Info: `Java 1.8 (OpenJDK 64-Bit Server VM 25.212-b01) Host: Linux 4.15.0-54-generic (amd64)` (`openjdk version "1.8.0_212"`)
Paper version: `git-Paper-637 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

I am trying to disable chat messages like "RalphORama used Super Breaker!" by typing `mcnotify` in the server console.  When I do, I get the following error:

```
mcnotify => [22:59:19 WARN]: Unexpected exception while parsing console command "mcnotify"
org.bukkit.command.CommandException: Unhandled exception executing command 'mcnotify' in plugin mcMMO v2.1.94
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-636]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-636]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-636]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:696) ~[patched_1.13.2.jar:git-Paper-636]
at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483) ~[patched_1.13.2.jar:git-Paper-636]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[patched_1.13.2.jar:git-Paper-636]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-636]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-636]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassCastException: com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to org.bukkit.entity.Player
at com.gmail.nossr50.commands.McnotifyCommand.onCommand(McnotifyCommand.java:19) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-636]
... 8 more
```

**Comment by electronicboy** [comment]
That command can only be used by players, there is no way in general to disable those messages for every player (without some plugin to basically set the option to disable those messages for them)

The handling of this could be improved, however
