### ISSUE TITLE
Attempting to programmatically raise child skill level results in NPE

### ISSUE THREAD

**Issue by PikaMug** [mcMMO-Dev/mcMMO#3994]
_I'm aware you're moving house, so please don't feel pressure to respond until that's sorted._

Consider the following code for an addon I'm writing:

```
for (PrimarySkillType pst : PrimarySkillType.values()) {

    // Player just joined, so get mcMMO to recognize them.
    if (!UserManager.hasPlayerDataKey(player)) {
        UserManager.track(new McMMOPlayer(player, new PlayerProfile(player.getName(), player.getUniqueId())));
    }

    // Add one level to each of their skill type
    if (!pst.toString().equals("SALVAGE") && !pst.toString().equals("SMELTING")) {
        UserManager.getPlayer(player).getProfile().addLevels(pst, 1);
    }
}
```

Works well enough, but note that I'm forced to exclude SALVAGE and SMELTING from the loop. If I don't, the following error occurs:

```
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.datatypes.player.PlayerProfile.addLevels(PlayerProfile.java:347) ~[?:?]
	at me.pikamug.mcMMO_OverhaulQuests.mcMMOSkillReward.giveReward(mcMMOSkillReward.java:55) ~[?:?]
	at me.blackvein.quests.Quest.completeQuest(Quest.java:672) ~[?:?]
	at me.blackvein.quests.Quest.nextStage(Quest.java:186) ~[?:?]
	at me.blackvein.quests.Quester.finishObjective(Quester.java:1989) ~[?:?]
	at me.blackvein.quests.Quester.breakBlock(Quester.java:1080) ~[?:?]
	at me.blackvein.quests.listeners.PlayerListener.onBlockBreak(PlayerListener.java:459) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[craftbukkit.jar:git-Spigot-947a8e7-3a91182]
	... 17 more
```

In writing this ticket, I realized using _PrimarySkillType.NON_CHILD_SKILLS_ instead of _PrimarySkillType.values()_ was the way to go, but that wasn't my first instinct. **Please consider updating the [#modifySkill](https://github.com/mcMMO-Dev/mcMMO/blob/0638f4c437e1a56a0261907c369aee65747708da/src/main/java/com/gmail/nossr50/datatypes/player/PlayerProfile.java#L325) method to throw a more descriptive error or just fail silently.**

**Comment by broccolai** [comment]
Yeah, this is intended but it's not clear for people using it. This is something that would likely have proper exceptions when the new api is done.
