### ISSUE TITLE
MCMMO /inspect returning error when player is offline.

### ISSUE THREAD

**Issue by WhyDoWeWonder** [mcMMO-Dev/mcMMO#3999]
Server version: git-Paper-122 (MC: 1.14.3)
MCMMO version: 2.1.91 - SNAPSHOT

`[18:08:25 INFO]: LordofLightning issued server command: /inspect AbysmicSword
[18:08:25 WARN]: [mcMMO] A valid mcMMOPlayer object could not be found for AbysmicSword.
[18:08:25 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'inspect' in plugin mcMMO v2.1.91-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.3.jar:git-Paper-127]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.3.jar:git-Paper-127]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1831) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1639) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-127]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
        at com.gmail.nossr50.datatypes.player.PlayerProfile.getXpToLevel(PlayerProfile.java:418) ~[?:?]
        at com.gmail.nossr50.util.commands.CommandUtils.displaySkill(CommandUtils.java:212) ~[?:?]
        at com.gmail.nossr50.commands.player.InspectCommand.onCommand(InspectCommand.java:51) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.3.jar:git-Paper-127]
        ... 17 more`

**Comment by nossr50** [comment]
First of all update mcMMO
Secondly, does this happen ever single time you try to inspect this player? FlatFile or MySQL?

**Comment by WhyDoWeWonder** [comment]
Using Mysql 5.7.26-Log

**Comment by WhyDoWeWonder** [comment]
And yes it happens every single time I try to inspect the player

**Comment by nossr50** [comment]
Is it just this particular player?

**Comment by WhyDoWeWonder** [comment]
It doesn't work on any offline player.

**Comment by nossr50** [comment]
@WhyDoWeWonder Try updating mcMMO and see if this issue persists, let me know. Get me a new error log if it happens again.

**Comment by WhyDoWeWonder** [comment]
Update to 2.1.97

`[22:02:51 WARN]: [mcMMO] A valid mcMMOPlayer object could not be found for Mrgexe.
[22:02:51 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'inspect' in plugin mcMMO v2.1.97
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.3.jar:git-Paper-127]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.3.jar:git-Paper-127]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1831) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1639) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-127]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-127]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
        at com.gmail.nossr50.datatypes.player.PlayerProfile.getXpToLevel(PlayerProfile.java:418) ~[?:?]
        at com.gmail.nossr50.util.commands.CommandUtils.displaySkill(CommandUtils.java:212) ~[?:?]
        at com.gmail.nossr50.commands.player.InspectCommand.onCommand(InspectCommand.java:51) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.3.jar:git-Paper-127]
        ... 17 more`

**Comment by nossr50** [comment]
@WhyDoWeWonder Hmm, I'm looking into this now to see if I can find any obvious reason why this might be happening.

**Comment by nossr50** [comment]
@WhyDoWeWonder If you wouldn't mind sending me a full log sometime, that may shed some light on this issue as well

**Comment by nossr50** [comment]
Yeah I can't seem to reproduce this on my own, I think I may have a better idea of what is going on if I could review the full log.
