### ISSUE TITLE
Mcmmo Wont run on my server???

### ISSUE THREAD

**Issue by DrbLOXoG** [mcMMO-Dev/mcMMO#4004]
I keep getting this error I have tried removing it and re adding but it does not work it shows up red in plugins and I get that error!

[00:16:01] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[00:16:01] [Server thread/WARN]: java.lang.NoSuchFieldError: FERN
[00:16:01] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadTreasures(TreasureConfig.java:274)
[00:16:01] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.loadKeys(TreasureConfig.java:94)
[00:16:01] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.<init>(TreasureConfig.java:37)
[00:16:01] [Server thread/WARN]: 	at com.gmail.nossr50.config.treasure.TreasureConfig.getInstance(TreasureConfig.java:43)
[00:16:01] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:512)
[00:16:01] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:154)
[00:16:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[00:16:01] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[00:16:01] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:16:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375)
[00:16:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325)
[00:16:01] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205)
[00:16:01] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
[00:16:01] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:16:01] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.98-SNAPSHOT
[00:16:02] [Server thread/WARN]: java.lang.NullPointerException
[00:16:02] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:333)
[00:16:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[00:16:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361)
[00:16:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[00:16:02] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:248)
[00:16:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[00:16:02] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[00:16:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:16:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375)
[00:16:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325)
[00:16:02] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205)
[00:16:02] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
[00:16:02] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:16:02] [Server thread/ERROR]: [mcMMO] Cannot read C:\Users\Zak\Desktop\Server\3-Prison\plugins\mcMMO\experience.yml(File Permissions?)
[00:16:02] [Server thread/ERROR]: [mcMMO] Cannot read C:\Users\Zak\Desktop\Server\3-Prison\plugins\mcMMO\repair.vanilla.yml(File Permissions?)
[00:16:02] [Server thread/ERROR]: Error occurred while disabling mcMMO v2.1.98-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:365) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:248) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[00:16:02] [Server thread/INFO]: [mcMMO] 0 entries in mcMMO World Blacklist

**Comment by nossr50** [comment]
To fix this error remove the experience.yml file and restart your server

**Comment by nossr50** [comment]
Also you need to use a version of mcMMO compatible with the version of MC you are using. The new versions of mcMMO only support 

Compatible versions of Minecraft
1.14.4, 1.14.3, 1.14.2, 1.14.1, 1.14
1.13.2

**Comment by DrbLOXoG** [comment]
I can't find a version using jenkins they don't tell you the version just what build it is...

**Comment by luzziejun** [comment]
yo am i on the #git text channel?

**Comment by DrbLOXoG** [comment]
> To fix this error remove the experience.yml file and restart your server

I don't seem to have that file just upgrades,treasure,skillrank,conifig, and rank

**Comment by nossr50** [comment]
@DrbLOXoG what version of Minecraft?

**Comment by DrbLOXoG** [comment]
> @DrbLOXoG what version of Minecraft?
1.11

**Comment by nossr50** [comment]
Looks like you'd need mcMMO 1.5.07-SNAPSHOT for that version, you can go back in our git history and compile it

**Comment by DrbLOXoG** [comment]
> Looks like you'd need mcMMO 1.5.07-SNAPSHOT for that version, you can go back in our git history and compile it

Where would I find that just by clicking code then releases?

**Comment by nossr50** [comment]
only way to find it would be going back through our commit history afaik
