### ISSUE TITLE
Rupture: Cannot add task while iterating timers

### ISSUE THREAD

**Issue by Bayminkk** [mcMMO-Dev/mcMMO#4033]
[15:54:03] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO v2.1.102
java.lang.IllegalStateException: Cannot add task while iterating timers!
	at com.gmail.nossr50.runnables.skills.BleedTimerTask.add(BleedTimerTask.java:182) ~[?:?]
	at com.gmail.nossr50.skills.swords.SwordsManager.ruptureCheck(SwordsManager.java:78) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processSwordCombat(CombatUtils.java:64) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:322) ~[?:?]
	at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:429) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor56.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-642]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-642]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-642]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-642]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104) ~[patched_1.13.2.jar:git-Paper-642]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834) ~[patched_1.13.2.jar:git-Paper-642]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:733) ~[patched_1.13.2.jar:git-Paper-642]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:866) ~[patched_1.13.2.jar:git-Paper-642]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1520) ~[patched_1.13.2.jar:git-Paper-642]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:993) ~[patched_1.13.2.jar:git-Paper-642]
	at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(EntityMonster.java:44) ~[patched_1.13.2.jar:git-Paper-642]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftLivingEntity.damage(CraftLivingEntity.java:274) ~[patched_1.13.2.jar:git-Paper-642]
	at com.gmail.nossr50.util.skills.CombatUtils.dealNoInvulnerabilityTickDamageRupture(CombatUtils.java:561) ~[?:?]
	at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:118) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-642]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-642]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-642]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-642]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-642]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-642]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by electronicboy** [comment]
Renamed the wrong one, duplicate of #4028
