### ISSUE TITLE
error report with rupture skill

### ISSUE THREAD

**Issue by Bayminkk** [mcMMO-Dev/mcMMO#4046]
[02:16:27] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO v2.1.104
java.lang.IllegalStateException: Cannot add task while iterating timers!
	at com.gmail.nossr50.runnables.skills.BleedTimerTask.add(BleedTimerTask.java:182) ~[?:?]
	at com.gmail.nossr50.skills.swords.SwordsManager.ruptureCheck(SwordsManager.java:78) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processSwordCombat(CombatUtils.java:64) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:322) ~[?:?]
	at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:418) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor55.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-643]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:733) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:866) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1520) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:993) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(EntityMonster.java:44) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.EntityZombie.damageEntity(EntityZombie.java:277) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftLivingEntity.damage(CraftLivingEntity.java:274) ~[patched_1.13.2.jar:git-Paper-643]
	at com.praya.agarthalib.utility.CombatUtil.areaDamage(CombatUtil.java:92) ~[?:?]
	at com.praya.myitems.builder.ability.weapon.AbilityWeaponLightning.cast(AbilityWeaponLightning.java:116) ~[?:?]
	at com.praya.myitems.listener.main.ListenerEntityDamageByEntity.entityDamageByEntityEvent(ListenerEntityDamageByEntity.java:384) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1089.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-643]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:733) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:866) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1520) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:993) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(EntityMonster.java:44) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.EntityZombie.damageEntity(EntityZombie.java:277) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftLivingEntity.damage(CraftLivingEntity.java:274) ~[patched_1.13.2.jar:git-Paper-643]
	at com.gmail.nossr50.util.skills.CombatUtils.dealNoInvulnerabilityTickDamage(CombatUtils.java:570) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.dealNoInvulnerabilityTickDamageRupture(CombatUtils.java:581) ~[?:?]
	at com.gmail.nossr50.runnables.skills.BleedTimerTask.run(BleedTimerTask.java:118) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-643]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-643]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-643]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by electronicboy** [comment]
>The only real risk I can see is that mmoitems is triggering damage on some other player other than what rupture is trying to damage, or some plugin has broken our flag somehow

>There is very little we can do around premium plugins, we don't have access to their source to see what is going on, nor do I have the ability to test them

From https://github.com/mcMMO-Dev/mcMMO/issues/4019#issuecomment-525190049 This is either something myitems will need to fix on their side, or we basically need to prevent plugins from being able to interact with rupture damage properly, which will obviously create its own headaches; Shamefully bukkits API leaves much to be desired for in terms of faking damage

**Comment by Bayminkk** [comment]
(= =)    So I have to wait for myitem to be fixed，or I must ban the rupture skill.
The fix of myitem must has a long time to come,cause the dev of myitem has fourcing his schoolarshop.

**Comment by nossr50** [comment]
Not much we can do on our end for this given Bukkits limited API

**Comment by electronicboy** [comment]
Closing in favor of #4069
( Duplicate of #4069 )
