### ISSUE TITLE
MCMMO stopped working

### ISSUE THREAD

**Issue by buzzysweet** [mcMMO-Dev/mcMMO#4049]
MCMMO used to work on the current minecraft server I am running, then without updating anything at all this appeared. 

```
[22:11:27 INFO]: [mcMMO] Enabling mcMMO v1.5.00-b3547*
[22:11:27 WARN]: [mcMMO] Invalid material: WOODEN_SWORD
[22:11:27 WARN]: [mcMMO] Invalid material: WOODEN_SHOVEL
[22:11:27 WARN]: [mcMMO] Invalid material: WOODEN_PICKAXE
[22:11:27 WARN]: [mcMMO] Invalid material: WOODEN_AXE
[22:11:27 WARN]: [mcMMO] Invalid material: WOODEN_HOE
[22:11:27 WARN]: [mcMMO] Invalid material: LAPIS_LAZULI
[22:11:27 WARN]: [mcMMO] Invalid material: STONE_SHOVEL
[22:11:27 WARN]: [mcMMO] Invalid material: GOLDEN_SWORD
[22:11:27 WARN]: [mcMMO] Invalid material: GOLDEN_SHOVEL
[22:11:27 WARN]: [mcMMO] Invalid material: GOLDEN_PICKAXE
[22:11:27 WARN]: [mcMMO] Invalid material: GOLDEN_AXE
[22:11:27 WARN]: [mcMMO] Invalid material: GOLDEN_HOE
[22:11:27 WARN]: [mcMMO] Invalid material: GOLDEN_BOOTS
[22:11:27 WARN]: [mcMMO] Invalid material: GOLDEN_HELMET
[22:11:27 WARN]: [mcMMO] Invalid material: GOLDEN_LEGGINGS
[22:11:27 WARN]: [mcMMO] Invalid material: GOLDEN_CHESTPLATE
[22:11:27 WARN]: [mcMMO] Invalid material: IRON_SHOVEL
[22:11:27 WARN]: [mcMMO] Invalid material: DIAMOND_SHOVEL
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_BLOCKS
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_CHIRP
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_FAR
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_MALL
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_MELLOHI
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_STAL
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_STRAD
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_WARD
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_11
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_WAIT
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_13
[22:11:27 WARN]: [mcMMO] Invalid material: GUNPOWDER
[22:11:27 WARN]: [mcMMO] Invalid material: CLOCK
[22:11:27 WARN]: [mcMMO] Invalid material: COBWEB
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_13
[22:11:27 WARN]: [mcMMO] Invalid material: MUSIC_DISC_CAT
[22:11:27 WARN]: [mcMMO] Invalid material: COCOA_BEANS
[22:11:27 WARN]: [mcMMO] Invalid material: COCOA_BEANS
[22:11:27 WARN]: [mcMMO] Invalid material: WITHER_SKELETON_SKULL
[22:11:27 WARN]: [mcMMO] Invalid material: CREEPER_HEAD
[22:11:27 WARN]: [mcMMO] Invalid material: GUNPOWDER
[22:11:27 WARN]: [mcMMO] Invalid material: SKELETON_SKULL
[22:11:27 WARN]: [mcMMO] Invalid material: ZOMBIE_HEAD
[22:11:27 WARN]: [mcMMO] Invalid material: GUNPOWDER
[22:11:27 WARN]: [mcMMO] Invalid material: COBWEB
[22:11:27 WARN]: [mcMMO] Invalid Potion_Type: 0|POISON
[22:11:27 WARN]: [mcMMO] Invalid Potion_Type: POTION|0|INSTANT_HEAL
[22:11:27 WARN]: [mcMMO] Invalid Potion_Type: POTION|0|FIRE_RESISTANCE
[22:11:27 WARN]: [mcMMO] Invalid Potion_Type: POTION|0|SPEED
[22:11:27 WARN]: [mcMMO] Invalid material: GUNPOWDER
[22:11:27 WARN]: [mcMMO] Invalid material: PORKCHOP
[22:11:27 WARN]: [mcMMO] Invalid material: WHITE_WOOL
[22:11:27 WARN]: [mcMMO] Invalid material: BEEF
[22:11:27 WARN]: [mcMMO] Invalid material: CHICKEN
[22:11:27 WARN]: [mcMMO] Invalid material: INK_SAC
[22:11:27 WARN]: [mcMMO] Invalid material: MUSHROOM_STEW
[22:11:27 WARN]: [mcMMO] Invalid material: BEEF
[22:11:27 WARN]: [mcMMO] Invalid material: SNOWBALL
[22:11:27 WARN]: [mcMMO] Invalid material: POPPY
[22:11:27 WARN]: [mcMMO] Invalid material: SKELETON_SKULL
[22:11:27 WARN]: [mcMMO] Invalid material: INVENTORY
[22:11:27 WARN]: [mcMMO] Amount of INVENTORY must be greater than 0! 0
[22:11:27 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[22:11:27 WARN]: java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
[22:11:27 WARN]:        at com.gmail.nossr50.config.HiddenConfig.load(HiddenConfig.java:31)
[22:11:27 WARN]:        at com.gmail.nossr50.config.HiddenConfig.<init>(HiddenConfig.java:18)
[22:11:27 WARN]:        at com.gmail.nossr50.config.HiddenConfig.getInstance(HiddenConfig.java:23)
[22:11:27 WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:400)
[22:11:27 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:134)
[22:11:27 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[22:11:27 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[22:11:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[22:11:27 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[22:11:27 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[22:11:27 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:227)
[22:11:27 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[22:11:27 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:11:27 INFO]: [mcMMO] Disabling mcMMO v1.5.00-b3547
[22:11:27 ERROR]: Error occurred while disabling mcMMO v1.5.00-b3547 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at com.gmail.nossr50.config.AutoUpdateConfigLoader.loadFile(AutoUpdateConfigLoader.java:29) ~[?:?]
        at com.gmail.nossr50.config.ConfigLoader.<init>(ConfigLoader.java:26) ~[?:?]
        at com.gmail.nossr50.config.AutoUpdateConfigLoader.<init>(AutoUpdateConfigLoader.java:23) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.<init>(AdvancedConfig.java:20) ~[?:?]
        at com.gmail.nossr50.config.AdvancedConfig.getInstance(AdvancedConfig.java:26) ~[?:?]
        at com.gmail.nossr50.skills.alchemy.Alchemy.<clinit>(Alchemy.java:51) ~[?:?]
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:203) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:445) ~[patched_1.14.4.jar:git-Paper-176]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:193) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-176]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:227) ~[patched_1.14.4.jar:git-Paper-176]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-176]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

**Comment by electronicboy** [comment]
1.5.00 is 3 years old, you need to obtain a newer build from spigots website or compile your own

**Comment by buzzysweet** [comment]
This is paper, not Spigot

**Comment by Remski01** [comment]
He's talking about mcMMO, not paper. https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/

**Comment by nossr50** [comment]
Delete your .yml files either way they need to be cleansed
