### ISSUE TITLE
Could not pass event PlayerTeleportEvent

### ISSUE THREAD

**Issue by kubotan** [mcMMO-Dev/mcMMO#4059]
mcMMO v2.1.101
```
[22:56:05] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to mcMMO v2.1.101
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1013) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:998) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:989) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:865) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassCastException: com.gmail.nossr50.datatypes.player.McMMOPlayer cannot be cast to com.gmail.nossr50.datatypes.player.McMMOPlayer
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:135) ~[?:?]
	at com.gmail.nossr50.listeners.PlayerListener.onPlayerTeleport(PlayerListener.java:89) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	... 18 more
```

**Comment by electronicboy** [comment]
Reloading is unsupported
