### ISSUE TITLE
Could not pass event FoodLevelChangeEvent

### ISSUE THREAD

**Issue by kubotan** [mcMMO-Dev/mcMMO#4060]
mcMMO v2.1.101
```
[22:56:05] [Server thread/ERROR]: Could not pass event FoodLevelChangeEvent to mcMMO v2.1.101
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:868) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.MobEffectList.tick(MobEffectList.java:70) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.MobEffect.b(SourceFile:135) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.MobEffect.tick(SourceFile:122) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.EntityLiving.tickPotionEffects(EntityLiving.java:584) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.EntityLiving.W(EntityLiving.java:307) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.Entity.tick(Entity.java:331) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2027) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:147) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:379) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.PlayerConnection.tick(PlayerConnection.java:140) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassCastException: com.gmail.nossr50.datatypes.player.McMMOPlayer cannot be cast to com.gmail.nossr50.datatypes.player.McMMOPlayer
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:135) ~[?:?]
	at com.gmail.nossr50.listeners.EntityListener.onFoodLevelChange(EntityListener.java:893) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-e7700ab]
	... 21 more
```

**Comment by electronicboy** [comment]
Do not reload mcmmo, this is unsupported and will cause such issues
