### ISSUE TITLE
I am having an error starting server

### ISSUE THREAD

**Issue by kelek22** [mcMMO-Dev/mcMMO#4086]
I am having  an error 

> [06:01:53 INFO]: [mcMMO] Loading mcMMO v2.1.97
[06:01:53 INFO]: mcMMO has registered WG flags successfully!
[06:01:53 INFO]: Server permissions file permissions.yml is empty, ignoring it
[06:01:53 INFO]: [WorldEdit] Enabling WorldEdit v7.0.1;61bc012
[06:01:53 INFO]: WEPIF: Using the Bukkit Permissions API.
[06:01:54 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_14_R4 as the Bukkit adapter
[06:01:54 INFO]: [mcMMO] Enabling mcMMO v2.1.97
[06:01:55 WARN]: [mcMMO] Fishing is not a valid skill type, or is a child skill!
[06:01:55 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[06:01:55 WARN]: java.lang.IllegalArgumentException: No enum constant com.gmail.nossr50.datatypes.skills.PrimarySkillType.FİSHİNG
[06:01:55 WARN]:        at java.lang.Enum.valueOf(Unknown Source)
[06:01:55 WARN]:        at com.gmail.nossr50.datatypes.skills.PrimarySkillType.valueOf(PrimarySkillType.java:36)
[06:01:55 WARN]:        at com.gmail.nossr50.skills.child.ChildConfig.loadKeys(ChildConfig.java:48)
[06:01:55 WARN]:        at com.gmail.nossr50.skills.child.ChildConfig.<init>(ChildConfig.java:13)
[06:01:55 WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:520)
[06:01:55 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:154)
[06:01:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[06:01:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[06:01:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[06:01:55 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[06:01:55 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[06:01:55 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:227)
[06:01:55 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[06:01:55 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:01:55 INFO]: [mcMMO] Disabling mcMMO v2.1.97
[06:01:55 WARN]: java.lang.NullPointerException
[06:01:55 WARN]:        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:333)
[06:01:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[06:01:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
[06:01:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453)
[06:01:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:445)
[06:01:55 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:248)
[06:01:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[06:01:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[06:01:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[06:01:55 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[06:01:55 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[06:01:55 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:227)
[06:01:55 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[06:01:55 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:01:55 ERROR]: [mcMMO] Cannot read C:\Users\90532\Desktop\server2\plugins\mcMMO\experience.yml(File Permissions?)
[06:01:55 ERROR]: [mcMMO] Cannot read C:\Users\90532\Desktop\server2\plugins\mcMMO\repair.vanilla.yml(File Permissions?)
[06:01:55 ERROR]: Error occurred while disabling mcMMO v2.1.97 (Is it up to date?)
java.lang.NullPointerException: null
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:365) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:445) ~[patched_1.14.4.jar:git-Paper-175]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:248) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-175]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:227) ~[patched_1.14.4.jar:git-Paper-175]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-175]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[06:01:55 INFO]: [mcMMO] 0 entries in mcMMO World Blacklist

**Comment by electronicboy** [comment]
Looks like a locale issue, I'll try and get to this when I'm a bit better, in the meantime, you could set your server's locale to Unicode to fix this, probably set to Turkish or something which handles capital I weirdly

**Comment by electronicboy** [comment]
Never mind, figured I'd hit it, I'll try and get nossr to push out a small release or something
