### ISSUE TITLE
McMMOPlayerNotificationEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by gaRt3n** [mcMMO-Dev/mcMMO#4112]
Got this error but I don't know what causes the issue...
`This server is running Paper version git-Paper-65 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`
`[16:21:25 WARN]: [mcMMO] Plugin mcMMO v2.1.48-SNAPSHOT generated an exception while executing task 838291
java.lang.IllegalStateException: McMMOPlayerNotificationEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.15.2.jar:git-Paper-65]
        at com.gmail.nossr50.util.player.NotificationManager.checkNotificationEvent(NotificationManager.java:108) ~[?:?]
        at com.gmail.nossr50.util.player.NotificationManager.sendPlayerInformation(NotificationManager.java:37) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AbilityCooldownTask.run(AbilityCooldownTask.java:26) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-65]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-65]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-65]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

**Comment by electronicboy** [comment]
Update, that build is old...
