### ISSUE TITLE
Cannot edit coreskills.yml, default config leads to errors.

### ISSUE THREAD

**Issue by Auxilor** [mcMMO-Dev/mcMMO#4115]
coreskills.yml keeps resetting itself, and when it does, it generates a config that creates this error message:

```[10:24:13 ERROR]: Cannot load plugins/mcMMO/coreskills.yml
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
in 'string', line 9, column 9:
Roll:
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.15.1.jar:git-Paper-62]
at com.gmail.nossr50.config.ConfigLoader.loadFile(ConfigLoader.java:43) ~[?:?]
at com.gmail.nossr50.config.AutoUpdateConfigLoader.loadFile(AutoUpdateConfigLoader.java:23) ~[?:?]
at com.gmail.nossr50.config.ConfigLoader.<init>(ConfigLoader.java:25) ~[?:?]
at com.gmail.nossr50.config.AutoUpdateConfigLoader.<init>(AutoUpdateConfigLoader.java:18) ~[?:?]
at com.gmail.nossr50.config.CoreSkillsConfig.<init>(CoreSkillsConfig.java:12) ~[?:?]
at com.gmail.nossr50.config.CoreSkillsConfig.getInstance(CoreSkillsConfig.java:24) ~[?:?]
at com.gmail.nossr50.mcMMO.registerCoreSkills(mcMMO.java:578) ~[?:?]
at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:199) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-62]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-62]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-62]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
in 'string', line 9, column 9:```

Paper 1.15.1, if that helps

**Comment by electronicboy** [comment]
You broke the formatting of the yaml file, I'd suggest using a better text
editor like notepad++ or Vs code which can help with highlighting, etc
