### ISSUE TITLE
Unable to fetch UUIDs! java.io.IOException: Server returned HTTP response code: 400

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#4121]
```
[06:55:41] [Craft Scheduler Thread - 17/ERROR]: [mcMMO] Unable to fetch UUIDs!
java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mojang.com/profiles/minecraft
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245) ~[?:?]
        at com.gmail.nossr50.util.uuid.UUIDFetcher.call(UUIDFetcher.java:52) ~[mcMMO-Overhaul.jar:?]
        at com.gmail.nossr50.runnables.database.UUIDUpdateAsyncTask.run(UUIDUpdateAsyncTask.java:67) [mcMMO-Overhaul.jar:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

```
>ver
[06:56:45] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-c574e08-37f32da (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[06:56:45] [Server thread/INFO]: Checking version, please wait...
[06:56:45] [Thread-80/INFO]: You are running the latest version
>ver mcmmo
[06:56:49] [Server thread/INFO]: mcMMO version 2.1.114
[06:56:49] [Server thread/INFO]: The goal of mcMMO is to take core Minecraft game mechanics and expand them into add an extensive and quality RPG experience. Everything in mcMMO has been carefully thought out and is constantly being improved upon. Currently, mcMMO adds thirteen unique skills to train and level in. Each of these skills is highly customizable through our configuration files, allowing server admins to tweak mcMMO to best suit the needs of his or her server. Know that the mcMMO team is dedicated to providing an ever-evolving experience, and that we carefully read all feedback and bug reports in order to evaluate and balance the mechanics of mcMMO in every update.

[06:56:49] [Server thread/INFO]: Website: https://www.mcmmo.org
[06:56:49] [Server thread/INFO]: Authors: nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking, electronicboy and kashike
>
```

Upgraded from Classic to Overhaul, and upon start of the server, right before it's done loading the server I get this msg, every time.

Looking forward to finding out why. No other plugin on the server has issues uuid related stuff or that url it seems.

**Comment by mrfloris** [comment]
[mcmmo.users-mrfloris.zip](https://github.com/mcMMO-Dev/mcMMO/files/4217999/mcmmo.users-mrfloris.zip)

I don't know how I can know if api is pooping itself. error 400 is a webserver response and server-side, but the query can also be malfored i guess. 

cat mentioned he might need the user file, so here it is.

in classic 1.6 i didn't have this error, it started showing as soon as i used spigotmc.org download and upgraded to 2.1

**Comment by mrfloris** [comment]
Friendly bump.

**Comment by mrfloris** [comment]
We're on mcMMO version 2.1.116, it still happens on every startup.

**Comment by electronicboy** [comment]
I was able to reproduce prior to making that change, which follows wiki.vg in terms of the changes, would suggest that something else is causing you to hit the profile API limit
As your data already has UUIDs in there, you might just be able to set that change to true inside of the upgrades file
