### ISSUE TITLE
Compiled mcMMO not working

### ISSUE THREAD

**Issue by in33ko** [mcMMO-Dev/mcMMO#4125]
Server version 1.15.2
mcMMO is the most recent version

error:
[23:54:16 INFO]: [mcMMO] Enabling mcMMO v2.1.119-SNAPSHOT
[23:54:17 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[23:54:17 WARN]: java.lang.NullPointerException
[23:54:17 WARN]: 	at com.gmail.nossr50.util.ItemUtils.isNetherriteTool(ItemUtils.java:353)
[23:54:17 WARN]: 	at com.gmail.nossr50.util.ItemUtils.isMinecraftTool(ItemUtils.java:382)
[23:54:17 WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.loadKeys(RepairConfig.java:118)
[23:54:17 WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfig.<init>(RepairConfig.java:23)
[23:54:17 WARN]: 	at com.gmail.nossr50.config.skills.repair.RepairConfigManager.<init>(RepairConfigManager.java:34)
[23:54:17 WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:544)
[23:54:17 WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:156)
[23:54:17 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:54:17 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[23:54:17 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432)
[23:54:17 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
[23:54:17 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
[23:54:17 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[23:54:17 WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274)
[23:54:17 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[23:54:17 WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:54:17 INFO]: [mcMMO] Disabling mcMMO v2.1.119-SNAPSHOT
[23:54:17 WARN]: java.lang.NullPointerException
[23:54:17 WARN]: 	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:335)
[23:54:17 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[23:54:17 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376)
[23:54:17 WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453)
[23:54:17 WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:250)
[23:54:17 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:54:17 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[23:54:17 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432)
[23:54:17 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
[23:54:17 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
[23:54:17 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
[23:54:17 WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274)
[23:54:17 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[23:54:17 WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:54:17 ERROR]: Error occurred while disabling mcMMO v2.1.119-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: null
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:367) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:250) [mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by emrstats** [comment]
You are having the exact same issue I was having. v2.1.119 is in preparation for Minecraft v1.16, and therefore is the reason you are having this issue.
You need to download and compile the v2.1.118 commit to run MCMMO on Minecraft v1.15.2

**Comment by in33ko** [comment]
Where can I download this?

**Comment by emrstats** [comment]
You need to checkout the previous commit for it

**Comment by in33ko** [comment]
I just compiled 2.1.118 (current stable version commit) and this was the result
[00:45:06 ERROR]: Could not load 'plugins\mcMMO.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bstats/bukkit/Metrics$CustomChart
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:349) ~[spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:268) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: org/bstats/bukkit/Metrics$CustomChart
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-8faa8b4-3d61a85]
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.bstats.bukkit.Metrics$CustomChart
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-8faa8b4-3d61a85]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-8faa8b4-3d61a85]
	... 6 more

No mcMMO folder was created.

**Comment by in33ko** [comment]
I ran mcMMO-2.1.118-shaded.jar and it worked. Thanks for the help.
