### ISSUE TITLE
[Bug] Exception error on /stop with 0 players

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#4131]
```
[07:36:36] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.123-SNAPSHOT
[07:36:36] [Server thread/INFO]: [PlaceholderAPI] Unregistered placeholder expansion: mcmmo
[07:36:36] [Server thread/INFO]: [mcMMO] Saving mcMMOPlayers... (0)
[07:36:36] [Server thread/INFO]: [mcMMO] Finished save operation for 0 players!
[07:36:36] [Server thread/WARN]: java.lang.NullPointerException
[07:36:36] [Server thread/WARN]:        at com.gmail.nossr50.util.player.UserManager.remove(UserManager.java:47)
[07:36:36] [Server thread/WARN]:        at com.gmail.nossr50.util.player.UserManager.clearAll(UserManager.java:60)
[07:36:36] [Server thread/WARN]:        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:327)
[07:36:36] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[07:36:36] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376)
[07:36:36] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453)
[07:36:36] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:445)
[07:36:36] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:398)
[07:36:36] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:699)
[07:36:36] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:696)
[07:36:36] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:864)
[07:36:36] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[07:36:36] [Server thread/INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v5.15.1
```

Caused by typing /stop

I was online in-game and typed: /stop, which kicked me out, it started shutting down and this msg came up, i thought id report it.

```
>ver
[07:40:00] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-6de3d4b-fc24934 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[07:40:00] [Server thread/INFO]: Checking version, please wait...
[07:40:00] [Thread-81/INFO]: You are running the latest version
>ver mcmmo
[07:40:01] [Server thread/INFO]: mcMMO version 2.1.123-SNAPSHOT
[07:40:01] [Server thread/INFO]: The goal of mcMMO is to take core Minecraft game mechanics and expand them into add an extensive and quality RPG experience. Everything in mcMMO has been carefully thought out and is constantly being improved upon. Currently, mcMMO adds thirteen unique skills to train and level in. Each of these skills is highly customizable through our configuration files, allowing server admins to tweak mcMMO to best suit the needs of his or her server. Know that the mcMMO team is dedicated to providing an ever-evolving experience, and that we carefully read all feedback and bug reports in order to evaluate and balance the mechanics of mcMMO in every update.

[07:40:01] [Server thread/INFO]: Website: https://www.mcmmo.org
[07:40:01] [Server thread/INFO]: Authors: nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking, electronicboy and kashike
[07:40:01] [Server thread/INFO]: mcmmo-placeholders version 1.0-SNAPSHOT
[07:40:01] [Server thread/INFO]: Author: electronicboy
>
```

**Comment by mrfloris** [comment]
Friendly bump

**Comment by nossr50** [comment]
Hmm, I'll look into this later. If you are able to replicate it provide details.

**Comment by mrfloris** [comment]
Ah, it happened again when there were 2 players online. I did `/save-all`, asked the players if it was ok to restart, got a yeah, and i did `/stop`.
```
[10:41:55] [Server thread/INFO]: [mcMMO] Finished save operation for 2 players!
[10:41:55] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[10:41:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:447)
[10:41:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:176)
[10:41:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:167)
[10:41:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:131)
[10:41:55] [Server thread/WARN]:        at org.bukkit.scheduler.BukkitRunnable.runTaskLater(BukkitRunnable.java:79)
[10:41:55] [Server thread/WARN]:        at com.gmail.nossr50.runnables.skills.AbilityDisableTask.run(AbilityDisableTask.java:66)
[10:41:55] [Server thread/WARN]:        at com.gmail.nossr50.datatypes.player.McMMOPlayer.resetAbilityMode(McMMOPlayer.java:270)
[10:41:55] [Server thread/WARN]:        at com.gmail.nossr50.datatypes.player.McMMOPlayer.cleanup(McMMOPlayer.java:1069)
[10:41:55] [Server thread/WARN]:        at com.gmail.nossr50.util.player.UserManager.remove(UserManager.java:47)
[10:41:55] [Server thread/WARN]:        at com.gmail.nossr50.util.player.UserManager.clearAll(UserManager.java:60)
[10:41:55] [Server thread/WARN]:        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:327)
[10:41:55] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[10:41:55] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376)
[10:41:55] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501)
[10:41:55] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:493)
[10:41:55] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:398)
[10:41:55] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:699)
[10:41:55] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:696)
[10:41:55] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:864)
[10:41:55] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[10:41:55] [Server thread/INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v5.15.1
```

Hope this helps.

**Comment by nossr50** [comment]
Fixed in 2.1.210, see https://github.com/mcMMO-Dev/mcMMO/commit/0bf3f98d9531f6c266f5a14382e6b3e4453f1bd9
