### ISSUE TITLE
CommandException: Unhandled exception executing command 'mcfools' 

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#4147]
McMMO dev 941

```
[03:37:59] [Server thread/INFO]: mibby issued server command: /mcfools
[03:37:59] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mcfools' in plugin mcMMO v2.1.126-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Purpur-528]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.15.2.jar:git-Purpur-528]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1851) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1659) ~[patched_1.15.2.jar:git-Purpur-528]
	at xuan.cat.XuanCatAPI.a.c.c.a.e.a(Unknown Source) ~[?:?]
	at xuan.cat.XuanCatAPI.a.c.c.a.e.a(Unknown Source) ~[?:?]
	at xuan.cat.XuanCatAPI.a.c.c.a.e.a(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$5113/0000000000000000.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1068) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1061) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1045) ~[patched_1.15.2.jar:git-Purpur-528]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:968) ~[patched_1.15.2.jar:git-Purpur-528]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.commands.skills.AprilCommand.getXPGainString(AprilCommand.java:73) ~[?:?]
	at com.gmail.nossr50.commands.skills.AprilCommand.onCommand(AprilCommand.java:40) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Purpur-528]
	... 21 more
```

**Comment by mrfloris** [comment]
Same here, can confirm, spigot 1.15.2 and mcMMO 2.1.215

```
[15:27:49] [User Authenticator #2/INFO]: UUID of player partyroom is dd3d28dd-ec7c-4b76-83c6-1acb0f68de46
[15:27:50] [Server thread/INFO]: partyroom[/127.0.0.1:59193] logged in with entity id 3875 at ([general]12575.300000011921, 61.0, 9506.404401507103)
[15:27:52] [Server thread/WARN]: [mcMMO] Task #9792 for mcMMO v2.1.125 generated an exception
java.lang.NullPointerException: null
        at com.gmail.nossr50.util.HolidayManager.levelUpApril(HolidayManager.java:370) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AprilTask.run(AprilTask.java:33) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-bbe3d58]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.2.jar:git-Spigot-a03b1fd-bbe3d58]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-a03b1fd-bbe3d58]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-a03b1fd-bbe3d58]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-a03b1fd-bbe3d58]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-a03b1fd-bbe3d58]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
