### ISSUE TITLE
McMMOPlayerLevelUpEvent

### ISSUE THREAD

**Issue by gmwatson** [mcMMO-Dev/mcMMO#4182]
>.... [01:47:53 ERROR]: Could not pass event McMMOPlayerLevelUpEvent to mcMMO v2.1.128
java.lang.IllegalStateException: Unregistered scoreboard component
at org.bukkit.craftbukkit.v1_15_R1.scoreboard.CraftObjective.checkState(CraftObjective.java:137) ~[patched_1.15.2.jar:git-Paper-137]
at org.bukkit.craftbukkit.v1_15_R1.scoreboard.CraftObjective.unregister(CraftObjective.java:129) ~[patched_1.15.2.jar:git-Paper-137]
at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.loadObjective(ScoreboardWrapper.java:391) ~[?:?]
at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.setTypeSkill(ScoreboardWrapper.java:302) ~[?:?]
at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerSkillLevelUpScoreboard(ScoreboardManager.java:276) ~[?:?]
at com.gmail.nossr50.util.scoreboards.ScoreboardManager.handleLevelUp(ScoreboardManager.java:232) ~[?:?]
at com.gmail.nossr50.listeners.SelfListener.onPlayerLevelUp(SelfListener.java:49) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor783.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-137]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-137]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-137]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-137]
at com.gmail.nossr50.util.EventUtils.tryLevelChangeEvent(EventUtils.java:197) ~[?:?]
at com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:630) ~[?:?]
at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:600) ~[?:?]
at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:563) ~[?:?]
at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:550) ~[?:?]
at com.gmail.nossr50.runnables.skills.AwardCombatXpTask.run(AwardCombatXpTask.java:42) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-137]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-137]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-137]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-137]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-137]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-137]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by gmwatson** [comment]
Turns out to be a Featherboard issue
