### ISSUE TITLE
internal error has occured.

### ISSUE THREAD

**Issue by markvanderwagen** [mcMMO-Dev/mcMMO#4193]
Hey!

I have been having problems with my mcmmo as it seems to throw an internal error when a mcmmo command is run such as /mcstats and so on.
here is the error list, please let me know what the issue us and if you need any other information :)

24.05 19:32:01 [Server] Server thread/INFO MiC_Einstein issued server command: /mcstats
24.05 19:32:01 [Server] Server thread/ERROR null
24.05 19:32:01 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mcstats' in plugin mcMMO v2.1.128
24.05 19:32:01 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
24.05 19:32:01 [Server] INFO Caused by: java.lang.NullPointerException
24.05 19:32:01 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerStatsScoreboard(ScoreboardManager.java:284) ~[?:?]
24.05 19:32:01 [Server] INFO at com.gmail.nossr50.commands.player.McstatsCommand.onCommand(McstatsCommand.java:38) ~[?:?]
24.05 19:32:01 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-800b93f-8160e29]
24.05 19:32:01 [Server] INFO ... 17 more

**Comment by jonathanmizzi18** [comment]
Hi,

I get the same error and I noticed that this happens when I switch worlds. Disconnecting and reconnecting fixes the issue but it has to happen every time someone switches a world. The plugin still continues to work on the non-blacklisted world but some commands throw and error and also levelling up throws an error in the console and the scoreboard and statsboard don't show up. I have all the worlds blacklisted except for 1 which I want mcmmo to work in.

https://pastebin.com/w0zixyKy

**Comment by broccolai** [comment]
This is an issue with how multiple scoreboards are handled, try to aim for only one plugin that uses scoreboards at a time
