### ISSUE TITLE
Command Issues

### ISSUE THREAD

**Issue by mannyseete** [mcMMO-Dev/mcMMO#4200]
Command /mining
```
18.06 00:36:59 [Server] INFO 30000005 issued server command: /mining
18.06 00:36:59 [Server] ERROR null
18.06 00:36:59 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mining' in plugin mcMMO v2.1.128
18.06 00:36:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
18.06 00:36:59 [Server] INFO Caused by: java.lang.NullPointerException
18.06 00:36:59 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerSkillScoreboard(ScoreboardManager.java:261) ~[?:?]
18.06 00:36:59 [Server] INFO at com.gmail.nossr50.commands.skills.SkillCommand.onCommand(SkillCommand.java:118) ~[?:?]
18.06 00:36:59 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:36:59 [Server] INFO ... 17 more
```

Command /mctop
```18.06 00:37:02 [Server] INFO 30000005 issued server command: /mctop
18.06 00:37:02 [Server] WARN Task #130953 for mcMMO v2.1.128 generated an exception
18.06 00:37:02 [Server] INFO java.lang.NullPointerException: null
18.06 00:37:02 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.showTopPowerScoreboard(ScoreboardManager.java:341) ~[?:?]
18.06 00:37:02 [Server] INFO at com.gmail.nossr50.runnables.commands.MctopCommandDisplayTask.displayBoard(MctopCommandDisplayTask.java:90) ~[?:?]
18.06 00:37:02 [Server] INFO at com.gmail.nossr50.runnables.commands.MctopCommandDisplayTask.run(MctopCommandDisplayTask.java:38) ~[?:?]
18.06 00:37:02 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:37:02 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:37:02 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:37:02 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:37:02 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:37:02 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-158]
18.06 00:37:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

**Comment by broccolai** [comment]
You have another plugin that is conflicting with mcmmos scoreboards c either turn mcmmos off or turn off the other scoreboards
