### ISSUE TITLE
McMMO + Mythicmobs Incompatibility Crash (Critical)

### ISSUE THREAD

**Issue by dungeon1010** [mcMMO-Dev/mcMMO#4201]
My server running the latest version of Paper 1.15.2 decided to crash suddenly when I spawned in a Mythicmob near a player. Here is the log as the server crashed:

[17:57:24] [Server thread/INFO]: Player(me) issued server command: /espawnmob zombie
[17:57:29] [Server thread/INFO]: Player(me) issued server command: /mm m spawn aggressivebat 1
[17:57:44] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-365 (MC: 1.15.2) ---
[17:57:44] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[17:57:44] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:57:44] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[17:57:44] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:57:44] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[17:57:44] [Paper Watchdog Thread/ERROR]: 	PID: 25 | Suspended: false | Native: false | State: RUNNABLE
[17:57:44] [Paper Watchdog Thread/ERROR]: 	Stack:
[17:57:44] [Paper Watchdog Thread/ERROR]: 		java.util.HashMap.hash(HashMap.java:339)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		java.util.LinkedHashMap.get(LinkedHashMap.java:440)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		org.bukkit.configuration.MemorySection.get(MemorySection.java:260)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		org.bukkit.configuration.MemorySection.getConfigurationSection(MemorySection.java:813)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		org.bukkit.configuration.MemorySection.get(MemorySection.java:252)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		org.bukkit.configuration.MemorySection.getInt(MemorySection.java:344)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		org.bukkit.configuration.MemorySection.getInt(MemorySection.java:339)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		com.gmail.nossr50.config.experience.ExperienceConfig.getBase(ExperienceConfig.java:148)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		com.gmail.nossr50.util.experience.FormulaManager.getCachedXpToLevel(FormulaManager.java:111)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		com.gmail.nossr50.datatypes.player.PlayerProfile.getXpToLevel(PlayerProfile.java:349)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		com.gmail.nossr50.datatypes.player.PlayerProfile.levelUp(PlayerProfile.java:215)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		com.gmail.nossr50.datatypes.player.McMMOPlayer.checkXp(McMMOPlayer.java:496)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:474)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:437)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:427)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		com.gmail.nossr50.runnables.skills.AwardCombatXpTask.run(AwardCombatXpTask.java:41)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[17:57:44] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)

**Comment by dungeon1010** [comment]
[17:58:36] [Server thread/WARN]: [mcMMO] Task #3319067 for mcMMO v1.6.1 generated an exception
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:853) [?:1.8.0_241]
	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:736) ~[patched_1.15.2.jar:git-Paper-365]
	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:753) ~[patched_1.15.2.jar:git-Paper-365]
	at net.minecraft.server.v1_15_R1.MinecraftServer.close(MinecraftServer.java:712) ~[patched_1.15.2.jar:git-Paper-365]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:157) ~[patched_1.15.2.jar:git-Paper-365]
[17:58:36] [Server thread/ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:853) [?:1.8.0_241]
	at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:736) ~[patched_1.15.2.jar:git-Paper-365]
	at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:753) ~[patched_1.15.2.jar:git-Paper-365]
	at net.minecraft.server.v1_15_R1.MinecraftServer.close(MinecraftServer.java:712) ~[patched_1.15.2.jar:git-Paper-365]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:157) ~[patched_1.15.2.jar:git-Paper-365]
