### ISSUE TITLE
Failure to load on AbstractMethodError

### ISSUE THREAD

**Issue by Jirubizu** [mcMMO-Dev/mcMMO#4205]
Server: Spigot - 1.16.1
Plugin Ver : mcMMO 2.1.129

`[16:26:16 ERROR]: [mcMMO] There was an error while enabling mcMMO!
[16:26:16 WARN]: java.lang.AbstractMethodError: Receiver class net.minecraft.server.v1_16_R1.RecipeSmithing does not define or inherit an implementation of the resolved method abstract toBukkitRecipe()Lorg/bukkit/inventory/Recipe; of interface net.minecraft.server.v1_16_R1.IRecipe.
[16:26:16 WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.inventory.RecipeIterator.next(RecipeIterator.java:31)
[16:26:16 WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.inventory.RecipeIterator.next(RecipeIterator.java:1)
[16:26:16 WARN]: 	at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:307)
[16:26:16 WARN]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfig.loadKeys(SalvageConfig.java:134)
[16:26:16 WARN]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfig.<init>(SalvageConfig.java:24)
[16:26:16 WARN]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfigManager.<init>(SalvageConfigManager.java:34)
[16:26:16 WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:534)
[16:26:16 WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:168)
[16:26:16 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:26:16 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[16:26:16 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[16:26:16 WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488)
[16:26:16 WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402)
[16:26:16 WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436)
[16:26:16 WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
[16:26:16 WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808)
[16:26:16 WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[16:26:16 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:835)
`

**Comment by broccolai** [comment]
For ease I'm just going to paste the Discord command answer:

You are running an outdated build of Spigot.

There are numerous spigot builds for each Minecraft version, and there is a known issue with older builds of spigot which cause issues with mcMMO on 1.16.1.

Sites that let you download spigot are often out of date and will cause issues. BuildTools is the only official way to obtain Spigot jars. 

Rerun BuildTools (`java -jar BuildTools.jar --rev 1.16.1`) and use the new jar it provides, to update your spigot build.

**Comment by Jirubizu** [comment]
> 
> 
> For ease I'm just going to paste the Discord command answer:
> 
> You are running an outdated build of Spigot.
> 
> There are numerous spigot builds for each Minecraft version, and there is a known issue with older builds of spigot which cause issues with mcMMO on 1.16.1.
> 
> Sites that let you download spigot are often out of date and will cause issues. BuildTools is the only official way to obtain Spigot jars.
> 
> Rerun BuildTools (`java -jar BuildTools.jar --rev 1.16.1`) and use the new jar it provides, to update your spigot build.

im using ggservers and they don't let me manually select a jar. Also, when I launch the server there is no mention of an outdated jar.

**Comment by broccolai** [comment]
Contact them, it was bugged in spigot and it's since been fixed. It's nothing to do with mcmmo
