### ISSUE TITLE
error running 1.16.1 spigit with 2.1.130 mcmmo

### ISSUE THREAD

**Issue by mrapples-error** [mcMMO-Dev/mcMMO#4210]
updated both versions, and I keep getting this error.
[help.txt](https://github.com/mcMMO-Dev/mcMMO/files/4841043/help.txt)
Any help with being very much appreciated.

**Comment by mrapples-error** [comment]
if you don't want to download the file. 
[mcMMO] Enabling mcMMO v2.1.130
[14:08:23] [Server thread/INFO]: [mcMMO] Platform String: 1.16.1-R0.1-SNAPSHOT
[14:08:23] [Server thread/INFO]: [mcMMO] Minecraft version determined to be - 1.16.1
[14:08:23] [Server thread/INFO]: [mcMMO] Loading compatibility layers...
[14:08:23] [Server thread/INFO]: [mcMMO] NMS not supported for this version of Minecraft, possible solutions include updating mcMMO or updating your server software. NMS Support is not available on every version of Minecraft.
[14:08:23] [Server thread/INFO]: [mcMMO] Certain features of mcMMO that require NMS will be disabled, you can check what is disabled by running the /mmocompat command!
[14:08:23] [Server thread/INFO]: [mcMMO] Finished loading compatibility layers.
[14:08:29] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[14:08:29] [Server thread/WARN]: java.lang.AbstractMethodError: Method net/minecraft/server/v1_16_R1/RecipeSmithing.toBukkitRecipe()Lorg/bukkit/inventory/Recipe; is abstract
[14:08:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.RecipeSmithing.toBukkitRecipe(SourceFile)
[14:08:29] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.inventory.RecipeIterator.next(RecipeIterator.java:31)
[14:08:29] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.inventory.RecipeIterator.next(RecipeIterator.java:1)
[14:08:29] [Server thread/WARN]:        at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:307)
[14:08:29] [Server thread/WARN]:        at com.gmail.nossr50.config.skills.salvage.SalvageConfig.loadKeys(SalvageConfig.java:134)
[14:08:29] [Server thread/WARN]:        at com.gmail.nossr50.config.skills.salvage.SalvageConfig.<init>(SalvageConfig.java:24)
[14:08:29] [Server thread/WARN]:        at com.gmail.nossr50.config.skills.salvage.SalvageConfigManager.<init>(SalvageConfigManager.java:44)
[14:08:29] [Server thread/WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:534)
[14:08:29] [Server thread/WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:168)
[14:08:29] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:08:29] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[14:08:29] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[14:08:29] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488)
[14:08:29] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402)
[14:08:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436)
[14:08:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
[14:08:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808)
[14:08:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[14:08:29] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[14:08:29] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.130
[14:08:29] [Server thread/WARN]: java.lang.NullPointerException
[14:08:29] [Server thread/WARN]:        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:315)
[14:08:29] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[14:08:29] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376)
[14:08:29] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501)
[14:08:29] [Server thread/WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:262)
[14:08:29] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:08:29] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[14:08:29] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[14:08:29] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488)
[14:08:29] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402)
[14:08:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436)
[14:08:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
[14:08:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808)
[14:08:29] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[14:08:29] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[14:08:29] [Server thread/ERROR]: [mcMMO] Cannot read C:\Users\eijae\Desktop\test\plugins\mcMMO\experience.yml(File Permissions?)
[14:08:29] [Server thread/ERROR]: Error occurred while disabling mcMMO v2.1.130 (Is it up to date?)
java.lang.NullPointerException: null
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:347) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[server.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[server.jar:git-Spigot-758abbe-2b00831]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:262) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[server.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488) ~[server.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-758abbe-2b00831]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[14:08:29] [Server thread/INFO]: [mcMMO] 0 entries in mcMMO World Blacklist

**Comment by broccolai** [comment]
Copying the Discord command for convenience;

You are running an outdated build of Spigot.
If you wish to confirm this, run /version ingame.

There are numerous spigot builds for each Minecraft version, and there is a known issue with older builds of spigot which cause issues with mcMMO on 1.16.1.

Jars from sites that let you download spigot will be out of date and should not be trusted.
BuildTools is the only official way to obtain Spigot.

Rerun BuildTools `(java -jar BuildTools.jar --rev 1.16.1)` and use the new jar it provides, to update your spigot build.

**Comment by Marcuri02** [comment]
Having same problem.

[16:13:57] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[16:13:57] [Server thread/WARN]: java.lang.AbstractMethodError: Method net/minecraft/server/v1_16_R1/RecipeSmithing.toBukkitRecipe()Lorg/bukkit/inventory/Recipe; is abstract
[16:13:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.RecipeSmithing.toBukkitRecipe(SourceFile)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.inventory.RecipeIterator.next(RecipeIterator.java:31)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.inventory.RecipeIterator.next(RecipeIterator.java:1)
[16:13:57] [Server thread/WARN]: 	at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:307)
[16:13:57] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfig.loadKeys(SalvageConfig.java:134)
[16:13:57] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfig.<init>(SalvageConfig.java:24)
[16:13:57] [Server thread/WARN]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfigManager.<init>(SalvageConfigManager.java:44)
[16:13:57] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:522)
[16:13:57] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:167)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.reload(CraftServer.java:858)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.Bukkit.reload(Bukkit.java:620)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:747)
[16:13:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:732)
[16:13:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:386)
[16:13:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:355)
[16:13:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1007)
[16:13:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:846)
[16:13:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[16:13:57] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by broccolai** [comment]
And the solution is the same as what I last posted.

**Comment by catronomix** [comment]
Confirming that building the latest version of spigot solves the problem.
