### ISSUE TITLE
[ERROR] Attempting to overwrite an in-use segment

### ISSUE THREAD

**Issue by MysteryOre** [mcMMO-Dev/mcMMO#4217]
Hello,

Recently, I have been frequently getting this error in my console.

[13:20:23 ERROR]: Could not pass event ChunkUnloadEvent to mcMMO v2.1.132
java.lang.IllegalStateException: Attempting to overwrite an in-use segment
at com.gmail.nossr50.util.blockmeta.chunkmeta.McMMOSimpleRegionFile.setInUse(McMMOSimpleRegionFile.java:222) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.McMMOSimpleRegionFile.<init>(McMMOSimpleRegionFile.java:90) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.McMMOSimpleRegionFile.<init>(McMMOSimpleRegionFile.java:45) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.getSimpleRegionFile(HashChunkManager.java:117) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.writeChunkStore(HashChunkManager.java:74) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.saveChunk(HashChunkManager.java:191) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.unloadChunk(HashChunkManager.java:167) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.chunkUnloaded(HashChunkManager.java:213) ~[?:?]
at com.gmail.nossr50.listeners.WorldListener.onChunkUnload(WorldListener.java:94) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor722.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-375]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-375]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-375]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.Chunk.unloadCallback(Chunk.java:893) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$6(PlayerChunk.java:582) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:145) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PlayerChunk.a(PlayerChunk.java:592) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.ChunkMapDistance.a(ChunkMapDistance.java:117) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:639) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:745) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:439) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-375]
at java.lang.Thread.run(Thread.java:834) [?:?]
[13:20:23 ERROR]: Could not pass event ChunkUnloadEvent to mcMMO v2.1.132
java.lang.IllegalStateException: Attempting to overwrite an in-use segment
at com.gmail.nossr50.util.blockmeta.chunkmeta.McMMOSimpleRegionFile.setInUse(McMMOSimpleRegionFile.java:222) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.McMMOSimpleRegionFile.<init>(McMMOSimpleRegionFile.java:90) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.McMMOSimpleRegionFile.<init>(McMMOSimpleRegionFile.java:45) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.getSimpleRegionFile(HashChunkManager.java:117) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.writeChunkStore(HashChunkManager.java:74) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.saveChunk(HashChunkManager.java:191) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.unloadChunk(HashChunkManager.java:167) ~[?:?]
at com.gmail.nossr50.util.blockmeta.chunkmeta.HashChunkManager.chunkUnloaded(HashChunkManager.java:213) ~[?:?]
at com.gmail.nossr50.listeners.WorldListener.onChunkUnload(WorldListener.java:94) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor722.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-375]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-375]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-375]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.Chunk.unloadCallback(Chunk.java:893) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$6(PlayerChunk.java:582) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:145) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PlayerChunk.a(PlayerChunk.java:592) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.ChunkMapDistance.a(ChunkMapDistance.java:117) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:639) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:745) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:439) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-375]
at java.lang.Thread.run(Thread.java:834) [?:?]

Any and all help would be appreciated!

**Comment by marcdubs** [comment]
Getting the same problem. Not sure what needs to be done to fix it. Already tried resetting the whole plugin/files and then replacing the user data.

**Comment by marcdubs** [comment]
Was fixed for me after I deleted the "mcmmo_regions" folder in my worlds. Not sure what data is stored in those files, so be wary. I had a pretty new world at the time so it didn't really matter. Just thought I would post a comment with what fixed it for me.

**Comment by nossr50** [comment]
@MysteryOre @marcdubs can either of you repeat this in the newest builds? We just rewrote the system involved with this error and if it happens again we should get a better error message to figure out how to solve this.

**Comment by alekso56** [comment]
been really unable to reproduce lately, sometimes on plugin disable, it comes with the error below:

> 
> [20:26:37] [Server thread/WARN]: java.lang.IllegalStateException: Attempting to overwrite an in-use segment
> [20:26:37] [Server thread/WARN]: 	at com.gmail.nossr50.util.blockmeta.McMMOSimpleRegionFile.markChunkSegments(McMMOSimpleRegionFile.java:188)
> [20:26:37] [Server thread/WARN]: 	at com.gmail.nossr50.util.blockmeta.McMMOSimpleRegionFile.<init>(McMMOSimpleRegionFile.java:100)
> [20:26:37] [Server thread/WARN]: 	at com.gmail.nossr50.util.blockmeta.HashChunkManager.lambda$getWriteableSimpleRegionFile$0(HashChunkManager.java:74)
> [20:26:37] [Server thread/WARN]: 	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
> [20:26:37] [Server thread/WARN]: 	at com.gmail.nossr50.util.blockmeta.HashChunkManager.getWriteableSimpleRegionFile(HashChunkManager.java:71)
> [20:26:37] [Server thread/WARN]: 	at com.gmail.nossr50.util.blockmeta.HashChunkManager.writeChunkStore(HashChunkManager.java:57)
> [20:26:37] [Server thread/WARN]: 	at com.gmail.nossr50.util.blockmeta.HashChunkManager.closeAll(HashChunkManager.java:31)
> [20:26:37] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:348)
>

**Comment by t00thpick1** [comment]
Interesting, what server software and plugins are you using>?

**Comment by alekso56** [comment]
paper-1.16.5-444
Advancedportals, worldedit, worldguard,brewery,craftbook,essentialsx,gadgetsmenu,multiverse core, luckperms, plotsquared, Skript, towny, vault, mcmmo,jobsreloaded

**Comment by nossr50** [comment]
How often do you run into this issue? @alekso56

**Comment by alekso56** [comment]
> 
> 
> How often do you run into this issue? @alekso56

Every single restart, each restart is on a 24h interval. it happens after each player is saved. [Finished save operation for x players]
