### ISSUE TITLE
mcMMO v2.1.132 error when use Super Breaker mining skill (paper 1.16.1)

### ISSUE THREAD

**Issue by cikalT** [mcMMO-Dev/mcMMO#4222]
[23:17:05 ERROR]: Could not pass event InventoryClickEvent to mcMMO v2.1.132
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.Arrays$ArrayList.get(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.server.v1_16_R1.NonNullList.get(SourceFile:46) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.PlayerInventory.getItem(PlayerInventory.java:541) ~[patched_1.16.1.jar:git-Paper-89]
        at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[patched_1.16.1.jar:git-Paper-89]
        at com.gmail.nossr50.listeners.InventoryListener.onInventoryClickEvent(InventoryListener.java:439) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor326.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-89]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-89]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2421) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-89]        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-89]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[23:17:06 ERROR]: Could not pass event InventoryClickEvent to mcMMO v2.1.132
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.Arrays$ArrayList.get(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.server.v1_16_R1.NonNullList.get(SourceFile:46) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.PlayerInventory.getItem(PlayerInventory.java:541) ~[patched_1.16.1.jar:git-Paper-89]
        at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[patched_1.16.1.jar:git-Paper-89]
        at com.gmail.nossr50.listeners.InventoryListener.onInventoryClickEvent(InventoryListener.java:439) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor326.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-89]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-89]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-89]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2421) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-89]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-89]        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-89]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[23:17:08 ERROR]: Could not pass event InventoryClickEvent to mcMMO v2.1.132
java.lang.ArrayIndexOutOfBoundsException: null
[23:17:30 INFO]: GenosydeSnap has made the advancement [Diamonds!]
[23:18:31 ERROR]: Block at 478, 39, 464 is Block{minecraft:cobblestone} but has net.minecraft.server.v1_16_R1.TileEntityChest@13767a5. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.

**Comment by Draycia** [comment]
Update to 2.1.133
`A fix for an 'array out of bounds' error related to players clicking outside the inventory windows has been fixed`

**Comment by cikalT** [comment]
> Update to 2.1.133
> `A fix for an 'array out of bounds' error related to players clicking outside the inventory windows has been fixed`

okay, thanks :D
