### ISSUE TITLE
Minecraft]: Could not pass event EntityDamageByEntityEvent to SuperLogin v1.1 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by slema20** [mcMMO-Dev/mcMMO#4261]
[Server thread/ERROR] [Minecraft]: Could not pass event EntityDamageByEntityEvent to SuperLogin v1.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:8903116]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:8903116]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:8903116]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:121) [CraftEventFactory.class:8903116]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:690) [CraftEventFactory.class:8903116]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:561) [CraftEventFactory.class:8903116]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:720) [CraftEventFactory.class:8903116]
	at net.minecraft.entity.EntityLivingBase.calculateDebuffsAndCallCB(EntityLivingBase.java:1663) [vp.class:?]
	at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1682) [vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1045) [vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1419) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1743) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1851) [pa.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) [li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) [li.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:924) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftChicken cannot be cast to org.bukkit.entity.Player
	at Crd.Code.Listeners.onDamage(Listeners.java:102) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:8903116]
	... 23 more

**Comment by Quavelen** [comment]
This is not an mcMMO stacktrace, and as such, does not belong here.
If you do happen to have a stacktrace which mentions mcMMO, please feel free to open a new issue with it, and explain when it happens.
