### ISSUE TITLE
Exception when tab completing party kick

### ISSUE THREAD

**Issue by CW-UK** [mcMMO-Dev/mcMMO#4283]
When tab completing /party commands, I receive the following error about 20 times non-stop in console, plus 'Internal error occurred' messages in-game. Sometimes I have to disconnect to stop the in-game message flood.

In-game message:
`An internal error occurred while attempting to tab-complete this command`

Server log:
`[19:14:17] [Server thread/ERROR]: Exception when CW_UK attempted to tab complete party kick 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/party kick ' in plugin mcMMO v2.1.145
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[patched_1.16.2.jar:git-Paper-188]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.16.2.jar:git-Paper-188]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.16.2.jar:git-Paper-188]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.tabCompleteCommand(CraftServer.java:1881) ~[patched_1.16.2.jar:git-Paper-188]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.tabComplete(CraftServer.java:1853) ~[patched_1.16.2.jar:git-Paper-188]
	at org.bukkit.craftbukkit.v1_16_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.16.2.jar:git-Paper-188]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.2.jar:git-Paper-188]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.16.2.jar:git-Paper-188]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.2.jar:git-Paper-188]
	at net.minecraft.server.v1_16_R2.PlayerConnection.lambda$a$4(PlayerConnection.java:584) ~[?:git-Paper-188]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-188]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-188]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-188]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-188]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.2.jar:git-Paper-188]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-188]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-188]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1202) ~[patched_1.16.2.jar:git-Paper-188]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-188]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-188]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NoClassDefFoundError: com/gmail/nossr50/commands/party/PartyCommand$1
	at com.gmail.nossr50.commands.party.PartyCommand.onTabComplete(PartyCommand.java:186) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[patched_1.16.2.jar:git-Paper-188]
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.commands.party.PartyCommand$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_262]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.2.jar:git-Paper-188]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-188]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
	at com.gmail.nossr50.commands.party.PartyCommand.onTabComplete(PartyCommand.java:186) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[patched_1.16.2.jar:git-Paper-188]
	... 20 more
`
Latest McMMO, running on Paper 1.16.2 (rev 184)

**Comment by nossr50** [comment]
did you reload? don't use the reload command

**Comment by CW-UK** [comment]
I didn't no. It seems to fix itself after a server restart but appears again at random. As yet I can't find a trigger or a cause though.
