### ISSUE TITLE
Could not pass event McMMOPlayerXpGainEvent to System v1.14.14

### ISSUE THREAD

**Issue by rodrigotriboni1** [mcMMO-Dev/mcMMO#4286]
> [12:12:16] [Server thread/ERROR]: Could not pass event McMMOPlayerXpGainEvent to System v1.14.14
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:git-Spigot-2740d5a-890130b]
at com.gmail.nossr50.util.EventUtils.handleXpGainEvent(EventUtils.java:305) ~[?:?]
at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:594) ~[?:?]
at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:562) ~[?:?]
at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:549) ~[?:?]
at com.gmail.nossr50.skills.SkillManager.applyXpGain(SkillManager.java:46) ~[?:?]
at com.gmail.nossr50.skills.herbalism.HerbalismManager.awardXPForPlantBlocks(HerbalismManager.java:394) ~[?:?]
at com.gmail.nossr50.skills.herbalism.HerbalismManager.processHerbalismOnBlocksBroken(HerbalismManager.java:238) ~[?:?]
at com.gmail.nossr50.skills.herbalism.HerbalismManager.processHerbalismBlockBreakEvent(HerbalismManager.java:169) ~[?:?]
at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:343) ~[?:?]
at sun.reflect.GeneratedMethodAccessor315.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:309) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:268) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:213) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1219) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[server.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-2740d5a-890130b]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NoSuchMethodError: com.gmail.nossr50.events.experience.McMMOPlayerXpGainEvent.getSkill()Lcom/gmail/nossr50/datatypes/skills/SkillType;
at rush.addons.Mcmmo.onGainXp(Mcmmo.java:37) ~[?:?]
at sun.reflect.GeneratedMethodAccessor323.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-2740d5a-890130b]
... 37 more

**Comment by nossr50** [comment]
This is an issue with a plugin not using correct mcMMO API

 at rush.addons.Mcmmo.onGainXp(Mcmmo.java:37) ~[?:?]

look into whatever rush is
