### ISSUE TITLE
NoClassDefFoundError: com/gmail/nossr50/kyori/adventure/platform/facet/FacetAudienceProvider

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#4287]
McMMO dev 1044
https://papermc.io/ci/view/all/job/mcMMO/

Downgrading to dev 1042, start-up is fine.
```
[10:32:30] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.148-SNAPSHOT
[10:32:30] [Server thread/INFO]: [mcMMO] Platform String: 1.16.3-R0.1-SNAPSHOT
[10:32:30] [Server thread/INFO]: [mcMMO] Minecraft version determined to be - 1.16.3
[10:32:30] [Server thread/INFO]: [mcMMO] Loading compatibility layers...
[10:32:30] [Server thread/INFO]: [mcMMO] Finished loading compatibility layers.
[10:32:30] [Server thread/INFO]: [mcMMO] Killing orphans
[10:32:30] [Server thread/INFO]: [mcMMO] Enabling Acrobatics Skills
[10:32:30] [Server thread/INFO]: [mcMMO] Registered subskill: Roll
[10:32:30] [Server thread/INFO]: [mcMMO] 0 entries in mcMMO World Blacklist
[10:32:30] [Server thread/ERROR]: Error occurred while enabling mcMMO v2.1.148-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/gmail/nossr50/kyori/adventure/platform/facet/FacetAudienceProvider
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at com.gmail.nossr50.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:50) ~[?:?]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:278) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:238) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.kyori.adventure.platform.facet.FacetAudienceProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Tuinity-"903f580"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 21 more
[10:32:30] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.148-SNAPSHOT
```

**Comment by Faicu** [comment]
I encounter this error at plugin loading as well.
Paper(208) 1.16.3-R0.1-SNAPSHOT

**Comment by nossr50** [comment]
dev builds are not guaranteed to run or compile properly, this issue will be fixed in upcoming commits
