### ISSUE TITLE
[Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO v2.1.144

### ISSUE THREAD

**Issue by elliottgoh** [mcMMO-Dev/mcMMO#4300]
this happens repeatedly till the server overloads. Can anyone give me advice on a current fix?

` [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO **v2.1.144**
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:238) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:931) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:818) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:774) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:963) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1624) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1028) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:259) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at cx.sfy.LagAssist.stacker.StackManipulator.spawnDeadEntity(StackManipulator.java:108) ~[?:?]
	at cx.sfy.LagAssist.stacker.StackManipulator.onDamage(StackManipulator.java:71) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at com.gmail.nossr50.util.skills.CombatUtils.sendEntityDamageEvent(CombatUtils.java:883) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.canDamage(CombatUtils.java:876) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.dealDamage(CombatUtils.java:562) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.dealDamage(CombatUtils.java:530) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.applyAbilityAoE(CombatUtils.java:678) ~[?:?]
	at com.gmail.nossr50.skills.swords.SwordsManager.serratedStrikes(SwordsManager.java:147) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processSwordCombat(CombatUtils.java:81) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:357) ~[?:?]
	at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:428) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:238) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:931) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:818) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:774) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:963) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1624) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1028) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:259) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at cx.sfy.LagAssist.stacker.StackManipulator.spawnDeadEntity(StackManipulator.java:108) ~[?:?]
	at cx.sfy.LagAssist.stacker.StackManipulator.onDamage(StackManipulator.java:71) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:238) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:931) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:818) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:774) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:963) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1624) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1028) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1547) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1879) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:453) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:181) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:172) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:136) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at org.bukkit.scheduler.BukkitRunnable.runTaskLater(BukkitRunnable.java:79) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]
	at com.gmail.nossr50.util.skills.CombatUtils.processCombatXP(CombatUtils.java:771) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processCombatXP(CombatUtils.java:691) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processSwordCombat(CombatUtils.java:90) ~[?:?]
	at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:357) ~[?:?]
	at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:428) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot_1.15.2.jar:git-Spigot-a99063f-be6aaf0]`

**Comment by elliottgoh** [comment]
I read through old cases with similar results and Healthbars are disabled as well.

**Comment by Quavelen** [comment]
Before anyone will address this, please update mcMMO to `2.1.149`, and please update Spigot to the latest 1.16.3 build. If you insist on using 1.15.2, then please verify you are on the latest version by typing `/version` ingame. Update, if you're not.

Once you do these two things, please return and tell us if the server still spits out this spam.

**Comment by elliottgoh** [comment]
Thanks It's been running fine since the update. But my user files have been reset. Is it possible to reinstall the old user file into the MCMMO file?

**Comment by Quavelen** [comment]
Updating mcMMO from `2.1.144` to `2.1.149` only consists of changing the jarfile. If you deleted the mcMMO directory as well, then no, that was a mistake you made and the data is lost.

**Comment by elliottgoh** [comment]
I still have the userfile. I made a copy before updating the jar. But it was overwritten. I'll just reinstall the userfile thank you
