### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by Gaming1111** [mcMMO-Dev/mcMMO#4316]
Hi! I got this error:

```
[14:28:36 ERROR]: Error occurred while enabling mcMMO v2.1.151-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/platform/bukkit/BukkitAudiences
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:271) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.platform.bukkit.BukkitAudiences
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[Paper-1.16.2-latest.jar:git-Paper-189]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	... 11 more
```

**Comment by nossr50** [comment]
You are using a corrupted jar
