### ISSUE TITLE
The wrong hex color codes cause StringIndexOutOfBoundsException error

### ISSUE THREAD

**Issue by andris155** [mcMMO-Dev/mcMMO#4404]
The text:
&#000000fd&#dsds

This caused this error:
```
[14:21:07 ERROR]: Could not pass event AsyncPlayerChatEvent to mcMMO v2.1.172
java.lang.StringIndexOutOfBoundsException: begin 131, end 137, length 135
        at java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[?:?]
        at java.lang.String.substring(String.java:1874) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.decodeTextFormat(LegacyComponentSerializerImpl.java:152) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:217) ~[?:?]
        at com.gmail.nossr50.util.text.TextUtils.colorizeText(TextUtils.java:117) ~[?:?]
        at com.gmail.nossr50.locale.LocaleLoader.formatComponent(LocaleLoader.java:119) ~[?:?]
        at com.gmail.nossr50.locale.LocaleLoader.getTextComponent(LocaleLoader.java:61) ~[?:?]
        at com.gmail.nossr50.chat.mailer.PartyChatMailer.addStyle(PartyChatMailer.java:65) ~[?:?]
        at com.gmail.nossr50.chat.mailer.PartyChatMailer.processChatMessage(PartyChatMailer.java:34) ~[?:?]
        at com.gmail.nossr50.chat.ChatManager.processPlayerMessage(ChatManager.java:80) ~[?:?]
        at com.gmail.nossr50.chat.ChatManager.processPlayerMessage(ChatManager.java:49) ~[?:?]
        at com.gmail.nossr50.listeners.PlayerListener.onPlayerChat(PlayerListener.java:915) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor252.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:1958) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1873) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1811) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

mcMMO version 2.1.172
1.16.5

**Comment by TheBusyBiscuit** [comment]
I was able to reproduce this and #4403.
However, the actual exception isn't coming from mcMMO here but rather from [KyoriPowered/adventure](https://github.com/KyoriPowered/adventure).

I was able to reproduce this in a clean adventure-only environment too. So this is something that'd need to be handled in that dependency instead.
I reckon that this issue can be closed, I will make an issue on adventure's bug tracker with my findings for you :)


One question though: Where is this malformed input coming from? Is that a chat message or sth you added to your locale file?

**Comment by andris155** [comment]
Malformed input coming from the mcMMO party chat.

**Comment by nossr50** [comment]
Will likely need to wait on kyori to fix this as sanitizing inputs for malformed hex codes seems like work we shouldn't have to do

**Comment by TheBusyBiscuit** [comment]
The issue has been fixed within Adventure by the Kyori team:
https://github.com/KyoriPowered/adventure/releases/tag/v4.5.1

Now it will only be a matter of bumping the dependency version.

**Comment by andris155** [comment]
Thanks.
