### ISSUE TITLE
Strange Error about piston 

### ISSUE THREAD

**Issue by kit8379** [mcMMO-Dev/mcMMO#4424]
[23:48:00 ERROR]: Could not pass event BlockPistonRetractEvent to mcMMO v2.1.174
java.lang.IndexOutOfBoundsException: x: 13 y: -1 z: 13 World Height: 256
        at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.coordToIndex(BitSetChunkStore.java:94) ~[?:?]
        at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.coordToIndex(BitSetChunkStore.java:89) ~[?:?]
        at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.set(BitSetChunkStore.java:79) ~[?:?]
        at com.gmail.nossr50.util.blockmeta.HashChunkManager.set(HashChunkManager.java:240) ~[?:?]
        at com.gmail.nossr50.util.blockmeta.HashChunkManager.setTrue(HashChunkManager.java:192) ~[?:?]
        at com.gmail.nossr50.listeners.BlockListener.onBlockPistonRetract(BlockListener.java:151) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor502.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-17]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Yatopia-17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.BlockPiston.a(BlockPiston.java:344) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.BlockPiston.a(BlockPiston.java:229) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:575) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.WorldServer.a(WorldServer.java:2258) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.WorldServer.ak(WorldServer.java:2248) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:856) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1443) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1288) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1013) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Yatopia-17]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by kit8379** [comment]
Keep spamming my console. How can i fix it?

**Comment by 0liverGMC** [comment]
I have a similar error, but through another plugin using Airplane instead of Yatopia. Same version of McMMO as well.

**Comment by kit8379** [comment]
> I have a similar error, but through another plugin using Airplane instead of Yatopia. Same version of McMMO as well.

Have you found out solution?

**Comment by kit8379** [comment]
Confirmed. All hopper placed at y=0 would cause this bug no matter what direction the piston are pointed. The error will occur when the piston changed its state everytime.

**Comment by nossr50** [comment]
Thanks for the report, the issue is from our system that tracks what blocks are considered "should not give XP" or "unnatural". The system got rewritten recently, I'll patch in a fix for this soon unless @t00thpick1 gets to it before me

**Comment by t00thpick1** [comment]
This should be resolved by https://github.com/mcMMO-Dev/mcMMO/commit/f9144e624ab9d96f052dfe18ecded6703a2f33ff

**Comment by TheBusyBiscuit** [comment]
@kit8379 Have you tested the newest mcMMO version (2.1.175) and/or does the issue still persist?
If it does not persist, then I reckon that the ticket can be closed since t00thpick1's changes should have fixed it.

**Comment by kit8379** [comment]
I think it is fixed. I didn’t have tested to put a piston in y=0 again but no more error occurs after I installed this.
