### ISSUE TITLE
McMMO doesnt enable

### ISSUE THREAD

**Issue by IdiomCoder** [mcMMO-Dev/mcMMO#4438]
log: 
[02:00:47] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.175-SNAPSHOT
[02:00:47] [Server thread/INFO]: [mcMMO] Platform String: 1.16.4-R0.1-SNAPSHOT
[02:00:47] [Server thread/INFO]: [mcMMO] Minecraft version determined to be - 1.16.4
[02:00:47] [Server thread/INFO]: [mcMMO] Loading compatibility layers...
[02:00:47] [Server thread/INFO]: [mcMMO] Finished loading compatibility layers.
[02:00:47] [Server thread/INFO]: [mcMMO] Registering enchantments for Fishing Book...
[02:00:49] [Server thread/INFO]: [mcMMO] Enabling Acrobatics Skills
[02:00:49] [Server thread/INFO]: [mcMMO] Registered subskill: Roll
[02:00:49] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[02:00:49] [Server thread/INFO]: [mcMMO] Please do not replace the mcMMO jar while the server is running.
[02:00:49] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.175-SNAPSHOT
[02:00:49] [Server thread/INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[02:00:49] [Server thread/INFO]: [mcMMO] 0 entries in mcMMO World Blacklist
[02:00:50] [Server thread/ERROR]: Error occurred while enabling mcMMO v2.1.175-SNAPSHOT (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register class org.bukkit.event.player.PlayerJoinEvent while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvent(SimplePluginManager.java:646) ~[spigot.jar:git-Spigot-a93cbb1-7a6c3c9]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.registerEvent(BukkitAudiencesImpl.java:215) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:100) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$instanceFor$2(BukkitAudiencesImpl.java:83) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1133) ~[?:?]
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2682) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:83) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:52) ~[?:?]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:287) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-a93cbb1-7a6c3c9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot.jar:git-Spigot-a93cbb1-7a6c3c9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:git-Spigot-a93cbb1-7a6c3c9]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot.jar:git-Spigot-a93cbb1-7a6c3c9]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot.jar:git-Spigot-a93cbb1-7a6c3c9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot.jar:git-Spigot-a93cbb1-7a6c3c9]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot.jar:git-Spigot-a93cbb1-7a6c3c9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot.jar:git-Spigot-a93cbb1-7a6c3c9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-a93cbb1-7a6c3c9]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by IdiomCoder** [comment]
seems to be something with Bukkit Audience?
