### ISSUE TITLE
[urgent] After recent mcMMO update the database gets borked?

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#4449]
never had this before, the other day when 2.1.179 came out i updated, i skipped the version before this.. and today out of nowhere things are borked.. could use some help.

mcmmo 2.1.179
paper 1.16.5 build 544

```
[18:23:44 ERROR]: [mcMMO] [A] mcMMO was unable to load the player data for TNGstorm. Please inspect your database setup. Attempts made so far 14.
[18:23:44 INFO]: [A] mcMMO was unable to load the player data for TNGstorm. Please inspect your database setup. Attempts made so far {1}.
[18:23:47 INFO]: Blue_Blossom85 issued server command: /home
[18:24:38 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 41 out of bounds for length 20
[18:24:38 WARN]:        at com.gmail.nossr50.database.FlatfileDatabaseManager.loadPlayerProfile(FlatfileDatabaseManager.java:496)
[18:24:38 WARN]:        at com.gmail.nossr50.runnables.player.PlayerProfileLoadingTask.run(PlayerProfileLoadingTask.java:45)
[18:24:38 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[18:24:38 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[18:24:38 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:24:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[18:24:38 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[18:24:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[18:24:38 ERROR]: [mcMMO] [A] mcMMO was unable to load the player data for TNGstorm. Please inspect your database setup. Attempts made so far 16.
[18:24:38 INFO]: [A] mcMMO was unable to load the player data for TNGstorm. Please inspect your database setup. Attempts made so far {1}.
[18:24:44 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 41 out of bounds for length 20
[18:24:44 WARN]:        at com.gmail.nossr50.database.FlatfileDatabaseManager.loadPlayerProfile(FlatfileDatabaseManager.java:496)
[18:24:44 WARN]:        at com.gmail.nossr50.runnables.player.PlayerProfileLoadingTask.run(PlayerProfileLoadingTask.java:45)
[18:24:44 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[18:24:44 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[18:24:44 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:24:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[18:24:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[18:24:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[18:24:44 ERROR]: [mcMMO] [A] mcMMO was unable to load the player data for Blue_Blossom85. Please inspect your database setup. Attempts made so far 13.
[18:24:44 INFO]: [A] mcMMO was unable to load the player data for Blue_Blossom85. Please inspect your database setup. Attempts made so far {1}.
[18:24:46 INFO]: UUID of player tiredpamster is bade2d34-ec4b-460a-8a38-c3a8a7d4a67c
[18:24:46 INFO]:  1MB Server » Welcome back tiredpamster ❤
[18:24:46 INFO]: tiredpamster[/redacted:2933] logged in with entity id 710135 at ([general]-16910.503989560988, 74.0, 11578.202133219896)
[18:24:49 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 41 out of bounds for length 20
[18:24:49 WARN]:        at com.gmail.nossr50.database.FlatfileDatabaseManager.loadPlayerProfile(FlatfileDatabaseManager.java:496)
[18:24:49 WARN]:        at com.gmail.nossr50.runnables.player.PlayerProfileLoadingTask.run(PlayerProfileLoadingTask.java:45)
[18:24:49 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[18:24:49 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[18:24:49 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:24:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[18:24:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[18:24:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[18:24:51 INFO]: general <TNGstorm> wb
[18:24:54 INFO]: general <Blue_Blossom85> wb tiredpamster
[18:24:58 INFO]: general <tiredpamster> ty
[18:24:59 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 41 out of bounds for length 20
[18:24:59 WARN]:        at com.gmail.nossr50.database.FlatfileDatabaseManager.loadPlayerProfile(FlatfileDatabaseManager.java:496)
[18:24:59 WARN]:        at com.gmail.nossr50.runnables.player.PlayerProfileLoadingTask.run(PlayerProfileLoadingTask.java:45)
[18:24:59 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[18:24:59 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[18:24:59 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:24:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[18:24:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[18:24:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[18:25:04 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 41 out of bounds for length 20
[18:25:04 WARN]:        at com.gmail.nossr50.database.FlatfileDatabaseManager.loadPlayerProfile(FlatfileDatabaseManager.java:496)
[18:25:04 WARN]:        at com.gmail.nossr50.runnables.player.PlayerProfileLoadingTask.run(PlayerProfileLoadingTask.java:45)
[18:25:04 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[18:25:04 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[18:25:04 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:25:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[18:25:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[18:25:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[18:25:04 ERROR]: [mcMMO] [A] mcMMO was unable to load the player data for TNGstorm. Please inspect your database setup. Attempts made so far 15.
[18:25:04 INFO]: [A] mcMMO was unable to load the player data for TNGstorm. Please inspect your database setup. Attempts made so far {1}.
> save-all
[18:25:05 INFO]: Saving the game (this may take a moment!)
[18:25:05 INFO]: Saved the game
[18:25:14 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 41 out of bounds for length 20
[18:25:14 WARN]:        at com.gmail.nossr50.database.FlatfileDatabaseManager.loadPlayerProfile(FlatfileDatabaseManager.java:496)
[18:25:14 WARN]:        at com.gmail.nossr50.runnables.player.PlayerProfileLoadingTask.run(PlayerProfileLoadingTask.java:45)
[18:25:14 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[18:25:14 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[18:25:14 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:25:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[18:25:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[18:25:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
> maintenance Seems we are having an issue with mcMMO -investigating
[18:25:24 INFO]: Server maintenance mode set to True with message: Seems we are having an issue with mcMMO -investigating
[18:25:24 INFO]: During maintenance mode players can remain in-game, but they cannot join the game.
[18:25:24 INFO]:  Maintenance: Seems we are having an issue with mcMMO -investigating :)
[18:25:34 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 41 out of bounds for length 20
[18:25:34 WARN]:        at com.gmail.nossr50.database.FlatfileDatabaseManager.loadPlayerProfile(FlatfileDatabaseManager.java:496)
[18:25:34 WARN]:        at com.gmail.nossr50.runnables.player.PlayerProfileLoadingTask.run(PlayerProfileLoadingTask.java:45)
[18:25:34 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[18:25:34 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[18:25:34 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:25:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[18:25:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[18:25:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[18:25:34 ERROR]: [mcMMO] [A] mcMMO was unable to load the player data for tiredpamster. Please inspect your database setup. Attempts made so far 3.
[18:25:34 INFO]: [A] mcMMO was unable to load the player data for tiredpamster. Please inspect your database setup. Attempts made so far {1}.
> stop
```

on /stop
```
[18:25:40 WARN]: java.lang.NullPointerException
[18:25:40 WARN]:        at com.gmail.nossr50.util.player.UserManager.remove(UserManager.java:47)
[18:25:40 WARN]:        at com.gmail.nossr50.util.player.UserManager.clearAll(UserManager.java:60)
[18:25:40 WARN]:        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:347)
[18:25:40 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[18:25:40 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[18:25:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[18:25:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502)
[18:25:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495)
[18:25:40 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:435)
[18:25:40 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:775)
[18:25:40 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:706)
[18:25:40 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1051)
[18:25:40 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[18:25:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mrfloris** [comment]
i checked, i never had `2.1.177`, we were on a version before that. i was on 6, the one from friday
