### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by strahil211** [mcMMO-Dev/mcMMO#4476]
mcMMO ver 2.1.186 (latest as of time of this post)
Server ver Airplane version git-Airplane-"3ed988c" (latest as of time of this post)

[06:35:14 ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO v2.1.186
java.lang.ClassCastException: class java.util.Collections$UnmodifiableRandomAccessList cannot be cast to class com.gmail.nossr50.datatypes.meta.RuptureTaskMeta (java.util.Collections$UnmodifiableRandomAccessList is in module java.base of loader 'bootstrap'; com.gmail.nossr50.datatypes.meta.RuptureTaskMeta is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @39fd306c)
        at com.gmail.nossr50.skills.swords.SwordsManager.processRupture(SwordsManager.java:68) ~[?:?]
        at com.gmail.nossr50.util.skills.CombatUtils.processSwordCombat(CombatUtils.java:98) ~[?:?]
        at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:389) ~[?:?]
        at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:437) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor372.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:250) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1070) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:957) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:913) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1102) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1935) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1263) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:74) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.EntityZombie.damageEntity(EntityZombie.java:317) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1191) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2179) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2466) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1311) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1304) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1280) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1124) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Airplane-"3ed988c"]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by SmallSansSerif** [comment]
Same ... https://pastebin.com/F6Jv3TsU

**Comment by TheBusyBiscuit** [comment]
Seems like there's just a `.get(0)` missing here. Common error, Bukkit and its metadata system are really a pain sometimes.

https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/skills/swords/SwordsManager.java#L68
