### ISSUE TITLE
Console Spam Caused By BlockTracker

### ISSUE THREAD

**Issue by Beastman9095** [mcMMO-Dev/mcMMO#4488]
Has started after the latest update I believe as I have recently been able to check how our server is doing.
<details>
<summary>Error</summary>

```[04:49:24] [Server thread/ERROR]: Could not pass event EntityBlockFormEvent to mcMMO v2.1.188
java.lang.IndexOutOfBoundsException: x: 5 y: 256 z: 9 World Min: 0 World Max: 256
	at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.coordToIndex(BitSetChunkStore.java:107) ~[?:?]
	at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.coordToIndex(BitSetChunkStore.java:102) ~[?:?]
	at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.set(BitSetChunkStore.java:92) ~[?:?]
	at com.gmail.nossr50.util.blockmeta.HashChunkManager.set(HashChunkManager.java:240) ~[?:?]
	at com.gmail.nossr50.util.blockmeta.HashChunkManager.setTrue(HashChunkManager.java:192) ~[?:?]
	at com.gmail.nossr50.listeners.BlockListener.onEntityBlockFormEvent(BlockListener.java:179) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor520.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1698) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1686) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.EntitySnowman.movementTick(EntitySnowman.java:119) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2591) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:378) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1457) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.World.a(World.java:1019) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1108) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1538) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1388) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"94f025a"]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by nossr50** [comment]
Thanks, will look into this soon.
