### ISSUE TITLE
MC Rank and MC Top Commands no longer function

### ISSUE THREAD

**Issue by NolanMC** [mcMMO-Dev/mcMMO#4491]
I recently updated from an older version of MCMMO (somewhere around 2.1.179) to 2.1.190, and when a user goes to use /mcrank it prints out this error in console: 
  ```
[12:51:00 WARN]: [mcMMO] Plugin mcMMO v2.1.190 generated an exception while executing task 522
java.lang.NullPointerException: null
        at java.util.EnumMap.typeCheck(EnumMap.java:743) ~[?:?]
        at java.util.EnumMap.put(EnumMap.java:264) ~[?:?]
        at java.util.EnumMap.put(EnumMap.java:78) ~[?:?]
        at com.gmail.nossr50.database.FlatFileDatabaseManager.readRank(FlatFileDatabaseManager.java:501) ~[?:?]
        at com.gmail.nossr50.runnables.commands.McrankCommandAsyncTask.run(McrankCommandAsyncTask.java:33) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Airplane-"8703980"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Airplane-"8703980"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Airplane-"8703980"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
 Following this, they can no longer execute related commands like /mctop and get a message stating "Your previous command is still being processed, please wait." Given the error, I have checked my flatfile data and it appears to be healthy, without corruption. Can provide any other information upon request.
 
 MCMMO Version: 2.1.190
 Server Version: Airplane 1.16.5

**Comment by nossr50** [comment]
Looking into this now

**Comment by nossr50** [comment]
Fixed
