### ISSUE TITLE
Data Base problem

### ISSUE THREAD

**Issue by S1iwa** [mcMMO-Dev/mcMMO#4497]
I have problem, since I upgraded mcmmo to 2.1.194 mcmmo doesn't connect to data base or has some errors. 
I'm getting this error everytime when player joins;
```[18:19:49] [Craft Scheduler Thread - 17/WARN]: [mcMMO] Plugin mcMMO v2.1.194 generated an exception while executing task 319
java.lang.NullPointerException: null
	at com.gmail.nossr50.database.SQLDatabaseManager.getConnection(SQLDatabaseManager.java:988) ~[?:?]
	at com.gmail.nossr50.database.SQLDatabaseManager.loadPlayerFromDB(SQLDatabaseManager.java:608) ~[?:?]
	at com.gmail.nossr50.database.SQLDatabaseManager.loadPlayerProfile(SQLDatabaseManager.java:585) ~[?:?]
	at com.gmail.nossr50.runnables.player.PlayerProfileLoadingTask.run(PlayerProfileLoadingTask.java:44) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-401]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-401]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-401]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]```

All plugin doesnt work, levels, abillities, commands.

**Comment by nossr50** [comment]
Looking into this now
