### ISSUE TITLE
Unable To Pass PlayerJoinEvent

### ISSUE THREAD

**Issue by KolakZ** [mcMMO-Dev/mcMMO#4502]
I keep getting this error in console

[15:05:06 ERROR]: Could not pass event PlayerJoinEvent to mcMMO v2.1.196
[15:05:06 ERROR]: Suspected Plugins: 
[15:05:06 ERROR]:       mcMMO{enabled,ver=2.1.196,path=plugins/mcMMO.jar}
[15:05:06 ERROR]: Exception details below: 
java.lang.NoSuchMethodError: 'us.myles.ViaVersion.api.protocol.ServerProtocolVersion us.myles.ViaVersion.api.ViaAPI.getServerVersion()'
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:91) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.Facet.of(Facet.java:100) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:104) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:85) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:89) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:88) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
        at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:317) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:607) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:163) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1608) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:442) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1144) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-88]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by TheBusyBiscuit** [comment]
Seems to be the result of https://github.com/KyoriPowered/adventure-platform/pull/50

This change is automatically pulled in since adventure-platform has a `SNAPSHOT` versioning system and therefore mcMMO will always be built against the latest version within that snapshot.

@KolakZ 
I assume you will need to update ViaVersion for the error to go away.
To quote @KennyTV
> we generally advise people to stay on dev builds atm

**Comment by nossr50** [comment]
@TheBusyBiscuit summed this up well enough, ViaVersion and mcMMO are not lining up in terms of expected API and thus you will need an updated ViaVersion

**Comment by KolakZ** [comment]
I get even more errors with other plugins when I update viaversion to the latest dev build because of the new api

**Comment by Hallowhead1** [comment]
I have latest version of viaversion and have this issue?
