### ISSUE TITLE
/mcrank not working for certain players

### ISSUE THREAD

**Issue by WhatsTheBadNews** [mcMMO-Dev/mcMMO#4513]
For some of my players /mcrank does not work, no scoreboard shows up. It works for me though (on the same server). So it seems only certain players are affected. When those affected try, this error pops up in console (with MySQL debug enabled). Is there anything I can do to resolve this?

```
[10:34:49 INFO]: gregormendele issued server command: /mcrank
[10:34:49 WARN]: java.sql.SQLException: Subquery returns more than 1 row
[10:34:49 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[10:34:49 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[10:34:49 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[10:34:49 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[10:34:49 WARN]:        at com.gmail.nossr50.database.SQLDatabaseManager.readRank(SQLDatabaseManager.java:425)
[10:34:49 WARN]:        at com.gmail.nossr50.runnables.commands.McrankCommandAsyncTask.run(McrankCommandAsyncTask.java:33)
[10:34:49 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[10:34:49 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[10:34:49 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:34:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[10:34:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[10:34:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[10:34:49 ERROR]: [mcMMO] Location: com.mysql.cj.jdbc.exceptions.SQLError createSQLException 129
[10:34:49 ERROR]: [mcMMO] SQLException: Subquery returns more than 1 row
[10:34:49 ERROR]: [mcMMO] SQLState: 21000
[10:34:49 ERROR]: [mcMMO] VendorError: 1242
```

I asked on the mcMMO Discord and TheBusyBiscuit responded with these findings:

> Alright, I think I know what's happening here.
> As the error message Subquery returns more than 1 row suggests, more than one entry was returned for a query that expected a single entry.
> https://github.com/mcMMO-Dev/mcMMO/blob/0d2f370185d8f6a0ce86bb857fa0ed46742950e8/src/main/java/com/gmail/nossr50/database/SQLDatabaseManager.java#L419-L421
> The error is the direct result of this query which has a subquery of SELECT [...] WHERE user = <player name>.
> And that query somehow returns more than one entry which leads me to believe that there may be two different users who once shared the same username, since usernames are no longer guaranteed to be unique in Minecraft.
> 
> One possible solution would be to completely switch over to UUIDs which might have a bad effect on old datasets though.
> Otherwise there would be the option to target some kind of heuristic approach and trim off any additional entries.

I hope they are of some help and thank you in advance!

**Comment by broken1arrow** [comment]
I think and hope he already use uuid, but i can check it later. 

But i think you has a user with same uuid in the database.
