### ISSUE TITLE
[MySQL (MariaDB 8.0)] SQLException: Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by RalphORama** [mcMMO-Dev/mcMMO#4516]
When using mcMMO with SQL backend and MariaDB >= 8.0, I get the following exception on startup:

```
[20:53:44] [Server thread/ERROR]: [mcMMO] Location: com.mysql.cj.jdbc.exceptions.SQLError createSQLException 110
[20:53:44] [Server thread/ERROR]: [mcMMO] SQLException: Public Key Retrieval is not allowed
[20:53:44] [Server thread/ERROR]: [mcMMO] SQLState: 08001
[20:53:44] [Server thread/ERROR]: [mcMMO] VendorError: 0
```

Other plugins have an option to add `allowPublicKeyRetrieval=true` to the JDBC launch options, but I do not see that option in the mcMMO config. Is there a way to add arbitrary options to the JDBC connection string?

**Comment by TheBusyBiscuit** [comment]
Could you perhaps enable mysql debugging and send the resulting error (if you don't mind)?
`config.yml`:
`MySQL -> Debug: true`

This will give you the full stacktrace.

**Comment by RalphORama** [comment]
```log
[01:41:41 WARN]: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
[01:41:41 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[01:41:41 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[01:41:41 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[01:41:41 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[01:41:41 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[01:41:41 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[01:41:41 WARN]:        at com.gmail.nossr50.mcmmo.database.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:278)
[01:41:41 WARN]:        at com.gmail.nossr50.mcmmo.database.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
[01:41:41 WARN]:        at com.gmail.nossr50.mcmmo.database.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701)
[01:41:41 WARN]:        at com.gmail.nossr50.mcmmo.database.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635)
[01:41:41 WARN]:        at com.gmail.nossr50.mcmmo.database.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:188)
[01:41:41 WARN]:        at com.gmail.nossr50.mcmmo.database.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127)
[01:41:41 WARN]:        at com.gmail.nossr50.database.SQLDatabaseManager.getConnection(SQLDatabaseManager.java:991)
[01:41:41 WARN]:        at com.gmail.nossr50.database.SQLDatabaseManager.checkStructure(SQLDatabaseManager.java:836)
[01:41:41 WARN]:        at com.gmail.nossr50.database.SQLDatabaseManager.<init>(SQLDatabaseManager.java:127)
[01:41:41 WARN]:        at com.gmail.nossr50.database.DatabaseManagerFactory.getDatabaseManager(DatabaseManagerFactory.java:29)
[01:41:41 WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:242)
[01:41:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[01:41:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[01:41:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[01:41:41 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[01:41:41 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[01:41:41 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:581)
[01:41:41 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281)
[01:41:41 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1057)
[01:41:41 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[01:41:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[01:41:41 WARN]: Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed
[01:41:41 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:41:41 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:41:41 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:41:41 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[01:41:41 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[01:41:41 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[01:41:41 WARN]:        at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:128)
[01:41:41 WARN]:        at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
[01:41:41 WARN]:        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:441)
[01:41:41 WARN]:        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:174)
[01:41:41 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1350)
[01:41:41 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
[01:41:41 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
[01:41:41 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
[01:41:41 WARN]:        ... 24 more
[01:41:41 ERROR]: [mcMMO] Location: com.mysql.cj.jdbc.exceptions.SQLError createSQLException 110
[01:41:41 ERROR]: [mcMMO] SQLException: Public Key Retrieval is not allowed
[01:41:41 ERROR]: [mcMMO] SQLState: 08001
[01:41:41 ERROR]: [mcMMO] VendorError: 0
```

I have had this issue with other plugins and the solution, as stated above, is a way to add `allowPublicKeyRetrieval=true` to the JDBC string. For example, my fix with Plan Analytics:

```yaml
# Launch options to append after mysql driver address
Launch_options: "?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
```

**Comment by rosaage** [comment]
I got the same error recently, so I tried compiling from source: https://github.com/mcMMO-Dev/mcMMO/blob/5575309b7914137b95223a920d347179bb258dd8/src/main/java/com/gmail/nossr50/database/SQLDatabaseManager.java#L50-L63
I added a new line with `        connectionString += "&allowPublicKeyRetrieval=true";` in this file and at least I got it to connect to the database now, as /mctop was working fine as well as well as /inspect. There were a bunch of other errors though but I don't think they were related to the databse (probably something with my compilation).
Afterwards I remove my compiled version and added back 2.1.201 and suddenly it started working fine again. Maybe the addition of a small config check here to enable this option would fix the issue?

I added a pull request for this option, I think I got all the necessary changes required for adding this (config file, function + check to add) #4635
