### ISSUE TITLE
Error even when use latest via I can find on github.

### ISSUE THREAD

**Issue by broken1arrow** [mcMMO-Dev/mcMMO#4519]
I think you has change the API too fast in mcmmo.

It seams to work ether way, but get it is ViaBackwards-3.2.1-SNAPSHOT and ViaVersion-3.2.2-SNAPSHOT I compile from github.

<details>
  <summary>Error</summary>
12.05 16:38:50 [Server] INFO java.lang.NoSuchMethodError: 'us.myles.ViaVersion.api.protocol.ServerProtocolVersion us.myles.ViaVersion.api.ViaAPI.getServerVersion()'
12.05 16:38:50 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:91) ~[?:?]
12.05 16:38:50 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.Facet.of(Facet.java:100) ~[?:?]
12.05 16:38:50 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:104) ~[?:?]
12.05 16:38:50 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:85) ~[?:?]
12.05 16:38:50 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
12.05 16:38:50 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
12.05 16:38:50 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:89) ~[?:?]
12.05 16:38:50 [Server] INFO at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
12.05 16:38:50 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:88) ~[?:?]
12.05 16:38:50 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
12.05 16:38:50 [Server] INFO at com.gmail.nossr50.mcmmo.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
12.05 16:38:50 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:167) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:390) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1380) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-415]
12.05 16:38:50 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]
<details>

**Comment by lexikiq** [comment]
Duplicate, use the latest viaversion from their Jenkins CI. Caused by mcMMO's dependency on Adventure, not the plugin

https://github.com/mcMMO-Dev/mcMMO/issues/4502#issuecomment-825871597

**Comment by lexikiq** [comment]
Possible the new ViaVersion is on a new branch other than master

https://ci.viaversion.com/job/ViaVersion-DEV/

**Comment by broken1arrow** [comment]
> Possible the new ViaVersion API is on a new branch other than master
> 
> https://ci.viaversion.com/job/ViaVersion-DEV/

yea they have a dev branch to, I miss that, at least they master branch seams to be more updated an the released version (but not all new changes apparently).

But I still think he was to fast to update the api, he should want little longer before update it (if he not needed something in the new api if not he should want).
