### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to mcMMO

### ISSUE THREAD

**Issue by ilyassos1** [mcMMO-Dev/mcMMO#4530]
> [18:44:02 ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO v2.1.186
> java.lang.ClassCastException: java.util.Collections$UnmodifiableRandomAccessList cannot be cast to com.gmail.nossr50.datatypes.meta.RuptureTaskMeta
>         at com.gmail.nossr50.skills.swords.SwordsManager.processRupture(SwordsManager.java:68) ~[?:?]
>         at com.gmail.nossr50.util.skills.CombatUtils.processSwordCombat(CombatUtils.java:98) ~[?:?]
>         at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:389) ~[?:?]
>         at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:437) ~[?:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor401.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-706]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-706]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-706]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:619) ~[patched_1.16.5.jar:git-Paper-706]
>         at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:254) ~[patched_1.16.5.jar:git-Paper-706]
>         at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1088) ~[patched_1.16.5.jar:git-Paper-706]
>         at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:975) ~[patched_1.16.5.jar:git-Paper-706]
>         at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:931) ~[patched_1.16.5.jar:git-Paper-706]
>         at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1120) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1932) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1260) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:74) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1224) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2021) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2404) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1217) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-706]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-706]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

im aware this issue has been opened before in 2016 and 2020 but the solutions didn't seem to work(tried disabling healthbars). 
ive used the plugin for a while this error doesnt seem to be affecting anything, if there are no known solutions i would like to know how to disable the error spamming in the console

**Comment by TheBusyBiscuit** [comment]
I doubt that this issue ever existed back in 2016.
However, it was reported sometime in 2021 and has been fixed almost immediately after.

Noteworthy to say that you are ~11 versions behind. Downloading the latest mcMMO version from SpigotMC or Polymart should resolve that issue for you.
