### ISSUE TITLE
Block Breaks under y:0 create Index Out of Bounds errors for mcMMO (min: 0, max: 320)

### ISSUE THREAD

**Issue by tmellen** [mcMMO-Dev/mcMMO#4550]
When people mine at -1 to -64, the server console is flooded with this for every block:

[15.06 10:11:12] [Server] [Server thread/ERROR]: Could not pass event BlockBreakEvent to mcMMO v2.1.198
[15.06 10:11:12] [Server] org.bukkit.event.EventExceptionnull
[15.06 10:11:12] [Server] 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:347) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:307) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:277) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1479) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:34) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot-1.17.jar:3141-Spigot-66f9d3c-72a2901]
[15.06 10:11:12] [Server] 	at java.lang.Thread.run(Thread.java:831) [?:?]
[15.06 10:11:12] [Server] Caused byjava.lang.IndexOutOfBoundsException: x: 7 y: -4 z: 9 World Min: 0 World Max: 320

**Comment by t00thpick1** [comment]
@nossr50 Does https://github.com/mcMMO-Dev/mcMMO/blob/master/src/main/java/com/gmail/nossr50/util/compat/CompatibilityManager.java#L80 need to be >= ?

**Comment by nossr50** [comment]
Just fixed this
