### ISSUE TITLE
scoreboard exception erorr

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#4553]
```
[18:24:35 INFO]: TigersSparkle issued server command: /mcscoreboard keep
[18:24:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mcscoreboard' in plugin mcMMO v2.1.197
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-778]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.isBoardShown()" because the return value of "java.util.Map.get(Object)" is null
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.isBoardShown(ScoreboardManager.java:562) ~[?:?]
        at com.gmail.nossr50.commands.McscoreboardCommand.onCommand(McscoreboardCommand.java:40) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-778]
        ... 19 more
```
```
> ver
[18:30:53 INFO]: Checking version, please wait...
[18:30:53 INFO]: This server is running Paper version git-Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-777 (MC: 1.16.5)
[18:30:58 INFO]: TigersSparkle issued server command: /afk
[18:30:58 INFO]:  * TigersSparkle has gone AFK ()
> ver mcmmo
[18:31:00 INFO]: mcMMO version 2.1.197
[18:31:00 INFO]: The goal of mcMMO is to take core Minecraft game mechanics and expand them into add an extensive and quality RPG experience. Everything in mcMMO has been carefully thought out and is constantly being improved upon. Currently, mcMMO adds thirteen unique skills to train and level in. Each of these skills is highly customizable through our configuration files, allowing server admins to tweak mcMMO to best suit the needs of his or her server. Know that the mcMMO team is dedicated to providing an ever-evolving experience, and that we carefully read all feedback and bug reports in order to evaluate and balance the mechanics of mcMMO in every update.

[18:31:00 INFO]: Website: https://www.mcmmo.org
[18:31:00 INFO]: Authors: nossr50, GJ, NuclearW, bm01, Glitchfinder, TfT_02, t00thpick1, Riking, electronicboy and kashike
>
```

**Comment by nossr50** [comment]
Thanks for the report, I’ll look into it

**Comment by mrfloris** [comment]
friendly bump

**Comment by realsnake2** [comment]
I get the same error on the latest version of paper. The scoreboard does not even show up.

```
25.12 00:50:55 [Server] INFO snake256 issued server command: /mcsb time 10
25.12 00:50:55 [Server] ERROR null
25.12 00:50:55 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mcsb' in plugin mcMMO v2.1.206
25.12 00:50:55 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
25.12 00:50:55 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
25.12 00:50:55 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-101]
25.12 00:50:55 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2268) ~[?:?]
25.12 00:50:55 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2079) ~[?:?]
25.12 00:50:55 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2060) ~[?:?]
25.12 00:50:55 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
25.12 00:50:55 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
25.12 00:50:55 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
25.12 00:50:55 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-101]
25.12 00:50:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
25.12 00:50:55 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
25.12 00:50:55 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-101]
25.12 00:50:55 [Server] INFO at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-101]
25.12 00:50:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
25.12 00:50:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-101]
25.12 00:50:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-101]
25.12 00:50:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
25.12 00:50:55 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.18.1.jar:git-Paper-101]
25.12 00:50:55 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-101]
25.12 00:50:55 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
25.12 00:50:55 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
25.12 00:50:55 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.showBoardAndScheduleRevert(int)" because the return value of "java.util.Map.get(Object)" is null
25.12 00:50:55 [Server] INFO at com.gmail.nossr50.util.scoreboards.ScoreboardManager.setRevertTimer(ScoreboardManager.java:574) ~[mcMMO.jar:?]
25.12 00:50:55 [Server] INFO at com.gmail.nossr50.commands.McscoreboardCommand.onCommand(McscoreboardCommand.java:60) ~[mcMMO.jar:?]
25.12 00:50:55 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
25.12 00:50:55 [Server] INFO ... 21 more
25.12 00:54:46 [Disconnect] User snake256 has disconnected, reason: Disconnected
25.12 00:54:46 [Server] INFO snake256 left the game
25.12 00:55:09 [Server] INFO Checking version, please wait...
25.12 00:55:09 [Server] INFO This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)
25.12 00:55:09 [Server] INFO You are running the latest version
25.12 00:55:09 [Server] INFO Previous version: git-Paper-68 (MC: 1.18.1)

**Comment by realsnake2** [comment]
After editing `config.yml` and setting `UseScoreboards` to `true` the error does not occur anymore. I think the command should show a user friendly error message in the log if scoreboards are not enabled, instead of crashing and showing an exception stack trace.
