### ISSUE TITLE
Warning on startup

### ISSUE THREAD

**Issue by JasonHorkles** [mcMMO-Dev/mcMMO#4571]
Every time my server starts up I get the following warning:
```accesslog
[mcMMO] Plugin mcMMO v2.1.200 generated an exception while executing task 105
java.lang.ArrayIndexOutOfBoundsException: Index 14 out of bounds for length 2
        at com.gmail.nossr50.database.FlatFileDatabaseManager.tryLoadSkillIntValuesFromRawData(FlatFileDatabaseManager.java:1293) ~[?:?]
        at com.gmail.nossr50.database.FlatFileDatabaseManager.getSkillMapFromLine(FlatFileDatabaseManager.java:1306) ~[?:?]
        at com.gmail.nossr50.database.FlatFileDatabaseManager.purgePowerlessUsers(FlatFileDatabaseManager.java:132) ~[?:?]
        at com.gmail.nossr50.runnables.database.UserPurgeTask.run(UserPurgeTask.java:13) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Tuinity-18]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Tuinity-18]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Tuinity-18]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
Is there any way to fix it?

This server is running Tuinity version git-Tuinity-18 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: ea43797 on HEAD)

mcMMO 2.1.200

**Comment by nossr50** [comment]
Can you post your databse file ( mcmmo.users )

**Comment by JasonHorkles** [comment]
https://1drv.ms/u/s!ArOS099NaR9LkbckA-4xGPCNn4wAKA?e=0d2GGA

**Comment by JasonHorkles** [comment]
Also I should note it happens after MCMMO starts trying to purge powerless users
