### ISSUE TITLE
weird error when attempting to reset player stats on paper

### ISSUE THREAD

**Issue by Ogmur** [mcMMO-Dev/mcMMO#4612]
weird error when attempting to reset player stats on paper, says an internal error has occurred in the game.

[00:15:28] [Server thread/INFO]: Ogmur issued server command: /skillreset X97Z Salvage
[00:15:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'skillreset' in plugin mcMMO v2.1.200
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-138]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:830) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-138]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because the return value of "java.util.Map.get(Object)" is null
	at com.gmail.nossr50.datatypes.player.PlayerProfile.getSkillXpLevelRaw(PlayerProfile.java:266) ~[?:?]
	at com.gmail.nossr50.commands.experience.SkillresetCommand.handleCommand(SkillresetCommand.java:124) ~[?:?]
	at com.gmail.nossr50.commands.experience.SkillresetCommand.editValues(SkillresetCommand.java:176) ~[?:?]
	at com.gmail.nossr50.commands.experience.SkillresetCommand.onCommand(SkillresetCommand.java:98) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-138]
	... 21 more

**Comment by Zoriot** [comment]
It works for me 🤷‍♂️

**Comment by OgmurHere** [comment]
No idea what causes it but doesn’t happen anymore. Cheers!
