### ISSUE TITLE
Alchemy console error

### ISSUE THREAD

**Issue by emanondev** [mcMMO-Dev/mcMMO#4660]
Error on console:
Game -> Paper version git-Paper-377 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 3f17694)
Mcmmo -> v2.1.204

[11:46:21 WARN]: [mcMMO] Task #753629 for mcMMO v2.1.204 generated an exception
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at **com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:144) ~[mcMMO-2.1.204.jar:?]**
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:102) ~[mcMMO-2.1.204.jar:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:90) ~[mcMMO-2.1.204.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-378]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Paper-378]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1481) ~[patched_1.17.1.jar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-378]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by nossr50** [comment]
Should be fixed
