### ISSUE TITLE
[mcMMO] Task #27397211 for mcMMO v2.1.204 generated an exception

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4663]
When there's a large amount of users disconnecting from the server, we caught this problem:

```
[18:01:24] [Server thread/WARN]: [mcMMO] Task #27397211 for mcMMO v2.1.204 generated an exception
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.datatypes.player.McMMOPlayer.addXp(com.gmail.nossr50.datatypes.skills.PrimarySkillType, float)" because the return value of "com.gmail.nossr50.util.player.UserManager.getPlayer(org.bukkit.entity.Player)" is null
	at com.gmail.nossr50.util.EventUtils.handleXpGainEvent(EventUtils.java:388) ~[mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:682) ~[mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:646) ~[mcMMO.jar:?]
	at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:633) ~[mcMMO.jar:?]
	at com.gmail.nossr50.runnables.skills.AwardCombatXpTask.run(AwardCombatXpTask.java:42) ~[mcMMO.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-378]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Paper-378]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1481) ~[patched_1.17.1.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1280) ~[patched_1.17.1.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-378]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nossr50** [comment]
I'll take a look soon, seems like an odd error though
