### ISSUE TITLE
Could not pass event BrewEvent to mcMMO v2.1.202

### ISSUE THREAD

**Issue by PanetiX** [mcMMO-Dev/mcMMO#4666]
Hey, the Alchemy Skill don't work on our Server. Every other Skill works fine.
When a user will brew something the following error appears in the console log:

```
[11:20:56] [Server thread/WARN]: [mcMMO] Task #30027 for mcMMO v2.1.202 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.event.inventory.BrewEvent.<init>(org.bukkit.block.Block, org.bukkit.inventory.BrewerInventory, int)'
	at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9) ~[mcMMO.jar:?]
	at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:136) ~[mcMMO.jar:?]
	at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:102) ~[mcMMO.jar:?]
	at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:90) ~[mcMMO.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper.jar:git-Paper-373]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper.jar:git-Paper-373]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[paper.jar:git-Paper-373]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[paper.jar:git-Paper-373]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[paper.jar:git-Paper-373]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[paper.jar:git-Paper-373]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper.jar:git-Paper-373]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[11:21:01] [Server thread/ERROR]: Could not pass event BrewEvent to mcMMO v2.1.202
java.lang.NoSuchMethodError: 'void org.bukkit.event.inventory.BrewEvent.<init>(org.bukkit.block.Block, org.bukkit.inventory.BrewerInventory, int)'
	at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9) ~[mcMMO.jar:?]
	at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:136) ~[mcMMO.jar:?]
	at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finishImmediately(AlchemyBrewTask.java:111) ~[mcMMO.jar:?]
	at com.gmail.nossr50.listeners.InventoryListener.onBrew(InventoryListener.java:356) ~[mcMMO.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor432.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper.jar:git-Paper-373]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper.jar:git-Paper-373]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper.jar:git-Paper-373]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper.jar:git-Paper-373]
	at net.minecraft.world.level.block.entity.BrewingStandBlockEntity.a(BrewingStandBlockEntity.java:260) ~[app:?]
	at net.minecraft.world.level.block.entity.BrewingStandBlockEntity.serverTick(BrewingStandBlockEntity.java:184) ~[app:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1459) ~[app:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1411) ~[app:?]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:974) ~[app:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:783) ~[app:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1624) ~[paper.jar:git-Paper-373]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[paper.jar:git-Paper-373]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[paper.jar:git-Paper-373]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[paper.jar:git-Paper-373]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper.jar:git-Paper-373]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by chrismwiggs** [comment]
Confirming that I am having this issue too with the latest release of mcmmo (2.1.204) on Paper (Purpur) 1.17.1. Any brewing, vanilla or mcmmo, fails with the above error. 

If this is a tricky bug to fix (and will take some time), might it be worth adding a temp toggle to Mcmmo alchemy so we can continue to use al teast vanilla brewing?

**Comment by nossr50** [comment]
This shouldn't happen in the newest build, @chrismwiggs if you have this on 2.1.205 please post an issue for it
