### ISSUE TITLE
Console error: Fake brew event

### ISSUE THREAD

**Issue by KickSquareMC** [mcMMO-Dev/mcMMO#4679]
```
java.lang.NoSuchMethodError: 'void org.bukkit.event.inventory.BrewEvent.<init>(org.bukkit.block.Block, org.bukkit.inventory.BrewerInventory, int)'
    at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9)
    at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:136)
    at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finishImmediately(AlchemyBrewTask.java:111)
    at com.gmail.nossr50.listeners.InventoryListener.onBrew(InventoryListener.java:356)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor683.execute
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
    at net.minecraft.world.level.block.entity.TileEntityBrewingStand.a(TileEntityBrewingStand.java:260)
    at net.minecraft.world.level.block.entity.TileEntityBrewingStand.a(TileEntityBrewingStand.java:184)
    at net.minecraft.world.level.chunk.Chunk$a.a(Chunk.java:1491)
    at net.minecraft.world.level.chunk.Chunk$c.a(Chunk.java:1443)
    at net.minecraft.world.level.World.tickBlockEntities(World.java:1066)
    at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:796)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1629)
    at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:495)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1485)
    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1284)
    at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
    at java.lang.Thread.run(Thread.java:831)
    ```
    
    Running pufferfish 1.17.1 and mcmmo version 2.1.202.

**Comment by Warriorrrr** [comment]
Update mcMMO.
