### ISSUE TITLE
Could not pass event BrewEvent to mcMMO v2.1.200

### ISSUE THREAD

**Issue by goldfrosch** [mcMMO-Dev/mcMMO#4697]
[12:48:35] [Server thread/WARN]: [mcMMO] Task #2091 for mcMMO v2.1.200 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.event.inventory.BrewEvent.<init>(org.bukkit.block.Block, org.bukkit.inventory.BrewerInventory, int)'
	at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9) ~[mcMMO_2.1.200.jar:?]
	at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:136) ~[mcMMO_2.1.200.jar:?]
	at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:102) ~[mcMMO_2.1.200.jar:?]
	at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:90) ~[mcMMO_2.1.200.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-402]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

[12:48:46] [Server thread/ERROR]: Could not pass event BrewEvent to mcMMO v2.1.200
java.lang.NoSuchMethodError: 'void org.bukkit.event.inventory.BrewEvent.<init>(org.bukkit.block.Block, org.bukkit.inventory.BrewerInventory, int)'
	at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:9) ~[mcMMO_2.1.200.jar:?]
	at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:136) ~[mcMMO_2.1.200.jar:?]
	at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finishImmediately(AlchemyBrewTask.java:111) ~[mcMMO_2.1.200.jar:?]
	at com.gmail.nossr50.listeners.InventoryListener.onBrew(InventoryListener.java:356) ~[mcMMO_2.1.200.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor387.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-402]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.world.level.block.entity.BrewingStandBlockEntity.a(BrewingStandBlockEntity.java:260) ~[app:?]
	at net.minecraft.world.level.block.entity.BrewingStandBlockEntity.serverTick(BrewingStandBlockEntity.java:184) ~[app:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1459) ~[app:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1411) ~[app:?]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:963) ~[app:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:783) ~[app:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-402]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-402]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
	
server version: 1.17.1

Plz Help

**Comment by nossr50** [comment]
Update your mcMMO
