### ISSUE TITLE
EntityChangeBlockEvent error

### ISSUE THREAD

**Issue by HeresJohnny320** [mcMMO-Dev/mcMMO#4698]
[08:41:47 ERROR]: Could not pass event EntityChangeBlockEvent to mcMMO v2.1.207-SNAPSHOT

		at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.coordToIndex(BitSetChunkStore.java:107) ~[mcMMO.jar:?]at com.gmail.nossr50.listeners.EntityListener.onEntityChangeBlock(EntityListener.java:243) ~[mcMMO.jar:?]at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.coordToIndex(BitSetChunkStore.java:102) ~[mcMMO.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor321.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-101]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1277) ~[paper-1.18.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1269) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.world.entity.item.FallingBlockEntity.tick(FallingBlockEntity.java:133) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Ghost-chu** [comment]
```
java.lang.IndexOutOfBoundsException: x: 4 y: -27 z: 10 World Min: 0 World Max: 256
        at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.coordToIndex(BitSetChunkStore.java:107) ~[mcMMO (2).jar:?]
        at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.coordToIndex(BitSetChunkStore.java:102) ~[mcMMO (2).jar:?]
        at com.gmail.nossr50.util.blockmeta.BitSetChunkStore.set(BitSetChunkStore.java:92) ~[mcMMO (2).jar:?]
        at com.gmail.nossr50.util.blockmeta.HashChunkManager.set(HashChunkManager.java:240) ~[mcMMO (2).jar:?]
        at com.gmail.nossr50.util.blockmeta.HashChunkManager.setTrue(HashChunkManager.java:197) ~[mcMMO (2).jar:?]
        at com.gmail.nossr50.listeners.BlockListener.onBlockFormEvent(BlockListener.java:222) ~[mcMMO (2).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor794.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-101]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1755) ~[paper-1.18.1.jar:git-Paper-101]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1747) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.world.level.material.LavaFluid.spreadTo(LavaFluid.java:215) ~[?:?]
        at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:151) ~[?:?]
        at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:506) ~[?:?]
        at net.minecraft.world.level.material.FluidState.tick(FluidState.java:77) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickFluid(ServerLevel.java:1067) ~[?:?]
        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:215) ~[?:?]
        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:98) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:614) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-101]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
