### ISSUE TITLE
Error while Initializing experience.yml

### ISSUE THREAD

**Issue by mare-on** [mcMMO-Dev/mcMMO#4732]
Server version: **Paper 1.18.1-b165**
Plugin version: **2.1.109**

Issue:
I have discover an issue during initializing config file "experience.yml".
I didn't wanted some animals in Taming section due to they doesn't work but oups... some of these values are... required???

Console log:
```
[Server thread/INFO]: [mcMMO] [config] Loading config from disk: experience.yml
[Server thread/INFO]: [mcMMO] [config] Config initialized: experience.yml
[Server thread/WARN]: [mcMMO] Experience_Values.Taming.Animal_Taming.Ocelot should be greater than 0!
[Server thread/WARN]: [mcMMO] Errors were found in experience.yml! mcMMO was disabled!
[Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.209
[Server thread/INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.util.blockmeta.ChunkManager.closeAll()" because "com.gmail.nossr50.mcMMO.placeStore" is null
[Server thread/WARN]: 	at mcMMO-2.1.209.jar//com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:369)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399)
[Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537)
[Server thread/WARN]: 	at mcMMO-2.1.209.jar//com.gmail.nossr50.config.BukkitConfig.validate(BukkitConfig.java:103)
[Server thread/WARN]: 	at mcMMO-2.1.209.jar//com.gmail.nossr50.config.experience.ExperienceConfig.<init>(ExperienceConfig.java:25)
[Server thread/WARN]: 	at mcMMO-2.1.209.jar//com.gmail.nossr50.config.experience.ExperienceConfig.getInstance(ExperienceConfig.java:30)
[Server thread/WARN]: 	at mcMMO-2.1.209.jar//com.gmail.nossr50.mcMMO.scheduleTasks(mcMMO.java:666)
[Server thread/WARN]: 	at mcMMO-2.1.209.jar//com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:256)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[Server thread/WARN]: java.lang.IllegalStateException: zip file closed
[Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[Server thread/WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[Server thread/WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[Server thread/WARN]: 	at mcMMO-2.1.209.jar//com.gmail.nossr50.mcMMO.scheduleTasks(mcMMO.java:672)
[Server thread/WARN]: 	at mcMMO-2.1.209.jar//com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:256)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by TheBusyBiscuit** [comment]
Can you please also post your `experience.yml` file?

**Comment by mare-on** [comment]
Hi, here is my experience,yml config file without added Ocelot in taming section: [https://paste.in/KQmZW9](https://paste.in/KQmZW9)

**Comment by Chew** [comment]
Please provide the broken YAML so we can find the issue...

**Comment by mare-on** [comment]
Interesting solution... literally removing of the config validation? LoL :D
