### ISSUE TITLE
Could not pass event FurnaceSmeltEvent to mcMMO.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4754]
Currently running 1.17.1 Paper Build 409
As well as mcMMO built on https://github.com/mcMMO-Dev/mcMMO/commit/d5ce8fc6ff5e761099ca31b0a9393e29ea4a27f6

Getting the following:

`[12:55:27] [Server thread/ERROR]: Could not pass event FurnaceSmeltEvent to mcMMO v2.1.208-SNAPSHOT
java.lang.IllegalArgumentException: Name cannot be null
    at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.17.1.jar:git-Paper-409]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.getPlayerExact(CraftServer.java:623) ~[patched_1.17.1.jar:git-Paper-409]
    at com.gmail.nossr50.util.player.UserManager.retrieveMcMMOPlayer(UserManager.java:142) ~[mcMMO.jar:?]
    at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:121) ~[mcMMO.jar:?]
    at com.gmail.nossr50.listeners.InventoryListener.onFurnaceSmeltEvent(InventoryListener.java:114) ~[mcMMO.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor538.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-409]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-409]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-409]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.burn(AbstractFurnaceBlockEntity.java:426) ~[app:?]
    at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.serverTick(AbstractFurnaceBlockEntity.java:376) ~[app:?]
    at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1459) ~[app:?]
    at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1411) ~[app:?]
    at net.minecraft.world.level.Level.tickBlockEntities(Level.java:963) ~[app:?]
    at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:783) ~[app:?]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-409]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by nossr50** [comment]
Fixed
