### ISSUE TITLE
Could not pass event BrewEvent to mcMMO

### ISSUE THREAD

**Issue by Kornflakez13** [mcMMO-Dev/mcMMO#4772]
Good Day
We have recently started having problems with brewing levels of players not going up, All other MCMMO level were tested and work fine. Only brewing is effected and not sure why.

Could not pass event BrewEvent to mcMMO v2.1.200
Task #7381101 for mcMMO v2.1.200 generated an exception
Could not pass event BrewEvent to mcMMO v2.1.200
Task #7393345 for mcMMO v2.1.200 generated an exception

Thanks

**Comment by Chew** [comment]
You're pretty far behind update wise. Latest is 2.1.212. Can you upgrade to that, and run `/version` and send that as well?

**Comment by Radiation-pi** [comment]
I updated my MCMMO from v2.1.196 to v2.1.212 these days. Then my player told me that the  brewing level can't going up, so I check my server and find this: 

Could not pass event BrewEvent to mcMMO v2.1.212
java.lang.NoSuchMethodError: 'void org.bukkit.event.inventory.BrewEvent.<init>(org.bukkit.block.Block, org.bukkit.inventory.BrewerInventory, java.util.List, int)'
        at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:12) ~[?:?]
        at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:137) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finishImmediately(AlchemyBrewTask.java:111) ~[?:?]
        at com.gmail.nossr50.listeners.InventoryListener.onBrew(InventoryListener.java:355) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor58.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1171]        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.TileEntityBrewingStand.j(TileEntityBrewingStand.java:252) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.TileEntityBrewingStand.tick(TileEntityBrewingStand.java:177) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.World.tickBlockEntities(World.java:990) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1183) ~[patched_1.16.5.jar:git-Purpur-1171]        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1567) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]

I tried to run MCMMO without other plugin, but it doesn't work.
Sorry about my poor English may make you confused ：D

**Comment by tuanhp0** [comment]
[23:48:43 ERROR]: Could not pass event BrewEvent to mcMMO v2.1.218
java.lang.NoSuchMethodError: 'void org.bukkit.event.inventory.BrewEvent.<init>(org.bukkit.block.Block, org.bukkit.inventory.BrewerInventory, java.util.List, int)'
        at com.gmail.nossr50.events.fake.FakeBrewEvent.<init>(FakeBrewEvent.java:12) ~[?:?]
        at com.gmail.nossr50.skills.alchemy.AlchemyPotionBrewer.finishBrewing(AlchemyPotionBrewer.java:137) ~[?:?]
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finishImmediately(AlchemyBrewTask.java:111) ~[?:?]
        at com.gmail.nossr50.listeners.InventoryListener.onBrew(InventoryListener.java:349) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor637.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TileEntityBrewingStand.j(TileEntityBrewingStand.java:252) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TileEntityBrewingStand.tick(TileEntityBrewingStand.java:177) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.World.tickBlockEntities(World.java:873) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:683) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1495) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]

**Comment by nossr50** [comment]
Likely fixed long ago, reopen if still an issue
