### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by RanWhite** [mcMMO-Dev/mcMMO#4780]
spigot 1.19
mcMMO v2.1.213
![QQ图片20220610092731](https://user-images.githubusercontent.com/69817107/172971894-e04cbb3a-c2bb-4ef5-8d73-e633a2eacb05.png)

[09:18:29] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to mcMMO v2.1.213
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:505) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:493) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1581) ~[?:3513-Spigot-fa893f0-576a037]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerAnimationEvent: method 'void <init>(org.bukkit.entity.Player)' not found
	at com.gmail.nossr50.events.fake.FakePlayerAnimationEvent.<init>(FakePlayerAnimationEvent.java:11) ~[?:?]
	at com.gmail.nossr50.listeners.PlayerListener.onPlayerInteractMonitor(PlayerListener.java:844) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor247.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 22 more

**Comment by nossr50** [comment]
Grab 2.1.214
