### ISSUE TITLE
Getting an error with my server and can't figure it out.

### ISSUE THREAD

**Issue by DedanKaze** [mcMMO-Dev/mcMMO#4824]
Before the logs, I'm running a modded/plugin server with: 
Magma 1.18.2
Version: cca106b5

Part of the log when mcMMO tries to start up:

> 30.08 23:02:47 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Enabling mcMMO v2.1.218-SNAPSHOT
30.08 23:02:47 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: config.yml
30.08 23:02:47 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: config.yml
30.08 23:02:47 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: config.yml
30.08 23:02:48 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [Debug] No errors found in config.yml!
30.08 23:02:50 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Loading locale from plugins/mcMMO/locales/locale_override.properties
30.08 23:02:50 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: advanced.yml
30.08 23:02:50 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: advanced.yml
30.08 23:02:50 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: advanced.yml
30.08 23:02:50 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [Debug] No errors found in advanced.yml!
30.08 23:02:50 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Platform String: 1.18.2-R0.1-SNAPSHOT
30.08 23:02:50 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Minecraft version determined to be - 1.18.2
30.08 23:02:51 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Loading compatibility layers...
30.08 23:02:51 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Finished loading compatibility layers.
30.08 23:02:52 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: persistent_data.yml
30.08 23:02:52 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: persistent_data.yml
30.08 23:02:52 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: persistent_data.yml
30.08 23:02:52 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [Debug] No errors found in persistent_data.yml!
30.08 23:02:52 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: upgrades_overhaul.yml
30.08 23:02:52 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: upgrades_overhaul.yml
30.08 23:02:52 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: upgrades_overhaul.yml
30.08 23:02:53 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: treasures.yml
30.08 23:02:53 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: treasures.yml
30.08 23:02:53 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: treasures.yml
30.08 23:02:53 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: fishing_treasures.yml
30.08 23:02:53 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: fishing_treasures.yml
30.08 23:02:53 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: fishing_treasures.yml
30.08 23:02:54 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Registering enchantments for Fishing Book...
30.08 23:02:54 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Loading mcMMO potions.yml File...
30.08 23:02:54 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: coreskills.yml
30.08 23:02:54 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: coreskills.yml
30.08 23:02:54 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: coreskills.yml
30.08 23:02:54 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: sounds.yml
30.08 23:02:54 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: sounds.yml
30.08 23:02:54 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: sounds.yml
30.08 23:02:54 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Loading mcMMO skillranks.yml File...
30.08 23:02:56 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: child.yml
30.08 23:02:56 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: child.yml
30.08 23:02:56 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: child.yml
30.08 23:02:56 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: repair.vanilla.yml
30.08 23:02:56 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: repair.vanilla.yml
30.08 23:02:56 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: repair.vanilla.yml
30.08 23:02:57 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Initializing config: salvage.vanilla.yml
30.08 23:02:57 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Loading config from disk: salvage.vanilla.yml
30.08 23:02:57 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] [config] Config initialized: salvage.vanilla.yml
30.08 23:02:57 [Server] Server thread/ERROR [co.gm.no.mcMMO/]: [mcMMO] There was an error while enabling mcMMO!
30.08 23:02:57 [Server] Server thread/WARN [/]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.Recipe.getResult()" because "bukkitRecipe" is null
30.08 23:02:57 [Server] Server thread/WARN [/]: at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:331)
30.08 23:02:57 [Server] Server thread/WARN [/]: at com.gmail.nossr50.config.skills.salvage.SalvageConfig.loadKeys(SalvageConfig.java:144)
30.08 23:02:57 [Server] Server thread/WARN [/]: at com.gmail.nossr50.config.skills.salvage.SalvageConfig.<init>(SalvageConfig.java:26)
30.08 23:02:57 [Server] Server thread/WARN [/]: at com.gmail.nossr50.config.skills.salvage.SalvageConfigManager.<init>(SalvageConfigManager.java:20)
30.08 23:02:57 [Server] Server thread/WARN [/]: at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:584)
30.08 23:02:57 [Server] Server thread/WARN [/]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:200)
30.08 23:02:57 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
30.08 23:02:57 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:450)
30.08 23:02:57 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
30.08 23:02:57 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:434)
30.08 23:02:57 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:348)
30.08 23:02:57 [Server] Server thread/WARN [/]: at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:452)
30.08 23:02:57 [Server] Server thread/WARN [/]: at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:361)
30.08 23:02:57 [Server] Server thread/WARN [/]: at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:244)
30.08 23:02:57 [Server] Server thread/WARN [/]: at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:761)
30.08 23:02:57 [Server] Server thread/WARN [/]: at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:254)
30.08 23:02:57 [Server] Server thread/WARN [/]: at java.base/java.lang.Thread.run(Thread.java:833)
30.08 23:02:57 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Disabling mcMMO v2.1.218-SNAPSHOT
30.08 23:02:57 [Server] Server thread/INFO [co.gm.no.mcMMO/]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
30.08 23:02:58 [Server] Server thread/WARN [/]: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.util.experience.FormulaManager.saveFormula()" because "com.gmail.nossr50.mcMMO.formulaManager" is null
30.08 23:02:58 [Server] Server thread/WARN [/]: at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:373)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:475)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501)
30.08 23:02:58 [Server] Server thread/WARN [/]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:298)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:450)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:434)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/forge@40.1.73/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:348)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:452)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:361)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:244)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:761)
30.08 23:02:58 [Server] Server thread/WARN [/]: at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:254)
30.08 23:02:58 [Server] Server thread/WARN [/]: at java.base/java.lang.Thread.run(Thread.java:833)
30.08 23:02:58 [Server] Server thread/ERROR [co.gm.no.mcMMO/]: [mcMMO] Cannot read /plugins/mcMMO/experience.yml(File Permissions?)
30.08 23:02:58 [Server] Server thread/ERROR [Minecraft/]: Error occurred while disabling mcMMO v2.1.218-SNAPSHOT (Is it up to date?)
30.08 23:02:58 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.database.DatabaseManager.onDisable()" because "com.gmail.nossr50.mcMMO.databaseManager" is null
30.08 23:02:58 [Server] INFO at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:397) ~[?:?] {}
30.08 23:02:58 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[forge-1.18.2-40.1.73-universal.jar%23241!/:?] {re:mixin,re:classloading,re:mixin,re:mixin,re:mixin}
30.08 23:02:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:475) ~[forge-1.18.2-40.1.73-universal.jar%23241!/:?] {re:classloading}
30.08 23:02:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[forge-1.18.2-40.1.73-universal.jar%23241!/:?] {re:classloading}
30.08 23:02:58 [Server] INFO at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:298) ~[?:?] {}
30.08 23:02:58 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.1.73-universal.jar%23241!/:?] {re:mixin,re:classloading,re:mixin,re:mixin,re:mixin}
30.08 23:02:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:450) ~[forge-1.18.2-40.1.73-universal.jar%23241!/:?] {re:classloading}
30.08 23:02:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge-1.18.2-40.1.73-universal.jar%23241!/:?] {re:classloading}
30.08 23:02:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[forge-1.18.2-40.1.73-universal.jar%23241!/:7e29f765-296df566-9fb885e8] {re:classloading}
30.08 23:02:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[forge-1.18.2-40.1.73-universal.jar%23241!/:7e29f765-296df566-9fb885e8] {re:classloading}
30.08 23:02:58 [Server] INFO at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:452) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
30.08 23:02:58 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:361) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
30.08 23:02:58 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:244) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
30.08 23:02:58 [Server] INFO at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:761) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
30.08 23:02:58 [Server] INFO at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:254) ~[server-1.18.2-20220404.173914-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
30.08 23:02:58 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}

If more info is needed I'll get it for ya.

**Comment by Chew** [comment]
More than likely this is a magma issue, which aren't supported. Try testing on Paper and see if you have issues.

**Comment by DedanKaze** [comment]
Thank you for the quick reply! I shall try, thank you.

**Comment by JustRed23** [comment]
I don't think that this is a magma issue.
This part is interesting: "30.08 23:02:58 [Server] Server thread/ERROR [co.gm.no.mcMMO/]: [mcMMO] Cannot read /plugins/mcMMO/experience.yml(File Permissions?)"
Check if you have valid read and write perms in your plugins directory

**Comment by JustRed23** [comment]
Nvm, this was indeed a magma issue, I just fixed this so future versions of magma will have full support for mcMMO.

**Comment by JustRed23** [comment]
See [PR](https://git.magmafoundation.org/magmafoundation/Magma-1-16-x/-/merge_requests/42)
