### ISSUE TITLE
could not load mcmmo

### ISSUE THREAD

**Issue by MTZoom** [mcMMO-Dev/mcMMO#4831]
works perfect with 1.18.2 purpur, but not with 1.19.2 purpur
console:
`[22:35:10 ERROR]: Could not load 'plugins/mcMMO2.1.217.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: JVMCFRE113 unexpected EOF; class=com/gmail/nossr50/mcMMOPlugin, offset=5968
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:417) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:325) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:453) ~[purpur-1.19.2.jar:git-Purpur-1799]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.19.2.jar:git-Purpur-1799]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1799]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1799]
at java.lang.Thread.run(Thread.java:858) ~[?:?]
Caused by: java.lang.ClassFormatError: JVMCFRE113 unexpected EOF; class=com/gmail/nossr50/mcMMOPlugin, offset=5968
at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:?]
at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:471) ~[?:?]
at java.lang.ClassLoader.defineClass(ClassLoader.java:432) ~[?:?]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:221) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1196) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:1111) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:131) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:1094) ~[?:?]
at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:?]
at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:471) ~[?:?]
at java.lang.ClassLoader.defineClass(ClassLoader.java:432) ~[?:?]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:221) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1196) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:1111) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:131) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:1094) ~[?:?]
at java.lang.Class.forNameImpl(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:428) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
... 7 more`

**Comment by MTZoom** [comment]
the problem was in the java version. I upgraded to 18 and everything worked
