### ISSUE TITLE
Error when gaining a level in acrobatics

### ISSUE THREAD

**Issue by EmanuelSimard** [mcMMO-Dev/mcMMO#4877]
[03:16:57 ERROR]: Could not pass event McMMOPlayerXpGainEvent to mcMMO v2.1.218
java.lang.NoClassDefFoundError: Could not initialize class org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftCriteria
        at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:69) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:20) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.initBoard(ScoreboardWrapper.java:73) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.<init>(ScoreboardWrapper.java:62) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.makeNewScoreboard(ScoreboardManager.java:590) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getWrapper(ScoreboardManager.java:471) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.handleXp(ScoreboardManager.java:260) ~[mcMMO.jar:?]
        at com.gmail.nossr50.listeners.SelfListener.onPlayerXp(SelfListener.java:66) ~[mcMMO.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor260.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1923]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.gmail.nossr50.util.EventUtils.handleXpGainEvent(EventUtils.java:386) ~[mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.applyXpGain(McMMOPlayer.java:679) ~[mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginUnsharedXpGain(McMMOPlayer.java:643) ~[mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.player.McMMOPlayer.beginXpGain(McMMOPlayer.java:630) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.skills.SkillUtils.applyXpGain(SkillUtils.java:44) ~[mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.skills.subskills.acrobatics.Roll.rollCheck(Roll.java:221) ~[mcMMO.jar:?]
        at com.gmail.nossr50.datatypes.skills.subskills.acrobatics.Roll.doInteraction(Roll.java:80) ~[mcMMO.jar:?]
        at com.gmail.nossr50.listeners.InteractionManager.processEvent(InteractionManager.java:82) ~[mcMMO.jar:?]
        at com.gmail.nossr50.listeners.EntityListener.onEntityDamage(EntityListener.java:565) ~[mcMMO.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor231.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1923]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at com.Zrips.CMI.Modules.FlightCharge.FlightListener.PlayerMoveEvent2(FlightListener.java:122) ~[CMI-9.3.0.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor578.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1923]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1661) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by EmanuelSimard** [comment]
MC Server: 1.19.3
PurPur build 1923

**Comment by EmanuelSimard** [comment]
More information:

[03:23:45 INFO]: Qalinox issued server command: /mcmmo:stats
[03:23:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mcmmo:stats' in plugin mcMMO v2.1.218
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:926) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftCriteria
        at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:69) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at org.bukkit.craftbukkit.v1_19_R2.scoreboard.CraftScoreboard.registerNewObjective(CraftScoreboard.java:20) ~[purpur-1.19.3.jar:git-Purpur-1923]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.initBoard(ScoreboardWrapper.java:73) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardWrapper.<init>(ScoreboardWrapper.java:62) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.makeNewScoreboard(ScoreboardManager.java:590) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.getWrapper(ScoreboardManager.java:471) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.scoreboards.ScoreboardManager.enablePlayerStatsScoreboard(ScoreboardManager.java:340) ~[mcMMO.jar:?]
        at com.gmail.nossr50.commands.player.McstatsCommand.onCommand(McstatsCommand.java:37) ~[mcMMO.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by EmanuelSimard** [comment]
The only things we modified in the MCMMO configs was the exp given from mobs. 

Here's an image of all the plugins on the server currently:
<img width="493" alt="Screenshot 2023-03-13 at 3 26 59 AM" src="https://user-images.githubusercontent.com/26827533/224634468-ee2ac130-759c-4508-aefe-5f15350ce389.png">
