### ISSUE TITLE
McMMO not working with Land Claim Plugin

### ISSUE THREAD

**Issue by walkendeath** [mcMMO-Dev/mcMMO#4905]
Hello,

I set up a server with several plugins and it worked fine till i added XClaim. If this is on the server Mc just cant start. The Log looks like this:

[18:16:51 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'mcrank' in plugin mcMMO v2.1.220 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.20.1.jar:git-Paper-19]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-19]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2298) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2258) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-19]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

I have no clue what to do. Maybe you guys can help me.

**Comment by Warriorrrr** [comment]
Provide your full server startup log, that stacktrace alone is not enough info

**Comment by walkendeath** [comment]
Sure

`[18:51:11] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:51:12] [ServerMain/INFO]: Loaded 7 recipes
[18:51:13] [Server thread/INFO]: Starting minecraft server version 1.20.1
[18:51:13] [Server thread/INFO]: Loading properties
[18:51:13] [Server thread/INFO]: This server is running Paper version git-Paper-19 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 837cc25)
[18:51:13] [Server thread/INFO]: Server Ping Player Sample Count: 12
[18:51:13] [Server thread/INFO]: Using 4 threads for Netty based IO
[18:51:13] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[18:51:13] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 28 worker threads, and gen parallelism of 28 threads
[18:51:13] [Server thread/INFO]: Default game type: SURVIVAL
[18:51:13] [Server thread/INFO]: Generating keypair
[18:51:13] [Server thread/INFO]: Starting Minecraft server on 134.255.209.104:15800
[18:51:13] [Server thread/INFO]: Using epoll channel type
[18:51:13] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[18:51:13] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[18:51:14] [Server thread/INFO]: [SpigotLibraryLoader] [DeathChest] Loading 1 libraries... please wait
[18:51:14] [Server thread/INFO]: [SpigotLibraryLoader] [DeathChest] Loaded library /mnt/minecraftbukkit/libraries/org/apache/commons/commons-text/1.9/commons-text-1.9.jar
[18:51:14] [Server thread/INFO]: [Minepacks] PCGF-PluginLib not installed. Switching to standalone mode!
[18:51:14] [Server thread/INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.88
[18:51:14] [Server thread/INFO]: [Vault] Loading server plugin Vault v1.7.3-b131
[18:51:14] [Server thread/INFO]: [Essentials] Loading server plugin Essentials v2.20.0
[18:51:14] [Server thread/INFO]: [Core] Loading server plugin Core v0.5.9
[18:51:14] [Server thread/INFO]: [Core] Checking update for Core v0.5.9
[18:51:14] [Server thread/INFO]: [LevelledMobs] Loading server plugin LevelledMobs v3.10.3 b763
[18:51:14] [Server thread/INFO]: [XC] Loading server plugin XClaim v1.10.5
[18:51:14] [Server thread/INFO]: [mcMMO] Loading server plugin mcMMO v2.1.220
[18:51:14] [Server thread/INFO]: [DeathChest] Loading server plugin DeathChest v1.5.24
[18:51:14] [Server thread/INFO]: [Bank] Loading server plugin Bank v4.6.3-RELEASE
[18:51:14] [Server thread/INFO]: [Core] Checking update for Bank v4.6.3-RELEASE
[18:51:14] [Server thread/INFO]: [Core] Attempting to load default ItemUtils
[18:51:14] [Server thread/INFO]: [Core] Loaded default, enjoy :)
[18:51:15] [Server thread/INFO]: [Bank] Block loaded
[18:51:15] [Server thread/INFO]: [Bank] Sign loaded
[18:51:15] [Server thread/INFO]: [Bank] Headdb loaded
[18:51:15] [Server thread/INFO]: [Bank] Bank loaded
[18:51:15] [Server thread/INFO]: [Minepacks] Loading server plugin Minepacks v2.4.20.4
[18:51:15] [Server thread/INFO]: [BackpackPlus] Loading server plugin BackpackPlus v0.0.4
[18:51:15] [Server thread/INFO]: [Sleeper] Loading server plugin Sleeper v1.4.4
[18:51:15] [Server thread/INFO]: [MobMoney] Loading server plugin MobMoney v4.0.0
[18:51:15] [Server thread/INFO]: [EssentialsProtect] Loading server plugin EssentialsProtect v2.19.7
[18:51:15] [Server thread/INFO]: [EzChestShop] Loading server plugin EzChestShop v1.5.9
[18:51:15] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:51:15] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.88
[18:51:15] [Server thread/INFO]:         __    
[18:51:15] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.88
[18:51:15] [Server thread/INFO]:   |___ |      Running on Bukkit - Paper
[18:51:15] [Server thread/INFO]: 
[18:51:15] [Server thread/INFO]: [LuckPerms] Loading configuration...
[18:51:15] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[18:51:16] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[18:51:16] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[18:51:16] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1182ms)
[18:51:16] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[18:51:16] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[18:51:16] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[18:51:16] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[18:51:16] [Server thread/INFO]: [LuckPerms] Registered Vault permission & chat hook.
[18:51:16] [Server thread/INFO]: [Core] Enabling Core v0.5.9
[18:51:16] [Server thread/INFO]: Preparing level "world"
[18:51:16] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[18:51:16] [Server thread/INFO]: Time elapsed: 150 ms
[18:51:16] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[18:51:16] [Server thread/INFO]: Time elapsed: 16 ms
[18:51:16] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[18:51:16] [Server thread/INFO]: Time elapsed: 12 ms
[18:51:16] [Server thread/INFO]: [Essentials] Enabling Essentials v2.20.0
[18:51:17] [Server thread/ERROR]: [Essentials] You are running an unsupported server version!
[18:51:17] [Server thread/WARN]: [Essentials] Version mismatch! Please update EssentialsProtect to the same version.
[18:51:17] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[18:51:17] [Server thread/INFO]: [Essentials] No kits found to migrate.
[18:51:17] [Server thread/INFO]: [Essentials] Loaded 38132 items from items.json.
[18:51:17] [Server thread/INFO]: [Essentials] Using locale en
[18:51:17] [Server thread/INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[18:51:17] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[18:51:17] [Server thread/INFO]: [Vault] [Economy] Essentials Economy hooked.
[18:51:17] [Server thread/INFO]: [Essentials] Using Vault based permissions (LuckPerms)
[18:51:17] [Server thread/INFO]: [LevelledMobs] Enabling LevelledMobs v3.10.3 b763
[18:51:17] [Server thread/INFO]: LevelledMobs: Using NMS version v1_20_R1 for nametag support
[18:51:17] [Server thread/INFO]: LevelledMobs: File Loader: Loading files...
[18:51:17] [Server thread/INFO]: LevelledMobs: File Loader: Loading file 'rules.yml'...
[18:51:17] [Server thread/INFO]: LevelledMobs: File Loader: Loading file 'settings.yml'...
[18:51:17] [Server thread/INFO]: LevelledMobs: File Loader: Loading file 'messages.yml'...
[18:51:17] [Server thread/INFO]: LevelledMobs: Listeners: Registering event listeners...
[18:51:17] [Server thread/INFO]: LevelledMobs: Commands: Registering commands...
[18:51:17] [Server thread/INFO]: LevelledMobs: Running misc procedures
[18:51:17] [Server thread/INFO]: LevelledMobs: Tasks: Starting async nametag auto update task...
[18:51:17] [Server thread/INFO]: LevelledMobs: File Loader: Loading file 'customdrops.yml'...
[18:51:18] [Server thread/INFO]: LevelledMobs: Start-up complete (took 296ms)
[18:51:18] [Server thread/INFO]: [XC] Enabling XClaim v1.10.5
[18:51:18] [Server thread/INFO]: [XC] Locating JAR file
[18:51:18] [Server thread/INFO]: [XC] Checking for Dynmap
[18:51:18] [Server thread/INFO]: [XC] Loading trusted players
[18:51:18] [Server thread/INFO]: [XC] Loading claims
[18:51:18] [Server thread/INFO]: [XC] Unpacking claims
[18:51:18] [Server thread/INFO]: [XC] Initializing chunk editor
[18:51:18] [Server thread/INFO]: [XC] Loading command manager
[18:51:18] [Server thread/INFO]: [XC] Registering default commands
[18:51:18] [Server thread/INFO]: [org.reflections.Reflections] Reflections took 62 ms to scan 1 urls, producing 6 keys and 26 values
[18:51:18] [Server thread/INFO]: [XC] Starting movement routine
[18:51:18] [Server thread/INFO]: [XC] Refreshing grace routine
[18:51:18] [Server thread/INFO]: [XC] Done
[18:51:18] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.220
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: config.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: config.yml to defaults/config.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: config.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: config.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [Debug] No errors found in config.yml!
[18:51:18] [Server thread/INFO]: [mcMMO] Loading locale from plugins/mcMMO/locales/locale_override.properties
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: advanced.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: advanced.yml to defaults/advanced.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: advanced.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: advanced.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [Debug] No errors found in advanced.yml!
[18:51:18] [Server thread/INFO]: [mcMMO] Platform String: 1.20.1-R0.1-SNAPSHOT
[18:51:18] [Server thread/INFO]: [mcMMO] Minecraft version determined to be - 1.20.1
[18:51:18] [Server thread/INFO]: [mcMMO] Loading compatibility layers...
[18:51:18] [Server thread/INFO]: [mcMMO] Finished loading compatibility layers.
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: persistent_data.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: persistent_data.yml to defaults/persistent_data.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: persistent_data.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: persistent_data.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [Debug] No errors found in persistent_data.yml!
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: upgrades_overhaul.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: upgrades_overhaul.yml to defaults/upgrades_overhaul.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: upgrades_overhaul.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: upgrades_overhaul.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: treasures.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: treasures.yml to defaults/treasures.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: treasures.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: treasures.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: fishing_treasures.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: fishing_treasures.yml to defaults/fishing_treasures.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: fishing_treasures.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: fishing_treasures.yml
[18:51:18] [Server thread/INFO]: [mcMMO] Registering enchantments for Fishing Book...
[18:51:18] [Server thread/INFO]: [mcMMO] Loading mcMMO potions.yml File...
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: coreskills.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: coreskills.yml to defaults/coreskills.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: coreskills.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: coreskills.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: sounds.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: sounds.yml to defaults/sounds.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: sounds.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: sounds.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: skillranks.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: skillranks.yml to defaults/skillranks.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: skillranks.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: skillranks.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: child.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: child.yml to defaults/child.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: child.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: child.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: repair.vanilla.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: repair.vanilla.yml to defaults/repair.vanilla.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: repair.vanilla.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: repair.vanilla.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: salvage.vanilla.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: salvage.vanilla.yml to defaults/salvage.vanilla.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: salvage.vanilla.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: salvage.vanilla.yml
[18:51:18] [Server thread/INFO]: [mcMMO] (plugins/mcMMO/flatfile/mcmmo.users) Validating database file..
[18:51:18] [Server thread/INFO]: [mcMMO] Enabling Acrobatics Skills
[18:51:18] [Server thread/INFO]: [mcMMO] Registered subskill: Roll
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Initializing config: experience.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: experience.yml to defaults/experience.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: experience.yml
[18:51:18] [Server thread/INFO]: [mcMMO] [config] Config initialized: experience.yml
[18:51:19] [Server thread/INFO]: [mcMMO] 0 entries in mcMMO World Blacklist
[18:51:19] [Server thread/INFO]: [mcMMO] [config] Initializing config: chat.yml
[18:51:19] [Server thread/INFO]: [mcMMO] [config] Copying default config to disk: chat.yml to defaults/chat.yml
[18:51:19] [Server thread/INFO]: [mcMMO] [config] Loading config from disk: chat.yml
[18:51:19] [Server thread/INFO]: [mcMMO] [config] Config initialized: chat.yml
[18:51:19] [Server thread/ERROR]: Error occurred while enabling mcMMO v2.1.220 (Is it up to date?)
java.lang.NoSuchMethodError: 'io.papermc.paper.threadedregions.scheduler.AsyncScheduler org.bukkit.Bukkit.getAsyncScheduler()'
	at com.gmail.nossr50.mcmmo.acf.ACFFoliaScheduler.createLocaleTask(ACFFoliaScheduler.java:51) ~[mcMMO.jar:?]
	at com.gmail.nossr50.mcmmo.acf.BukkitCommandManager.<init>(BukkitCommandManager.java:132) ~[mcMMO.jar:?]
	at com.gmail.nossr50.commands.CommandManager.<init>(CommandManager.java:32) ~[mcMMO.jar:?]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:319) ~[mcMMO.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-19]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-19]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.20.1.jar:git-Paper-19]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-19]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:51:19] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.1.220
[18:51:19] [Server thread/INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[18:51:19] [Server thread/INFO]: [DeathChest] Enabling DeathChest v1.5.24
[18:51:19] [Server thread/INFO]: [DeathChest] 0 death chests loaded.
[18:51:19] [Server thread/INFO]: [Bank] Enabling Bank v4.6.3-RELEASE
[18:51:19] [Server thread/INFO]: [Bank] Bank Enabled
[18:51:19] [Server thread/INFO]: [Minepacks] Enabling Minepacks v2.4.20.4
[18:51:19] [Server thread/INFO]: [Minepacks] Starting Minepacks in standalone mode!
[18:51:19] [Server thread/INFO]: [Minepacks] Config file successfully loaded.
[18:51:19] [Server thread/INFO]: [Minepacks] Language file successfully loaded. Language: english  Author: GeorgH93
[18:51:19] [Server thread/INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Starting...
[18:51:19] [Server thread/INFO]: [at.pcgamingfreaks.MinepacksStandalone.libs.com.zaxxer.hikari.HikariDataSource] Minepacks-Connection-Pool - Start completed.
[18:51:19] [Server thread/INFO]: [Minepacks]  Minepacks has been enabled!  :) 
[18:51:19] [Server thread/INFO]: [BackpackPlus] Enabling BackpackPlus v0.0.4
[18:51:19] [Server thread/INFO]: [BackpackPlus] Successfully connected to the database
[18:51:19] [Server thread/INFO]: [Sleeper] Enabling Sleeper v1.4.4
[18:51:19] [Server thread/INFO]: [Sleeper] Sleeper Version 1.4.4 Has Been Enabled!
[18:51:19] [Server thread/INFO]: [MobMoney] Enabling MobMoney v4.0.0
[18:51:19] [Server thread/WARN]: [MobMoney] Could not save strikeSystem.sample.yml to plugins/MobMoney/strikeSystem.sample.yml because strikeSystem.sample.yml already exists.
[18:51:19] [Server thread/WARN]: [MobMoney] Could not save English.yml to plugins/MobMoney/language/English.yml because English.yml already exists.
[18:51:19] [Server thread/WARN]: [MobMoney] Could not save Spanish.yml to plugins/MobMoney/language/Spanish.yml because Spanish.yml already exists.
[18:51:19] [Server thread/WARN]: [MobMoney] Could not save Dutch.yml to plugins/MobMoney/language/Dutch.yml because Dutch.yml already exists.
[18:51:19] [Server thread/WARN]: [MobMoney] Could not save Chinese.yml to plugins/MobMoney/language/Chinese.yml because Chinese.yml already exists.
[18:51:19] [Server thread/WARN]: [MobMoney] Could not save Catalan.yml to plugins/MobMoney/language/Catalan.yml because Catalan.yml already exists.
[18:51:19] [Server thread/WARN]: [MobMoney] Could not save Valencian.yml to plugins/MobMoney/language/Valencian.yml because Valencian.yml already exists.
[18:51:19] [Server thread/INFO]: [EssentialsProtect] Enabling EssentialsProtect v2.19.7
[18:51:19] [Server thread/INFO]: [EssentialsProtect] Continuing to enable Protect.
[18:51:19] [Server thread/WARN]: [EssentialsProtect] Version mismatch! Please update all Essentials jars to the same version.
[18:51:19] [Server thread/INFO]: [EssentialsProtect] Starting Metrics. Opt-out using the global bStats config.
[18:51:19] [Server thread/INFO]: [EzChestShop] Enabling EzChestShop v1.5.9
[18:51:19] [Server thread/INFO]: [EzChestShop] Enabling EzChestShop - version 1.5.9
[18:51:19] [Server thread/INFO]: [EzChestShop] Initializing SQLite database...
[18:51:19] [Server thread/INFO]: [EzChestShop] SQLite database initialized!
[18:51:19] [Server thread/INFO]: [EzChestShop] Current Protocol version initialized.
[18:51:19] [Server thread/INFO]: [EzChestShop] Locale_EN successfully loaded
[18:51:20] [Server thread/INFO]: Starting GS4 status listener
[18:51:20] [Server thread/INFO]: Thread Query Listener started
[18:51:20] [Query Listener #1/INFO]: Query running on 134.255.209.104:15801
[18:51:20] [Server thread/INFO]: Running delayed init tasks
[18:51:20] [Craft Scheduler Thread - 3 - Essentials/INFO]: [Essentials] Fetching version information...
[18:51:20] [Server thread/INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[18:51:20] [Server thread/INFO]: [XC] Saving claims
[18:51:20] [Server thread/INFO]: [XC] Created new claims.yml
[18:51:20] [Server thread/INFO]: Done (7.088s)! For help, type "help"
[18:51:20] [Server thread/INFO]: Timings Reset
[18:51:20] [Craft Scheduler Thread - 6 - Vault/INFO]: [Vault] Checking for Updates ... 
[18:51:20] [Craft Scheduler Thread - 5 - BackpackPlus/INFO]: [BackpackPlus] §cPlugin has an update. (§6Beta§c)
[18:51:20] [Craft Scheduler Thread - 6 - Vault/INFO]: [Vault] No new version available
[18:51:25] [User Authenticator #0/INFO]: UUID of player Walkendeath is 1186b7a4-9f50-46ac-ac99-2eb5d4c7113b
[18:51:28] [Bank - Loader Thread/INFO]: [Bank] Loading 1186b7a4-9f50-46ac-ac99-2eb5d4c7113b
[18:51:28] [Bank - Loader Thread/INFO]: [Bank] Loaded 1186b7a4-9f50-46ac-ac99-2eb5d4c7113b after 20ms
[18:51:28] [Server thread/INFO]: Walkendeath[/95.223.228.203:18813] logged in with entity id 230 at ([world]-154.84188771301248, 77.0, -71.47639497130893)
[18:51:28] [Server thread/INFO]: Willkomen zurück, Walkendeath
[18:51:36] [Server thread/INFO]: Walkendeath issued server command: /plugins
[18:51:39] [Server thread/INFO]: Walkendeath lost connection: Disconnected
[18:51:39] [Bank - Loader Thread/INFO]: [Bank] Saving 1186b7a4-9f50-46ac-ac99-2eb5d4c7113b
[18:51:39] [Bank - Loader Thread/INFO]: [Bank] Saved 1186b7a4-9f50-46ac-ac99-2eb5d4c7113b after 6ms
[18:51:39] [Server thread/INFO]: Walkendeath left the game

**Comment by Warriorrrr** [comment]
This is an issue caused by ACF, the command library that mcmmo uses, it's trying to use a folia compatible scheduler on a paper server. You can update paper to the latest build (since that includes folia's scheduling api now) to fix it, but ideally it should still work on lower versions

**Comment by nossr50** [comment]
> This is an issue caused by ACF, the command library that mcmmo uses, it's trying to use a folia compatible scheduler on a paper server. You can update paper to the latest build (since that includes folia's scheduling api now) to fix it, but ideally it should still work on lower versions

I think we only have a few commands using ACF (2 or 3), I should probably just remove ACF if there's no workaround

**Comment by walkendeath** [comment]
Sorry for the late response, i just updated paper. But unfortunately it is still not working. Anything else i could do?

**Comment by walkendeath** [comment]
It is working. Thank you :)
