### ISSUE TITLE
BlockBreak Error

### ISSUE THREAD

**Issue by red0fireus** [mcMMO-Dev/mcMMO#4922]
`[03:16:07 ERROR]: Could not pass event BlockBreakEvent to mcMMO v2.1.222
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge-1.20.1-47.1.59-universal.jar%23178!/:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.1.59-universal.jar%23178!/:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:600) ~[forge-1.20.1-47.1.59-universal.jar%23178!/:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:584) ~[forge-1.20.1-47.1.59-universal.jar%23178!/:?]
        at com.mohistmc.eventhandler.dispatcher.BlockEventDispatcher.onBlockBreak(BlockEventDispatcher.java:99) ~[forge-1.20.1-47.1.59-universal.jar%23178!/:?]
        at com.mohistmc.eventhandler.dispatcher.__BlockEventDispatcher_onBlockBreak_BreakEvent.invoke(.dynamic) ~[forge-1.20.1-47.1.59-universal.jar%23178!/:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2381!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:318) ~[eventbus-6.0.5.jar%2381!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:298) ~[eventbus-6.0.5.jar%2381!/:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:543) ~[forge-1.20.1-47.1.59-universal.jar%23178!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:319) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_215116_(ServerPlayerGameMode.java:305) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_214168_(ServerPlayerGameMode.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:1468) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1028) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:171) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1011) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1005) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:991) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:910) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:280) ~[server-1.20.1-20230612.114412-srg.jar%23173!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2312 out of bounds for length 1402
        at com.gmail.nossr50.util.text.StringUtils.getFriendlyConfigBlockDataString(StringUtils.java:104) ~[?:?]
        at com.gmail.nossr50.config.experience.ExperienceConfig.doesBlockGiveSkillXP(ExperienceConfig.java:400) ~[?:?]
        at com.gmail.nossr50.util.BlockUtils.affectedByGreenTerra(BlockUtils.java:155) ~[?:?]
        at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:376) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor140.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge-1.20.1-47.1.59-universal.jar%23178!/:?]
        ... 29 more`

**Comment by Greymagic27** [comment]
Forge support isn't there yet. Using magma has no garunteed compatiablity
