### ISSUE TITLE
Could not pass event BlockDamageEvent (Needs update for latest Paper).

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO#4928]
Getting spammed really heavily with this:
Everyone complaining that tree feller is basically broken lol.
McMMO needs update for latest Paper.

```
[14:54:53] [Server thread/INFO]: Could not pass event BlockDamageEvent to mcMMO v2.1.222
[14:54:53] [Server thread/WARN]: java.lang.NoSuchMethodError: 'void org.bukkit.event.block.BlockDamageEvent.<init>(org.bukkit.entity.Player, org.bukkit.block.Block, org.bukkit.inventory.ItemStack, boolean)'
[14:54:53] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.events.fake.FakeBlockDamageEvent.<init>(FakeBlockDamageEvent.java:13)
[14:54:53] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.util.EventUtils.simulateBlockBreak(EventUtils.java:344)
[14:54:53] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.util.EventUtils.simulateBlockBreak(EventUtils.java:330)
[14:54:53] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.listeners.BlockListener.onBlockDamageHigher(BlockListener.java:652)
[14:54:53] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor338.execute(Unknown Source)
[14:54:53] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[14:54:53] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[14:54:53] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:54:53] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:54:53] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:54:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[14:54:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callBlockDamageEvent(CraftEventFactory.java:658)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:261)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1927)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1287)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1175)
[14:54:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[14:54:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
```

McMMO 2.1.222
Paper 1.20.1 Build 161

Looks like something in paper, as a rollback to paper 1.20.1 Build 145 fixes it.
I am unsure which commit between 145 to 161 broke it.

**Comment by Strahilchu** [comment]
Same here!

**Comment by andrewkm** [comment]
Fixed via latest Paper build.
