### ISSUE TITLE
Error when touching Leaves with Axe (BlockDamageEvent)

### ISSUE THREAD

**Issue by Strahilchu** [mcMMO-Dev/mcMMO#4929]
McMMO 2.1.222
Purpur 2044

Plugins:
- AdvancedPortals, ajLeaderboards, ArtMap, AuctionHouse, AutomatedCrafting, Autorank, BetterTridents, BigDoors, BlockParticles, BottledExp, Brewery, ChestCleaner, ChestShop, CMI, CMILib, CommandPanels, CoreProtect, DiscordSRV, dynmap, Dynmap-WorldGuard, Elevator, ExcellentCrates, FreedomChat, HeadDatabase, ImageMaps, **Jobs**, Lands, LuckPerms, mcMMO, MobFarmManager, NexEngine, Not-Too-Expensive, PlaceholderAPI, ProtocolLib, Quests, SafariNet, ShopGUIPlus, SimpleScore, **SmoothTimber**, spark, SurvivalInvisiframes, TempFly, TryMe, Vault, Vehicles, **VeinMiner**, Vulcan, WorldEdit, WorldGuard

[11:13:05 ERROR]: Could not pass event BlockDamageEvent to mcMMO v2.1.222
java.lang.NoSuchMethodError: 'void org.bukkit.event.block.BlockDamageEvent.<init>(org.bukkit.entity.Player, org.bukkit.block.Block, org.bukkit.inventory.ItemStack, boolean)'
        at com.gmail.nossr50.events.fake.FakeBlockDamageEvent.<init>(FakeBlockDamageEvent.java:13) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.EventUtils.simulateBlockBreak(EventUtils.java:344) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.EventUtils.simulateBlockBreak(EventUtils.java:330) ~[mcMMO.jar:?]
        at com.gmail.nossr50.listeners.BlockListener.onBlockDamageHigher(BlockListener.java:652) ~[mcMMO.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor300.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2044]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callBlockDamageEvent(CraftEventFactory.java:667) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:261) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:2010) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2044]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by Chew** [comment]
This is a Paper bug, you'll need to revert to a working build until they fix it. In your case, you'd have to wait until Purpur pulls in the change or fixes it themselves.

Per nossr:

> Paper Bug 🐛 
> The latest Paper binary is currently missing some API for `BlockDamageEvent`, which will result in some errors when running mcMMO with the latest Paper, I have informed Paper devs about the issue and they are working on it, for now you can roll back your paper version or wait for their patch.

> For those on other server software, you can ignore this message.
