### ISSUE TITLE
Tree Feller not working for me

### ISSUE THREAD

**Issue by TheFishNextDoor** [mcMMO-Dev/mcMMO#4931]
Tree feller makes the sound but does not break additional logs.

Latest Purpur 1.20.1

Plugins: ArmorStandAdjustor, AuctionHouse, BetterRTP, ChestCommands, ChestShop, Chunky, Citizens, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, floodgate, Geyser-Spigot, GPFlags, GriefPrevention, GSit, HeadDatabase, HolographicDisplays, InfiniteJump, InteractiveChat, ItemEdit, Jobs, Leashable, LuckPerms, mcMMO, MiniMOTD, Multiverse-Core, Multiverse-NetherPortals, NexEngine, PlaceholderAPI, Plan, PlayerWarps, ProtocolLib, spark, Spartan, SpawnerLagFix, Terra, TerraformGenerator, TradeSystem, UnbreakableLeashes, Vault, VehicleTeleportation, VotifierPlus, VotingPlugin, WorldEdit, WorldGuard

28.08 18:31:52 [Server] ERROR Could not pass event BlockBreakEvent to mcMMO v2.1.223
28.08 18:31:52 [Server] INFO java.lang.NoSuchMethodError: 'void org.bukkit.event.block.BlockDamageEvent.<init>(org.bukkit.entity.Player, org.bukkit.block.Block, org.bukkit.inventory.ItemStack, boolean)'
28.08 18:31:54 [Server] INFO at com.gmail.nossr50.events.fake.FakeBlockDamageEvent.<init>(FakeBlockDamageEvent.java:13) ~[mcMMO.jar:?]
28.08 18:31:54 [Server] INFO at com.gmail.nossr50.util.EventUtils.simulateBlockBreak(EventUtils.java:344) ~[mcMMO.jar:?]
28.08 18:31:54 [Server] INFO at com.gmail.nossr50.skills.woodcutting.WoodcuttingManager.dropTreeFellerLootFromBlocks(WoodcuttingManager.java:282) ~[mcMMO.jar:?]
28.08 18:31:54 [Server] INFO at com.gmail.nossr50.skills.woodcutting.WoodcuttingManager.processTreeFeller(WoodcuttingManager.java:123) ~[mcMMO.jar:?]
28.08 18:31:54 [Server] INFO at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:413) ~[mcMMO.jar:?]
28.08 18:31:54 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor280.execute(Unknown Source) ~[?:?]
28.08 18:31:54 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
28.08 18:31:54 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2042]
28.08 18:31:54 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
28.08 18:31:54 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2042]
28.08 18:31:54 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2042]
28.08 18:31:54 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
28.08 18:31:54 [Server] INFO at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
28.08 18:31:54 [Server] INFO at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
28.08 18:31:54 [Server] INFO at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:301) ~[?:?]
28.08 18:31:54 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:2010) ~[?:?]
28.08 18:31:54 [Server] INFO at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
28.08 18:31:59 [Server] INFO at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
28.08 18:31:59 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
28.08 18:31:59 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2042]
28.08 18:31:59 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
28.08 18:31:59 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
28.08 18:31:59 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2042]
28.08 18:31:59 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2042]
28.08 18:31:59 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
28.08 18:31:59 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2042]
28.08 18:31:59 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2042]
28.08 18:31:59 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
28.08 18:31:59 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2042]
28.08 18:31:59 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2042]
28.08 18:31:59 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2042]
28.08 18:31:59 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Warriorrrr** [comment]
Purpur version 2042 is in fact not the latest one, update to the actual latest one and the issue will be fixed.
