### ISSUE TITLE
locale error when using 1.20.2

### ISSUE THREAD

**Issue by Legoman99573** [mcMMO-Dev/mcMMO#4941]
How to reproduce:
1. Join the server
2. Error will print upon joining the server. Plugin still functions like normal otherwise

Paper version: 
`git-Paper-206 (MC: 1.20.2)`

Error:
```applescript
[10:20:00 INFO]: [mcMMO] [ACF] Can't read players locale, you will be unable to automatically detect players language. Only Bukkit 1.7+ is supported for this.
[10:20:00 INFO]: [mcMMO] [ACF] java.lang.NoSuchFieldException: locale
[10:20:00 INFO]: [mcMMO] [ACF]  at java.base/java.lang.Class.getDeclaredField(Class.java:2663)
[10:20:00 INFO]: [mcMMO] [ACF]  at mcMMO.jar//com.gmail.nossr50.mcmmo.acf.BukkitCommandManager.readPlayerLocale(BukkitCommandManager.java:324)
[10:20:00 INFO]: [mcMMO] [ACF]  at mcMMO.jar//com.gmail.nossr50.mcmmo.acf.ACFBukkitListener.onPlayerJoin(ACFBukkitListener.java:57)
[10:20:00 INFO]: [mcMMO] [ACF]  at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[10:20:00 INFO]: [mcMMO] [ACF]  at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[10:20:00 INFO]: [mcMMO] [ACF]  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:20:00 INFO]: [mcMMO] [ACF]  at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[10:20:00 INFO]: [mcMMO] [ACF]  at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[10:20:00 INFO]: [mcMMO] [ACF]  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.server.players.PlayerList.a(PlayerList.java:325)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[10:20:00 INFO]: [mcMMO] [ACF]  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[10:20:00 INFO]: [mcMMO] [ACF]  at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by andrewkm** [comment]
Same issue here @nossr50

**Comment by nossr50** [comment]
Looks to be an issue in ACF, I'd report it to them and once a fix is deployed on their end I will update mcMMO

**Comment by chickeneer** [comment]
I have wrote a fix on the ACF side of things. I don't have 1.20.2 setup to test yet, just let me know if there is still an issue :)

**Comment by andrewkm** [comment]
Compiling mcMMO again didn't fix it for me, perhaps this requires @nossr50 to make some changes on the mcMMO side.

**Comment by nakanotti** [comment]
@chickeneer 
> I have wrote a fix on the ACF side of things. I don't have 1.20.2 setup to test yet, just let me know if there is still an issue :)

Thank you for your fix code.
I tried it on 1.20.2.
https://github.com/aikar/commands/issues/402#issuecomment-1742526429

**Comment by andrewkm** [comment]
Thank you @nossr50 and @chickeneer 
This issue is now fixed for me :)

**Comment by Legoman99573** [comment]
I guess this can be closed since it was resolved with https://github.com/aikar/commands/commit/26d72f27c6dd455d047d3aa5c8f4cf89124cf139 and just requires re-compiling to fix it.

**Comment by Ger9424** [comment]
i have the same issue with 1.20.40 

[Mimic] [ACF] Can't read players locale, you will be unable to automatically detect players language. Only Bukkit 1.7+ is supported for this.
