### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to mcMMO v2.1.224

### ISSUE THREAD

**Issue by Bimmr** [mcMMO-Dev/mcMMO#4943]
Spigot v: 1.19.4

Had player A kill player B unarmed.

```
[10:10:21] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO v2.1.224
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:263) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1071) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:938) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:887) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1105) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2045) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.world.entity.player.EntityHuman.damageEntity0(EntityHuman.java:1028) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1349) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:935) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:979) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1273) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:1920) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.network.PlayerConnection$4.a(PlayerConnection.java:2491) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(SourceFile:166) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:66) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2416) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:53) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1133) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1110) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3748-Spigot-7da74da-01b2e1a]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class com.gmail.nossr50.datatypes.meta.OldName cannot be cast to class com.gmail.nossr50.datatypes.meta.OldName (com.gmail.nossr50.datatypes.meta.OldName is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @7b5ea6c5; com.gmail.nossr50.datatypes.meta.OldName is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @3ebc4b5e)
        at com.gmail.nossr50.util.skills.CombatUtils.fixNames(CombatUtils.java:440) ~[?:?]
        at com.gmail.nossr50.listeners.EntityListener.onEntityDamageMonitor(EntityListener.java:425) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 35 more
```

**Comment by TechnicallyCoded** [comment]
This looks like a plugin depending on mcMMO included the class files into their jar file instead of marking the dependency as "provided" (maven) or "compileOnly" (gradle). That or maybe a hot reload of the plugin but this second one is unlikely.

Probably not mcMMO's fault.

**Comment by Bimmr** [comment]
I can confirm that the error is from reloading the server. Although I did discover an issue with final damage in the EntityDamgeByEntityEvent not matching what mcMMO is showing/doing so I'll create a new ticket for that.
