### ISSUE TITLE
Entity task for mcMMO v2.1.225 generated an exception

### ISSUE THREAD

**Issue by ranminecraft** [mcMMO-Dev/mcMMO#4952]
mcMMO version 2.1.225

This server is running Folia version git-Folia-"edafbce" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: edafbce)
You are running the latest version
Previous version: git-Folia-"372d479" (MC: 1.20.1)

```
[17:52:18] [Region Scheduler Thread #0/WARN]: [mcMMO] Entity task for mcMMO v2.1.225 generated an exception
java.lang.IllegalStateException: Accessing entity state off owning region's thread
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftWarden.getHandle(CraftWarden.java:27) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftWarden.getHandle(CraftWarden.java:12) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftLivingEntity.getHealth(CraftLivingEntity.java:100) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at com.gmail.nossr50.runnables.skills.RuptureTask.applyRupture(RuptureTask.java:82) ~[mcMMO.jar:?]
	at com.gmail.nossr50.runnables.skills.RuptureTask.run(RuptureTask.java:60) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7) ~[mcMMO.jar:?]
	at com.gmail.nossr50.mcmmo.folialib.impl.FoliaImplementation.lambda$runAtEntityTimer$21(FoliaImplementation.java:342) ~[mcMMO.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:168) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:115) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1523) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[17:52:19] [Region Scheduler Thread #0/ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftWarden.getHandle(CraftWarden.java:27) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftWarden.getHandle(CraftWarden.java:12) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftLivingEntity.getHealth(CraftLivingEntity.java:100) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at com.gmail.nossr50.runnables.skills.RuptureTask.applyRupture(RuptureTask.java:82) ~[mcMMO.jar:?]
	at com.gmail.nossr50.runnables.skills.RuptureTask.run(RuptureTask.java:60) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7) ~[mcMMO.jar:?]
	at com.gmail.nossr50.mcmmo.folialib.impl.FoliaImplementation.lambda$runAtEntityTimer$21(FoliaImplementation.java:342) ~[mcMMO.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:168) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:115) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1523) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[17:52:19] [Region Scheduler Thread #0/WARN]: [mcMMO] Entity task for mcMMO v2.1.225 generated an exception
java.lang.IllegalStateException: Accessing entity state off owning region's thread
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftWarden.getHandle(CraftWarden.java:27) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftWarden.getHandle(CraftWarden.java:12) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftLivingEntity.getHealth(CraftLivingEntity.java:100) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at com.gmail.nossr50.runnables.skills.RuptureTask.applyRupture(RuptureTask.java:82) ~[mcMMO.jar:?]
	at com.gmail.nossr50.runnables.skills.RuptureTask.run(RuptureTask.java:60) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7) ~[mcMMO.jar:?]
	at com.gmail.nossr50.mcmmo.folialib.impl.FoliaImplementation.lambda$runAtEntityTimer$21(FoliaImplementation.java:342) ~[mcMMO.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:168) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:115) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1523) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

**Comment by nossr50** [comment]
Fixed in 2.2.019
