### ISSUE TITLE
Exception in newest version

### ISSUE THREAD

**Issue by RobZenFL** [mcMMO-Dev/mcMMO#4975]
Hey, after updating the plugin on the server we get an error message every 10 minutes in the console.

Server: last 1.20.2
mcMMO version: latest (2.1.229)

Error message:
! [Wed 15:47:14 WARN  mcMMO] Task #4096 for mcMMO v2.1.229 generated an exception
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.party.PartyManager.saveParties()" because the return value of "com.gmail.nossr50.mcMMO.getPartyManager()" is null
    at mcMMO.jar//com.gmail.nossr50.runnables.SaveTimerTask.run(SaveTimerTask.java:24)
    at mcMMO.jar//com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20)
    at mcMMO.jar//com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7)
    at mcMMO.jar//com.gmail.nossr50.mcmmo.folialib.impl.SpigotImplementation.lambda$runTimer$4(SpigotImplementation.java:105)
    at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:103)
    at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
    at java.base/java.lang.Thread.run(Thread.java:833)

Thanks for your time and work!

**Comment by IAISI** [comment]
Should be fixed with https://github.com/mcMMO-Dev/mcMMO/commit/cdc187b2117c2427cfa500bc1fb320404bdd75c9 and it's not really harmful as it's not breaking anything, just spams console if Parties are disabled.
