### ISSUE TITLE
Error when enabling mcMMO when using a mySQL database for storage

### ISSUE THREAD

**Issue by thunderlight411** [mcMMO-Dev/mcMMO#4987]
When using a MySQL database the plugin can't be enabled because the column crossbow does not exist.
And i think it will be the same for tridents

Can you please add a alter of this table mcmmo_skills to add those 2 columns

```[18:46:40] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.2.000
[18:46:41] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `crossbows` int(32) unsigned NOT NULL DEFAULT '0'' at line 1
[18:46:41] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[18:46:41] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[18:46:41] [Server thread/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335)
[18:46:41] [Server thread/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2081)
[18:46:41] [Server thread/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1246)
[18:46:41] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:46:41] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.mcmmo.database.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar/jdk.proxy12/jdk.proxy12.$Proxy128.executeUpdate(Unknown Source)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.SQLDatabaseManager.updateStructure(SQLDatabaseManager.java:1045)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.SQLDatabaseManager.checkStructure(SQLDatabaseManager.java:1030)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.SQLDatabaseManager.<init>(SQLDatabaseManager.java:131)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.SQLDatabaseManager.<init>(SQLDatabaseManager.java:54)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.DatabaseManagerFactory.getDatabaseManager(DatabaseManagerFactory.java:31)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:237)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[18:46:41] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[18:46:41] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:46:41] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:46:41] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[18:46:41] [Server thread/WARN]: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `crossbows` int(32) unsigned NOT NULL DEFAULT '0'' at line 1
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.SQLDatabaseManager.updateStructure(SQLDatabaseManager.java:1050)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.SQLDatabaseManager.checkStructure(SQLDatabaseManager.java:1030)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.SQLDatabaseManager.<init>(SQLDatabaseManager.java:131)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.SQLDatabaseManager.<init>(SQLDatabaseManager.java:54)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.DatabaseManagerFactory.getDatabaseManager(DatabaseManagerFactory.java:31)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:237)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[18:46:41] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[18:46:41] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:46:41] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:46:41] [Server thread/WARN]: Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `crossbows` int(32) unsigned NOT NULL DEFAULT '0'' at line 1
[18:46:41] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[18:46:41] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[18:46:41] [Server thread/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335)
[18:46:41] [Server thread/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2081)
[18:46:41] [Server thread/WARN]: 	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1246)
[18:46:41] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[18:46:41] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.mcmmo.database.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar/jdk.proxy12/jdk.proxy12.$Proxy128.executeUpdate(Unknown Source)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.database.SQLDatabaseManager.updateStructure(SQLDatabaseManager.java:1045)
[18:46:41] [Server thread/WARN]: 	... 17 more
[18:46:41] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.2.000
[18:46:41] [Server thread/INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[18:46:41] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.party.PartyManager.saveParties()" because the return value of "com.gmail.nossr50.mcMMO.getPartyManager()" is null
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:387)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290)
[18:46:41] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223)
[18:46:41] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537)
[18:46:41] [Server thread/WARN]: 	at mcMMO_2.2.000.jar//com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:313)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[18:46:41] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[18:46:41] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[18:46:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[18:46:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:46:41] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:46:41] [Server thread/ERROR]: Error occurred while disabling mcMMO v2.2.000
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.database.DatabaseManager.onDisable()" because "com.gmail.nossr50.mcMMO.databaseManager" is null
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:417) ~[mcMMO_2.2.000.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:git-Paper-451]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-451]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:313) ~[mcMMO_2.2.000.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-451]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-451]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-451]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-451]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-451]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by nossr50** [comment]
Technically the code does do that, but I'll try to see why it isn't working for you (and potentially other users).

**Comment by nossr50** [comment]
Fixed
