### ISSUE TITLE
[1.20.1] java.lang.IllegalArgumentException: Invalid record type for Material REDSTONE_WIRE! 

### ISSUE THREAD

**Issue by timmbobb** [mcMMO-Dev/mcMMO#4990]
This warning is getting repeatedly spammed in server logs.

[02Apr2024 18:44:12.148] [Server thread/WARN] [com.gmail.nossr50.mcMMO/]: [mcMMO] Task #1232 for mcMMO v2.1.231 generated an exception
java.lang.IllegalArgumentException: Invalid record type for Material REDSTONE_WIRE!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.1-jre.jar%2336!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftEffect.getDataValue(CraftEffect.java:62) ~[forge-1.20.1-47.2.20-universal.jar%23108!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.playEffect(CraftWorld.java:1071) ~[forge-1.20.1-47.2.20-universal.jar%23108!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftWorld.playEffect(CraftWorld.java:1058) ~[forge-1.20.1-47.2.20-universal.jar%23108!/:?]
	at com.gmail.nossr50.util.skills.ParticleEffectUtils.playBleedEffect(ParticleEffectUtils.java:32) ~[?:?]
	at com.gmail.nossr50.runnables.skills.RuptureTask.playAnimation(RuptureTask.java:76) ~[?:?]
	at com.gmail.nossr50.runnables.skills.RuptureTask.run(RuptureTask.java:59) ~[?:?]
	at com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20) ~[?:?]
	at com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7) ~[?:?]
	at com.gmail.nossr50.mcmmo.folialib.impl.SpigotImplementation.lambda$runAtEntityTimer$9(SpigotImplementation.java:239) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[forge-1.20.1-47.2.20-universal.jar%23108!/:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:408) ~[forge-1.20.1-47.2.20-universal.jar%23108!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1267) ~[server-1.20.1-20230612.114412-srg.jar%23103!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:400) ~[server-1.20.1-20230612.114412-srg.jar%23103!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1201) ~[server-1.20.1-20230612.114412-srg.jar%23103!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:1012) ~[server-1.20.1-20230612.114412-srg.jar%23103!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:285) ~[server-1.20.1-20230612.114412-srg.jar%23103!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by nossr50** [comment]
Thanks for the report, will look into it.

**Comment by nossr50** [comment]
Could not recreate, what version of MC are you using? Spigot, Paper, Folia?

**Comment by nossr50** [comment]
Determined to be using an unsupported MC version

**Comment by timmbobb** [comment]
I was using magma.
