### ISSUE TITLE
A little error

### ISSUE THREAD

**Issue by Ekkoy06** [mcMMO-Dev/mcMMO#4999]
```
[15:52:52 ERROR]: Could not pass event EntityDamageByEntityEvent to mcMMO v2.2.006
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.party.PartyManager.inSameParty(org.bukkit.entity.Player, org.bukkit.entity.Player)" because the return value of "com.gmail.nossr50.mcMMO.getPartyManager()" is null
        at com.gmail.nossr50.util.skills.CombatUtils.shouldBeAffected(CombatUtils.java:935) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.skills.CombatUtils.applyAbilityAoE(CombatUtils.java:782) ~[mcMMO.jar:?]
        at com.gmail.nossr50.skills.swords.SwordsManager.serratedStrikes(SwordsManager.java:162) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.skills.CombatUtils.processSwordCombat(CombatUtils.java:89) ~[mcMMO.jar:?]
        at com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:470) ~[mcMMO.jar:?]
        at com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:388) ~[mcMMO.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor536.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-485]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-485]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-485]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:267) ~[paper-1.20.4.jar:git-Paper-485]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1203) ~[paper-1.20.4.jar:git-Paper-485]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1188) ~[paper-1.20.4.jar:git-Paper-485]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1120) ~[paper-1.20.4.jar:git-Paper-485]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1081) ~[paper-1.20.4.jar:git-Paper-485]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1237) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.world.entity.LivingEntity.actuallyHurt(LivingEntity.java:2243) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1480) ~[?:?]
        at net.minecraft.world.entity.monster.warden.Warden.hurt(Warden.java:545) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1323) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2283) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2787) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2711) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-485]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-485]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Eris7090** [comment]
What version of mcmmo and paper?

**Comment by Ekkoy06** [comment]
![imagine_2024-04-23_212515880](https://github.com/mcMMO-Dev/mcMMO/assets/113153015/9aa58482-8ed6-4403-96db-2f6a26881eae)

**Comment by Eris7090** [comment]
update paper and see if issue persist. I remember at some point they changed how EntityDamage was called so you might still be using the old version of paper and mcmmo is using the new call that isn't there

> ![imagine_2024-04-23_212515880](https://private-user-images.githubusercontent.com/113153015/324951950-9aa58482-8ed6-4403-96db-2f6a26881eae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTcwMjIsIm5iZiI6MTcxMzg5NjcyMiwicGF0aCI6Ii8xMTMxNTMwMTUvMzI0OTUxOTUwLTlhYTU4NDgyLThlZDYtNDQwMy05NmRiLTJmNmEyNjg4MWVhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxODI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjA4ODRiNjg4Njg4MTFhMGNmNDVlZmY3ZTYwMTdmMzY2MTk1MzY3NjUzZTc0ZGJkZTJkZjNlZTcyYWExMDQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.08ogP_7JYs2rsHw3ZB2R33jsLbWUhFUwfVz9ebV9pcw)

**Comment by nossr50** [comment]
This was fixed
