### ISSUE TITLE
mcMMO Failing to start on Fabric Server Running Cardboard

### ISSUE THREAD

**Issue by ChromesDuzez** [mcMMO-Dev/mcMMO#5002]
Just as the title says, mcMMO Failing to start on Fabric Server Running Cardboard and I'm not sure if I can configure it in any way to work or if its just not going to work period.
```
[08:53:45] [Server thread/INFO]: Enabling mcMMO v2.2.006
[08:53:45] [Server thread/INFO]: [D] Initializing config: config.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: config.yml to defaults/config.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: config.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: config.yml
[08:53:45] [Server thread/INFO]: [D] No errors found in config.yml!
[08:53:45] [Server thread/INFO]: [D] Loading locale from plugins/mcMMO/locales/locale_override.properties
[08:53:45] [Server thread/INFO]: [D] Initializing config: advanced.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: advanced.yml to defaults/advanced.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: advanced.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: advanced.yml
[08:53:45] [Server thread/INFO]: [D] No errors found in advanced.yml!
[08:53:45] [Server thread/INFO]: [D] Initializing config: party.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: party.yml to defaults/party.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: party.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: party.yml
[08:53:45] [Server thread/INFO]: [D] No errors found in party.yml!
[08:53:45] [Server thread/INFO]: [D] Initializing config: custom_item_support.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: custom_item_support.yml to defaults/custom_item_support.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: custom_item_support.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: custom_item_support.yml
[08:53:45] [Server thread/INFO]: [D] No errors found in custom_item_support.yml!
[08:53:45] [Server thread/INFO]: [D] Platform String: 1.20.4-R0.1-SNAPSHOT
[08:53:45] [Server thread/INFO]: [D] Minecraft version determined to be - 1.20.4
[08:53:45] [Server thread/INFO]: [D] Loading compatibility layers...
[08:53:45] [Server thread/INFO]: [D] Finished loading compatibility layers.
[08:53:45] [Server thread/INFO]: [D] Initializing config: persistent_data.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: persistent_data.yml to defaults/persistent_data.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: persistent_data.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: persistent_data.yml
[08:53:45] [Server thread/INFO]: [D] No errors found in persistent_data.yml!
[08:53:45] [Server thread/INFO]: [D] Initializing config: upgrades_overhaul.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: upgrades_overhaul.yml to defaults/upgrades_overhaul.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: upgrades_overhaul.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: upgrades_overhaul.yml
[08:53:45] [Server thread/INFO]: [D] Needed upgrades: [ADD_FISHING, ADD_BLAST_MINING_COOLDOWN, ADD_SQL_INDEXES, ADD_MOB_HEALTHBARS, DROP_SQL_PARTY_NAMES, DROP_SPOUT, ADD_ALCHEMY, ADD_UUIDS, ADD_UUIDS_PARTY, ADD_SCOREBOARD_TIPS, DROP_NAME_UNIQUENESS, ADD_SKILL_TOTAL, ADD_UNIQUE_PLAYER_DATA, FIX_SPELLING_NETHERITE_SALVAGE, FIX_SPELLING_NETHERITE_REPAIR, SQL_CHARSET_UTF8MB4]
[08:53:45] [Server thread/INFO]: [D] Initializing config: treasures.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: treasures.yml to defaults/treasures.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: treasures.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: treasures.yml
[08:53:45] [Server thread/INFO]: [D] No errors found in treasures.yml!
[08:53:45] [Server thread/INFO]: [D] Initializing config: fishing_treasures.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: fishing_treasures.yml to defaults/fishing_treasures.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: fishing_treasures.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: fishing_treasures.yml
[08:53:45] [Server thread/INFO]: [D] Registering enchantments for Fishing Book...
[08:53:45] [Server thread/INFO]: [D] No errors found in fishing_treasures.yml!
[08:53:45] [Server thread/INFO]: [D] Loading mcMMO potions.yml File...
[08:53:45] [Server thread/INFO]: [D] Loaded 220 Alchemy potions, skipped 0.
[08:53:45] [Server thread/INFO]: [D] Initializing config: coreskills.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: coreskills.yml to defaults/coreskills.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: coreskills.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: coreskills.yml
[08:53:45] [Server thread/INFO]: [D] No errors found in coreskills.yml!
[08:53:45] [Server thread/INFO]: [D] Initializing config: sounds.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: sounds.yml to defaults/sounds.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: sounds.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: sounds.yml
[08:53:45] [Server thread/INFO]: [D] No errors found in sounds.yml!
[08:53:45] [Server thread/INFO]: [D] Initializing config: skillranks.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: skillranks.yml to defaults/skillranks.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: skillranks.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: skillranks.yml
[08:53:45] [Server thread/INFO]: [D] No errors found in skillranks.yml!
[08:53:45] [Server thread/INFO]: [D] Initializing config: repair.vanilla.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: repair.vanilla.yml to defaults/repair.vanilla.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: repair.vanilla.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: repair.vanilla.yml
[08:53:45] [Server thread/INFO]: [D] Initializing config: salvage.vanilla.yml
[08:53:45] [Server thread/INFO]: [D] Copying default config to disk: salvage.vanilla.yml to defaults/salvage.vanilla.yml
[08:53:45] [Server thread/INFO]: [D] Loading config from disk: salvage.vanilla.yml
[08:53:45] [Server thread/INFO]: [D] Config initialized: salvage.vanilla.yml
[08:53:45] [Server thread/FATAL]: There was an error while enabling mcMMO!
[08:53:45] [Server thread/INFO]: [STDERR]: java.lang.IllegalArgumentException: Invalid recipe type: class net.minecraft.class_8062
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_8786.toBukkitRecipe(class_8786.java:656)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.cardboardpowered.impl.inventory.recipe.RecipeIterator.next(RecipeIterator.java:32)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.cardboardpowered.impl.inventory.recipe.RecipeIterator.next(RecipeIterator.java:15)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:330)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfig.loadKeys(SalvageConfig.java:146)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfig.<init>(SalvageConfig.java:28)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at com.gmail.nossr50.config.skills.salvage.SalvageConfigManager.<init>(SalvageConfigManager.java:20)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:600)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:213)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:571)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:502)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$zzf000$cardboard$afterWorldLoad(MinecraftServer.java:2562)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:345)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3176.method_3823(class_3176.java:169)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:53:45] [Server thread/INFO]: Disabling mcMMO v2.2.006
[08:53:45] [Server thread/INFO]: Server shutdown has been executed, saving and cleaning up data...
[08:53:45] [Server thread/INFO]: [D] Completing 0 unfinished Alchemy brews.
[08:53:45] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.party.PartyManager.saveParties()" because the return value of "com.gmail.nossr50.mcMMO.getPartyManager()" is null
[08:53:45] [Server thread/INFO]: [STDERR]: 	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:389)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:315)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:571)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:502)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$zzf000$cardboard$afterWorldLoad(MinecraftServer.java:2562)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:345)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3176.method_3823(class_3176.java:169)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
[08:53:45] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:53:45] [Server thread/INFO]: [D] Backing up your mcMMO Configuration... 
[08:53:45] [Server thread/FATAL]: Cannot read /home/platformplayz/servers/Port 25566 servers/Cattieah's Servers/Season 1/Cattieah Server 1.20.4/plugins/mcMMO/experience.yml(File Permissions?)
[08:53:45] [Server thread/INFO]: [D] Backup Completed.
[08:53:45] [Server thread/INFO]: [D] Canceling all tasks...
[08:53:45] [Server thread/INFO]: [D] Unregister all events...
[08:53:45] [Server thread/FATAL]: Error occurred while disabling mcMMO v2.2.006 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.database.DatabaseManager.onDisable()" because "com.gmail.nossr50.mcMMO.databaseManager" is null
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:419) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Cardboard-1.20.4.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[Cardboard-1.20.4.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.4-550.jar:?]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:315) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Cardboard-1.20.4.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[Cardboard-1.20.4.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.4-550.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:571) ~[Cardboard-1.20.4.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:502) ~[Cardboard-1.20.4.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zzf000$cardboard$afterWorldLoad(MinecraftServer.java:2562) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:345) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:169) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nossr50** [comment]
Try updating mcMMO, what server software + version is this?
What does /version print out?

**Comment by Walter-o** [comment]
Since cardboard is supposed to be a translation for spigot plugins -> fabric servers.

i think the ball is in their court.

**Comment by Konpaku-LVX** [comment]
just use arclight tbh(if you want a mods + plugin environment)

**Comment by Konpaku-LVX** [comment]
i tested pretty much every combo server last year or so and arclight was the only one that well, worked? to put it shortly. and it worked so well i didnt bother looking any further

**Comment by Konpaku-LVX** [comment]
but yeah mcMMO works flawlessly.

**Comment by Konpaku-LVX** [comment]
the one thing to keep in mind is arclight has very limited support for the paper API, but works well with spigot/bukkit standard plugin API
