### ISSUE TITLE
Could not pass event ProjectileLaunchEvent to mcMMO v2.2.007-SNAPSHOT

### ISSUE THREAD

**Issue by IAISI** [mcMMO-Dev/mcMMO#5004]
```
com.destroystokyo.paper.exception.ServerEventException: Could not pass event ProjectileLaunchEvent to mcMMO v2.2.007-SNAPSHOT
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:72)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1473)
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:699)
	at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1714)
	at net.minecraft.server.level.WorldServer.addFreshEntity(WorldServer.java:1636)
	at net.minecraft.server.level.WorldServer.b(WorldServer.java:1631)
	at net.minecraft.world.item.ItemBow.a(ItemBow.java:85)
	at net.minecraft.world.item.ItemStack.a(ItemStack.java:837)
	at net.minecraft.world.entity.EntityLiving.fs(EntityLiving.java:4121)
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1832)
	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
	at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
	at net.minecraft.network.protocol.PlayerConnectionUtils.a(PlayerConnectionUtils.java:54)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1474)
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:195)
	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1451)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1374)
	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1352)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1241)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.datatypes.player.McMMOPlayer.getSkillLevel(com.gmail.nossr50.datatypes.skills.PrimarySkillType)" because the return value of "com.gmail.nossr50.util.player.UserManager.getPlayer(org.bukkit.entity.Player)" is null
	at mcMMO.jar//com.gmail.nossr50.events.skills.McMMOPlayerSkillEvent.<init>(McMMOPlayerSkillEvent.java:20)
	at mcMMO.jar//com.gmail.nossr50.events.skills.secondaryabilities.SubSkillEvent.<init>(SubSkillEvent.java:21)
	at mcMMO.jar//com.gmail.nossr50.util.EventUtils.callSubSkillEvent(EventUtils.java:187)
	at mcMMO.jar//com.gmail.nossr50.util.random.ProbabilityUtil.getSkillProbability(ProbabilityUtil.java:156)
	at mcMMO.jar//com.gmail.nossr50.util.random.ProbabilityUtil.isSkillRNGSuccessful(ProbabilityUtil.java:130)
	at mcMMO.jar//com.gmail.nossr50.listeners.EntityListener.onProjectileLaunch(EntityListener.java:171)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor362.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1473)
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:699)
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1714)
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1636)
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1631)
	at net.minecraft.world.item.BowItem.releaseUsing(BowItem.java:85)
	at net.minecraft.world.item.ItemStack.releaseUsing(ItemStack.java:837)
	at net.minecraft.world.entity.LivingEntity.releaseUsingItem(LivingEntity.java:4121)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1832)
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42)
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54)
	at net.minecraft.server.TickTask.run(TickTask.java:18)
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149)
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1474)
	at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:195)
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1451)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1374)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1352)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1241)
	... 2 more
```

For some reason getPlayer() returns null even tho it gets object that is Player (instanceof Player) as param in onProjectileLaunch, not quite sure what is going on here...

**Comment by nossr50** [comment]
I know what's going on, I'll fix it 🫡
