### ISSUE TITLE
Error starting mcMMO after 2.2.008 update

### ISSUE THREAD

**Issue by Momshroom** [mcMMO-Dev/mcMMO#5007]
When attempting to update to mcMMO 2.2.008, I got this error on startup:

https://paste.gg/p/Momshroom/a17387e736df477ab60d2453ea4bb53f

paper 496 (1.20.4)

**Comment by KyleFree33** [comment]
Maybe related, but this is my error:
Looking into my files created from the jar there is no experience.yml or repair.vanilar.yml - any ideas why?
User
[22:19:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[22:19:51 ERROR]: [mcMMO] Cannot read C:\Users\kyle3\Mohist\plugins\mcMMO\experience.yml(File Permissions?)
[22:19:51 ERROR]: [mcMMO] Cannot read C:\Users\kyle3\Mohist\plugins\mcMMO\repair.vanilla.yml(File Permissions?)
[22:19:51 ERROR]: Error occurred while disabling mcMMO v2.2.008 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.database.DatabaseManager.onDisable()" because "com.gmail.nossr50.mcMMO.databaseManager" is null
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:417) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:349) ~[forge-1.20.1-47.2.32-universal.jar%23201!/:?]

**Comment by ILikeOrangeJuice** [comment]
Maybe related too, got those startup errors on 1.20.1 paper (relative to the first one with potion stuff?:
https://pastebin.com/kuNBqgrG

**Comment by nossr50** [comment]
This is fixed now
