### ISSUE TITLE
Error starting MCMMO using Mohist

### ISSUE THREAD

**Issue by KyleFree33** [mcMMO-Dev/mcMMO#5008]
I cloned the repo
ran mvn clean install
added the jar file to the plugins folder

got this error when starting server:
[22:19:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[22:19:51 ERROR]: [mcMMO] Cannot read C:\Users\kyle3\Mohist\plugins\mcMMO\experience.yml(File Permissions?)
[22:19:51 ERROR]: [mcMMO] Cannot read C:\Users\kyle3\Mohist\plugins\mcMMO\repair.vanilla.yml(File Permissions?)
[22:19:51 ERROR]: Error occurred while disabling mcMMO v2.2.008 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.database.DatabaseManager.onDisable()" because "com.gmail.nossr50.mcMMO.databaseManager" is null
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:417) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:349) ~[forge-1.20.1-47.2.32-universal.jar%23201!/:?]

The files experience.yml and repair.vanilla.yml do not even exist - are they expected?

Any ideas help - thank you!

**Comment by KyleFree33** [comment]
server command: /mcstats
[22:55:39 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'mcstats' in plugin mcMMO v2.2.008 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:38) ~[forge-1.20.1-47.2.32-universal.jar%23201!/:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[forge-1.20.1-47.2.32-universal.jar%23201!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:883) ~[forge-1.20.1-47.2.32-universal.jar%23201!/:997de31d-ddc9a2dad-d2eba2c8-47.1.105]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:51) ~[forge-1.20.1-47.2.32-universal.jar%23201!/:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.20.1.jar%23146!/:?]
        at net.minecraft.commands.Commands.m_242674_(Commands.java:321) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_246958_(ServerGamePacketListenerImpl.java:1873) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:1837) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:58) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1015) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:998) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:992) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:978) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:894) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23196!/:?]
        at java.lang.Thread.run(Thread.java:1570) [?:?]

**Comment by Chew** [comment]
We don't support Bukkit+Forge hybrids, especially [Mohist](https://essentialsx.net/do-not-use-mohist.html).

But, by the looks of it, it looks like you have some permission issue preventing you from making files? If this happens on just Spigot or Paper, we can look into it.
