### ISSUE TITLE
plugin warn

### ISSUE THREAD

**Issue by YuanYuanOwO** [mcMMO-Dev/mcMMO#5017]
```
[16:09:04 WARN]: [mcMMO] Task #31835433 for mcMMO v2.2.013-SNAPSHOT generated an exception
java.lang.NullPointerException: null
[16:09:04 ERROR]: Could not pass event BrewEvent to mcMMO v2.2.013-SNAPSHOT
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.datatypes.player.McMMOPlayer.getPlayer()" because "this.mmoPlayer" is null
        at com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finishImmediately(AlchemyBrewTask.java:168) ~[mcMMO.jar:?]
        at com.gmail.nossr50.listeners.InventoryListener.onBrew(InventoryListener.java:348) ~[mcMMO.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor278.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.BrewingStandBlockEntity.doBrew(BrewingStandBlockEntity.java:265) ~[?:?]
        at net.minecraft.world.level.block.entity.BrewingStandBlockEntity.serverTick(BrewingStandBlockEntity.java:185) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1170) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1122) ~[?:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1299) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:925) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by nossr50** [comment]
This one was fixed a while back in https://github.com/mcMMO-Dev/mcMMO/commit/bac16238ac56f8f724b257e410c7e52d72dd50a3 (shipped in 2.2.020). The brew task now handles the player being gone when brewing finishes. Closing, but if you see it again on a current build please reopen with the new stack trace.
