### ISSUE TITLE
[08:02:33 ERROR]: Could not pass event PlayerInteractEvent to mcMMO v2.2.013

### ISSUE THREAD

**Issue by fancypork** [mcMMO-Dev/mcMMO#5025]
Server is running on paper and I have the newest world guard and mcmmo. Mcmmo has been working fine and I just installed world guard and now my console is spammed with this error

java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WorldGuardPlugin
        at com.gmail.nossr50.worldguard.WorldGuardUtils.getWorldGuard(WorldGuardUtils.java:72) ~[mcMMO.jar:?]
        at com.gmail.nossr50.worldguard.WorldGuardUtils.isWorldGuardLoaded(WorldGuardUtils.java:48) ~[mcMMO.jar:?]
        at com.gmail.nossr50.listeners.PlayerListener.onPlayerInteractMonitor(PlayerListener.java:754) ~[mcMMO.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor267.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1935) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.bukkit.WorldGuardPlugin
        ... 29 more

**Comment by Chew** [comment]
What is your Paper/mcMMO/WorldGuard versions?

Check these with:
- `/version`
- `/version Worldguard`
- `/version mcMMO`

**Comment by fancypork** [comment]
This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

Mcmmo 2.2.013

WorldGuard 7.0.10

**Comment by Chew** [comment]
WorldGuard probably didn't load, 7.0.10 is only for MC 1.20.6.

You'll either want to:
1. Downgrade WorldGuard to 7.0.9 (easiest): https://dev.bukkit.org/projects/worldguard/files/4675318
2. Upgrade Paper and your plugins to 1.20.6.
