### ISSUE TITLE
Chimera Wing Issues

### ISSUE THREAD

**Issue by wuwcat** [mcMMO-Dev/mcMMO#5049]
Recently the Chimera Wing in mcmmo has stopped working for me, possibly because of the early 1.21 snapshots of paper servers.
After using the chimera Wing, it starts the warmup timer before, teleporting than proceeds to say/do nothing after that(Does not teleport at all even after trying without a spawnpoint set at a bed). No messages to tell that the teleport has been cancelled due to any errors/exceptions. Except in the console it prints an exepction for an Illegal Argument Exception. I have printed the exception down below as im not too if it is a Paper or an mcmmo bug.

[09:47:25 WARN]: [mcMMO] Task https://github.com/mcMMO-Dev/mcMMO-Classic/issues/12 for mcMMO v2.2.017-SNAPSHOT generated an exception
java.lang.IllegalArgumentException: amount must be greater than 0
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
at org.bukkit.inventory.ItemStack.of(ItemStack.java:59) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.inventory.ItemStack.(ItemStack.java:138) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.inventory.ItemStack.(ItemStack.java:117) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.inventory.ItemStack.(ItemStack.java:104) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at mcMMO.jar/com.gmail.nossr50.util.ChimaeraWing.getChimaeraWing(ChimaeraWing.java:151) ~[mcMMO.jar:?]
at mcMMO.jar/com.gmail.nossr50.runnables.items.ChimaeraWingWarmup.checkChimaeraWingTeleport(ChimaeraWingWarmup.java:31) ~[mcMMO.jar:?]
at mcMMO.jar/com.gmail.nossr50.runnables.items.ChimaeraWingWarmup.run(ChimaeraWingWarmup.java:24) ~[mcMMO.jar:?]
at mcMMO.jar/com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20) ~[mcMMO.jar:?]
at mcMMO.jar/com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7) ~[mcMMO.jar:?]
at mcMMO.jar/com.gmail.nossr50.mcmmo.folialib.impl.SpigotImplementation.lambda$runAtEntityLater$8(SpigotImplementation.java:219) ~[mcMMO.jar:?]
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:103) ~[paper-1.21.jar:1.21-63-2288e13]
at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.21.jar:1.21-63-2288e13]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1718) ~[paper-1.21.jar:1.21-63-2288e13]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-63-2288e13]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1602) ~[paper-1.21.jar:1.21-63-2288e13]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1309) ~[paper-1.21.jar:1.21-63-2288e13]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-63-2288e13]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Mercyssh** [comment]
I believe this issue is caused inside ChimaeraWingWarmup.java : line 31

`    private void checkChimaeraWingTeleport() {
        Player player = mcMMOPlayer.getPlayer();
        Location previousLocation = mcMMOPlayer.getTeleportCommenceLocation();

        if (player.getLocation().distanceSquared(previousLocation) > 1.0 || !player.getInventory().containsAtLeast(ChimaeraWing.getChimaeraWing(0), 1)) {
            player.sendMessage(LocaleLoader.getString("Teleport.Cancelled"));
            mcMMOPlayer.setTeleportCommenceLocation(null);
            return;
        }`

Inside the if statement, ChimaeraWing.getChimaeraWing(0) passing in the amount 0 is causing the issue. changing this to 1 fixed it for me, sorry I can't commit or request a merge right now

**Comment by nossr50** [comment]
> I believe this issue is caused inside ChimaeraWingWarmup.java : line 31
> 
> ` private void checkChimaeraWingTeleport() { Player player = mcMMOPlayer.getPlayer(); Location previousLocation = mcMMOPlayer.getTeleportCommenceLocation();
> 
> ```
>     if (player.getLocation().distanceSquared(previousLocation) > 1.0 || !player.getInventory().containsAtLeast(ChimaeraWing.getChimaeraWing(0), 1)) {
>         player.sendMessage(LocaleLoader.getString("Teleport.Cancelled"));
>         mcMMOPlayer.setTeleportCommenceLocation(null);
>         return;
>     }`
> ```
> 
> Inside the if statement, ChimaeraWing.getChimaeraWing(0) passing in the amount 0 is causing the issue. changing this to 1 fixed it for me, sorry I can't commit or request a merge right now

Good catch
