### ISSUE TITLE
mcMMO disabled - Recipe must have non-AIR result

### ISSUE THREAD

**Issue by Thomasiio** [mcMMO-Dev/mcMMO#5060]
As of yesterday I receive the attached error when starting my server. 
[mcMMO_error.txt](https://github.com/user-attachments/files/16431577/mcMMO_error.txt)

"[18:45:42] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[18:45:42] [Server thread/WARN]: java.lang.IllegalArgumentException: Recipe must have non-AIR result."

I have gone through the salvage and repair YAML files and have not found any missing recipe results or other recipes missing fields.
This error is causing the plugin to automatically disable on startup. 

Error log contents also pasted below.

`[18:45:42] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[18:45:42] [Server thread/WARN]: java.lang.IllegalArgumentException: Recipe must have non-AIR result.
[18:45:42] [Server thread/WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[18:45:42] [Server thread/WARN]:        at org.bukkit.inventory.CraftingRecipe.<init>(CraftingRecipe.java:21)
[18:45:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftComplexRecipe.<init>(CraftComplexRecipe.java:17)
[18:45:42] [Server thread/WARN]:        at net.minecraft.world.item.crafting.IRecipeComplex.toBukkitRecipe(IRecipeComplex.java:43)
[18:45:42] [Server thread/WARN]:        at net.minecraft.world.item.crafting.RecipeHolder.toBukkitRecipe(RecipeHolder.java:16)
[18:45:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:24)
[18:45:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:10)
[18:45:42] [Server thread/WARN]:        at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:315)
[18:45:42] [Server thread/WARN]:        at com.gmail.nossr50.config.skills.salvage.SalvageConfig.loadKeys(SalvageConfig.java:146)
[18:45:42] [Server thread/WARN]:        at com.gmail.nossr50.config.skills.salvage.SalvageConfig.<init>(SalvageConfig.java:28)
[18:45:42] [Server thread/WARN]:        at com.gmail.nossr50.config.skills.salvage.SalvageConfigManager.<init>(SalvageConfigManager.java:20)
[18:45:42] [Server thread/WARN]:        at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:605)
[18:45:42] [Server thread/WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:200)
[18:45:42] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[18:45:42] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[18:45:42] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
[18:45:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575)
[18:45:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489)
[18:45:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[18:45:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426)
[18:45:42] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269)
[18:45:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
[18:45:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[18:45:42] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[18:45:42] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.2.018
[18:45:42] [Server thread/INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[18:45:42] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.party.PartyManager.saveParties()" because the return value of "com.gmail.nossr50.mcMMO.getPartyManager()" is null
[18:45:42] [Server thread/WARN]:        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:372)
[18:45:42] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:269)
[18:45:42] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367)
[18:45:42] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:513)
[18:45:42] [Server thread/WARN]:        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:299)
[18:45:42] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[18:45:42] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[18:45:42] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
[18:45:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575)
[18:45:42] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489)
[18:45:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[18:45:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426)
[18:45:42] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269)
[18:45:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
[18:45:42] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[18:45:42] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[18:45:42] [Server thread/ERROR]: Error occurred while disabling mcMMO v2.2.018 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.database.DatabaseManager.onDisable()" because "com.gmail.nossr50.mcMMO.databaseManager" is null
        at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:402) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:269) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:513) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:299) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4285-Spigot-fb8fb72-00fc9fb]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by Lilliat86** [comment]
I am having the same issue with the same error.  I will add, that my issue appears to have started when I upgraded EconomyShopGUI to the premium version, which required a server restart to happen.

**Comment by nossr50** [comment]
Unable to reproduce on latest Spigot or Paper
Try deleting your config files and regenerating them
And check what version of Spigot/Paper you are on, remember they get updates everyday and you should keep them up to date.

**Comment by nossr50** [comment]
Reopening to allow more info

**Comment by PrismaticCardinal** [comment]
[15:25:47] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.2.018
[15:25:47] [Server thread/INFO]: [mcMMO] Loaded 220 Alchemy potions, skipped 0.
[15:25:47] [Server thread/INFO]: [mcMMO] Fixing incorrect Salvage quantities on Netherite gear, this will only run once...
[15:25:47] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[15:25:47] [Server thread/WARN]: java.lang.IllegalArgumentException: Recipe must have non-AIR result.
[15:25:47] [Server thread/WARN]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[15:25:47] [Server thread/WARN]: at org.bukkit.inventory.CraftingRecipe.<init>(CraftingRecipe.java:21)
[15:25:47] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_21_R1.inventory.CraftComplexRecipe.<init>(CraftComplexRecipe.java:17)
[15:25:47] [Server thread/WARN]: at net.minecraft.world.item.crafting.IRecipeComplex.toBukkitRecipe(IRecipeComplex.java:43)
[15:25:47] [Server thread/WARN]: at net.minecraft.world.item.crafting.RecipeHolder.toBukkitRecipe(RecipeHolder.java:16)
[15:25:47] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:24)
[15:25:47] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_21_R1.inventory.RecipeIterator.next(RecipeIterator.java:10)
[15:25:47] [Server thread/WARN]: at com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:315)
[15:25:47] [Server thread/WARN]: at com.gmail.nossr50.config.skills.salvage.SalvageConfig.loadKeys(SalvageConfig.java:146)
[15:25:47] [Server thread/WARN]: at com.gmail.nossr50.config.skills.salvage.SalvageConfig.<init>(SalvageConfig.java:28)
[15:25:47] [Server thread/WARN]: at com.gmail.nossr50.config.skills.salvage.SalvageConfigManager.<init>(SalvageConfigManager.java:20)
[15:25:47] [Server thread/WARN]: at com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:605)
[15:25:47] [Server thread/WARN]: at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:200)
[15:25:47] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[15:25:47] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[15:25:47] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
[15:25:47] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575)
[15:25:47] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489)
[15:25:47] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641)
[15:25:47] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426)
[15:25:47] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269)
[15:25:47] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017)
[15:25:47] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[15:25:47] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
[15:25:47] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.2.018

Plugins currently used:
![image](https://github.com/user-attachments/assets/3b8efbb6-7ebb-4aa2-910f-d5dc1f5032e5)

WorldGuard version 7.0.10 

All plugins fresh installed within the last 5 days

**Comment by Thomasiio** [comment]
I am on the latest version of Spigot, 1.21. Prior to submitting the issue here I tried deleting all of my config files, reinstalled the mcMMO .jar I was on, updated to the most recent mcMMO, reverted to a backup of mcMMO during a working state and none of them worked. It started working again on its own 2 days ago without further intervention.

**Comment by PrismaticCardinal** [comment]
Converting from spigot to the latest version of paper fixed the issue

**Comment by nossr50** [comment]
Unable to reproduce, if anyone encounters this issue try the latest Paper/Spigot
