### ISSUE TITLE
Spam the console too much about health limit errors

### ISSUE THREAD

**Issue by PhamDat2427** [mcMMO-Dev/mcMMO#5063]
It spams a lot. It seems that this is an error about the player's health limit while I have set the blood limit in the spigot.yml folder to 2000 and this error I don't know where to fix in mcmmo's config folder and has nothing to do with it. blood limit
[2024-08-04-3.log](https://github.com/user-attachments/files/16488219/2024-08-04-3.log)

**Comment by nossr50** [comment]
Thanks I'll look into this error, are you running anything that is changing player max health?

`java.lang.IllegalArgumentException: Health value (45.73334503173828) must be between 0 and 40.0. (attribute base value: 20.0, player: _Mihthuw100d)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:472) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:112) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
	at com.gmail.nossr50.runnables.skills.RuptureTask.applyRupture(RuptureTask.java:100) ~[mcMMO.jar:?]
	at com.gmail.nossr50.runnables.skills.RuptureTask.run(RuptureTask.java:61) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7) ~[mcMMO.jar:?]
	at com.gmail.nossr50.mcmmo.folialib.impl.SpigotImplementation.lambda$runAtEntityTimer$9(SpigotImplementation.java:239) ~[mcMMO.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1493) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1407) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[lightspigot-1.20.1.jar:git-LightSpigot-"ad20ecf"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Comment by nossr50** [comment]
@PhamDat2427 could you clarify what you mean by blood limit?
