### ISSUE TITLE
1.21.1 Folia Not loaded

### ISSUE THREAD

**Issue by Euphillya** [mcMMO-Dev/mcMMO#5067]
Hello I reported this bug on the discord but totally ignored... I hope you will read it here.

On Folia 1.21.1, mcMMO does not load:
```
[15:33:58] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[15:33:58] [Server thread/WARN]: java.lang.IllegalArgumentException: Recipe cannot have an empty result
[15:33:58] [Server thread/WARN]:     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[15:33:58] [Server thread/WARN]:     at org.bukkit.inventory.CraftingRecipe.checkResult(CraftingRecipe.java:105)
[15:33:58] [Server thread/WARN]:     at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:39)
[15:33:58] [Server thread/WARN]:     at org.bukkit.craftbukkit.inventory.CraftShapelessRecipe.<init>(CraftShapelessRecipe.java:19)
[15:33:58] [Server thread/WARN]:     at org.bukkit.craftbukkit.inventory.CraftShapelessRecipe.<init>(CraftShapelessRecipe.java:23)
[15:33:58] [Server thread/WARN]:     at net.minecraft.world.item.crafting.ShapelessRecipe.toBukkitRecipe(ShapelessRecipe.java:42)
[15:33:58] [Server thread/WARN]:     at net.minecraft.world.item.crafting.ShapelessRecipe.toBukkitRecipe(ShapelessRecipe.java:22)
[15:33:58] [Server thread/WARN]:     at net.minecraft.world.item.crafting.RecipeHolder.toBukkitRecipe(RecipeHolder.java:15)
[15:33:58] [Server thread/WARN]:     at org.bukkit.craftbukkit.inventory.RecipeIterator.next(RecipeIterator.java:26)
[15:33:58] [Server thread/WARN]:     at org.bukkit.craftbukkit.inventory.RecipeIterator.next(RecipeIterator.java:10)
[15:33:58] [Server thread/WARN]:     at mcMMO.jar//com.gmail.nossr50.util.skills.SkillUtils.getRepairAndSalvageQuantities(SkillUtils.java:315)
[15:33:58] [Server thread/WARN]:     at mcMMO.jar//com.gmail.nossr50.config.skills.salvage.SalvageConfig.loadKeys(SalvageConfig.java:146)
[15:33:58] [Server thread/WARN]:     at mcMMO.jar//com.gmail.nossr50.config.skills.salvage.SalvageConfig.<init>(SalvageConfig.java:28)
[15:33:58] [Server thread/WARN]:     at mcMMO.jar//com.gmail.nossr50.config.skills.salvage.SalvageConfigManager.<init>(SalvageConfigManager.java:20)
[15:33:58] [Server thread/WARN]:     at mcMMO.jar//com.gmail.nossr50.mcMMO.loadConfigFiles(mcMMO.java:605)
[15:33:58] [Server thread/WARN]:     at mcMMO.jar//com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:200)
[15:33:58] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[15:33:58] [Server thread/WARN]:     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[15:33:58] [Server thread/WARN]:     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[15:33:58] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[15:33:58] [Server thread/WARN]:     at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:647)
[15:33:58] [Server thread/WARN]:     at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596)
[15:33:58] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:780)
[15:33:58] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:527)
[15:33:58] [Server thread/WARN]:     at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:330)
[15:33:58] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281)
[15:33:58] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357)
[15:33:58] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:1583)
[15:33:58] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.2.018
```

I would like to point out that on 1.21 it loads, and that I have reset the default configurations.

**Comment by Euphillya** [comment]
Fixed on latest version folia
