### ISSUE TITLE
AlchemyBrewTask#finish NPE

### ISSUE THREAD

**Issue by IAISI** [mcMMO-Dev/mcMMO#5073]
```
[00:00:35] [Server thread/WARN]: [mcMMO] Task #3566623 for mcMMO v2.2.019-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.datatypes.player.McMMOPlayer.getPlayer()" because "mmoPlayer" is null
	at mcMMO.jar/com.gmail.nossr50.events.skills.McMMOPlayerSkillEvent.<init>(McMMOPlayerSkillEvent.java:33) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.events.skills.alchemy.McMMOPlayerBrewEvent.<init>(McMMOPlayerBrewEvent.java:29) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:155) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:102) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.mcmmo.folialib.impl.SpigotImplementation.lambda$runTimer$4(SpigotImplementation.java:105) ~[mcMMO.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:88) ~[sakura-1.21.1.jar:1.21.1-DEV-8179a24]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[sakura-1.21.1.jar:1.21.1-DEV-8179a24]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734) ~[sakura-1.21.1.jar:1.21.1-DEV-8179a24]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478) ~[sakura-1.21.1.jar:1.21.1-DEV-8179a24]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[sakura-1.21.1.jar:1.21.1-DEV-8179a24]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1311) ~[sakura-1.21.1.jar:1.21.1-DEV-8179a24]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[sakura-1.21.1.jar:1.21.1-DEV-8179a24]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:00:35] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerSchedulerException: Task #3566623 for mcMMO v2.2.019-SNAPSHOT generated an exception
[00:00:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:486)
[00:00:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734)
[00:00:35] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478)
[00:00:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606)
[00:00:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1311)
[00:00:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331)
[00:00:35] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[00:00:35] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.datatypes.player.McMMOPlayer.getPlayer()" because "mmoPlayer" is null
[00:00:35] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.events.skills.McMMOPlayerSkillEvent.<init>(McMMOPlayerSkillEvent.java:33)
[00:00:35] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.events.skills.alchemy.McMMOPlayerBrewEvent.<init>(McMMOPlayerBrewEvent.java:29)
[00:00:35] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.runnables.skills.AlchemyBrewTask.finish(AlchemyBrewTask.java:155)
[00:00:35] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.runnables.skills.AlchemyBrewTask.run(AlchemyBrewTask.java:102)
[00:00:35] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20)
[00:00:35] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7)
[00:00:35] [Server thread/WARN]: 	at mcMMO.jar//com.gmail.nossr50.mcmmo.folialib.impl.SpigotImplementation.lambda$runTimer$4(SpigotImplementation.java:105)
[00:00:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:88)
[00:00:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[00:00:35] [Server thread/WARN]: 	... 6 more
```

I assume player loaded brewing stand then left? If did start spitting NPEs right after player disconnected.

**Comment by IAISI** [comment]
I think this could be fixed with:

```
    private void finish() {
        if(mmoPlayer != null) {
            final McMMOPlayerBrewEvent event = new McMMOPlayerBrewEvent(mmoPlayer, brewingStand);
            mcMMO.p.getServer().getPluginManager().callEvent(event);

            if (!event.isCancelled()) {
                AlchemyPotionBrewer.finishBrewing(brewingStand, mmoPlayer, false);
            }
        }

        Alchemy.brewingStandMap.remove(brewingStand.getLocation());
    }
```
