### ISSUE TITLE
Playerdata issues

### ISSUE THREAD

**Issue by AdamDAuria** [mcMMO-Dev/mcMMO#5078]
java.io.FileNotFoundException: plugins/mcMMO/flatfile/mcmmo.users (Too many open files)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/ERROR]: [mcMMO] PlayerProfile saving failed for player: xpl0r321 660ede51-19a7-4816-9066-b3e9e19c0fd6
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/ERROR]: [mcMMO] Attempted to save profile for player xpl0r321 resulted in failure. 8 have been made so far.

[mcmmo bug.txt](https://github.com/user-attachments/files/16833238/mcmmo.bug.txt)

**Comment by AdamDAuria** [comment]
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: java.io.FileNotFoundException: plugins/mcMMO/flatfile/mcmmo.users (Too many open files)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at java.base/java.io.FileReader.<init>(FileReader.java:60)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.database.FlatFileDatabaseManager.saveUser(FlatFileDatabaseManager.java:349)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.datatypes.player.PlayerProfile.save(PlayerProfile.java:131)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.runnables.player.PlayerProfileSaveTask.run(PlayerProfileSaveTask.java:17)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.mcmmo.folialib.impl.SpigotImplementation.lambda$runAsync$1(SpigotImplementation.java:51)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:88)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/ERROR]: [mcMMO] PlayerProfile saving failed for player: xpl0r321 660ede51-19a7-4816-9066-b3e9e19c0fd6
[21:42:26] [Craft Scheduler Thread - 140 - mcMMO/ERROR]: [mcMMO] Attempted to save profile for player xpl0r321 resulted in failure. 8 have been made so far.
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: java.io.FileNotFoundException: plugins/mcMMO/flatfile/mcmmo.users (Too many open files)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at java.base/java.io.FileReader.<init>(FileReader.java:60)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.database.FlatFileDatabaseManager.saveUser(FlatFileDatabaseManager.java:349)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.datatypes.player.PlayerProfile.save(PlayerProfile.java:131)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.runnables.player.PlayerProfileSaveTask.run(PlayerProfileSaveTask.java:17)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.mcmmo.folialib.impl.SpigotImplementation.lambda$runAsync$1(SpigotImplementation.java:51)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:88)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/ERROR]: [mcMMO] PlayerProfile saving failed for player: Seth392 9f19e182-7da5-4383-8b94-b8365b10f342
[21:42:26] [Craft Scheduler Thread - 177 - mcMMO/ERROR]: [mcMMO] Attempted to save profile for player Seth392 resulted in failure. 9 have been made so far.
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: java.io.FileNotFoundException: plugins/mcMMO/flatfile/mcmmo.users (Too many open files)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at java.base/java.io.FileReader.<init>(FileReader.java:60)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.database.FlatFileDatabaseManager.saveUser(FlatFileDatabaseManager.java:349)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.datatypes.player.PlayerProfile.save(PlayerProfile.java:131)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.runnables.player.PlayerProfileSaveTask.run(PlayerProfileSaveTask.java:17)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:20)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.util.CancellableRunnable.accept(CancellableRunnable.java:7)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at mcMMO (1).jar//com.gmail.nossr50.mcmmo.folialib.impl.SpigotImplementation.lambda$runAsync$1(SpigotImplementation.java:51)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:88)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/ERROR]: [mcMMO] PlayerProfile saving failed for player: ConArtist22310 ea967261-dff1-469a-9bf1-d5bcb63d4c53
[21:42:26] [Craft Scheduler Thread - 166 - mcMMO/ERROR]: [mcMMO] Attempted to save profile for player ConArtist22310 resulted in failure. 7 have been made so far.

**Comment by nossr50** [comment]
This bit here seems to be hinting at possible culprits
>(Too many open files)
Seems like the OS has too many files opened, could be the result of other plugins, or processes in the background
mcMMO only really opens one or two files at a time max, so it wouldn't be from mcMMO.
