### ISSUE TITLE
1.21.3 fresh install on Spigot fails 

### ISSUE THREAD

**Issue by mrfloris** [mcMMO-Dev/mcMMO#5105]
```
[22:29:53] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.2.021-SNAPSHOT
[22:29:53] [Server thread/ERROR]: [mcMMO] Unable to find the Generic Jump Strength or Horse Jump Strength attribute, mcMMO will not function properly.
[22:29:53] [Server thread/ERROR]: [mcMMO] There was an error while enabling mcMMO!
[22:29:53] [Server thread/WARN]: java.lang.IllegalStateException: Unable to find the Generic Jump Strength or Horse Jump Strength attribute
[22:29:53] [Server thread/WARN]: 	at com.gmail.nossr50.util.AttributeMapper.initHorseJumpStrength(AttributeMapper.java:39)
[22:29:53] [Server thread/WARN]: 	at com.gmail.nossr50.util.AttributeMapper.<init>(AttributeMapper.java:15)
[22:29:53] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:198)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugin(CraftServer.java:579)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugins(CraftServer.java:493)
[22:29:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:656)
[22:29:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441)
[22:29:53] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:268)
[22:29:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1032)
[22:29:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[22:29:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[22:29:53] [Server thread/INFO]: [mcMMO] Disabling mcMMO v2.2.021-SNAPSHOT
[22:29:53] [Server thread/INFO]: [mcMMO] Server shutdown has been executed, saving and cleaning up data...
[22:29:53] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.party.PartyManager.saveParties()" because the return value of "com.gmail.nossr50.mcMMO.getPartyManager()" is null
[22:29:53] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:372)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:269)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:513)
[22:29:53] [Server thread/WARN]: 	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:299)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugin(CraftServer.java:579)
[22:29:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugins(CraftServer.java:493)
[22:29:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:656)
[22:29:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441)
[22:29:53] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:268)
[22:29:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1032)
[22:29:53] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[22:29:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[22:29:53] [Server thread/ERROR]: [mcMMO] Cannot read /Users/floris/MinecraftServer/pointthree/plugins/mcMMO/experience.yml(File Permissions?)
[22:29:53] [Server thread/ERROR]: [mcMMO] Cannot read /Users/floris/MinecraftServer/pointthree/plugins/mcMMO/treasures.yml(File Permissions?)
[22:29:53] [Server thread/ERROR]: [mcMMO] Cannot read /Users/floris/MinecraftServer/pointthree/plugins/mcMMO/repair.vanilla.yml(File Permissions?)
[22:29:53] [Server thread/ERROR]: Error occurred while disabling mcMMO v2.2.021-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.database.DatabaseManager.onDisable()" because "com.gmail.nossr50.mcMMO.databaseManager" is null
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:402) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:269) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:513) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at com.gmail.nossr50.mcMMO.onEnable(mcMMO.java:299) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugin(CraftServer.java:579) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4353-Spigot-5eb8a94-18b8ae1]
	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugins(CraftServer.java:493) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4353-Spigot-5eb8a94-18b8ae1]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:656) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4353-Spigot-5eb8a94-18b8ae1]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4353-Spigot-5eb8a94-18b8ae1]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:268) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4353-Spigot-5eb8a94-18b8ae1]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1032) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4353-Spigot-5eb8a94-18b8ae1]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4353-Spigot-5eb8a94-18b8ae1]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
```

**Comment by nossr50** [comment]
Fixed in the new version, please update mcMMO when you can
