### ISSUE TITLE
Could not pass event PlayerFishEvent to mcMMO

### ISSUE THREAD

**Issue by SrBedrock** [mcMMO-Dev/mcMMO#5108]
```
[02:39:27 ERROR]: Could not pass event PlayerFishEvent to mcMMO v2.2.023
java.lang.NoClassDefFoundError: Could not initialize class com.gmail.nossr50.skills.fishing.Fishing
        at com.gmail.nossr50.skills.fishing.FishingManager.getPossibleEnchantments(FishingManager.java:692) ~[mcMMO-2.2.023.jar:?]
        at com.gmail.nossr50.skills.fishing.FishingManager.processMagicHunter(FishingManager.java:656) ~[mcMMO-2.2.023.jar:?]
        at com.gmail.nossr50.skills.fishing.FishingManager.processFishing(FishingManager.java:414) ~[mcMMO-2.2.023.jar:?]
        at com.gmail.nossr50.listeners.PlayerListener.onPlayerFishMonitor(PlayerListener.java:447) ~[mcMMO-2.2.023.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor361.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:525) ~[?:?]
        at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:32) ~[?:?]
        at net.minecraft.world.item.ItemStack.use(ItemStack.java:577) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:481) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2087) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1475) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1376) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IncompatibleClassChangeError: Method 'org.bukkit.block.Biome[] org.bukkit.block.Biome.values()' must be Methodref constant [in thread "Server thread"]
        at com.gmail.nossr50.util.adapter.BiomeAdapter.getAllBiomes(BiomeAdapter.java:29) ~[mcMMO-2.2.023.jar:?]
        at com.gmail.nossr50.util.adapter.BiomeAdapter.<clinit>(BiomeAdapter.java:12) ~[mcMMO-2.2.023.jar:?]
        at com.gmail.nossr50.skills.fishing.Fishing.<clinit>(Fishing.java:21) ~[mcMMO-2.2.023.jar:?]
        ... 32 more
```

**Comment by nossr50** [comment]
Thanks for the report, working on this one and it will be fixed in the next patch
