### ISSUE TITLE
Smelting error on mcMMO version 2.2.024 on Paper 1.20.6

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [mcMMO-Dev/mcMMO#5109]
Hey!

We just updated to todays release of mcMMO from Spigotmc and we noticed this error coming up in the console each time something does get smelted.

`[14:16:49 ERROR]: Could not pass event FurnaceBurnEvent to mcMMO v2.2.024
java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because the return value of "java.util.Map.get(Object)" is null
        at mcMMO.jar/com.gmail.nossr50.config.experience.ExperienceConfig.getXp(ExperienceConfig.java:358) ~[mcMMO.jar:?]
        at mcMMO.jar/com.gmail.nossr50.skills.smelting.Smelting.getSmeltXP(Smelting.java:11) ~[mcMMO.jar:?]
        at mcMMO.jar/com.gmail.nossr50.util.ItemUtils.isSmeltable(ItemUtils.java:480) ~[mcMMO.jar:?]
        at mcMMO.jar/com.gmail.nossr50.listeners.InventoryListener.onFurnaceBurnEvent(InventoryListener.java:52) ~[mcMMO.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor623.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-148-20f5165]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.serverTick(AbstractFurnaceBlockEntity.java:361) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1168) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1120) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1282) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:931) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1779) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:16:53 ERROR]: Could not pass event FurnaceSmeltEvent to mcMMO v2.2.024
java.lang.NullPointerException: null
[14:16:54 ERROR]: Could not pass event FurnaceSmeltEvent to mcMMO v2.2.024
java.lang.NullPointerException: null`

We run Paper 1.20.6#151 if that helps and well, the latest mcmmo version!

Best regards.

**Comment by cloakfox** [comment]
Getting the same spam on latest mcmmo build.

**Comment by nossr50** [comment]
> Hey!
> 
> We just updated to todays release of mcMMO from Spigotmc and we noticed this error coming up in the console each time something does get smelted.
> 
> `[14:16:49 ERROR]: Could not pass event FurnaceBurnEvent to mcMMO v2.2.024 java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because the return value of "java.util.Map.get(Object)" is null at mcMMO.jar/com.gmail.nossr50.config.experience.ExperienceConfig.getXp(ExperienceConfig.java:358) ~[mcMMO.jar:?] at mcMMO.jar/com.gmail.nossr50.skills.smelting.Smelting.getSmeltXP(Smelting.java:11) ~[mcMMO.jar:?] at mcMMO.jar/com.gmail.nossr50.util.ItemUtils.isSmeltable(ItemUtils.java:480) ~[mcMMO.jar:?] at mcMMO.jar/com.gmail.nossr50.listeners.InventoryListener.onFurnaceBurnEvent(InventoryListener.java:52) ~[mcMMO.jar:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor623.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-148-20f5165] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?] at net.minecraft.world.level.block.entity.AbstractFurnaceBlockEntity.serverTick(AbstractFurnaceBlockEntity.java:361) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1168) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1120) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1282) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:931) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1779) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] [14:16:53 ERROR]: Could not pass event FurnaceSmeltEvent to mcMMO v2.2.024 java.lang.NullPointerException: null [14:16:54 ERROR]: Could not pass event FurnaceSmeltEvent to mcMMO v2.2.024 java.lang.NullPointerException: null`
> 
> We run Paper 1.20.6#151 if that helps and well, the latest mcmmo version!
> 
> Best regards.

Thank you for this report, I'll look into it ASAP.

**Comment by nossr50** [comment]
Done
