### ISSUE TITLE
Server crash with Overflow exception: Could not pass event ChunkUnloadEvent to mcMMO v2.2.028

### ISSUE THREAD

**Issue by minhsieh** [mcMMO-Dev/mcMMO#5118]
MCMMO Version:  v2.2.028
Spigot Version: CraftBukkit version 4397-Spigot-60c9969-40dd796 (MC: 1.21.3) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

[19:07:29] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to mcMMO v2.2.028
org.bukkit.event.EventException: null
  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]
  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21.3-R0.1-SNAPSHOT.jar:?]

**Comment by Chew** [comment]
That error log is incomplete, please send a full log so we can track down the error

**Comment by minhsieh** [comment]
Original log is too large
I pasted it to gist: https://gist.github.com/minhsieh/bacd4438855dbbb62444665b9687bca1

**Comment by nossr50** [comment]
Thanks for the report, will take a look once I'm feeling better (currently have a bad cold).

**Comment by InsideIntel-dev** [comment]
Hey, I don't mean to message here, i know it needs attention, but I was having this same issue with the same ChunkUnloadEvent overflow exception in 1.21.4. I was wondering if there's an update on this. 

Also, hope you're feelin better! <3

**Comment by moonies44** [comment]
We're getting the same issue over on our network, but instead of unloadchunk its entitydamagebyentity, please take a look!
https://github.com/mcMMO-Dev/mcMMO/issues/5129

**Comment by xGravelight** [comment]
Also having this issue with ChunkUnloadEvent on my own server.
