### ISSUE TITLE
Anomalies caused by sound.

### ISSUE THREAD

**Issue by tygh89071388** [mcMMO-Dev/mcMMO#5120]
When the following error message appears, it causes players to experience lag, including issues such as ores not being mined properly and mobs not taking damage when attacked.

This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
 
`Could not pass event EntityDamageByEntityEvent to mcMMO v2.2.028
java.lang.IncompatibleClassChangeError: Method 'org.bukkit.Sound org.bukkit.Sound.valueOf(java.lang.String)' must be Methodref constant
	at mcMMO.jar/com.gmail.nossr50.util.sounds.SoundManager.getCrippleSound(SoundManager.java:113) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.sounds.SoundManager.getSound(SoundManager.java:103) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.sounds.SoundManager.sendCategorizedSound(SoundManager.java:40) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.skills.ParticleEffectUtils.playCrippleEffect(ParticleEffectUtils.java:42) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.skills.maces.MacesManager.processCripple(MacesManager.java:97) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.skills.CombatUtils.processMacesCombat(CombatUtils.java:252) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.util.skills.CombatUtils.processCombatAttack(CombatUtils.java:543) ~[mcMMO.jar:?]
	at mcMMO.jar/com.gmail.nossr50.listeners.EntityListener.onEntityDamageByEntity(EntityListener.java:387) ~[mcMMO.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor524.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-132-b48403b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1199) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1129) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1092) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1247) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:319) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1344) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2420) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2879) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2790) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by nossr50** [comment]
Fixed by the sound system rework in 2.2.042 (https://github.com/mcMMO-Dev/mcMMO/commit/df69410e675e6db3283e03e193a726ffe1510600). mcMMO no longer calls Sound.valueOf directly, which is what blew up when Paper changed Sound from an enum to an interface. Closing, please reopen if it recurs on 2.2.042 or newer.
